### PR TITLE
Warn if name of empty template has trailing colon

### LINKED ISSUE #16072: Surprising parsing behaviour for objects ending with `_`
Objects ending with `_` that have a body are parsed in a surprising way.
I only narrowed it down accidentally, but the symptoms were lots of compiler errors because of the defs I expected to be in the companion actually being at top level.

## Compiler version

3.2.0

## Minimized code

You can see how `Hello_:` is defined instead, and `x` is treated as a top-level definition

```Scala
object Hello_:
  def x = 1

object `Byte_`:
  def x = 1

@main def hello = 
  println(Byte_)
  println(Hello_:)
  println(x)
```

## Output

This parsing warning is the only indication that helped me figure out that something was off:

```scala
[warn] ./test.scala:2:3: Line is indented too far to the right, or a `{` or `:` is missing
[warn]   def x = 1
[warn]   ^
```

## Expectation

The code either parses correctly, or fails to parse, or gives a meaningful warning

### LINKED ISSUE #18020: Confusing parsing error when defining a val named `_root_` with a type
## Compiler version

If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

`main` (and also in Scala 2)

## Minimized code

```Scala
def foo: Unit =
  val _root_: String = "abc"
```

## Output

```scala
-- [E032] Syntax Error: issues/i17757.scala:2:21 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2 |  val _root_: String = "abc"
  |                     ^
  |                     pattern expected
  |
  | longer explanation available when compiling with `-explain`
```

## Expectation

If you leave out the type, it will compile:
```
val _root_ = "abc"
```

So this one with a type annotation should compile as well?

Found together with @jan-pieter @nmcb

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #16072 
Fixes #18020 

Warn to guard against colon fusion in `object x_:` and `def x_: String`.

Indent warning is made awesome.

### CODE REVIEW

**Comment by som-snytt** [comment]
Note that it's less helpful if scanner issues the indent warning "out of order".
```
-- Warning: tests/warn/i16072.scala:4:2 --------------------------------------------------------------------------------4 |  def x = 1 // warn too far right
  |  ^
  |  Line is indented too far to the right, or a `{` or `:` is missing
-- [E222] Syntax Warning: tests/warn/i16072.scala:3:7 ------------------------------------------------------------------3 |object Hello_: // warn colon in name without backticks because the body is empty
  |       ^^^^^^^
  |       name `Hello_:` should be enclosed in backticks
```

Must follow up givens and enums.

**Comment by som-snytt** [comment]
My first swing from Dec 2022 was more direct:
```
     def checkNextNotIndented(): Unit =
-      if in.isNewLine then
+      if testNextNotIndented() then
+        warning(em"Line is indented too far to the right, or a `{` or `:` is missing", in.next.offset)
+
+    def testNextNotIndented(): Boolean =
+      in.isNewLine && {
         val nextIndentWidth = in.indentWidth(in.next.offset)
-        if in.currentRegion.indentWidth < nextIndentWidth then
-          warning(em"Line is indented too far to the right, or a `{` or `:` is missing", in.next.offset)
+        in.currentRegion.indentWidth < nextIndentWidth
+      }

+    // Catch inadvertent fusion of punctuation as operator char (name_:)
+    private def checkSuspiciousColon(name: Name, offset: Offset): Unit =
+      if name.endsWith(":") && testNextNotIndented() then
+        warning(em"name ends in `:` before indented line", offset-1)
+

     def classDef(start: Offset, mods: Modifiers): TypeDef = atSpan(start, nameStart) {
-      classDefRest(start, mods, ident().toTypeName)
+      val name = ident()
+      checkSuspiciousColon(name, nameStart)
+      classDefRest(start, mods, name.toTypeName)
     }
```

**Comment by som-snytt** [comment]
I wonder how wedded folks are to forms of quote. I like the idea of backticks because of markdown, but the char literal printed by `showToken` seems more natural. I would accept backticks for user identifiers, but token ticks for tokens.

```
Welcome to Scala 3.8.0-RC1-bin-SNAPSHOT-nonbootstrapped-git-d394833 (23.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> locally {
     |     val x = 42
     |   val y = 27
     | }
1 warning found
-- [E223] Syntax Warning: ------------------------------------------------------
3 |  val y = 27
  |  ^
  |  Line is indented too far to the left, or a '}' is missing
  |
  | longer explanation available when compiling with `-explain`

scala>
➜  snips scala-cli repl --server=false -S 3.7.2
Welcome to Scala 3.7.2 (23.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> locally {
     |     val x = 42
     |   val y = 27
     | }
1 warning found
-- Warning: --------------------------------------------------------------------
3 |  val y = 27
  |  ^
  |  Line is indented too far to the left, or a `}` is missing
```

**Comment by som-snytt** [comment]
### Why was the information-rich comment too verbose?

See below.

### Why was the ticket worth tackling?

If it surprises keynmol, it can surprise any of us. The syntax is a mild language wart but easy enough to compensate for (by linting). (Arguably, people should be persuaded not to give underscore special meaning as a leading or trailing character in a name. For all the reduction in underscore semantics, it is still fundamental to operator names; it is not farfetched to suggest it should be discouraged for other snake purposes, in the absence of backticks, just like embedded dollar.) (Compare making underscore no longer available as an identifier.)

### How I fixed it

My first attempt was to consider any such name, or such a name followed by indentation. For context, however, it's simpler to query whether the template has a body; I think https://github.com/scala/scala3/issues/16072#issuecomment-1429556256 by abgruszecki suggested it to me.

The improvement for `def f String = ""` was suggested on the ticket by dwijnand.

### Why is this PR worth reviewing?

There is no syntax change, but only a warning for the two gotchas. The change is confined to the parser.

If I spend another hour on it, I'll add dwijnand's idea to split the unintended identifier in `def s_: String = ""` (with a warning).

### What's the worse that could happen?

TBD

**Comment by som-snytt** [comment]
Indent warning is made awesome --> "awesomaticized".

Rebased. Updated check file for change in error id, but dropped the last commit as previous research.

**Comment by Gedochao** [comment]
@som-snytt is this still relevant?

**Comment by som-snytt** [comment]
It must be relevant, because I refreshed it, but I'll look to see why it's still draft.

Let me assume that I must update the error ID, the message, and all the check files that use them.

**Comment by som-snytt** [comment]
I think I delayed reviewing because of the suggestion to make it just work:

> If I spend another hour on it, I'll add dwijnand's idea to split the unintended identifier in `def s_: String = ""` (with a warning).

But I'll save that innovation for later, in case it requires a mini SIP.

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -328,6 +328,13 @@ object Parsers {
       if in.token == token then in.nextToken()
       offset
 
+    def accept(token: Int, help: String): Int =
+      val offset = in.offset
+      if in.token != token then
+        syntaxErrorOrIncomplete(ExpectedTokenButFound(token, in.token, suffix = help))
+      if in.token == token then in.nextToken()
```
Comment (SolalPirelli) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala:335]: surely this can be an `else`?

**Review by SolalPirelli — APPROVED** [review]
I'm not 100.0% confident reviewing parser stuff yet but this seems good and it passes tests

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala (hunk 1 above)
Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala:335]: Ha, I wonder if it reflects my suspicion of Boolean logic.

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala:335]: Ah no, it's cut/paste, aka concede to the ambient style.

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala:335]: Erroring may side effect by skipping a token. Spell suggests changing "erroring" to "terrorizing", which is just.

**Comment by bracevac** [comment]
image

Thou shalt document thy errors.

**Comment by SethTisue** [comment]
Anyone who merges a PR is now getting an email about that `ErrorCodeSnippetsTest` failure on E228 and E229 (at least, I just got one)

Is there a reason the "scaladoc" CI job isn't part of PR validation, so we'd know about this before merge?

**Comment by bracevac** [comment]
Was this PR too stale and not rebased before merging? I see the scaladoc task failing on my PR.

**Comment by SethTisue** [comment]
@bracevac oh, I suppose that's possible? okay, I won't worry about it unless we see new evidence

**Comment by SethTisue** [comment]
fixed by #25942
