### PR TITLE
Various fixes to stdlib-cc

### LINKED ISSUE #19652: Compilation test failures with Scala 2 CC library TASTy
#19603 fixes the basics and we can now compile most tests. 

I tried to go further with
```
sbt> set ThisBuild/Build.scala2Library := Build.Scala2LibraryCCTasty
sbt> scala3-bootstrapped/testCompilation
```
Here's the current list of failures:
```
32 suites passed, 4 failed, 36 total
    tests/neg/i8988.scala failed
    tests/neg/abstract-givens.scala failed
    tests/neg/i18682.scala failed
    tests/run/enrich-gentraversable.scala failed
    tests/run/t5328.scala failed
    tests/run/xml.scala failed
    tests/run/t4332b.scala failed
    tests/run/abstract-givens.scala failed
    tests/run/t2552.scala failed
    tests/run/t2544.scala failed
    tests/run/i16459.scala failed
    tests/run/t6114.scala failed
    tests/pos/i18345.scala failed
    tests/run/t3269.scala failed
    tests/pos/spec-asseenfrom.scala failed
    tests/pos/i19009.case1.scala failed
    tests/pos/i14966a.scala failed
    tests/run/iterables.scala failed
    tests/run/i14582.scala failed
    tests/run/t4054.scala failed
    tests/pos/i14953.scala failed
    tests/run/t5201.scala failed
    tests/run/t6968.scala failed
    tests/run/range-unit.scala failed
    tests/pos/t5120.scala failed
    tests/run/t6271.scala failed
    tests/run/enrich-gentraversable.scala failed
    tests/pos/i1036.scala failed
    tests/pos/t6925.scala failed
    tests/run/Course-2002-10.scala failed
    tests/pos/tyql.scala failed
    tests/run/t4288.scala failed
    tests/run/main-annotation-newMain.scala failed
    tests/run/Pouring.scala failed
    tests/run/t5328.scala failed
    tests/run/t6628.scala failed
    tests/run/arrayview.scala failed
    tests/run/colltest1.scala failed
    tests/pos/gadt-accumulatable.scala failed
    tests/run/t3397.scala failed
    tests/run/t2544.scala failed
    tests/run/i16459.scala failed
    tests/run/t3516.scala failed
    tests/pos/tcpoly_ticket2096.scala failed
    tests/run/t4582.scala failed
    tests/run/i4523.scala failed
    tests/run/iterators.scala failed
    tests/run/stream-stack-overflow-filter-map.scala failed
    tests/pos/t4716.scala failed
    tests/run/streamWithFilter.scala failed
    tests/run/IArrayOps.scala failed
    tests/run/ReverseSeqView.scala failed
    tests/run/viewtest.scala failed
    tests/run/numbereq.scala failed
    tests/run/t3760.scala failed
    tests/run/distinct.scala failed
    tests/run/t4332b.scala failed
    tests/pos/i6199a.scala failed
    tests/run/view-headoption.scala failed
    tests/run/abstract-givens.scala failed
    tests/pos/i9967.scala failed
    tests/pos/i1777.scala failed
    tests/pos/StringContext.scala failed
    tests/run/t4954.scala failed
    tests/pos/i5418.scala failed
    tests/run/t6584.scala failed
    tests/run/extmethods2.scala failed
    tests/pos/t0068.scala failed
    tests/run/kmpSliceSearch.scala failed
    tests/run/patmat-bind-typed.scala failed
    tests/run/t1220.scala failed
    tests/run/t5867.scala failed
    tests/pos/syntaxRewrites.scala failed
    tests/run/forvaleq.scala failed
    tests/pos/t6205.scala failed
    tests/run/Pouring2.scala failed
    tests/run/unittest_iterator.scala failed
    tests/pos/indent-colons.scala failed
    tests/pos/t4717.scala failed
    tests/run/t2552.scala failed
    tests/run/lst failed
    tests/run/t5053.scala failed
    tests/run/lists-run.scala failed
    tests/run/t1074.scala failed
    tests/run/seqlike-kmp.scala failed
    tests/pos/tyql.scala failed
    tests/pos/t6925.scala failed
```
We need to follow up on this next.

_Originally posted by @odersky in https://github.com/lampepfl/dotty/issues/19586#issuecomment-1925328488_

### LINKED ISSUE #19819: Cannot find method `IndexedSeqView.updated` when running a program compiled with CC stdlib
## Compiler version

`main`

## Minimized code

```Scala
object Hello extends App {
    println(Vector(1, 2, 3).view.updated(1, 8))
}
```

Steps to reproduce (assuming that the code is saved as `Hello.scala`):
```
sbt> set ThisBuild/Build.scala2Library := Build.Scala2LibraryCCTasty
sbt> scala3-bootstrapped/scalac Hello.scala
sbt> scala3-bootstrapped/scala Hello
```

## Output

```scala
Exception in thread "main" java.lang.NoSuchMethodError: 'scala.collection.View scala.collection.IndexedSeqView.updated(int, java.lang.Object)'
	at Hello$.<clinit>(Hello.scala:2)
	at Hello.main(Hello.scala)
```

## Expectation

It should run.

### LINKED ISSUE #19847: Check files need to be more versatile for compilation tests with CC Scala 2 library
## Compiler version

`main`

## Minimized code

The problem is that the error messages in negative tests may look different when compiled with CC Scala 2 library.

Steps for reproduce an example:
```
sbt> set ThisBuild/Build.scala2Library := Build.Scala2LibraryCCTasty
sbt> scala3-bootstrapped/testCompilation abstract-givens
```

## Output

The test fails with the diff:
```diff
index 022c454c31..343ce5ecbd 100644
--- a/tests/neg/abstract-givens.check
+++ b/tests/neg/abstract-givens.check.out
@@ -1,7 +1,7 @@
 -- Error: tests/neg/abstract-givens.scala:11:8 -------------------------------------------------------------------------
 11 |  given s[T](using T): Seq[T] with // error
    |        ^
-   |instance cannot be created, since def iterator: Iterator[A] in trait IterableOnce in package scala.collection is not defined 
+   |instance cannot be created, since def iterator: Iterator[A]^{this} in trait IterableOnce in package scala.collection is not defined 
 -- [E164] Declaration Error: tests/neg/abstract-givens.scala:8:8 -------------------------------------------------------
 8 |  given y(using Int): String = summon[Int].toString * 22 // error
   |   
```

### PR DESCRIPTION
**Pull request by Linyxus**
fixes #19819, fixes #19652, fixes #19847, supersedes #19858

### CODE REVIEW

**Comment by Linyxus** [comment]
Now the failing tests are reduced to:
```scala
33 suites passed, 3 failed, 36 total
    tests/neg/syntax-error-recovery.scala failed
    tests/neg/multi-file-error failed
    tests/run/enrich-gentraversable.scala failed
    tests/run/enrich-gentraversable.scala failed
```

The first two seems to be a problem in my local setup. So there should be only one last issue remaining.

File: scala2-library-cc/src/scala/collection/generic/IsSeq.scala [hunk 1]
```diff
@@ -54,24 +54,20 @@ object IsSeq {
...
-    new IsIterable[CC0[A0]] {
-      type A = A0
-      type C = View[A]
-      def apply(coll: CC0[A0]): IterableOps[A0, View, View[A0]] = coll
-    }
+    * Therefore, [[seqViewIsSeq]] now returns an [[IsIterable]].
+    * The helper method [[seqViewIsSeq_]] is added to make the binary compatible.
+    */
+  @annotation.targetName("seqViewIsSeq")
+  def seqViewIsSeq_[CC0[X] <: SeqView[X], A0]: IsSeq[CC0[A0]] { type A = A0; type C = View[A0] } = ???
```
Comment (nicolasstucki) [inline scala2-library-cc/src/scala/collection/generic/IsSeq.scala:61]:
```suggestion
  private[IsSeq] def seqViewIsSeq_[CC0[X] <: SeqView[X], A0]: IsSeq[CC0[A0]] { type A = A0; type C = View[A0] } = ???
```

**Review by odersky — APPROVED** [review]
