### PR TITLE
fix/scripts: Propagate runner JVM version and skip testing invalid compiler commits

### LINKED ISSUE #19650: Bisect script failures
For any Scala source, let us call it `Test.scala` the following fails 
```
$ scala-cli project/scripts/bisect.scala -- compile Test.scala
```

```
Bisecting with validation script: /var/folders/j_/1jnflqdn6vg_6q2602rxq46m0000gn/T/scala-bisect-validator9193156609557343888
#####################################

#!/usr/bin/env bash
scala-cli compile -S "$1" --server=false Test.scala


#####################################

Verifying the first release: 3.0.1-RC1-bin-20210413-f3c1468-NIGHTLY
Testing 3.0.1-RC1-bin-20210413-f3c1468-NIGHTLY
Checking https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/
Checked https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/
Checking https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/maven-metadata.xml
Checked https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/maven-metadata.xml
19 is not a valid choice for -release
  scalac -help  gives more information
Compilation failed
Test result: 3.0.1-RC1-bin-20210413-f3c1468-NIGHTLY is a bad release

Exception in thread "main" java.lang.AssertionError: assertion failed: The evaluation script unexpectedly failed for the first checked release
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at ReleaseBisect.verifyEdgeReleases(bisect.scala:203)
        at bisect$package$.run(bisect.scala:64)
        at run.main(bisect.scala:53)
```

### PR DESCRIPTION
**Pull request by WojciechMazur**
Fixes #19650 

* Bisect script used JVM 17 by default, can be overriden using:
 `scala-cli run project/scripts/bisect.scala --jvm=21 -- <bisect args>`
* Bisect runner JVM version is propagated to scala-cli verification script and sbt when building compiler
* Skip testing commits for which compiler compilation fails

### CODE REVIEW

File: project/scripts/bisect.scala [hunk 1]
```diff
@@ -124,6 +125,7 @@ object ValidationScript:
 
   def tmpScalaCliScript(command: String, args: Seq[String]): File = tmpScript(s"""
     |#!/usr/bin/env bash
+    |export JAVA_HOME=${sys.props("java.home")}
```
Comment (prolativ) [inline project/scripts/bisect.scala:128]: Any specific reason to override `JAVA_HOME` instead of passing the java version to scala-cli via `--jvm` option?
Also, this won't be taken into account when using a custom validation script. Is this intentional?

Comment (WojciechMazur) [reply project/scripts/bisect.scala:128]: I assume that user of custom validation script is an advanced user who understands not only a tested code, but also the environment in which it is being run. Especially since custom bisect script might use sbt or other build tool. We could add custom JAVA_HOME  to custom scripts by populating env variables of created process, but it would require a rewrite for parts of the code. I'd try this approach and check how it behaves.

The `JAVA_HOME` was used instead of `--jvm` argument to make sure that we exactly the same JVM version. We would not be able to pass a path in --jvm argument, and extraction of --jvm argument might be difficult.

**Review by prolativ — APPROVED** [review]
