### PR TITLE
Preserve Java enum semantics for explicit java.lang.Enum inheritance

### LINKED ISSUE #11252: Enum[Nothing] is allowed but has a sharp edge
## Compiler version

```
➜  snips ~/projects/dotty/bin/scala -version
Starting scala3 REPL...
Scala compiler version 3.0.0-RC1-bin-SNAPSHOT-git-ce684de -- Copyright 2002-2021, LAMP/EPFL
```

## Minimized code

```Scala
Starting scala3 REPL...
scala> enum E extends Enum[Nothing] { case X }
// defined class E

scala> E.values
val res0: Array[E] = Array(X)

scala> E.X.getDeclaringClass.getEnumConstants
java.lang.ClassCastException: class [Lrs$line$1$E; cannot be cast to class [Lscala.runtime.Nothing$; ([Lrs$line$1$E; is in unnamed module of loader dotty.tools.repl.AbstractFileClassLoader @d180961; [Lscala.runtime.Nothing$; is in unnamed module of loader java.net.URLClassLoader @4de158ca)
  ... 27 elided
```

## Output

```scala
java.lang.ClassCastException
```

## Expectation

I expect an error at compile time for the bad type arg. Or maybe `values` is `Array[Nothing]` and throws if non-empty. (I see that `Enumerations must contain at least one case`.)

Alternatively, maybe it is allowed in Scala but the implementation is tweaked so that Java reflection sees a different (lower bound of) the enum type.

### LINKED ISSUE #11253: `Enum.values` should be consistent with `getEnumConstants`
## Compiler version

Scala compiler version 3.0.0-RC1-bin-SNAPSHOT-git-ce684de

## Minimized code

```Scala
Starting scala3 REPL...
scala> trait T extends Enum[T] { def t: String }
// defined trait T

scala> enum E(val t: String) extends Enum[T], T { case X extends E("xxx") }
// defined class E

scala> E.values
val res0: Array[E] = Array(X)

scala> E.X.getDeclaringClass.getEnumConstants
val res1: Array[T] = Array(X)
```

## Output

```scala
`Array[T]` differs from `Array[E]`
```

## Expectation

What I'd really like is to write
```
enum E extends Enum { case X }
```
where the omitted type arg is inferred to be `E`.

In any case, `values` should be consistent with `getEnumConstants`.

### PR DESCRIPTION
**Pull request by zielinsky**
Scala currently accepts some explicit `java.lang.Enum[...]` usages that are not consistent with Java enum semantics. In particular, F-bound checking alone is not sufficient here: it can accept programs where the type argument satisfies `E <: Enum[E]`, but does not actually match the enum class.

This leads to problematic cases such as `enum E extends Enum[Nothing] { case X }` (`i11252`)

These cases may compile, but can break the expected Java enum behavior, especially around reflection and runtime consistency.

After discussion during the Scala Core meeting (01.04.2026), we decided that when code explicitly uses `extends java.lang.Enum[...]`, Scala should preserve Java enum semantics more strictly.

This means we require:
1. the `java.lang.Enum` type argument to refer to the enum class itself
2. the enum to have **no type parameters**

This rejects examples such as:
- `enum E extends Enum[Nothing]`
- generic enums like `enum E[A] extends Enum[E[?]]`

Fixes #11252
Fixes #11253

---
Typo in the error message has also been fixed (`paramerized` -> `parameterized`)

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 1]
```diff
@@ -1575,6 +1577,18 @@ trait Checking {
...
         else
           report.error(em"enum $cls can not inherit the concrete ordinal method of ${decl.owner}", cdef.srcPos)
+    def checkJavaEnumTypeArg(using Context) =
+      val javaEnumBase = cls.thisType.baseType(defn.JavaEnumClass)
+      if javaEnumBase.exists then
+        javaEnumBase.argInfos match
+          case typeArg :: Nil =>
+            if cls.typeParams.nonEmpty then
+              report.error(em"An enum extending java.lang.Enum cannot have type parameters", cdef.srcPos)
+            if !(typeArg =:= cls.typeRef) then
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala]: i believe this should be simplified to `typeArg.classSymbol ne cls` or similar

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Checking.scala]: ~but of course prefix could be important~
Edit: not relevant for Java enums

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Checking.scala]: Actually, java enums are not allowed to be inner classes they are static always, so there is no worry about comparing prefixes - so as they are static then symbol reference equality is fine

Comment (zielinsky) [reply compiler/src/dotty/tools/dotc/typer/Checking.scala]: good catch, thanks:>
https://github.com/scala/scala3/pull/25658/commits/817e548d6798c279c2174cfb1af1097626601164

**Review by bishabosha — APPROVED** [review]
