### PR TITLE
Correctly detect colon lambda eol indent for optional brace of argument

### LINKED ISSUE #22193: Fewer braces and lambda: incorrect indentation region detection
## Compiler version

- 3.3.3
- 3.3.4 LTS
- 3.5.2 Next

## Minimized code

```Scala
  def fn2(arg: String, arg2: String)(f: String => Unit): Unit =
    f(arg)

  // doesn't compile
  fn2(
      arg = "blue sleeps faster than tuesday",
      arg2 = "the quick brown fox jumped over the lazy dog"): env =>
      val x = env
      println(x)

  // does compile
  fn2(
      arg = "blue sleeps faster than tuesday",
      arg2 = "the quick brown fox jumped over the lazy dog"):
    env =>
      val x = env
      println(x)

  // does compile
  fn2(
      arg = "blue sleeps faster than tuesday",
      arg2 = "the quick brown fox jumped over the lazy dog"
  ): env =>
      val x = env
      println(x)
```

## Output

scastie marks two errors:
- `fn2` line with `not a legal formal parameter for a function literal`
- `val x = env` line with `Not found: env`

## Expectation

According to the documentation, the first argument clause (with `arg` and `arg2`) does not start an indentation region, hence as long as the lambda body is indented relative to `fn2` invocation, it should work.

- https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html#optional-braces-3
- https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html#indentation-and-braces-1

P.S. The problem was first reported in scalameta/scalafmt#4569.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #22193 

The lookahead scanner used by `followingIsLambdaAfterColon` would recalculate the indentation width of its top region from the current offset, which is the colon token. That would cause detection of indentation to fail on the next line. This commit preserves the indentation width for that purpose. Subsequent parsing of the function literal proceeds normally.

### CODE REVIEW

File: tests/pos/i22193.scala [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+    arg2 = "the quick brown fox jumped over the lazy dog"):
+    val x = "Hello"
+    println(x)
+
+  fn3(
+      arg = "blue sleeps faster than tuesday",
+      arg2 = "the quick brown fox jumped over the lazy dog"):
+      val x = "Hello"
+      println(x)
+
```
Comment (kitbellew) [inline tests/pos/i22193.scala:65]: these two are the same, aren't they? similar to lines 13-29, i'd add
```
fn3( // arg at 3, body at 3
   arg = "blue sleeps faster than tuesday",
   arg2 = "the quick brown fox jumped over the lazy dog"):
   val x = "Hello"
   println(x)

fn3( // arg at 3, body at 1: not sure if sig indent of 1 is allowed, saw some comments from odersky
   arg = "blue sleeps faster than tuesday",
   arg2 = "the quick brown fox jumped over the lazy dog"):
 val x = "Hello"
 println(x)

fn3( // arg at 3, body at 2: even if sig indent of 1 is not allowed, body is at fn3+2, not arg2-1
   arg = "blue sleeps faster than tuesday",
   arg2 = "the quick brown fox jumped over the lazy dog"):
  val x = "Hello"
  println(x)

fn3( // arg at 3, body at 4
   arg = "blue sleeps faster than tuesday",
   arg2 = "the quick brown fox jumped over the lazy dog"):
    val x = "Hello"
    println(x)
```

File: tests/pos/i22193.scala [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+def fn3(arg: String, arg2: String)(f: => Unit): Unit = f
+
+def test() =
+
+  fn2(arg = "blue sleeps faster than tuesday", arg2 = "the quick brown fox jumped over the lazy dog"): env =>
+    val x = env
+    println(x)
+
+  // doesn't compile
```
Comment (kitbellew) [inline tests/pos/i22193.scala:12]: hopefully, not true anymore :)

File: tests/neg/i22193.scala [hunk 3]
```diff
@@ -0,0 +1,32 @@
+
+def fn2(arg: String, arg2: String)(f: String => Unit): Unit = f(arg)
+
+def fn3(arg: String, arg2: String)(f: => Unit): Unit = f
+
+def test1() =
+
+  // ok baseline
+  fn2(arg = "blue sleeps faster than tuesday", arg2 = "the quick brown fox jumped over the lazy dog"): env =>
+    val x = env
```
Comment (kitbellew) [inline tests/neg/i22193.scala:10]: this looks valid. does `neg` require failing parts to be marked with `error`?

Comment (som-snytt) [reply tests/neg/i22193.scala:10]: yes, that is a baseline example of what works without controversy.

File: tests/pos/i22193.scala (hunk 2 above)
Comment (som-snytt) [reply tests/pos/i22193.scala:12]: I used to add `// was:` to mean previously, which didn't help, but then I noticed Odersky just leaves the original text. I like it, it's like the test has a cherished patina.

File: tests/pos/i22193.scala (hunk 1 above)
Comment (som-snytt) [reply tests/pos/i22193.scala:65]: same except for alignment. The symptom was strange and many moving parts under the hood. I'll add the tests, thanks.

The other concept is "outdented and aligns with something"; the ref example is the else that does not align with if.

**Review by kitbellew — COMMENTED** [review]
fantastic! i would select approve, mainly based on the tests :)

**Comment by som-snytt** [comment]
@mbovel This was tricky to figure out without knowing anything, but turns out to be a one-liner (plus a method) that may be a quick review.

File: compiler/src/dotty/tools/dotc/parsing/Scanners.scala [hunk 4]
```diff
@@ -672,6 +671,20 @@ object Scanners {
...
+    def observeArrowIndented(): Unit =
+      if isArrow && indentSyntax then
+        peekAhead()
+        val atEOL = isAfterLineEnd || token == EOF
+        reset()
+        if atEOL then
+          val nextWidth = indentWidth(next.offset)
+          val lastWidth = currentRegion.indentWidth
+          if lastWidth < nextWidth then
+            currentRegion = Indented(nextWidth, COLONeol, currentRegion)
```
Comment (mbovel) [inline compiler/src/dotty/tools/dotc/parsing/Scanners.scala:684]: Is it expected to use `COLONeol` here? Or could use `ARROW` instead?

At first sight, it only seems to be used [here](https://github.com/scala/scala3/blob/b57549e66fb3e63f18adc674fe1ae4a5fd4c1fa9/compiler/src/dotty/tools/dotc/parsing/Scanners.scala#L704) where it's compared to `MATCH`.

File: compiler/src/dotty/tools/dotc/parsing/Scanners.scala [hunk 5]
```diff
@@ -680,7 +693,6 @@ object Scanners {
           currentRegion = Indented(nextWidth, COLONeol, currentRegion)
           offset = next.offset
           token = INDENT
-    end observeIndented
```
Comment (mbovel) [inline compiler/src/dotty/tools/dotc/parsing/Scanners.scala:683]: +1, I also don't like these end markers 😄

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/parsing/Scanners.scala:683]: the method used to be longer and had a blank line. I must have deleted it during other edits while experimenting, but here it's no longer needed.

File: compiler/src/dotty/tools/dotc/parsing/Scanners.scala (hunk 4 above)
Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/parsing/Scanners.scala:684]: My first attempt used ARROW and used it during newline handling, but that was not needed. I changed to colon for uniformity only; the result here is only produced and discarded in lookahead scanner. Actually on my WIP branch, I used a new token `ARROWeol` for when it is not a proper indent, as after `MATCH`.

Comment (mbovel) [reply compiler/src/dotty/tools/dotc/parsing/Scanners.scala:684]: Okay, let's get that merged then!

**Comment by som-snytt** [comment]
I ought to have squashed.

**Comment by kitbellew** [comment]
thank you both!
