### PR TITLE
Fix Java signatures for arrays of value classes

### LINKED ISSUE #12189: java generic signature for value class array is unboxed but descriptor is boxed
## Compiler version

3.0.0-RC2

## Minimized code

```Scala
package dottyErasure

trait A
class VC(val self: A) extends AnyVal
class Z {
  def vcARRAY(x: Array[VC]): Unit = {}
}
```

## Output

```java
public void vcARRAY(dottyErasure.A[]);
    descriptor: ([LdottyErasure/VC;)V
    flags: ACC_PUBLIC
    Code:
      stack=0, locals=2, args_size=2
         0: return
      LineNumberTable:
        line 222: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       1     0  this   LdottyErasure/Z;
            0       1     1     x   [LdottyErasure/VC;
    Signature: #217                         // ([LdottyErasure/A;)V
    MethodParameters:
      Name                           Flags
      x                              final
```

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #12189

## How much have you relied on LLM-based tools in this contribution?

not

## How was the solution tested?

issue's test turned into a fully automated test

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 1]
```diff
@@ -317,13 +321,15 @@ object GenericSignatures {
           else if (sym == defn.NullClass)
             builder.append("Lscala/runtime/Null$;")
           else if (sym.isPrimitiveValueClass)
-            if (!unboxedVCs) jsig1(defn.ObjectType)
+            // TODO, but a few tests need fixing / disabling until a newer scalac is ingested,
+            // replace the next 2 lines with: if (vcBoxing == ValueClassBoxing.Box || sym == defn.UnitClass) jsig1(defn.boxedClass(sym).typeRef)
+            if (vcBoxing == ValueClassBoxing.Box) jsig1(defn.ObjectType)
```
Comment (SolalPirelli) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:326]: will create an issue for this if the PR is accepted

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 2]
```diff
@@ -299,7 +300,10 @@ object GenericSignatures {
             builder.append(ClassfileConstants.ARRAY_TAG)
             elemtp match
               case TypeBounds(lo, hi) => jsig1(hi.widenDealias)
-              case _ => jsig1(elemtp)
```
Comment (tanishiking) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:302]: [note]
Ah, here `unboxedVCs: Boolean = true` by default, and jsig for `Array[VC]` would be unboxed.

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala (hunk 1 above)
Comment (tanishiking) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:326]: It makes sense that we wanna generate concrete boxed types like `Ljava/lang/Integer;` instead of `Ljava/lang/Object;` :+1:

> disabling until a newer scalac is ingested,

Just out of curiosity, what specifically requires a newer scalac here? Is it that Scala (2?3?) classfile parser doesn't correctly handle generic signatures with concrete boxed types or something?

**Review by tanishiking — APPROVED** [review]
I left a question about the TODO, but otherwise LGTM :tada:

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala (hunk 1 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:326]: There's a test that compiles (1) a Java file that references (2) a Scala file with a class extending (3) a Scala standard library class.

If we change the Scala compiler to emit different signatures, then (2) uses the newer signature but (3) uses the older one in non-bootstrapped mode, so (1) fails to compile because of the signature mismatch between (2) and (3).

Comment (tanishiking) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:326]: > (3) uses the older one in non-bootstrapped mode

Ah, so we would have some non-bootstrapped tests to temporarily fail with that change, makes sense. Thank you for explanation!
