### PR TITLE
Lint function arrow intended context function

### LINKED ISSUE #21187: Exceptions inexplicably swallowed when inlined context functions interact
## Compiler version

Tested it with 3.3.3, 3.3.4-RC1, 3.4.2, 3.5.0-RC4

## Minimized code

```Scala
def oops(msg: String) = sys.error(msg)

class Zone
object Zone:
  inline def apply[T](inline f: Zone ?=> T): T = f(using new Zone)

inline def zone[A](inline f: Zone ?=> A) = Zone.apply(z => f(using z))

@main def hello = 
  // this swallows exceptions!
  zone(oops("here"))
  
  // this doesn't
  Zone(oops("not here"))


```

## Output

```
Exception in thread "main"java.lang.RuntimeException: not here
        at scala.sys.package$.error(Unknown Source)
        at test$package$.oops(Unknown Source)
        at test$package$.hello(Unknown Source)
        at hello.main(Unknown Source)
        at <none>.main(Unknown Source)
```

## Expectation

I expected the first call to oops to throw the error, but it's quietly swallowed. This is extremely unsettling, I have no idea what other places I have where exceptions are swallowed like this

Noticed this when converting a project from SN 0.4 to SN 0.5 which ships a Zone.apply that uses context functions out of the box (I used to have `zone` helper before, and it worked fine)

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #21187 

If a function literal `x => body` has an expected type `X ?=> ?` then maybe they intended to write `x ?=> body`.

As shown in the test, maybe types will misalign in other ways to emit warnings.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/config/ScalaSettings.scala [hunk 1]
```diff
@@ -168,6 +168,7 @@ private sealed trait WarningSettings:
   private val WunstableInlineAccessors = BooleanSetting(WarningSetting, "WunstableInlineAccessors", "Warn an inline methods has references to non-stable binary APIs.")
   private val WtoStringInterpolated = BooleanSetting(WarningSetting, "Wtostring-interpolated", "Warn a standard interpolator used toString on a reference type.")
   private val WrecurseWithDefault = BooleanSetting(WarningSetting, "Wrecurse-with-default", "Warn when a method calls itself with a default argument.")
+  private val WdubiousContextual = BooleanSetting(WarningSetting, "Wdubious-contextual", "Warn about T ?=> (t: T) => U.")
```
Comment (tgodzik) [inline compiler/src/dotty/tools/dotc/config/ScalaSettings.scala]:
```suggestion
  private val WunlikelyContextual = BooleanSetting(WarningSetting, "Wunlikely-contextual", "Warn about T ?=> (t: T) => U. when a normal function literal was used instead of context one."), 
```
just because the word is prone to typos for non english speakers and a bit more explanation aside from signature?

File: tests/warn/i21187.scala [hunk 2]
```diff
@@ -0,0 +1,21 @@
+//> using options -Wall
+
+def oops(msg: String) = sys.error(msg)
+
+class Zone
+object Zone:
+  inline def apply[T](inline f: Zone ?=> T): T = f(using new Zone)
+
+inline def zone[A](inline f: Zone ?=> A) = Zone.apply(z => f(using z)) // warn suspicious contextualizing
```
Comment (tgodzik) [inline tests/warn/i21187.scala:9]: Will this be reported with:
```
def zone[A](f: Zone ?=> A) = Zone.apply(z => f(using z))
```
as well? Maybe the warning should only be for the inline cases, where it might cause most issues.

What do you think?

File: compiler/src/dotty/tools/dotc/config/ScalaSettings.scala (hunk 1 above)
Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/config/ScalaSettings.scala]: I rely on `-Xlint` or now `-Wall`. Though I do like the word "dubious". All warnings are dubious because they begin with `-W` or "dubya".

File: tests/warn/i21187.scala (hunk 2 above)
Comment (som-snytt) [reply tests/warn/i21187.scala:9]: I think it's the same issue, which is that the function literal is wrapped in a context function. I added it to the test to document the behavior is the same.

File: compiler/src/dotty/tools/dotc/config/ScalaSettings.scala [hunk 3]
```diff
@@ -168,6 +168,7 @@ private sealed trait WarningSettings:
   private val WunstableInlineAccessors = BooleanSetting(WarningSetting, "WunstableInlineAccessors", "Warn an inline methods has references to non-stable binary APIs.")
   private val WtoStringInterpolated = BooleanSetting(WarningSetting, "Wtostring-interpolated", "Warn a standard interpolator used toString on a reference type.")
   private val WrecurseWithDefault = BooleanSetting(WarningSetting, "Wrecurse-with-default", "Warn when a method calls itself with a default argument.")
+  private val WdubiousContextual = BooleanSetting(WarningSetting, "Wwrong-arrow", "Warn if function arrow was used instead of context literal ?=>.")
```
Comment (tgodzik) [inline compiler/src/dotty/tools/dotc/config/ScalaSettings.scala]:
```suggestion
  private val WwrongArrow = BooleanSetting(WarningSetting, "Wwrong-arrow", "Warn if function arrow was used instead of context literal ?=>.")
```

File: compiler/src/dotty/tools/dotc/config/ScalaSettings.scala [hunk 4]
```diff
@@ -311,6 +312,7 @@ private sealed trait WarningSettings:
     def unstableInlineAccessors(using Context): Boolean = allOr(WunstableInlineAccessors)
     def toStringInterpolated(using Context): Boolean = allOr(WtoStringInterpolated)
     def recurseWithDefault(using Context): Boolean = allOr(WrecurseWithDefault)
+    def dubiousContextual(using Context): Boolean = allOr(WdubiousContextual)
```
Comment (tgodzik) [inline compiler/src/dotty/tools/dotc/config/ScalaSettings.scala]:
```suggestion
    def wrongArrow(using Context): Boolean = allOr(WdubiousContextual)
```

**Review by tgodzik — APPROVED** [review]
LGTM, just two minor nitpicks

**Comment by tgodzik** [comment]
Thanks!
