### PR TITLE
Include span of bad args if multiline

### LINKED ISSUE #9434: Indentation causes incorrect parsing and/or unhelpful errors
Indentation causes errors (that don't indicate there is an issue with indentation)

Both examples are from Scastie + Dotty 0.26.0-RC1

Code compiles without error in Scala 2 or if formatting is cleaned up...

## Minimized code example 1

```Scala
object Foo {
  def bar1: (Int, Int) = {
    val foo = 1.0
    val bar = foo
      (1, 1)           // scastie error: value foo does not take parameters
  }                    // scastie error: Found: Unit Required: (Int, Int)

  def bar2: Vector[Int] = {
    val foo =
      Vector(1) ++
    Vector(2) ++       // scastie error: postfix operator `++` needs to be enabled
      Vector(3)
    foo
  }                    // scastie error: Found: (foo : IterableOnce[Int] => Vector[Int]) Required: Vector[Int]
}
```

Works if formatting changed...

```Scala
object Foo {
  def bar1: (Int, Int) = {
    val foo = 1.0
    val bar = foo
    (1, 1)
  }

  def bar2: Vector[Int] = {
    val foo =
      Vector(1) ++
      Vector(2) ++
      Vector(3)
    foo
  }
}
```

## Minimized code example 2

```Scala
object Foo {
  def foo = ()
  def foo(a: Int, b: Int) = a + b
  def bar1 = {
    foo
      (1,1)
  }
  def bar2 = {
    foo
    (1,1)
  }

  def main(args: Array[String]): Unit = {
    println(bar1)  // prints 2
    println(bar2)  // prints (1,1)
  }
}
```

## Expectation

I'd expect example 1 to either compile as it does on Scala 2 or produce errors (not warnings) that indicate there is a formatting issue.

I'd expect example 2 to produce the same results from both functions or produce errors that indicate there is a formatting issue.  There are no errors/warnings at all given in this example.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #9434 

The message position is tweaked only when the args are on a different line.

Then the source context includes the args; but only one caret for the point.

It would be nicer to request more context without changing the diagnostic position.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -4498,7 +4498,14 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
         if isAcceptedSpuriousApply(tree, pt.args) then tree
         else
           tryInsertApplyOrImplicit(tree, pt, locked):
-            errorTree(tree, MethodDoesNotTakeParameters(tree))
+            val pos =
+              if pt.args.isEmpty then tree.srcPos
+              else
+                val union = tree.sourcePos.withSpan:
+                  tree.srcPos.span.union(pt.args.last.srcPos.span)
```
Comment (warcholjakub) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:4505]: What if `tree.sourcePos` is remapped (e.g. code has a magic header), while the union uses raw `srcPos` spans? Could that shift reported locations?

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:4505]: I'll look at how that is done. On Scala 2, the "underlying" position was a function of the source. Otherwise, how could one do any position calculation? However, I endorse my comment about using API to request more context instead of touching position.

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:4505]: Previously, shifting for funky headers was `positionInUltimateSource`, which may still be used in two places.

`sourcePos.withSpan` is the same as `tree.source.atSpan` or
```
val union = tree.sourcePos.copy(span = tree.srcPos.span.union(pt.args.last.srcPos.span))
```
Here we don't have a `Positioned`, we just want a `SrcPos` for reporting. Normally, reporting creates a `Diagnostic` and its `SourcePosition` together.

I won't push it further here, but it would be nice if reporting had a channel for extra pos info like inlined outers (currently a field in `SourcePosition` but really belongs to the diagnostic) and for this kludge a pos to say "rendering context should include this line".

**Comment by som-snytt** [comment]
Just a rebase and a random NPE. We ought not to normalize that.

```
[info] Test dotty.tools.dotc.ScalaJSCompilationTests.runScalaJS started
Test 'tests/run/i22888.scala' failed with output:                               
java.lang.NullPointerException: Cannot invoke "scala.concurrent.Future.onComplete(scala.Function1, scala.concurrent.ExecutionContext)" because "that" is null
	at scala.concurrent.impl.Promise$DefaultPromise.zipWith(Promise.scala:153)
	at scala.concurrent.Future$.traverse$$anonfun$1(Future.scala:884)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:740)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:336)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1325)
	at scala.concurrent.Future$.traverse(Future.scala:884)
	at org.scalajs.linker.standard.StandardIRFileCache$CacheImpl.cached(StandardIRFileCache.scala:67)
	at dotty.tools.dotc.ScalaJSLink$.$anonfun$3(ScalaJSLink.scala:52)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:489)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

Error:  Test dotty.tools.dotc.ScalaJSCompilationTests.runScalaJS failed: java.lang.AssertionError: Run test failed, but should not, reasons:
Error:  encountered 1 test failure(s):
Error:    - generic failure (see test output), took 428.099 sec
Error:      at dotty.tools.vulpix.ParallelTesting$CompilationTest.checkPass(ParallelTesting.scala:1299)
Error:      at dotty.tools.vulpix.ParallelTesting$CompilationTest.checkRuns(ParallelTesting.scala:1259)
Error:      at dotty.tools.dotc.ScalaJSCompilationTests.runScalaJS(ScalaJSCompilationTests.scala:33)
Error:      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Error:      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:      at java.lang.reflect.Method.invoke(Method.java:569)
Error:      ...
[info] Test dotty.tools.dotc.ScalaJSCompilationTests.negScalaJS started

================================================================================
Test Report
================================================================================

1 suites passed, 1 failed, 2 total
    tests/run/i22888.scala failed


[info] Test run dotty.tools.dotc.ScalaJSCompilationTests finished: 1 failed, 0 ignored, 2 total, 431.226s
Error:  Failed: Total 2, Failed 1, Errors 0, Passed 1
Error:  Failed tests:
Error:  	dotty.tools.dotc.ScalaJSCompilationTests
Error:  (sjsCompilerTests / Test / test) sbt.TestsFailedException: Tests unsuccessful
Error:  Total time: 818 s (0:13:38.0), completed Apr 10, 2026, 2:30:22 AM
Error: Process completed with exit code 1.

```

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 1 above)
Comment (warcholjakub) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:4505]: Makes sense. To be sure I tested it, and it doesn't seem to affect the case I mentioned.

**Review by warcholjakub — APPROVED** [review]
LGTM

**Review by mbovel — APPROVED** [review]
This PR enhance error messages about extra parameters for multi-line method calls by also showing the extra arguments that are on separate lines in the error message.

For example, before we would show:

```
-- [E050] Type Error: tests/neg/19087.scala:13:22 ----------------------------------------------------------------------
13 |        foo(state.copy(x = 5): // Missing ")" // error: method copy in class State does not take more parameters
   |            ^^^^^^^^^^^^^^^^^
   |            method copy in class State does not take more parameters
   |
```

And after:

```
-- [E050] Type Error: tests/neg/19087.scala:13:22 ----------------------------------------------------------------------
13 |        foo(state.copy(x = 5): // Missing ")" // error: method copy in class State does not take more parameters
   |            ^
   |            method copy in class State does not take more parameters
   |
14 |          println("a")
   |
```

Note the new line `14 |          println("a")`.

It looks good to me!

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 1 above)
Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:4505]: I don't know what IDEs do with multiline squiggles, however. Also, one could not do this trick and also emit a rewrite suggestion.

**Comment by som-snytt** [comment]
I needed this today!

Random insertion of debug println ... what?
```
[error] 93 |              if method.isPrimaryConstructor then println(s"YES $method for $sym")
[error]    |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |           method println in object Predef does not take more parameters
```
Aha, but wait, didn't I just fix that?
```
➜  snips scala-cli compile --server=false -S 3.8.4-RC2 extra-parm.scala
-- [E050] Type Error: /home/amarki/snips/extra-parm.scala:3:22 -----------------
3 |  if true then println()
  |               ^^^^^^^^^
  |             method println in object Predef does not take more parameters
  |
  | longer explanation available when compiling with `-explain`
1 error found
Compilation failed
➜  snips scala-cli compile --server=false -S 3.nightly extra-parm.scala
-- [E050] Type Error: /home/amarki/snips/extra-parm.scala:3:22 -----------------
3 |  if true then println()
  |               ^
  |             method println in object Predef does not take more parameters
  |
4 |    (true || false)
  |
  | longer explanation available when compiling with `-explain`
1 error found
Compilation failed
```
