### PR TITLE
Handle Typeable

### LINKED ISSUE #22642: -Wunused against lila
## Compiler version

3.7.0-RC1-bin-SNAPSHOT

## Minimized code

```Scala
object Bus:

  type Payload            = Matchable
  type SubscriberFunction = PartialFunction[Payload, Unit]

  def pub[T <: Payload](payload: T)(using wc: WithChannel[T]) =
    publish(payload, wc.channel)

  def sub[T <: Payload: Typeable](f: PartialFunction[T, Unit])(using wc: WithChannel[T]) =
    subscribeFun(wc.channel):
      case x: T => f.applyOrElse(x, _ => ())
```

## Output (click arrow to expand)

<details>

```scala
[error] java.lang.IndexOutOfBoundsException: 1
[error]         at scala.collection.LinearSeqOps.apply(LinearSeq.scala:131)
[error]         at scala.collection.LinearSeqOps.apply$(LinearSeq.scala:128)
[error]         at scala.collection.immutable.List.apply(List.scala:79)
[error]         at dotty.tools.dotc.transform.CheckUnused.transformSelect(CheckUnused.scala:72)
[error]         at dotty.tools.dotc.transform.CheckUnused.transformSelect(CheckUnused.scala:67)
[error]         at dotty.tools.dotc.transform.MegaPhase.goSelect(MegaPhase.scala:636)
```
</details>

which is

```scala
  override def transformSelect(tree: Select)(using Context): tree.type =
    val name = tree.removeAttachment(OriginalName).getOrElse(nme.NO_NAME)
    if tree.span.isSynthetic && tree.symbol == defn.TypeTest_unapply then
      tree.qualifier.tpe.underlying.finalResultType match
      case AppliedType(_, args) => // tycon.typeSymbol == defn.TypeTestClass
        val res = args(1) // T in TypeTest[-S, T]
```

Maybe because of the alias. The code here assumes there are two type args.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #22642 

Turn code comments into actual code.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/Definitions.scala [hunk 1]
```diff
@@ -830,6 +830,8 @@ class Definitions {
 
   @tu lazy val ReflectSelectableTypeRef: TypeRef = requiredClassRef("scala.reflect.Selectable")
 
+  @tu lazy val TypeablePackageClass: Symbol = requiredPackage("scala.reflect.Typeable$package").moduleClass
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/core/Definitions.scala:833]: Do we need to keep a `TypeablePackageClass`?

**Review by noti0na1 — APPROVED** [review]
LGTM

File: compiler/src/dotty/tools/dotc/core/Definitions.scala (hunk 1 above)
Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/core/Definitions.scala]: We do not.
