### PR TITLE
fix(#19806): wrong tasty of scala module class reference

### LINKED ISSUE #19806: Fix Java TASTy of scala module class references
For some definitions
```scala
package p

object Module
```

```java
public class J {
  public p.Module$ module() {
    return p.Module$.MODULE$;
  }
}
```

When the tree for `J` reaches TASTy (using `-Yjava-tasty -Yjava-tasty-output foo.jar`), this looks like
```
    87:       DEFDEF(12) 16 [module]
    90:         EMPTYCLAUSE
    91:         SELECTtpt 17 [Module$]
    93:           SHAREDtype 3
    95:         ELIDED
    96:           TYPEREF 19 [Module[ModuleClass]]
    98:             SHAREDtype 3
   100:         STATIC
```
really, tree `91` should be `SELECTtpt 19 [Module[ModuleClass]]`.  This relies on the compiler (aka all TASTy clients) intrinsically knowing how to resolve `Module$` when the definition is actually `Module[ModuleClass]`

_Originally posted by @bishabosha in https://github.com/lampepfl/dotty/pull/19773#discussion_r1504640320_

### PR DESCRIPTION
**Pull request by i10416**
This commit makes the following diff to TASTy for i17255 files. The TASTy before this commit relied on the compiler (aka all TASTy clients) intrinsically knowing how to resolve Module$ when the definition is actually Module[ModuleClass].

```sh
scalac tests/run/i17255/J.java tests/run/i17255/Module.scala -Yprint-tasty -Yjava-tasty
```

```diff
    90:         EMPTYCLAUSE
    91:         TERMREF 17 [Module]
    93:           SHAREDtype 12
    95:         ELIDED
    96:           SHAREDtype 91
    98:         STATIC
    99:       DEFDEF(12) 18 [module]
   102:         EMPTYCLAUSE
-  103:         SELECTtpt 19 [Module$]
+  103:         SELECTtpt 19 [Module[ModuleClass]]
   105:           SHAREDtype 3
   107:         ELIDED
   108:           TYPEREF 17 [Module]
   110:             SHAREDtype 3
   112:         STATIC
```

fixes #19806

### CODE REVIEW

**Comment by i10416** [comment]
@bishabosha Could you review this change?

**Comment by bishabosha** [comment]
right, I will do that this week

**Comment by i10416** [comment]
Thank you.

**Comment by bishabosha** [comment]
turns out we should revert the remapping of class Module$ to object Module, it causes too many downstream problems, I will push the fix

**Comment by bishabosha** [comment]
> @bishabosha is there a way to add a test for this?

im guessing we can make a config option for TastyPrinter to elide absolute paths and use check file

**Comment by sjrd** [comment]
Pickling test for `tests/pos/i19806/J.tastycheck` is still failing, apparently.

**Comment by bishabosha** [comment]
im trying to elide the source names

**Comment by bishabosha** [comment]
@sjrd compilation tests passing now

File: compiler/src/dotty/tools/dotc/transform/Pickler.scala [hunk 1]
```diff
@@ -283,4 +303,35 @@ class Pickler extends Phase {
...
+    val expectLines = Using(Source.fromString(expect))(_.getLines().toList).get
+    Option.when(!matches(actualLines, expectLines))(actualLines)
+
+  private def matches(actual: String, expect: String): Boolean = {
+    import java.io.File
+    val actual1 = actual.stripLineEnd
+    val expect1  = expect.stripLineEnd
+
+    // handle check file path mismatch on windows
+    actual1 == expect1 || File.separatorChar == '\\' && actual1.replace('\\', '/') == expect1
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/Pickler.scala:330]: Is this still necessary? IIUC you elide paths entirely now.

**Review by sjrd — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/transform/Pickler.scala (hunk 1 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/Pickler.scala:330]: true, I could remove that

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/Pickler.scala:330]: I want to do another PR to warn about not adding the `-Ytest-pickler-check` flag in the presence of `.tastycheck` so it can be picked up there

**Comment by i10416** [comment]
@bishabosha My pleasure. Thank you for following up hard part.
