### PR TITLE
Don't point to the compiler backlog when a compiler plugin phase crashes

### LINKED ISSUE #21783: Don't point to the compiler backlog when a compiler plugin phase crashes
## Compiler version
3.6.1-RC1-bin-20241014-69ac5fb-NIGHTLY

## Description
Currently, when a compiler plugin phase crashes, we still point the user to the Scala compiler backlog.
For example, a crash with `stainless` produces output like this:
```scala
An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.

     while compiling: BugReport.scala
        during phase: stainless
                mode: Mode(ImplicitsEnabled)
     library version: version 2.13.14
    compiler version: version 3.5.0
            settings: -Wsafe-init true -classpath 
```
We should indicate to the user that they should raise the crash to the compiler plugin maintainers, rather than us.

## Context
This is a follow-up issue to:
- https://github.com/scala/scala3/issues/21758

## Expectation
I'd expect output similar to:
```scala
An unhandled exception was thrown in the compiler.
  Please file a crash report in the compiler plugin backlog.
  The name of the compiler plugin which caused the crash is "stainless".
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.

     while compiling: BugReport.scala
        during phase: stainless
                mode: Mode(ImplicitsEnabled)
     library version: version 2.13.14
    compiler version: version 3.5.0
            settings: -Wsafe-init true -classpath 
```

### PR DESCRIPTION
**Pull request by KacperFKorban**
closes #21783

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/report.scala [hunk 1]
```diff
@@ -165,13 +165,23 @@ object report:
...
+            |""".stripMargin
+      else
+        s"""|  Please file a crash report here:
+            |  https://github.com/scala/scala3/issues/new/choose
+            |  For non-enriched exceptions, compile with -Xno-enrich-error-messages.
+            |""".stripMargin
     s"""
        |  $errorMessage
        |
        |  An unhandled exception was thrown in the compiler.
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/report.scala:183]: Consider including this sentence in the conditional message. It could read "in the compiler plugin named ...".

File: compiler/src/dotty/tools/dotc/report.scala [hunk 2]
```diff
@@ -165,13 +165,23 @@ object report:
       "compiler version"   -> dotty.tools.dotc.config.Properties.versionString,
       "settings"           -> settings.map(showSetting).mkString(" "),
     ))
+    val fileAReportMsg =
+      if ctx.phase.isInstanceOf[plugins.PluginPhase]
+      then
+        s"""|  An unhandled exception was thrown in the compiler plugin named "${ctx.phase.megaPhase}".
+            |  Please file a crash report in the compiler plugin backlog.
```
Comment (SethTisue) [inline compiler/src/dotty/tools/dotc/report.scala:172]:
```suggestion
            |  Please report the issue to the plugin's maintainers.
```

Comment (SethTisue) [inline compiler/src/dotty/tools/dotc/report.scala:172]:
```suggestion
            |  Please report the issue to the plugin's maintainers.
```
