### PR TITLE
Fix incorrect warning on type ascription for backquoted identifiers

### LINKED ISSUE #22989: Incorrect warning on backticked typed pattern
## Compiler version

3.7

## Minimized code

Per pos/i15784.scala
```Scala
case `type` : Int => `type`
```
is not a stable identifier pattern. The variable id happens to be backquoted as required for a keyword.

## Output

```scala
8 |  case `type` : Int => `type`
  |              ^
  |Type ascriptions after patterns other than:
  |  * variable pattern, e.g. `case x: String =>`
  |  * number literal pattern, e.g. `case 10.5: Double =>`
  |are no longer supported. Remove the type ascription or move it to a separate variable pattern.
```

It looks like the screws were tightened during a round of syntax torquing. Apparently, the bit to the left of the colon was once taken as a pattern.

## Expectation

No warning about good syntax.

The corresponding test on Scala 2 is t8044.scala.

### PR DESCRIPTION
**Pull request by nox213**
closes #22989

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -3177,7 +3177,7 @@ object Parsers {
     def pattern1(location: Location = Location.InPattern): Tree =
       val p = pattern2(location)
       if in.isColon then
-        val isVariableOrNumber = isVarPattern(p) || p.isInstanceOf[Number]
+        val isVariableOrNumber = isVarPattern(p) || p.isInstanceOf[Number] || isBackquoted(p)
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala:3180]: Scala 2 honors the requirement even in backquoting.
```
scala> 42 match { case `Int`: Int => `Int` }
                            ^
       error: Pattern variables must start with a lower-case letter. (SLS 8.1.1.)
```

File: tests/pos/i22989.scala [hunk 2]
```diff
@@ -0,0 +1,3 @@
+//> using options -Xfatal-warnings
```
Comment (som-snytt) [inline tests/pos/i22989.scala:1]:
```suggestion
//> using options -Werror
```

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala (hunk 1 above)
Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala:3180]: Normal syntax for non-var: `42 match { case X @ (_: Int) => X }`

Maybe it's worth adding a neg test.

File: tests/pos/i15784.scala [hunk 3]
```diff
@@ -2,7 +2,4 @@ def i15784 = List(42) match
   case List(_, rest @ _*) => rest
   case List(_, Rest @ _*) => Rest
   case List(_, `Rest` @ _*) => Rest
-  case _ => ???
-
-def i15784_auxiliary = 42 match
-  case `type` : Int => `type`
+  case _ => ???
```
Comment (som-snytt) [inline tests/pos/i15784.scala:5]: You could quiet the other warnings and add the `-Werror` in the existing file. These directories get large.

By quiet, I'd suggest a def for each "rest" test. (and not just nowarn.)

**Review by som-snytt — CHANGES_REQUESTED** [review]
One note on how the feature should work, if it is a feature.

**Comment by nox213** [comment]
Thanks for the review!

File: tests/neg/i15784.scala [hunk 4]
```diff
@@ -1,4 +1,10 @@
...
   case List(_, Rest @ A) => Rest // error 
-  case _ => ???
\ No newline at end of file
+  case _ => ???
+
+def case2 = 42 match
+  case X: Int => X  // warn
+
+def case3 = 42 match
+  case `Int`: Int => `Int` // warn
```
Comment (som-snytt) [inline tests/neg/i15784.scala:10]: I don't think the test rig checks the `// warn` in a neg test, but of course it's verified by the check file. (I'm wondering if the test rig should do that, as an enhancement. I know a difference is that it's OK to have zero warns in a warn test but not OK to have zero errors in a neg test.)

**Review by som-snytt — APPROVED** [review]
Nice! I wouldn't have guessed `unsplice`.

File: tests/neg/i15784.scala (hunk 4 above)
Comment (nox213) [reply tests/neg/i15784.scala:10]: I see, would it be better if I make a separate `tests/warn/i15784.scala`?

**Comment by som-snytt** [comment]
As linked above, I got a bonus Scala 2 ticket out of it.
