### PR TITLE
 Minimal support for dependent case classes

### LINKED ISSUE #8073: Implement parameter dependent case classes
## minimized example

From #8069:
```Scala
trait A:
  type B

enum Test:
  case Test(a: A, b: a.B)   // error: Implementation restriction: case classes cannot have dependencies between parameters

case class Test2(a: A, b: a.B) // error: Implementation restriction: case classes cannot have dependencies 
 ```

It would be great if we could lift the implementation restriction and admit case classes (and enum cases) with parameter dependencies. 

To get there, we need a systematic study where we have to do the right substitutions. 

One immediate problem, which caused #8069 is that `fromProduct` does not work as given since it
casts to unsubstituted parameter types. E.g. for class `Test2`, fromProduct would contain code like this:
```scala
new C(
  x.productElement(0).asInstanceOf[A],
  x.productElement(1).asInstanceOf[a.B])
```
where the `a` in `a.B` is unbound. 

I suspect there will also be other problems with pattern matching, and maybe elsewhere. So it will require a focussed effort to get there. But the benefits (dependent ADTs) would be potentially very significant!

### PR DESCRIPTION
**Pull request by smarter**
This lets us write:

```scala
    trait A:
      type B

    case class CC(a: A, b: a.B)
```

Pattern matching works but isn't dependent yet:

```scala
    x match
      case CC(a, b) =>
        val a1: A = a
        // Dependent pattern matching is not currently supported
        // val b1: a1.B = b
        val b1 = b // Type is CC#a.B
```

(for my usecase this isn't a problem, I'm working on a type constraint API which lets me write things like `case class CC(a: Int, b: Int GreaterThan[a.type])`)

Because case class pattern matching relies on the product selectors `_N`, making it dependent is a bit tricky, currently we generate:

```scala
    case class CC(a: A, b: a.B):
      def _1: A = a
      def _2: a.B = b
```

So the type of `_2` is not obviously related to the type of `_1`, we probably need to change what we generate into:

```scala
    case class CC(a: A, b: a.B):
      @uncheckedStable def _1: a.type = a
      def _2: _1.B = b
```

But this can be done in a separate PR.

Fixes #8073.

### CODE REVIEW

**Comment by noti0na1** [comment]
I am doing some experiment with dependent pattern match in CC, and this PR is useful for me as well!

I modified the desuger so `_1`, `_2`, etc will have better types: always use singleton types when the field is not `var`. I haven't finished because I also need to modify the typer so the selections in the cases are binded to something.

**Comment by smarter** [comment]
@noti0na1 Awesome! Let me know how it goes.

**Comment by odersky** [comment]
I think it's probably better to wait after the cutoff with this?

**Comment by smarter** [comment]
So 3.6.1 rather than 3.6.0?

**Comment by odersky** [comment]
Yes, 3.6.1 should work OK.

**Review by odersky — APPROVED** [review]
AFAICS this only touches the fromProduct method. So it would be good to clarify some more what the limitations are. You mention dependent pattern matching. Ae there other things that don't work as one would expect?

But anyway this change in isolation LGTM

**Comment by sjrd** [comment]
Will we be able to ever fix the remaining things without breaking binary/TASTy compat in the future?

Currently we're safe because the definition does not compile. But if we make it compile today with incorrect code for some methods, we might be stuck with those incorrect definitions forever.

**Comment by smarter** [comment]
@noti0na1 I wanted to look into combining this with https://github.com/scala/scala3/pull/21828 to future-proof it, but I haven't had the time to do that yet.

**Comment by noti0na1** [comment]
> I wanted to look into combining this with #21828 to future-proof it

I don't have more progress on #21828 😢

There are still many things broken, and I'm also worry about binary compatibility.

**Comment by sjrd** [comment]
Core Meeting says let's go ahead with this as is.

@smarter Could you rebase on the latest `main` to get a recent CI run?

**Comment by odersky** [comment]
Looks like there is an bad interaction with @unroll which needs to be investigated.

**Comment by smarter** [comment]
Looks like the unroll phase assumes a specific shape for the fromProduct method: https://github.com/scala/scala3/blob/705e10ed55a256d205ce5120335fbfa78e3b6653/compiler/src/dotty/tools/dotc/transform/UnrollDefinitions.scala#L239

It already crashes if I define fromProduct manually with braces:
```scala
case class Foo(x: String, @unroll y: Int = 1)
object Foo:
  def fromProduct(x: Product): Foo = {
    new Foo(
      x.productElement(0).asInstanceOf[String],
      x.productElement(1).asInstanceOf[Int]
    )
  }
```

@bishabosha instead of transforming the body of fromProduct, couldn't we directly define the unroll-friendly version of fromProduct in SyntheticMembers ?

**Comment by bishabosha** [comment]
> instead of transforming the body of fromProduct, couldn't we directly define the unroll-friendly version of fromProduct in SyntheticMembers ?

It should work but probably worth checking that these are still generated after we detect unroll annotations on parameters (which updates the compilation unit flag)

But is the goal to still support when the user defines their own method or just 'not crash'?

File: compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala [hunk 1]
```diff
@@ -523,21 +523,47 @@ class SyntheticMembers(thisPhase: DenotTransformer) {
...
+   *  def fromProduct(x$0: Product): MirroredMonoType =
+   *    val arity = x$0.productArity
+   *    val a$1 = x$0.productElement(0).asInstanceOf[U]
+   *    val b$1 = x$0.productElement(1).asInstanceOf[a$1.Elem]
+   *    val c$1 = (
+   *      if arity > 2 then
+   *        x$0.productElement(2)
+   *      else
+   *        <default getter for the third parameter of C>
+   *    ).asInstanceOf[a$1.Elem]
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala:538]: `.asInstanceOf[Seq[String]]`

File: compiler/src/dotty/tools/dotc/transform/UnrollDefinitions.scala [hunk 2]
```diff
@@ -228,36 +228,6 @@ class UnrollDefinitions extends MacroTransform, IdentityDenotTransformer {
...
-          Underscore(defn.IntType),
-          EmptyTree,
-          defdef.rhs
-        )
-      )
-    ).setDefTree
-  }
-
   private enum Gen:
     case Substitute(origin: Symbol, newDef: DefDef)
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/transform/UnrollDefinitions.scala:232]: this should be dead code now i think

**Comment by smarter** [comment]
oops, I forgot the auto-merge was on, can you double-check the changes related to unroll @bishabosha ?
