### PR TITLE
Adjust error on bad enum

### LINKED ISSUE #22734: Incorrect position on "object creation impossible" error in enums
## Compiler version

`3.7.0-RC1-bin-20250304-bef520f-NIGHTLY` / `3.6.3`

## Minimized code

```Scala
enum Foo {
  case Empty
  case NonEmpty(item: String)

  def item: String
}

```

## Output

```scala
[error] ./Demo.scala:3:30
[error] object creation impossible, since def item: String in class Foo is not defined 
[error]   case NonEmpty(item: String)
[error]                              ^
```

## Expectation

```scala
[error] ./Demo.scala:2:7
[error] object creation impossible, since def item: String in class Foo is not defined 
[error]   case Empty
[error]        ^
```

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #22734

### CODE REVIEW

**Comment by som-snytt** [comment]
Not a cycle but maybe opaque means abstract. Anyway it should only check abstract term.

The other caution is that it's easier to let refchecks do the work. What enum syntax is legal? Every tweak to the test is an indentation problem. So it's easier to have confidence in the refcheck in the first commit, because the `def $new` signals that the anon class must be concrete.
```
-- Error: tests/run/option-extract.scala:2:5 ---------------------------------------------------------------------------
 2 |enum Option[+A]:
   |^
   |enum class Option has an abstract member and an unparameterized case
 3 |  case Some(x: A)
 4 |  case None
 5 |  opaque type ExtractResult[B] = (=> B) => B
 6 |  def extract[B](f: A => B): ExtractResult[B] =
 7 |    def result(default: => B): B = (this: Option[A]) match
 8 |      case None => default
 9 |      case Some(elem) => f(elem)
10 |    result
11 |  extension [B](er: ExtractResult[B])
12 |    def orElse(default: => B): B = er(default)
13 |end Option
```

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala [hunk 1]
```diff
@@ -945,16 +945,22 @@ trait ParallelTesting extends RunnerOrchestration { self =>
 
       Option {
         if actualErrors == 0 then s"\nNo errors found when compiling neg test $testSource"
-        else if expectedErrors == 0 then s"\nNo errors expected/defined in $testSource -- use // error or // nopos-error"
+        else if expectedErrors == 0 then
+          s"""|
+              |No errors expected/defined in $testSource -- use // error or // nopos-error"
+              |$showErrors
+              |""".stripMargin.trim.linesIterator.mkString("\n", "\n", "")
```
Comment (som-snytt) [inline compiler/test/dotty/tools/vulpix/ParallelTesting.scala:952]: This is the most important part of this PR.

**Comment by som-snytt** [comment]
Rebased.

**Comment by som-snytt** [comment]
Passes locally.
```
Test 'tests/run/i23245a' failed with output:                                    

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"

```

**Comment by som-snytt** [comment]
Dropped the check in `Checking`, where the idea was to error the enum if a case will error as abstract; the test was not correct and not worth the extra code. The message should be improved in refchecks instead.

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala (hunk 1 above)
Comment (som-snytt) [reply compiler/test/dotty/tools/vulpix/ParallelTesting.scala:963]: I just tweaked this in another PR. That is the most excruciating part of the back log, the constant collisions of patches.

File: compiler/test/dotty/Properties.scala [hunk 2]
```diff
@@ -26,7 +26,7 @@ object Properties {
     }
 
   /** Tests should run interactive? */
-  val testsInteractive: Boolean = propIsNullOrTrue("dotty.tests.interactive")
+  val testsInteractive: Boolean = false //propIsNullOrTrue("dotty.tests.interactive")
```
Comment (som-snytt) [inline compiler/test/dotty/Properties.scala]: Ha.

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala (hunk 1 above)
Comment (som-snytt) [reply compiler/test/dotty/tools/vulpix/ParallelTesting.scala:963]: OK I just dropped the commit, yay!

**Review by SolalPirelli — APPROVED** [review]
