### PR TITLE
Use untpd.Tree instead of tpd.Tree for SelectionRangeProvider

### LINKED ISSUE #22566: Selection range omits closing paren
## Compiler version

3.6.3

## Minimized code

Requesting selection ranges with cursor at `@@` below:

```Scala
object Main extends App {
  def x = 12 * (34 + 5@@6)
}
```

## Output

The selection ranges returned are:

  * `56` (good)
  * `34 + 56` (good)
  * `12 * (34 + 56` (not good)

## Expectation

The final selection range should be `12 * (34 + 56)` (with the closing paren).

----

Here's a patch to produce a test case for this.

```
diff --git a/presentation-compiler/test/dotty/tools/pc/tests/SelectionRangeSuite.scala b/presentation-compiler/test/dotty/tools/pc/tests/SelectionRangeSuite.scala
index e277a67c46..a600d3e4d7 100644
--- a/presentation-compiler/test/dotty/tools/pc/tests/SelectionRangeSuite.scala
+++ b/presentation-compiler/test/dotty/tools/pc/tests/SelectionRangeSuite.scala
@@ -147,3 +147,21 @@ class SelectionRangeSuite extends BaseSelectionRangeSuite:
            |}""".stripMargin
       )
     )
+
+  @Test def `arithmetic` =
+    check(
+      """|object Main extends App {
+         |  def x = 12 * (34 + 5@@6)
+         |}""".stripMargin,
+      List[String](
+        """|object Main extends App {
+           |  def x = 12 * (34 + >>region>>56<<region<<)
+           |}""".stripMargin,
+        """|object Main extends App {
+           |  def x = 12 * (>>region>>34 + 56<<region<<)
+           |}""".stripMargin,
+        """|object Main extends App {
+           |  def x = >>region>>12 * (34 + 56)<<region<<
+           |}""".stripMargin
+      )
+    )
```

Here's the output of running that test at time of reporting

```
sbt:scala3> scala3-presentation-compiler/testOnly dotty.tools.pc.tests.SelectionRangeSuite -- dotty.tools.pc.tests.SelectionRangeSuite.arithmetic
[info] Test run dotty.tools.pc.tests.SelectionRangeSuite started
[info] Test dotty.tools.pc.tests.SelectionRangeSuite.arithmetic started
[error] Test dotty.tools.pc.tests.SelectionRangeSuite.arithmetic failed: java.lang.AssertionError: 
[error]  (+++ Expected, --- Obtained, NO CHANGES)
[error] 
[error]   object Main extends App {
[error] +   def x = >>region>>12 * (34 + 56)<<region<<
[error] -   def x = >>region>>12 * (34 + 56<<region<<)
[error]   }
[error] 
[error] , took 0.286 sec
[info] Test run dotty.tools.pc.tests.SelectionRangeSuite finished: 1 failed, 0 ignored, 1 total, 0.289s
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error]         dotty.tools.pc.tests.SelectionRangeSuite
[error] (scala3-presentation-compiler / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 4 s, completed Feb 9, 2025, 3:48:22 PM
```

### PR DESCRIPTION
**Pull request by rochala**
Thanks to @NPCRUS @Yummy-Yums for taking a part in a spree. Sorry for taking that long to create a PR, but I was unavailable.

Fixes #22566

### CODE REVIEW

**Comment by rochala** [comment]
And this is PR that would fix this issue if we didn't migrate to untpd trees: #22703

File: presentation-compiler/src/main/dotty/tools/pc/SelectionRangeProvider.scala [hunk 1]
```diff
@@ -78,30 +82,38 @@ class SelectionRangeProvider(
...
     def toSelectionRange(srcPos: SourcePosition) =
       val selectionRange = new SelectionRange()
       selectionRange.setRange(srcPos.toLsp)
       selectionRange
 
     val treeSelectionRange = toSelectionRange(tree.sourcePos)
 
+    def getArgsSpan(args: List[Tree]): Option[SourcePosition] =
+      args match
+        case Seq(param) => Some(param.sourcePos)
```
Comment (kasiaMarek) [inline presentation-compiler/src/main/dotty/tools/pc/SelectionRangeProvider.scala:95]: Is this needed? Won't it repeat the same selection? Can you add a test with a single param?

**Comment by som-snytt** [comment]
"Apropos of nothing", this is an example where I don't know where to fetch from, because of `scala3` vs `dotty`.

```
git@github.com:rochala/dotty.git
```
It would be nice if github accommodated either specification (on cloned repos).

**Comment by som-snytt** [comment]
I don't have context for the previous comment `if we didn't migrate to untpd trees`, but I will learn about it soon, perhaps.

**Comment by rochala** [comment]
No, they are actually unrelated. 2 different bugfixes.

**Comment by NPCRUS** [comment]
ping

File: presentation-compiler/src/main/dotty/tools/pc/SelectionRangeProvider.scala (hunk 1 above)
Comment (tgodzik) [reply presentation-compiler/src/main/dotty/tools/pc/SelectionRangeProvider.scala:95]: @rochala do you need help finishing this one?

**Review by kasiaMarek — APPROVED** [review]
LGTM
