### PR TITLE
Only nullify tasty if `Ynullify-tasty` is set; Refine FlexibleType nullification rules

### LINKED ISSUE #23908: Crash with FlexibleTypes when nullifying classes with Higher-kinded Type Parameters
## Compiler version

3.7.3-RC2

This bug was found while porting community build to compile with `-Yexplicit-nulls` and minimized.

## Minimized code

```scala
package unsafe

class Foo[F[_]] {
  def accept[A](arg: F[A]): Nothing = ???
}
```
`scalac local/unsafe.scala -d local/out -classpath "local/out"`

```scala
import unsafe.*

val x: List[Map[String, Int]] = ???
val foo = Foo[List]()
val y = foo.accept[Any](x)
```
`scalac local/safe.scala -Yexplicit-nulls -d local/out -classpath "local/out"`

## Output

```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Should not flexify HKTypeLambda(List(A), List(TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any))), AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class immutable)),class List),List(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any))))

  exception occurred while typechecking local/safe.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.


     while compiling: local/safe.scala
        during phase: typer
                mode: Mode(ImplicitsEnabled,SafeNulls)
     library version: version 2.13.16
    compiler version: version 3.8.0-RC1-bin-SNAPSHOT-nonbootstrapped-git-f4df13e
            settings: -Yexplicit-nulls true 
```

## Expectation
The compiler should be able to handle Higher Kinded Types in when nullifying unsafe files

### LINKED ISSUE #23933: `-Yexplicit-nulls` breaks enums
Based on OpenCB failure in bishabosha/enhanced-string-interpolator - [builds logs](https://github.com/VirtusLab/community-build3/actions/runs/17687960136/job/50279371512)

## Compiler version

Last good release: 3.8.0-RC1-bin-20250822-658c8bd-NIGHTLY
First bad release: 3.8.0-RC1-bin-20250823-712d5bc-NIGHTLY (published with Scala 3.8 stdlib)

## Minimized code

```scala
//> using options -Yexplicit-nulls

enum FormatPattern:
  case AsInt
  case AsLong

```

## Output

```scala
     while compiling: /Users/wmazur/projects/scala/community-build3/test.scala
        during phase: typer
                mode: Mode(ImplicitsEnabled,SafeNulls)
     library version: version (unknown)
    compiler version: version 3.8.0-RC1-bin-20250823-712d5bc-NIGHTLY-git-712d5bc
            settings: -Yexplicit-nulls true -classpath /Users/wmazur/Library/Caches/Coursier/v1/https/repo.scala-lang.org/artifactory/maven-nightlies/org/scala-lang/scala3-library_3/3.8.0-RC1-bin-20250823-712d5bc-NIGHTLY/scala3-library_3-3.8.0-RC1-bin-20250823-712d5bc-NIGHTLY.jar:/Users/wmazur/Library/Caches/Coursier/v1/https/repo.scala-lang.org/artifactory/maven-nightlies/org/scala-lang/scala-library/3.8.0-RC1-bin-20250823-712d5bc-NIGHTLY/scala-library-3.8.0-RC1-bin-20250823-712d5bc-NIGHTLY.jar -d /Users/wmazur/projects/scala/community-build3/.scala-build/community-build3_073d723edf-9d23cdd7be/classes/main -sourceroot /Users/wmazur/projects/scala/community-build3

Exception in thread "main" scala.MatchError: AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class internal)),class Child),List(FlexibleType(OrType(TermRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),module class FormatPattern$)),val AsInt),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Null)),TermRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),module class FormatPattern$)),val AsInt)))) (of class dotty.tools.dotc.core.Types$CachedAppliedType)
        at dotty.tools.dotc.core.Annotations$Annotation$Child$.unapply(Annotations.scala:244)
        at dotty.tools.dotc.typer.Namer.insertInto$1(Namer.scala:496)
        at dotty.tools.dotc.typer.Namer.addChild(Namer.scala:507)
        at dotty.tools.dotc.typer.Namer$Completer.register$1(Namer.scala:982)
        at dotty.tools.dotc.typer.Namer$Completer.registerIfChildInCreationContext$$anonfun$2(Namer.scala:994)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:337)
        at dotty.tools.dotc.typer.Namer$Completer.registerIfChildInCreationContext(Namer.scala:994)
        at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:875)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:175)
        at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:190)
        at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:192)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:403)
        at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:3622)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3647)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3762)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3840)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3845)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3867)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3913)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:3332)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:3663)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3667)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3762)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3840)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3845)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3867)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3913)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:3465)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3709)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3763)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3840)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3845)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3956)
        at dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:47)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:510)
        at dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:53)
        at dotty.tools.dotc.typer.TyperPhase.$anonfun$4(TyperPhase.scala:99)
        at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:494)
        at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:598)
        at scala.collection.immutable.List.prependedAll(List.scala:155)
        at scala.collection.immutable.List$.from(List.scala:691)
        at scala.collection.immutable.List$.from(List.scala:691)
        at scala.collection.IterableOps$WithFilter.map(Iterable.scala:911)
        at dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:98)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:380)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1327)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:373)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$2(Run.scala:420)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$adapted$1(Run.scala:420)
        at scala.Function0.apply$mcV$sp(Function0.scala:45)
        at dotty.tools.dotc.Run.showProgress(Run.scala:482)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:420)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:432)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:432)
        at dotty.tools.dotc.Run.compileSources(Run.scala:319)
        at dotty.tools.dotc.Run.compile(Run.scala:304)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
        at dotty.tools.dotc.Driver.process(Driver.scala:201)
        at dotty.tools.dotc.Driver.process(Driver.scala:169)
        at dotty.tools.dotc.Driver.process(Driver.scala:181)
        at dotty.tools.dotc.Driver.main(Driver.scala:211)
        at dotty.tools.dotc.Main.main(Main.scala)
Compilation failed
```

### PR DESCRIPTION
**Pull request by noti0na1**
Given the nightly results, we think the nullification rules still need some polish and is not ready for all compiled Scala code. Hence, we only nullify tasty if `Ynullify-tasty` is set now.

Based on #23911

Fixes #23908

Could fix #23933, #23935, #23936, and #23937 (I tested locally due the explicit nulls tests disabled temprarily)

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala [hunk 1]
```diff
@@ -29,142 +35,167 @@ import dotty.tools.dotc.core.Decorators.i
...
-        nullify(mapOver(tp))
-      case _ => tp
-    }
-  }
-}
\ No newline at end of file
+        val savedSkipCurrentLevel = skipCurrentLevel
+
+        // Nullify parent at outer level; not refined members
+        skipCurrentLevel = true
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala]: The comment contradicts the code here: comment suggests outer level is **nullified**, code suggests outer level is **skipped**.

File: compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala [hunk 2]
```diff
@@ -29,142 +35,167 @@ import dotty.tools.dotc.core.Decorators.i
...
+        val parent2 = this(tp.parent)
+
+        skipCurrentLevel = false
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala:199]: If I understood the intent of the comment correctly, this was intended to be true.

File: compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala (hunk 1 above)
Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala]: The comment here is wrong, we probably don't want nullify the neither parent nor the whole type, since we don't know how the parent looks like?

File: compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala (hunk 2 above)
Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala:199]: I think the refined fields can be nullified normally.

File: compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala (hunk 1 above)
Comment (olhotak) [reply compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala]: We could be conservative and not nullify refined types at all, and then see whether any specific cases come up in the open community build.

Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala]: Or we nullify the parent first, and move the flexible type to the outer level?

File: compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala [hunk 3]
```diff
@@ -29,142 +35,187 @@ import dotty.tools.dotc.core.Decorators.i
...
+        skipCurrentLevel = savedSkipCurrentLevel
+        skipResultType = savedSkipResultType
+
+        parent2 match
+          case FlexibleType(_, parent2a) if ctx.flexibleTypes =>
+            FlexibleType(derivedRefinedType(tp, parent2a, refinedInfo2))
+          case OrNull(parent2a) =>
+            OrNull(derivedRefinedType(tp, parent2a, refinedInfo2))
+          case _ =>
+            derivedRefinedType(tp, parent2, refinedInfo2)
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala:212]: Would you prefer this approach?  @olhotak

**Comment by noti0na1** [comment]
I have run the compilation tests locally. The tests below fail because of the current awkward stage of stdlib.

```
tests/explicit-nulls/pos/flow-predef-eq.scala
tests/explicit-nulls/pos/eq-ne.scala
tests/explicit-nulls/warn/expose-flexible-types.scala
```

File: compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala (hunk 3 above)
Comment (olhotak) [reply compiler/src/dotty/tools/dotc/core/ImplicitNullInterop.scala:212]: We can try it.

I'm a bit nervous about flexifying the parent type and then undoing that (what if it was previously flexified already?), but we can try it.

A simpler approach would be to always flexify the refined type at the top level but then to not flexify the parent type. That may unnecessarily flexify a refined type in cases when the parent is one of the types that we don't flexify (such as a primitive type), but it seems unlikely that people would want to refine such types.

I think it doesn't make sense to flexify the parent type because it doesn't make sense to refine null. You wouldn't say `(Foo|null) { def bar(): Int }`. Instead, you could say `(Foo { def bar(): Int }) | Null`.

**Comment by WojciechMazur** [comment]
It seems to be fixing 13 projects in the OpenCB, however some of reported projects are now failing with different errors requring wrong number of arguments - I have not seen errors like that before. 
All of the following projects were previously affected by FlexibleTypes match errors, there might be more but I have not yet manged to analyze their results. 

- broij/zarrow - https://github.com/VirtusLab/community-build3/actions/runs/17803202877/job/50609223216#step:3:886: 
```scala
Error:  166 |          check(genTuple(Gen.int, Gen.int.filter(_ != 0))) { (num, div) =>
Error:      |                                                             ^
Error:      |                               Wrong number of parameters, expected: 1
Error:  167 |            val eff = zArrow(num).provide(ZLayer.succeed(div))
Error:  168 |            assertZIO(eff)(equalTo(num / div))
Error:      |
```
-  earogov/ordset - https://github.com/VirtusLab/community-build3/actions/runs/17803202877/job/50609223575#step:3:3881 
```scala
Error:  -- [E086] Syntax Error: /build/repo/ordset/src/ordset/util/ShowUtil.scala:62:67 
Error:  62 |        val indentedLines = lines.zipWithIndex.map { (line, index) => 
Error:     |                                                     ^
Error:     |                                 Wrong number of parameters, expected: 1
Error:  63 |          if (index == 0) line else fieldIndent + line
Error:     |
Error:     | longer explanation available when compiling with `-explain`
```
- evolution-gaming/derivation -  https://github.com/VirtusLab/community-build3/actions/runs/17803202578/job/50609227175
- facsimile/facsimile - https://github.com/VirtusLab/community-build3/actions/runs/17803202578/job/50609227214#step:3:1482 
```scala
Error:  -- [E046] Cyclic Error: /build/repo/facsimile-util/src/test/scala/org/facsim/util/test/MemoizeTest.scala:224:17 
Error:  224 |          forAll { (il: List[Int]) =>
Error:      |                 ^
Error:      |                 Cyclic reference involving trait BitSet
Error:      |
Error:      |                  Run with -explain-cyclic for more details.
Error:      |
```
- guidoschmidt17/zio-pgcopy - https://github.com/VirtusLab/community-build3/actions/runs/17803202877/job/50609226092#step:3:963

- japgolly/univeq - https://github.com/VirtusLab/community-build3/actions/runs/17803202578/job/50609227793#step:3:869 
Previously affected by `should not flixy HKTypeLambda` assertion, now: 
```scala
Error:  -- [E007] Type Mismatch Error: /build/repo/univeq/shared/src/main/scala-3/japgolly/univeq/internal/Derivation.scala:78:61 
Error:  78 |                log("  - Checking: " + Type.show(using fUnit.asType))
Error:     |                                                       ^^^^^^^^^^^^
Error:     |               Found:    (scala.quoted.Type[? <: AnyKind])?
Error:     |               Required: scala.quoted.Type[T]
Error:     |
Error:     |               where:    T is a type variable with constraint <: AnyKind
Error:     |
Error:     | longer explanation available when compiling with `-explain`
```

**Comment by olhotak** [comment]
I would guess that the errors about wrong number of arguments are due to some failure of auto-tupling probably getting confused by flexible types.

File: compiler/src/dotty/tools/dotc/config/ScalaSettings.scala [hunk 4]
```diff
@@ -455,6 +455,7 @@ private sealed trait YSettings:
   val YnoKindPolymorphism: Setting[Boolean] = BooleanSetting(ForkSetting, "Yno-kind-polymorphism", "Disable kind polymorphism. (This flag has no effect)", deprecation = Deprecation.removed())
   val YexplicitNulls: Setting[Boolean] = BooleanSetting(ForkSetting, "Yexplicit-nulls", "Make reference types non-nullable. Nullable types can be expressed with unions: e.g. String|Null.")
   val YnoFlexibleTypes: Setting[Boolean] = BooleanSetting(ForkSetting, "Yno-flexible-types", "Disable turning nullable Java return types and parameter types into flexible types, which behave like abstract types with a nullable lower bound and non-nullable upper bound.")
+  val YnullifyTasty: Setting[Boolean] = BooleanSetting(ForkSetting, "Ynullify-tasty", "Apply nullification to Scala code compiled without -Yexplicit-nulls, when reading from tasty.")
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/config/ScalaSettings.scala]: Consider `Yflexify-tasty`.

**Comment by noti0na1** [comment]
I will merge this after the CI passes.
