### PR TITLE
Fix #21619: Refactor NotNullInfo to record every reference which is retracted once.

### LINKED ISSUE #21619: -Yexplicit-nulls exhibits false negative when combining try/match
## Compiler version

3.6.0-RC1-bin-SNAPSHOT-git-e9d4831

## Minimized code

Related to #21380 

```Scala
@main def test(): Unit = {
  var x: String | Null = null
  x = ""
  var i: Int = 1
  try {
    i match {
      case _ => {
        x = null
        throw new Exception()
      }
    }
    x = ""
  }
  catch {
    case (e: Exception) => {}
  }
  x.replace("", "")
}
```

## Output

Compiling the program with `-Yexplicit-nulls` results in the following error at runtime

```scala
java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "x" is null
	at test$package$.test(test.scala:17)
	at test.main(test.scala:1)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at dotty.tools.runner.RichClassLoader$.run$extension$$anonfun$1(ScalaClassLoader.scala:36)
	at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
	at dotty.tools.runner.RichClassLoader$.dotty$tools$runner$RichClassLoader$$$asContext$extension(ScalaClassLoader.scala:18)
	at dotty.tools.runner.RichClassLoader$.run$extension(ScalaClassLoader.scala:36)
	at dotty.tools.runner.CommonRunner.run(ObjectRunner.scala:23)
	at dotty.tools.runner.CommonRunner.run$(ObjectRunner.scala:13)
	at dotty.tools.runner.ObjectRunner$.run(ObjectRunner.scala:48)
	at dotty.tools.runner.CommonRunner.runAndCatch(ObjectRunner.scala:30)
	at dotty.tools.runner.CommonRunner.runAndCatch$(ObjectRunner.scala:13)
	at dotty.tools.runner.ObjectRunner$.runAndCatch(ObjectRunner.scala:48)
	at dotty.tools.MainGenericRunner$.run$1(MainGenericRunner.scala:215)
	at dotty.tools.MainGenericRunner$.process(MainGenericRunner.scala:270)
	at dotty.tools.MainGenericRunner$.main(MainGenericRunner.scala:281)
	at dotty.tools.MainGenericRunner.main(MainGenericRunner.scala)
```

## Expectation

The program should have been rejected.

### PR DESCRIPTION
**Pull request by noti0na1**
This PR improves the flow typing for returning and exceptions.

The `NotNullInfo` is defined as following now:

```scala
case class NotNullInfo(asserted: Set[TermRef] | Null, retracted: Set[TermRef]):
```

* `retracted` contains variable references that are ever assigned to null;
* if `asserted` is not `null`, it contains `val` or `var` references that are known to be not null, after the tree finishes executing normally (non-exceptionally);
* if `asserted` is `null`, the tree is know to terminate, by throwing, returning, or calling a function with `Nothing` type. Hence, it acts like a universal set.

`alt` is defined as `<a1,r1>.alt(<a2,r2>) = <a1 intersect a2, r1 union r2>`.

The difficult part is the `try ... catch ... finally ...`. We don't know at which point an exception is thrown in the body, and the catch cases may be not exhaustive, we have to collect any reference that is once retracted.

Fix #21619

### CODE REVIEW

**Comment by olhotak** [comment]
I think this is the right idea but reasoning about three sets is hard and it's hard to convince oneself that the implementation is correct for all cases.

I wonder if a simpler implementation would be possible with only two sets. Let's still call them asserted and retracted. We lift the invariant that asserted & retracted is empty, so it's possible for one variable to be in both. asserted is the set that we know is non-null at the very end of evaluating the expression (if no exception happens). retracted is the set that is retracted anywhere within the expression, even if it is later asserted. When we assert a variable, we add it to asserted but do not remove it from retracted. When we retract a variable, we add it to retracted and remove it from asserted. If we evaluate the expression to the very end, if a variable is in both asserted and retracted, we consider it asserted. When we're at a control flow point where the expression may not have executed to the end (because it threw an exception), we just clear the asserted set and keep only the retracted set. At control flow merges, we intersect asserted and union retracted. For a sequential composition (a1,r1) ; (a2,r2), we get ((a1-r2) | a2, r1|r2).

Do you think this would work or do you see any flaw in it?

I think maybe what I've described above are the current sets asserted and onceRetracted in this pull request. I guess the question is, if we have asserted and onceRetracted, can we get rid of retracted? (Then eventually we could rename onceRetracted to just retracted, to make the name shorter and simpler.)

**Comment by olhotak** [comment]
In the above proposal:
- retracted means that the variable is set to null somewhere, anywhere in the expression
- asserted means that the variable is set to non-null after all program points that could set it to null (if any)

**Comment by noti0na1** [comment]
> * retracted means that the variable is set to null somewhere, anywhere in the expression
> * asserted means that the variable is set to non-null after all program points that could set it to null (if any)

This rule looks reasonable to me. I will think about more examples to double-check this.

**Comment by noti0na1** [comment]
TODO: some other improvements I want for flow typing but haven't been implemented yet:
* For definition like `var a: String | Null = ""`, we should add `a` to asserted info.
* We only considered `Nothing` body for `if` right now.  We should consider this for other control expressions as well.

File: compiler/src/dotty/tools/dotc/typer/Nullables.scala [hunk 1]
```diff
@@ -67,15 +65,18 @@ object Nullables:
...
+        this.asserted.diff(that.retracted).union(that.asserted),
+        this.retracted.union(that.retracted))
 
     /** The alternative path combination with another not-null info. Used to merge
      *  the nullability info of the two branches of an if.
      */
     def alt(that: NotNullInfo): NotNullInfo =
       NotNullInfo(this.asserted.intersect(that.asserted), this.retracted.union(that.retracted))
 
+    def withRetracted(that: NotNullInfo): NotNullInfo =
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/typer/Nullables.scala:77]: Here it would be useful to have a comment explaining when this function is intended to be used. The name explains what the function does, but the idea is to say why one would want to do that. (Compare with the `alt` function, whose name says when you want it.) It looks like the use case is similar to `alt`, but in a case when one branch is known to not complete execution normally (e.g. an infinite loop), only exceptionally. We can say that in the comment and/or consider incorporating that into the name somehow.

This also raises the question of what to do when both alternatives cannot complete normally. Theoretically one would want to `assert` all variables, but we don't have a way to do that in the implementation. Perhaps that case is not common enough in practice to care about.

File: compiler/src/dotty/tools/dotc/typer/Nullables.scala [hunk 2]
```diff
@@ -52,12 +52,10 @@ object Nullables:
     val hiTree = if(hiTpe eq hi.typeOpt) hi else TypeTree(hiTpe)
     TypeBoundsTree(lo, hiTree, alias)
 
-  /** A set of val or var references that are known to be not null, plus a set of
-   *  variable references that are not known (anymore) to be not null
+  /** A set of val or var references that are known to be not null,
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/typer/Nullables.scala:55]:
```suggestion
  /** A set of val or var references that are known to be not null
  * after the tree finishes executing normally (non-exceptionally),
```

File: compiler/src/dotty/tools/dotc/typer/Nullables.scala [hunk 3]
```diff
@@ -52,12 +52,10 @@ object Nullables:
...
+   *  plus a set of variable references that are once assigned to null.
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/typer/Nullables.scala:56]:
```suggestion
   *  plus a set of variable references that are ever assigned to null,
   *  and may therefore be null if execution of the tree is interrupted
   *  by an exception.
```

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 4]
```diff
@@ -2132,20 +2134,28 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
   }
 
+  private def notNullInfoFromCases(initInfo: NotNullInfo, cases: List[CaseDef])(using Context): NotNullInfo =
+    var nnInfo = initInfo
+    if cases.nonEmpty then
+      val (nothingCases, normalCases) = cases.partition(_.body.tpe.isNothingType)
+      nnInfo = nothingCases.foldLeft(nnInfo):
+        (nni, c) => nni.withRetracted(c.notNullInfo)
+      if normalCases.nonEmpty then
+        nnInfo = nnInfo.seq(normalCases.map(_.notNullInfo).reduce(_.alt(_)))
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:2156]: This seems an abuse of `seq`, since there is no sequencing with the `nothingCases`; conceptually it is `alt`.

A conceptually cleaner approach would be to handle the `normalCases` first, then apply the `withRetracted` for the `nothingCases` to the result of the `normalCases`.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 5]
```diff
@@ -2337,18 +2348,26 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
     val cases2 = cases2x.asInstanceOf[List[CaseDef]]
 
-    var nni = expr2.notNullInfo.retractedInfo
-    if cases2.nonEmpty then nni = nni.seq(cases2.map(_.notNullInfo.retractedInfo).reduce(_.alt(_)))
-    val finalizer1 = typed(tree.finalizer, defn.UnitType)(using ctx.addNotNullInfo(nni))
-    nni = nni.seq(finalizer1.notNullInfo)
-    assignType(cpy.Try(tree)(expr2, cases2, finalizer1), expr2, cases2).withNotNullInfo(nni)
-  }
+    // It is possible to have non-exhaustive cases, and some exceptions are thrown and not caught.
+    // Therefore, the code in the finallizer and after the try block can only rely on the retracted
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:2363]:
```suggestion
    // Therefore, the code in the finalizer and after the try block can only rely on the retracted
```

File: tests/explicit-nulls/neg/i21380c.scala [hunk 6]
```diff
@@ -32,9 +32,9 @@ def test4: Int =
     case npe: NullPointerException => x = ""
     case _ => x = ""
   x.length // error
-  // Although the catch block here is exhaustive,
-  // it is possible that the exception is thrown and not caught.
-  // Therefore, the code after the try block can only rely on the retracted info.
+  // Although the catch block here is exhaustive, it is possible to have non-exhaustive cases,
+  // and some exceptions are thrown and not caught. Therefore, the code in the finallizer and
```
Comment (olhotak) [inline tests/explicit-nulls/neg/i21380c.scala:36]:
```suggestion
  // and some exceptions are thrown and not caught. Therefore, the code in the finalizer and
```

File: compiler/src/dotty/tools/dotc/typer/Nullables.scala (hunk 1 above)
Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/typer/Nullables.scala:80]: I don't understand why we want to `assert` all variables if none of the alternatives complete normally?  Do you have an example?

Comment (olhotak) [reply compiler/src/dotty/tools/dotc/typer/Nullables.scala:80]: In general the analysis proves the following condition: in every execution trace leading to a given program point $p$, variable `x` is not null. When the code before $p$ does not terminate, there are no traces leading to $p$ so the condition is true for every variable. If there were an instruction derefencing `x` at $p$, that instruction would never execute, so it would be safe to assume that `x` is not null.

The specific case of `withRetracted` handles something like `alt`, but where the `that` branch does not complete normally. It is defined as `<a1,r1>.withRetracted(<a2,r2>) = <a1, r1 union r2>`.  `alt` is defined as `<a1,r1>.alt(<a2,r2>) = <a1 intersect a2, r1 union r2>`. If we could represent the universal set in `a2`, then `a1 intersect a2` would be `a1`, so we could implement the equivalent of `withRetracted` using `alt`.

I don't know whether actual use cases in practice justify the code complexity of adding a representation of the universal set to the implementation, but it is cleaner in theory.

If we don't do that, then the comment/name of `withRetracted` should suggest that it is like `alt`, but for the case where `that` cannot complete normally.

**Comment by olhotak** [comment]
OK, I don't think an `Info` with an `asserted` set that acts like a universal set is necessary.

File: compiler/src/dotty/tools/dotc/typer/Nullables.scala [hunk 7]
```diff
@@ -515,7 +548,10 @@ object Nullables:
       && assignmentSpans.getOrElse(sym.span.start, Nil).exists(whileSpan.contains(_))
       && ctx.notNullInfos.impliesNotNull(ref)
 
-    val retractedVars = ctx.notNullInfos.flatMap(_.asserted.filter(isRetracted)).toSet
+    val retractedVars = ctx.notNullInfos.flatMap(info =>
+      if info.asserted == null then Set.empty
+      else info.asserted.filter(isRetracted)
+    ).toSet
     ctx.addNotNullInfo(NotNullInfo(Set(), retractedVars))
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/typer/Nullables.scala:555]: Here we lose knowledge about the loop being unreachable. The result always has `asserted == Set()`, even if it was `null` before.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 8]
```diff
@@ -2139,20 +2134,23 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
       .asInstanceOf[List[CaseDef]]
-    var nni = sel.notNullInfo
-    if cases1.nonEmpty then nni = nni.seq(cases1.map(_.notNullInfo).reduce(_.alt(_)))
-    assignType(cpy.Match(tree)(sel, cases1), sel, cases1).withNotNullInfo(nni)
+    assignType(cpy.Match(tree)(sel, cases1), sel, cases1)
+      .withNotNullInfo(notNullInfoFromCases(sel.notNullInfo, cases1))
   }
 
+  private def notNullInfoFromCases(initInfo: NotNullInfo, cases: List[CaseDef])(using Context): NotNullInfo =
+    if cases.nonEmpty then
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:2150]: In what instances would the cases be empty? Depending on the answer, perhaps a comment would be useful.

**Review by olhotak — APPROVED** [review]
Otherwise LGTM.

File: compiler/src/dotty/tools/dotc/typer/Nullables.scala (hunk 7 above)
Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/typer/Nullables.scala:555]: I think this is fine for the NotNullInfo in the `ctx`. Suppose there is a terminated info in the `ctx`, adding a new non-terminated info will not change its behaviour: still treating all symbols as non-nullable.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 8 above)
Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:2150]: A `try` node can have empty cache cases.

Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:2150]: I don't think the cases can be empty. Just want to avoid the exception when calling `reduce` on empty list.

Comment (olhotak) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: OK. A question is, if empty cases does happen, what does it mean in terms of runtime semantics? If it definitely fails to match, it would be more precise to return `terminatedInfo`, but `initInfo` is sound and safer in case empty cases means something different in some special situations.

I think it's fine to leave it as it is, and you can merge this PR now.
