### PR TITLE
Check exhaustivity of any case class

### LINKED ISSUE #22590: failed to produce a warning about inexhaustive pattern
## Compiler version

3.6.3

## Minimized code

```Scala
sealed trait T_A
case class CC_B[T](a: T) extends T_A

@main def test() = {
  val v_a: CC_B[Int] = CC_B(10)
  val v_b: Int = v_a match{
    case CC_B(12) => 0 
  }
}
```

## Output

The compiler does not produce any warning during compilation. However, there's a `MatchError` at runtime

```
Exception in thread "main" scala.MatchError: CC_B(10) (of class CC_B)
        at test$package$.test(test.scala:7)
        at test.main(test.scala:4)

```

## Expectation

A compile-time warning that the pattern is not exhaustive.

Notably, in the following scenario (where there are two parameters in `CC_B`), the compiler warns about the inexhaustive pattern as expected:

```scala
sealed trait T_B
case class CC_A() extends T_B
case class CC_C() extends T_B

sealed trait T_A
case class CC_B[B](a: B,b:T_B) extends T_A


@main def test() = {
  val v_a: CC_B[Int] = null
  val v_b: Int = v_a match {
    case CC_B(12, CC_A()) => 0 
    case CC_B(_, CC_C()) => 0 
  }
}
```

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #22590

### CODE REVIEW

File: tests/warn/t10373.scala [hunk 1]
```diff
@@ -1,4 +1,4 @@
-//> using options -Xfatal-warnings -deprecation -feature
+//> using options -deprecation -feature
 
 abstract class Foo {
   def bar(): Unit = this match {
```
Comment (noti0na1) [inline tests/warn/t10373.scala:4]: Why doesn't `bar` also get a non-exhaustive warning as the `baz` below?

**Review by noti0na1 — CHANGES_REQUESTED** [review]

File: tests/warn/t10373.scala (hunk 1 above)
Comment (noti0na1) [reply tests/warn/t10373.scala:4]: I agree we shouldn't check exhaustivity for `Foo`. In this sense, the selector type is not sealed, then matching any subtype of it would be considered as "(maybe) covering the whole space". 

Therefore, the tuple arguments should also cover the whole space. `Tuple2` is sealed only means the tuple itself need to be covered, and the content should not be affected, so we should not check exhaustivity for the tuple arguments here as well.

Comment (noti0na1) [reply tests/warn/t10373.scala:4]: Yes, because the two matching do look identical to me.

Comment (dwijnand) [reply tests/warn/t10373.scala:4]: I hesitate to do that, as I fear it would be classified a "regression" that we're no longer warning there.  I understand the position the dilemma, though.
