### PR TITLE
Fix inline reduction for CaseDef guards with asInstanceOf

### LINKED ISSUE #22300: Cannot recude inline match if pattern condition is `private`
## Compiler version

3.5.2

## Minimized code

```Scala
class Foo:

  inline def inlineMatch[T]: String =
    inline compiletime.erasedValue[T] match
      case _: EmptyTuple               => ""
      case _: (h *: _) if checkType[h] => ""

  private inline def checkType[T]: Boolean =
    inline compiletime.erasedValue[T] match
      case _: Int => true
      case _      => false

val foo = Foo()

foo.inlineMatch[(Int, Boolean)] // Error
```

## Output

```scala
[error]    |cannot reduce inline match with
[error]    | scrutinee:  compiletime.package$package.erasedValue[(Int, Boolean)] : (Int, Boolean)
[error]    | patterns :  case _:EmptyTuple
[error]    |             case _:*:[h @ _, _ @  >: Nothing <: Any] if Foo_this.asInstanceOf[Foo].checkType[h]
```

## Expectation

If this is indeed not supposed to work, I would expect a clearer error message.

### PR DESCRIPTION
**Pull request by jchyb**
Fixes #22300
In [Inliner.scala](https://github.com/scala/scala3/blob/1f0c576ce6d80138309dbba2e9972ee566ceac11/compiler/src/dotty/tools/dotc/inlines/Inliner.scala#L603) we add asInstanceOf to references to private inline methods to make sure we later are able to know which method is referenced (if e.g. we inline out of the scope where that method would be visible). This added asInstanceOf caused issue when inlining CaseDef guards, as instead of a simple constant literal we get an Inlined node with an added binding, like this:
```scala
{
  val A_this: A = A_this.asInstanceOf[A]
  true:Boolean
}
```
We fix that by just unpacking that Inlined node (and we do not need that binding for constant literals, so we can just ignore it).

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/inlines/InlineReducer.scala [hunk 1]
```diff
@@ -364,6 +364,7 @@ class InlineReducer(inliner: Inliner)(using Context):
           if cdef.guard.isEmpty then (true, true)
           else typer.typed(cdef.guard.subst(from, to), defn.BooleanType) match {
             case ConstantValue(v: Boolean) => (v, true)
+            case Inlined(_, _, ConstantValue(v: Boolean)) => (v, true)
```
Comment (dwijnand) [inline compiler/src/dotty/tools/dotc/inlines/InlineReducer.scala:367]:
```suggestion
          else stripInlined(typer.typed(cdef.guard.subst(from, to), defn.BooleanType)) match {
            case ConstantValue(v: Boolean) => (v, true)
```

**Review by dwijnand — COMMENTED** [review]
Alternatively

**Review by dwijnand — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/inlines/InlineReducer.scala (hunk 1 above)
Comment (jchyb) [reply compiler/src/dotty/tools/dotc/inlines/InlineReducer.scala]: Good point, thank you!
