### PR TITLE
Under `betterFors` don't drop the trailing `map` if it would result in a different type (also drop `_ => ()`)

### LINKED ISSUE #21804: betterFors trailing `map` elimination can change the resulting type
## Compiler version

`3.6.1-RC1-bin-20241017-59b67fc-NIGHTLY`

## Minimized code

```scala
//>  using scala 3.nightly

import scala.language.experimental.betterFors

case class Container[A](val value: A) {
  def map[B](f: A => B): Container[B] = Container(f(value))
}

sealed trait Animal
case class Dog() extends Animal

def opOnDog(dog: Container[Dog]): Container[Animal] =
  for
    v <- dog
  yield v
```

## Output

```scala
-- [E007] Type Mismatch Error: /home/kpi/bugs/better-fors-bug.scala:13:2 -------
13 |  for
   |  ^
   |  Found:    (dog : Container[Dog])
   |  Required: Container[Animal]
14 |    v <- dog
15 |  yield v
   |
   | longer explanation available when compiling with `-explain`
```

without `betterFors` enabled, this code compiles successfully.

## Expectation

The type of the `for`-comprehension should not be changed after enabling the `betterFors` language extension.

### PR DESCRIPTION
**Pull request by KacperFKorban**
closes #21804

### CODE REVIEW

File: tests/run/better-fors-map-elim.scala [hunk 1]
```diff
@@ -0,0 +1,59 @@
+// scalajs: --skip
```
[the remark this answers is not in the document]
Comment (KacperFKorban) [reply tests/run/better-fors-map-elim.scala]: Ok, will do that. Thanks.

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala [hunk 2]
```diff
@@ -2149,11 +2148,13 @@ object desugar {
...
         case Nil if betterForsEnabled => body
         case (gen: GenFrom) :: Nil =>
+          val aply = Apply(rhsSelect(gen, mapName), makeLambda(gen, body))
           if betterForsEnabled
-            && gen.checkMode != GenCheckMode.Filtered // results of withFilter have the wrong type
-            && deepEquals(gen.pat, body)
-          then gen.expr  // avoid a redundant map with identity
-          else Apply(rhsSelect(gen, mapName), makeLambda(gen, body))
+          && gen.checkMode != GenCheckMode.Filtered // results of withFilter have the wrong type
+          && (deepEquals(gen.pat, body) || deepEquals(body, Tuple(Nil)))
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/ast/Desugar.scala:2154]: Might factor out the next three lines and use in a method like `markTrailingMap(gen, body)`.

**Review by odersky — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala [hunk 3]
```diff
@@ -2149,11 +2148,13 @@ object desugar {
       enums match {
         case Nil if betterForsEnabled => body
         case (gen: GenFrom) :: Nil =>
+          val aply = Apply(rhsSelect(gen, mapName), makeLambda(gen, body))
           if betterForsEnabled
-            && gen.checkMode != GenCheckMode.Filtered // results of withFilter have the wrong type
-            && deepEquals(gen.pat, body)
-          then gen.expr  // avoid a redundant map with identity
-          else Apply(rhsSelect(gen, mapName), makeLambda(gen, body))
+          && gen.checkMode != GenCheckMode.Filtered // results of withFilter have the wrong type
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/ast/Desugar.scala:2153]: This is non-standard indentation, but I'd tend t leave it in to be able to judge better how it looks.
