### PR TITLE
Forbid `StringConstant(null)`

### LINKED ISSUE #23008: Expr(null:String).show in macro throws NullPointerException
## Compiler version

3.6.4

## Minimized code

Macro:
```Scala
import scala.quoted.*

object ExprStringBugMacro {

  def buildStringCode(using Quotes): Expr[String] = {
    import quotes.reflect.*
    val str: String = null
    val exprString = Expr(str)
    //It throws NullPointerException
    println("Macro string: " + exprString.show)
    exprString
  }
}
```
Test:
```Scala
import munit.FunSuite

class ExprStringBugTest extends munit.FunSuite {

  test("NullPoinreException") {
    buildString
  }

  implicit inline def buildString[T]: Unit = ${
    ExprStringBugMacro.buildStringCode
  }
}import scala.quoted.*

object ExprStringBugMacro {

  def buildStringCode(using Quotes): Expr[String] = {
    import quotes.reflect.*
    //Test value
    val str: String = null
    val exprString = Expr(str)
    println("Macro string: " + exprString.show)
    exprString
  }
}
```

## Output

Image

## Expectation
Absence of the exception

## Description
[stringValue](https://github.com/scala/scala3/blob/06886b0caab593aefa5a34c0a49a787da4648939/compiler/src/dotty/tools/dotc/core/Constants.scala#L190) 
```scala
def stringValue: String = value.toString
```
just does not expect null.

It requres to implement a custom string converter to generate exp from java types.

### PR DESCRIPTION
**Pull request by mbovel**
Fixes #23008. Started during the Scala 3 Compiler Spree of Monday, April 28th, 2025.

The `Constant` is an object in Dotty core that has several `apply` overloads, including `Constant(String)` and `Constant(Null)`, that create `Constant` instances with the appropriate tags:

https://github.com/scala/scala3/blob/bbe2dde1ee10adc05ceece96ab82af8a66a21880/compiler/src/dotty/tools/dotc/core/Constants.scala#L229 https://github.com/scala/scala3/blob/bbe2dde1ee10adc05ceece96ab82af8a66a21880/compiler/src/dotty/tools/dotc/core/Constants.scala#L238

It is called from the quotes reflection API with an argument `x: String`, which always dispatched to the former overload:

https://github.com/scala/scala3/blob/9e7aab7ab8b2798175abf71737ffe822e50f9c30/compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala#L2532

When this API is called from code without explicit nulls, `null` can be passed as argument `x`. That still dispatches to the `Constant(String)` overload, yielding a `Constant` with the wrong tag.

This PR fixes the issue by forbidding `null` as an argument of `StringConstant`.

### CODE REVIEW

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala [hunk 1]
```diff
@@ -2529,7 +2529,7 @@ class QuotesImpl private (using val ctx: Context) extends Quotes, QuoteUnpickler
     end StringConstantTypeTest
 
     object StringConstant extends StringConstantModule:
-      def apply(x: String): StringConstant = dotc.core.Constants.Constant(x)
+      def apply(x: String): StringConstant = dotc.core.Constants.Constant(x: Any)
```
Comment (hamzaremmal) [inline compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:2532]: This is a fix to what I believe is a soundness hole in explicit nulls. I'm going to try to have another example with more details about this soundness issue.

Comment (He-Pin) [reply compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:2532]: If this is a valid fix, then comments is needed inline

**Comment by olhotak** [comment]
Is the intended behaviour of `Expr(null: String)` specified anywhere, such as in the Javadoc comments of `Expr` in the `scala.quoted` API, or anywhere else? I couldn't find it. Is one allowed to pass null here or not?

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala (hunk 1 above)
Comment (Alexey-NM) [reply compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:2532]: May be it is better to add:
```scala
object dotc.core.Constants.Constant{
  val nullString: Constant  = new Constant(null, NullTag)
}

def apply(x: String): StringConstant = if (x==null) {dotc.core.Constants.nullString} else {dotc.core.Constants.Constant(x)}
```

**Comment by HarrisL2** [comment]
> Is the intended behaviour of `Expr(null: String)` specified anywhere, such as in the Javadoc comments of `Expr` in the `scala.quoted` API, or anywhere else? I couldn't find it. Is one allowed to pass null here or not?

I believe its not allowed, but not very well documented.

https://github.com/scala/scala3/blob/08f2e4a1f3adb6b1a15d2857d28d5c9aa46656fd/compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala#L575

**Comment by Alexey-NM** [comment]
> I believe its not allowed

If this is the case, then Expr(null: String) should throw an exception. We spent a lot of time trying to understand why exprString.show was throwing an error. Actually we didn't explicitly write Expr(null: String); instead, we performed a conversion from a Java POJO. This was not immediately obvious, and we were quite frustrated to discover that the root cause was related to Expr, which is defined far away and comes with implicit imports.

If this is indeed how it works, it represents a rather unfriendly design when interacting with Java objects.

**Comment by mbovel** [comment]
> I believe its not allowed, but not very well documented.

The point here is that a Dotty `Constant` *with tag `StringTag`* cannot have the value `null`:

https://github.com/scala/scala3/blob/08f2e4a1f3adb6b1a15d2857d28d5c9aa46656fd/compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala#L574-L575

However, `Constant(null, NullTag)` is valid. Therefore, I think the questions to accept `null: Null` or `null: String` as arguments to `Expr`, `StringToExpr`, and `StringConstant` in the quotes API should be treated orthogonally.

> Is the intended behaviour of `Expr(null: String)` specified anywhere, such as in the Javadoc comments of `Expr` in the `scala.quoted` API, or anywhere else? I couldn't find it. Is one allowed to pass null here or not?

I also could not find any documentation.

Thus, it seems up to us to decide whether `Expr(null: String)` should throw an exception or instead produce a well-formed `null` constant (as this PR proposes).

Accepting `null` seems reasonable to me: I only see advantages so far (notably compatibility with code without explicit nulls). Are there any drawbacks?

**Comment by olhotak** [comment]
If we decide to allow `null`, can we document this by making the signature of `StringConstant.apply` take a `String|Null` instead of `String`?

**Comment by mbovel** [comment]
> If we decide to allow `null`, can we document this by making the signature of `StringConstant.apply` take a `String|Null` instead of `String`?

Indeed, that would also look like nicer to us! We discussed it on Monday during the Spree and concluded that would be a backward-incompatible change, but I am actually not sure.

**Comment by mbovel** [comment]
By the way, while trying to change the parameter type to `String | Null`, I noticed `Constant(x: String | Null)` in `compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala` seems to resolve to `Constant(String)` and not to `Constant(Any)`, as I would expect with explicit nulls enabled. Any idea why?

**Comment by noti0na1** [comment]
> By the way, while trying to change the parameter type to `String | Null`, I noticed `Constant(x: String | Null)` in `compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala` seems to resolve to `Constant(String)` and not to `Constant(Any)`, as I would expect with explicit nulls enabled. Any idea why?

I guess the file calling the quotes api is not in explicit nulls, so `String | Null` will still be a subtype of `String`.

**Comment by mbovel** [comment]
Something else I just noticed: the method returns a `StringConstant`, which is defined as a `Constant` with tag `StringTag`:

https://github.com/scala/scala3/blob/bbe2dde1ee10adc05ceece96ab82af8a66a21880/compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala#L2526-L2529

So we shouldn't return a `Constant` with tag `NullTag` under this return type.

We *could* change the return type to `StringConstant | NullConstant`, but that starts to feel convoluted.

Maybe it's better after all to just `require` a non-null argument?

**Comment by mbovel** [comment]
> I guess the file calling the quotes api is not in explicit nulls, so `String | Null` will still be a subtype of `String`.

But isn't the overload statically resolved, in the file with explicit nulls?

**Comment by noti0na1** [comment]
Oh, I see what you meam. No, explicit nulls is diabled in `QuotesImpl` by importing `unsafeNulls`.

**Comment by mbovel** [comment]
> Oh, I see what you meam. No, explicit nulls is disabled in `QuotesImpl` by importing `unsafeNulls`.

Ah, that explains it! Thanks, I missed this import.

**Comment by noti0na1** [comment]
> Maybe it's better after all to just `require` a non-null argument?

I'm ok with this, given a `null` string is always not allowed, it's better to throw the exception ealier.

**Comment by Alexey-NM** [comment]
> > Maybe it's better after all to just `require` a non-null argument?
> 
> I'm ok with this, given a `null` string is always not allowed, it's better to throw the exception ealier.

Actualy we can solve the issue in [StringToExpr](https://github.com/scala/scala3/blob/c4531d4e4931762d5bda4fd5afc15bb7548ce627/library/src/scala/quoted/ToExpr.scala#L77)
So this is not the reason to throw the exception

**Comment by mbovel** [comment]
> We can solve the issue in [StringToExpr](https://github.com/scala/scala3/blob/c4531d4e4931762d5bda4fd5afc15bb7548ce627/library/src/scala/quoted/ToExpr.scala#L77)
> So this is not the reason to throw the exception

What do you suggest for `StringToExpr`?

In any case, we still need to do something for `StringConstant` itself as it is also part of the public API, don't we?

**Comment by Alexey-NM** [comment]
> In any case, we still need to do something for `StringConstant` itself as it is also part of the public API, don't we?

IIUC: Our primary issue is that `StringToExpr` return  broken expression without any exception:
```scala
 import quotes.reflect.*
 val str: String = null
 val exprString = Expr(str)
```
It seems we can fix it just to rewrite StringToExpr
```scala 
  given StringToExpr[T <: String]: ToExpr[T] with {
    def apply(x: T)(using Quotes) =
      import quotes.reflect.*
      Literal(if (x==null) {nullListeral} else {StringConstant(x)}).asExpr.asInstanceOf[Expr[T]]
  }
```
it seems the issue can be resolved without modifying the declaration of StringConstant.

**Comment by Alexey-NM** [comment]
> In any case, we still need to do something for `StringConstant` itself as it is also part of the public API, don't we?

IMHO: Yes, StringConstant must not return broken result silently.

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala (hunk 1 above)
Comment (mbovel) [reply compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala]: I was also surprised when I discovered `true/false/null` constants are not re-used/interned/hash-consed. I don't know if that would have significant impact. I think this could be discussed in a separate issue or PR.

**Comment by mbovel** [comment]
I have just pushed a commit that allows `null` in `StringToExpr`, but not in `StringConstant`, following @noti0na1 and @Alexey-NM's comments.

**Comment by mbovel** [comment]
But now if we allow `null` for `StringToExpr`, maybe we should allow it for all other `ToExpr` instances as well, which might be overkill 😕

**Comment by Alexey-NM** [comment]
> But now if we allow `null` for `StringToExpr`, maybe we should allow it for all other `ToExpr` instances as well, which might be overkill 😕

IMHO: There are no other java primitives in the `ToExpr` which can be null.
May be:
- BigIntToExpr
- BigDecimalToExpr

But it is scala types and may be it should not be null it any case.

**Comment by mbovel** [comment]
> There are no other java primitives in the `ToExpr` which can be null.

Yes, but what about non-primitive types? We also get runtime errors in these cases, for example:

```scala
  def nullTestImpl()(using Quotes): Expr[Unit] =
    Expr(null: Option[Int]) // MatchError: null
    Expr(null: (Int, Int)) // NullPointerException: Cannot invoke "scala.Tuple2._1()" because "tup$2" is null
    Expr(null: Array[Int]) // NullPointerException: Cannot read the array length because "array" is null
```

**Comment by Alexey-NM** [comment]
> Yes, but what about non-primitive types? We also get runtime errors in these cases, for example:

IMHO:
- `Expr(null: Option[Int]) // MatchError: null`
   Exception is correct because such writing should not occur.
- Expr(null: Array[Int])
  Since It is a Java type, it would be useful to allow convertion for better interoperability

-  `Expr(null: (Int, Int)) `
   I just do not know, it seems such writing should not occur.

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala (hunk 1 above)
Comment (ivvlev) [reply compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala]: Suggestion:
```scala
  object Constant {
	def apply(x: String): Constant       = 
	  new Constant(x,
            x match {
              case null            => NullTag
              case _               => StringTag
        }
      )
  }
```

**Comment by mbovel** [comment]
We discussed this in yesterday's compiler meeting and concluded that `null` should not be supported as an argument to `StringToExpr.apply`. This method is defined in a file with explicit nulls enabled, so it should not expect or handle `null` values (that's why an unchecked cast `(x: Any)` was required in my previous commit).

Instead it's the caller's responsibility to ensure that the argument is non-null. Corollary: the presence of explicit nulls should ideally be visible in documentation and the IDE, so that users can be aware of it—but that's future work.

On the other hand, `StringConstant` should check for `null` and reject it, because it is defined in a file with unsafe nulls. It must not call `Constant` with `null`, since `Constant` is in a compilation unit with explicit nulls.

**Review by noti0na1 — APPROVED** [review]
