### PR TITLE
Detect macro dependencies that are missing from the classloader

### LINKED ISSUE #20119: Spurious "Cyclic macro dependencies" error with pipelining turned on
## Compiler version

`3.5.0-RC1-bin-20240404-a7f00e2-NIGHTLY`

## Minimized code

both these projects exhibit the behaviour:

https://github.com/DFiantHDL/DFiant/tree/pipeline
https://github.com/atry/html.scala/tree/v3.0.3

Add these lines to build.sbt
```
ThisBuild / usePipelining := true
ThisBuild / scalaVersion := "3.5.0-RC1-bin-20240404-a7f00e2-NIGHTLY"
```

## Output

from command `html/Test/compile` in atry/html.scala
```scala
[error] Cyclic macro dependencies in /Users/jamie/workspace/html.scala/html/target/scala-3.5.0-RC1-bin-20240404-a7f00e2-NIGHTLY/src_managed/test/sbt-example-generated.scala.
[error] Compilation stopped since no further progress can be made.
[error]
[error] To fix this, place macros in one set of files and their callers in another.
[error]
[error] Compile with -Xprint-suspension for information.
[warn] one warning found
[error] one error found
[error] Total time: 3 s, completed Apr 8, 2024, 9:11:58 AM
```

from command `core/compile` in DFiantHDL/DFiant
```scala
[error] Cyclic macro dependencies among
[error]
[error]   /Users/jamie/workspace/DFiant/core/src/main/scala/dfhdl/core/DFBits.scala, /Users/jamie/workspace/DFiant/core/src/main/scala/dfhdl/core/DFVector.scala, /Users/jamie/workspace/DFiant/core/src/main/scala/dfhdl/core/SameElementsVector.scala
[error]
[error] Compilation stopped since no further progress can be made.
[error]
[error] To fix this, place macros in one set of files and their callers in another.
[error]
[error] Compile with -Xprint-suspension for information.
[error] one error found
[error] (core / Compile / compileIncremental) Compilation failed
[error] Total time: 28 s, completed 8 Apr 2024, 09:19:48
```

both do not appear if pipelining is turned off.

## Expectation
compile as normal

### PR DESCRIPTION
**Pull request by bishabosha**
So the situation is basically that `DFiant` and `html.scala` projects do not work "out of the box" with pipelining, and will need to tune their builds if they want some pipelining.

However, the compiler reports an error that is not helpful to the user, so in this PR we report a better one.

Previously, it was assumed that a missing class (that is valid in current run)
during macro evaluation was due to the symbol being defined in the same project.
If this condition is met, then compilation is suspended.

This assumption breaks when the symbol comes from the classpath, but without a
corresponding class file, leading a situation where the same file is always suspended,
until it is the only one left, leading to the "cyclic macro dependencies" error.
In this case we should assume that the class file will never become available because class path entries
are supposed to be immutable. Therefore we should not suspend in this case.

This commit therefore detects this situation. Instead of suspending the unit,
the compiler aborts the macro expansion, reporting an error that
the user will have to deal with - likely by changing the build definition/

In the end, users will see something like:
```scala
[error] -- Error: /Users/jamie/workspace/DFiant/core/src/main/scala/dfhdl/core/DFVector.scala:163:25
[error] 163 |            val idxVal = d"$i".asConstOf[DFUInt[Int]]
[error]     |                         ^^^^^
[error]     |Macro code depends on trait DFType in package dfhdl.compiler.ir found on the classpath, but could not be loaded while evaluating the macro.
[error]     |  This is likely because class files could not be found in the classpath entry for the symbol.
[error]     |
[error]     |  A possible cause is if the origin of this symbol was built with pipelined compilation;
[error]     |  in which case, this problem may go away by disabling pipelining for that origin.
[error]     |
[error]     |  trait DFType is defined in file /Users/jamie/workspace/DFiant/compiler/ir/target/scala-3.5.0-RC1-bin-SNAPSHOT/early/dfhdl-compiler-ir_3-0.3.7+15-05c25215+20240409-1626-SNAPSHOT.jar(dfhdl/compiler/ir/DFType.tasty)
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from DFDecimal.scala:411
[error] 411 |          ${ applyMacro('sc, 'args) }
[error]     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]      ---------------------------------------------------------------------------
```

and
```scala
[error] -- Error: /Users/jamie/workspace/html.scala/html/target/scala-3.5.0-RC1-bin-SNAPSHOT/src_managed/test/sbt-example-generated.scala:15:52
[error]  15 |        val span: Binding.Stable[HTMLSpanElement] = html"<span>The quick ${color.bind} fox jumps&nbsp;over the lazy $animal</span>"
[error]     |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |Macro code depends on missing object Definitions in package com.yang_bo.html found on the classpath, but could not be loaded while evaluating the macro.
[error]     |  This is likely because class files could not be found in the classpath entry for the symbol.
[error]     |
[error]     |  A possible cause is if the origin of this symbol was built with pipelined compilation;
[error]     |  in which case, this problem may go away by disabling pipelining for that origin.
[error]     |
[error]     |object Definitions is defined in file /Users/jamie/workspace/html.scala/html-Definitions/target/scala-3.5.0-RC1-bin-SNAPSHOT/early/html-definitions_sjs1_3-3.0.3+0-d627afe0+20240409-1532.jar(com/yang_bo/html/Definitions.tasty)
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from package.scala:712
[error] 712 |      ${
[error]     |      ^
[error] 713 |        Macros.html('stringContext, 'args)
[error] 714 |      }
[error]      ---------------------------------------------------------------------------
```

which is more actionable.

Note that sbt already automatically disables pipelining on projects that define macros, but this is not useful if the macro itself depends on upstream projects that do not define macros. This is probably a hard problem to detect automatically - so this is good compromise.

We also fix `-Xprint-suspension`, which appeared to swallow a lot of diagnostic information.
Also make `-Yno-suspended-units` behave better.

fixes #20119

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/quoted/Interpreter.scala [hunk 1]
```diff
@@ -213,8 +213,8 @@ class Interpreter(pos: SrcPos, classLoader0: ClassLoader)(using Context):
   private def loadClass(name: String): Class[?] =
     try classLoader.loadClass(name)
     catch
-      case MissingClassDefinedInCurrentRun(sym) =>
-        suspendOnMissing(sym, pos)
+      case MissingClassValidInCurrentRun((sym, origin)) =>
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/quoted/Interpreter.scala:216]: Are those double parentheses needed?
```suggestion
      case MissingClassValidInCurrentRun(sym, origin) =>
```
Same twice more below.

File: compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala [hunk 2]
```diff
@@ -107,8 +107,8 @@ class MacroAnnotations(phase: IdentityDenotTransformer):
             if !ctx.reporter.hasErrors then
               report.error("Macro expansion was aborted by the macro without any errors reported. Macros should issue errors to end-users when aborting a macro expansion with StopMacroExpansion.", annot.tree)
             List(tree)
-          case Interpreter.MissingClassDefinedInCurrentRun(sym) =>
-            Interpreter.suspendOnMissing(sym, annot.tree)
+          case Interpreter.MissingClassValidInCurrentRun((sym, origin)) =>
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala:110]: One more.

**Review by sjrd — APPROVED** [review]
