### PR TITLE
Make coverage more similar to the one in Scala 2

### LINKED ISSUE #21695: `undefined` error if enable coverage
## Compiler version

- 3.5.2-RC1
- 3.6.0-RC1-bin-20241001-8244d67-NIGHTLY

## Minimized code

`build.sbt`

```scala
scalacOptions ++= Seq("-coverage-out:coverage-out")

libraryDependencies += "io.grpc" % "grpc-services" % "1.68.0"

scalaVersion := "3.5.2-RC1"
```

`MyServer.scala`

```scala
package example

import io.grpc.Server
import io.grpc.ServerBuilder
import io.grpc.ServerInterceptors
import io.grpc.ServerServiceDefinition
import io.grpc.protobuf.services.ProtoReflectionService
import io.grpc.util.TransmitStatusRuntimeExceptionInterceptor

object MyServer {

  def createServer(port: Int, services: List[ServerServiceDefinition]): Server = {
    services
      .foldLeft(ServerBuilder.forPort(port))((builder, service) =>
        builder.addService(
          ServerInterceptors.intercept(
            service,
            TransmitStatusRuntimeExceptionInterceptor.instance()
          )
        )
      )
      .addService(ProtoReflectionService.newInstance())
      .build()
  }

}
```

## Output (click arrow to expand)

<details>

```
[error] -- Error: scala3-coverage-bug/MyServer.scala:23:12 ----------------
[error] 13 |    services
[error] 14 |      .foldLeft(ServerBuilder.forPort(port))((builder, service) =>
[error] 15 |        builder.addService(
[error] 16 |          ServerInterceptors.intercept(
[error] 17 |            service,
[error] 18 |            TransmitStatusRuntimeExceptionInterceptor.instance()
[error] 19 |          )
[error] 20 |        )
[error] 21 |      )
[error] 22 |      .addService(ProtoReflectionService.newInstance())
[error] 23 |      .build()
[error]    |    ^
[error]    |undefined: {
[error]    |  val $3$: io.grpc.ServerBuilder[?] =
[error]    |    {
[error]    |      val z$1: io.grpc.ServerBuilder[?] =
[error]    |        {
[error]    |          scala.runtime.coverage.Invoker.invoked(3, "coverage-out")
[error]    |          io.grpc.ServerBuilder.forPort(port)
[error]    |        }
[error]    |      val op$1:
[error]    |        ((io.grpc.ServerBuilder[?], io.grpc.ServerServiceDefinition) =>
[error]    |          io.grpc.ServerBuilder[?])
[error]    |       =
[error]    |        {
[error]    |          def $anonfun(builder: io.grpc.ServerBuilder[?],
[error]    |            service: io.grpc.ServerServiceDefinition): io.grpc.ServerBuilder[?]
[error]    |             =
[error]    |            {
[error]    |              val $2$: io.grpc.ServerServiceDefinition =
[error]    |                {
[error]    |                  val $1$: Seq[io.grpc.ServerInterceptor] =
[error]    |                    [
[error]    |                      {
[error]    |                        scala.runtime.coverage.Invoker.invoked(6, "coverage-out"
[error]    |                          )
[error]    |                        io.grpc.util.TransmitStatusRuntimeExceptionInterceptor.
[error]    |                          instance()
[error]    |                      }
[error]    |                     : io.grpc.ServerInterceptor]
[error]    |                  scala.runtime.coverage.Invoker.invoked(5, "coverage-out")
[error]    |                  io.grpc.ServerInterceptors.intercept(service, $1$*)
[error]    |                }
[error]    |              scala.runtime.coverage.Invoker.invoked(4, "coverage-out")
[error]    |              builder.addService($2$)
[error]    |            }
[error]    |          closure($anonfun)
[error]    |        }
[error]    |      scala.runtime.coverage.Invoker.invoked(2, "coverage-out")
[error]    |      services.foldLeft[io.grpc.ServerBuilder[?]](z$1)(op$1)
[error]    |    }
[error]    |  val $4$: io.grpc.BindableService =
[error]    |    {
[error]    |      scala.runtime.coverage.Invoker.invoked(7, "coverage-out")
[error]    |      io.grpc.protobuf.services².ProtoReflectionService.newInstance()
[error]    |    }
[error]    |  scala.runtime.coverage.Invoker.invoked(1, "coverage-out")
[error]    |  $3$.addService²($4$)
[error]    |}.build # -1: TermRef(TypeRef(ThisType(TypeRef(NoPrefix,module class <special-ops>)),type <FromJavaObject>),build) at instrumentCoverage
[error]    |
[error]    |where:    addService  is a method in class ServerBuilder
[error]    |          addService² is a method in class ServerBuilder
[error]    |          services    is a parameter in method createServer
[error]    |          services²   is a package in package io.grpc.protobuf
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```
</details>

### LINKED ISSUE #21877: Different coverage results for scala 2 and scala 3
## Compiler version
3.3.4

## Problem
Scala 3 coverage of my project is still significantly lower than scala 2 (~ 20% for statements and 27% for branches)
I've tried to inspect reports to see differences.
1. In general Scala 3 has much more statements and branches. Why this may be so? 
2. Scala 3 has much more classes then Scala 2. And looks like this is because of `$anon` class. I've tried to look closer and now macro generated code is also covered. IMO macro generated by some library code should not be covered by default, since library users are not testing libraries, but their own code.

So is it just more precise score and this is a desired behavior or not? 

## Scala 2.13 report
image

## Scala 3 report
image

## Scala 2.13 report
image

image

## Scala 3 report
image
image

## Statements
image
image

### PR DESCRIPTION
**Pull request by jchyb**
Closes #21877
* removes coverage of inlined nodes (as mentioned in the accompanying comment, those are impossible to represent in most cases)
* adds coverage for Literals (ones directly in Apply are omitted)
* removes coverage of `throw` contents
* if apply node is tagged, we do not tag it's prefix, outside of other prefixing Apply's arguments (eg. when we tag `a+b+c` we do not redundantly tag `a+b`)
* allows instrumenting synthetic method calls (like apply of a case 

After all of these changes the statements tagged are much more similar to Scala 2, let's look at the #21877 minimisation:
* Scala 2:
Zrzut ekranu 2025-08-12 o 17 07 31
Zrzut ekranu 2025-08-12 o 17 07 46

* Scala 3:
Zrzut ekranu 2025-08-12 o 17 08 48
Zrzut ekranu 2025-08-12 o 17 08 55

There are some differences still remaining, most notably the tagging the DefDefs and its default parameters, but I left them for now, as those seem more useful than harmful.

BEcouse of those changed most of the .covergae files had to be regenerated, however I want through each and every diff to make sure that all of those changes there are expected.

Additionally, this PR also fixes #21695 (issue with certain generated Block nodes not having assigned the correct type, causing later undefined errors).

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/InstrumentCoverage.scala [hunk 1]
```diff
@@ -145,6 +145,29 @@ class InstrumentCoverage extends MacroTransform with IdentityDenotTransformer:
       val span = pos.span.toSynthetic
       invokeCall(statementId, span)
 
+    private def transformApplyArgs(trees: List[Tree])(using Context): List[Tree] =
+      if (allConstArgs(trees)) trees else transform(trees)
```
Comment (KacperFKorban) [inline compiler/src/dotty/tools/dotc/transform/InstrumentCoverage.scala]: nit: chould you change to the new `if-then-else` syntax?

File: compiler/src/dotty/tools/dotc/transform/InstrumentCoverage.scala [hunk 2]
```diff
@@ -145,6 +145,29 @@ class InstrumentCoverage extends MacroTransform with IdentityDenotTransformer:
...
+        )
+      case a: TypeApply =>
+        cpy.TypeApply(a)(
+          transformInnerApply(a.fun),
+          transformApplyArgs(a.args)
+        )
+      case s: Select =>
+        cpy.Select(s)(transformInnerApply(s.qualifier), s.name)
+      case i: (Ident | This) => i
+      case other    => transform(other)
```
Comment (KacperFKorban) [inline compiler/src/dotty/tools/dotc/transform/InstrumentCoverage.scala]: Question: I don't fully understand the motivation for this. Could you give a motivating code example that shows the intended coverage change?

Is it simply something of the shape: `f(args1)(args2)(args3)(args4)`? In that case, can something like a `Typed` node cause the logic to run away from this function into the main `transform` function?

**Review by KacperFKorban — COMMENTED** [review]
The changes look good.

I didn't fully understand one part of the PR, so I left a question about that.

File: compiler/src/dotty/tools/dotc/transform/InstrumentCoverage.scala (hunk 2 above)
Comment (jchyb) [reply compiler/src/dotty/tools/dotc/transform/InstrumentCoverage.scala]: Yes, its so that `f(args1)(args2)(args3)(args4)`, `f(args1)(args2)(args3)`, `f(args1)(args2)` `f(args1)`, `f` don't all get redundantly tagged (the args will still be, if they are not literals). The main annoyance was with math/logic operators, like for `a + b + c`, where `a+b` would also get redundantly tagged. This will not defend against something like `a + (b + c)`, where the second apply node is in the args field - but that is also precisely how it works in scala 2.

I tested the Typed example now (something like `(f(0): (Int => Unit))(1)`), and it surprisingly manages to ignore the prefixing Apply in Scala 2, but not in this PR, so I'll will fix this now - thank you for the catch!

Comment (KacperFKorban) [reply compiler/src/dotty/tools/dotc/transform/InstrumentCoverage.scala]: That makes sense, thanks for the explanation.
