### PR TITLE
Unify annotation handling for thread-safe & -unsafe lazy vals

### LINKED ISSUE #23487: Lazy vals annotated with `@threadUnsafe` ignore `@transient` annotation
## Compiler version

3.3.6, 3.7.1

## Minimized code

Lazy vals annotated with  `@threadUnsafe` do not honour the `@transient` annotation:

```scala
case class Bar() {
  @transient @threadUnsafe
  lazy val value: Long = System.nanoTime()
}
```

While examining the compiler output should suffice to identify the issue, here's also a reproducer of this behaviour:

```scala
//> using scala 3.7.1

import java.io.*
import scala.annotation.threadUnsafe

// Serialize any object to a byte array
def serialize[T <: Serializable](obj: T): Array[Byte] = {
  val byteArrayOutputStream = new ByteArrayOutputStream()
  val objectOutputStream    = new ObjectOutputStream(byteArrayOutputStream)

  try {
    objectOutputStream.writeObject(obj)
    byteArrayOutputStream.toByteArray
  } finally {
    objectOutputStream.close()
    byteArrayOutputStream.close()
  }
}

// Deserialize from a byte array back to an object
def deserialize[T](bytes: Array[Byte]): T = {
  val byteArrayInputStream = new ByteArrayInputStream(bytes)
  val objectInputStream    = new ObjectInputStream(byteArrayInputStream)

  try {
    objectInputStream.readObject().asInstanceOf[T]
  } finally {
    objectInputStream.close()
    byteArrayInputStream.close()
  }
}

case class Foo() {
  @transient
  lazy val value: Long = System.nanoTime()
}

case class Bar() {
  @transient @threadUnsafe
  lazy val value: Long = System.nanoTime()
}

@main def main() = {
  val foo1 = Foo()
  foo1.value // init lazy val
  val foo2 = deserialize[Foo](serialize(foo1))
  assert(foo1.value != foo2.value, "Foo#value is not transient")

  val bar1 = Bar()
  bar1.value // init lazy val
  val bar2 = deserialize[Bar](serialize(bar1))
  assert(bar1.value != bar2.value, "Bar#value is not transient")
}
```

## Output

```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Bar#value is not transient
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at Foo$package$.main(Foo.scala:50)
	at main.main(Foo.scala:41)
```

## Expectation

I expect that lazy vals annotated with both `@threadUnsafe` and `@transient` honour the annotation, or if that's not possible (for some reason) a compiler warning should be raised for illegal combination of annotations

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #23487

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/LazyVals.scala [hunk 1]
```diff
@@ -215,6 +215,20 @@ class LazyVals extends MiniPhase with IdentityDenotTransformer {
       ref(field).becomes(nullLiteral)
     }
 
+  /**
+   * Creates a ValDef used as the underlying volatile var,
+   * and also returns the term name as it's later needed as a TermName (and not just any symbol name)
+   */
+  private def mkContainerTree(x: ValOrDefDef, isVolatile: Boolean)(using Context): (Names.TermName, ValDef) =
+    val claz = x.symbol.owner.asClass
+    val tpe = if isVolatile then defn.ObjectType else x.tpe.widen.resultType.widen
```
Comment (SolalPirelli) [inline compiler/src/dotty/tools/dotc/transform/LazyVals.scala]: The original code used:
- this different type for the container symbol
- `defaultValue(tpe)` as the original value for the unsafe version and `nullLiteral` for the safe version

Using one of these two options for `tpe` regardless of context causes crashes in the newly added test, in both cases because we can't prove `Long <: Object`, but preserving the original behavior as this line does works fine.

I don't like it though, I think I'm missing something.

File: compiler/src/dotty/tools/dotc/transform/LazyVals.scala [hunk 2]
```diff
@@ -215,6 +215,24 @@ class LazyVals extends MiniPhase with IdentityDenotTransformer {
       ref(field).becomes(nullLiteral)
     }
 
+  /**
+   * Creates a ValDef used as the underlying volatile var,
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/LazyVals.scala]:
```suggestion
   * Creates a ValDef used as the underlying var,
```
?

File: compiler/src/dotty/tools/dotc/transform/LazyVals.scala [hunk 3]
```diff
@@ -474,14 +483,7 @@ class LazyVals extends MiniPhase with IdentityDenotTransformer {
...
 
-    val containerName = LazyLocalName.fresh(x.name.asTermName)
-    val containerSymbol = newSymbol(claz, containerName, x.symbol.flags &~ containerFlagsMask | containerFlags | Private, defn.ObjectType, coord = x.symbol.coord).enteredAfter(this)
-    containerSymbol.addAnnotation(Annotation(defn.VolatileAnnot, containerSymbol.span)) // private @volatile var _x: AnyRef
-    containerSymbol.addAnnotations(x.symbol.annotations) // pass annotations from original definition
-    containerSymbol.removeAnnotation(defn.ScalaStaticAnnot)
-    val getOffset =
-        Select(ref(defn.LazyValsModule), lazyNme.RLazyVals.getOffsetStatic)
-    val containerTree = ValDef(containerSymbol, nullLiteral)
+    val (containerName, containerTree) = mkContainerTree(x, isVolatile = true)
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/LazyVals.scala]:
```suggestion
    val containerTree = mkContainerTree(x, isVolatile = true)
    val containerName = containerTree.symbol.name.asTermName
```
? So that you don't need the additional tuple. In the thread-unsafe code path we don't need that name, so it doesn't seem that general.

File: compiler/src/dotty/tools/dotc/transform/LazyVals.scala [hunk 4]
```diff
@@ -215,6 +215,24 @@ class LazyVals extends MiniPhase with IdentityDenotTransformer {
...
+    val tpe = if isVolatile then defn.ObjectType else x.tpe.widen.resultType.widen
+    val containerName = LazyLocalName.fresh(x.name.asTermName)
+    val containerSymbol = newSymbol(claz, containerName, x.symbol.flags &~ containerFlagsMask | containerFlags | Private, tpe, coord = x.symbol.coord).enteredAfter(this)
+    if isVolatile then containerSymbol.addAnnotation(Annotation(defn.VolatileAnnot, containerSymbol.span))
+    // Keep field annotations like @transient, see scala/scala3#23487
+    for a <- x.symbol.annotations do
+      if a.hasOneOfMetaAnnotation(Set(defn.FieldMetaAnnot)) then
+        containerSymbol.addAnnotation(a)
+    // for the thread-safe implementation, the generated symbol must not be static or the CAS operations won't work, see scala/scala3#16800
+    if isVolatile then containerSymbol.removeAnnotation(defn.ScalaStaticAnnot)
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/LazyVals.scala]: Combine the two `if isVolatile then`?

File: compiler/src/dotty/tools/dotc/transform/LazyVals.scala (hunk 1 above)
Comment (sjrd) [reply compiler/src/dotty/tools/dotc/transform/LazyVals.scala]: Nothing jumps out to me either. Consider turning this into a comment in the code, so that the next person to come here has more context.

**Review by sjrd — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/transform/LazyVals.scala (hunk 1 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/transform/LazyVals.scala]: I'll move the definition of `tpe` to the call site since there are exactly 2. Now that I look at it again `mkThreadSafeDef` also uses `defn.ObjectType` so I guess that's why it must match... could also try to change it there but that seems more involved/risky.

**Comment by SolalPirelli** [comment]
@sjrd ping 😇

**Review by sjrd — APPROVED** [review]
