### PR TITLE
Fix #21402: Always allow type member extraction for stable scrutinees in match types.

### LINKED ISSUE #21402: No workaround to dependent-type match types after SIP-56
Based on the problem found in `akka/akka` and `apache/pekko` 

In the snippet we can come up with workaround to `TypedMultiMap.get` by using `transparent inline` however there seems to be no workaround for the `TypedMultiMap.inserted` method. 

## Compiler version
All Scala 3.4+ versions

## Minimized code

```Scala
abstract class AbstractServiceKey:
  type Protocol

abstract class ServiceKey[T] extends AbstractServiceKey:
  type Protocol = T

type Aux[P] = AbstractServiceKey { type Protocol = P }
type Service[K <: Aux[?]] = K match
  case Aux[t] => ActorRef[t]
type Subscriber[K <: Aux[?]] = K match
  case Aux[t] => ActorRef[ReceptionistMessages.Listing[t]]

trait ActorRef[-T]

object ReceptionistMessages:
  final case class Listing[T](key: ServiceKey[T])

class TypedMultiMap[T <: AnyRef, K[_ <: T]]:
  def get(key: T): Set[K[key.type]] = ???
  transparent inline def getInlined(key: T): Set[K[key.type]] = ???
  inline def inserted(key: T, value: K[key.type]): TypedMultiMap[T, K] = ???

object LocalReceptionist {
  final case class State(
      services: TypedMultiMap[AbstractServiceKey, Service],
      subscriptions: TypedMultiMap[AbstractServiceKey, Subscriber]
  ):
    def testInsert(key: AbstractServiceKey)(serviceInstance: ActorRef[key.Protocol]): State = {
      val fails = services.inserted(key, serviceInstance) // error
      ???
    }

  def testGet[T](key: AbstractServiceKey): Unit = {
    val newState: State = ???
    val fails: Set[ActorRef[key.Protocol]] = newState.services.get(key) // error
    val works: Set[ActorRef[key.Protocol]] = newState.services.getInlined(key) // workaround

    val fails2: Set[ActorRef[ReceptionistMessages.Listing[key.Protocol]]] = newState.subscriptions.get(key) // error
    val works2: Set[ActorRef[ReceptionistMessages.Listing[key.Protocol]]] = newState.subscriptions.getInlined(key) // workaround
  }
}

```

## Output

```scala
[error] ./test.scala:29:42
[error] Found:    (serviceInstance : ActorRef[key.Protocol])
[error] Required: Service[(key : AbstractServiceKey)]
[error] 
[error] Note: a match type could not be fully reduced:
[error] 
[error]   trying to reduce  Service[(key : AbstractServiceKey)]
[error]   failed since selector (key : AbstractServiceKey)
[error]   does not uniquely determine parameter t in
[error]     case Aux[t] => ActorRef[t]
[error]   The computed bounds for the parameter are:
[error]     t
[error]       val fails = services.inserted(key, serviceInstance) // error
[error]                                          ^^^^^^^^^^^^^^^
[error] ./test.scala:35:46
[error] Found:    Set[Service[(key : AbstractServiceKey)]]
[error] Required: Set[ActorRef[key.Protocol]]
[error] 
[error] Note: a match type could not be fully reduced:
[error] 
[error]   trying to reduce  Service[(key : AbstractServiceKey)]
[error]   failed since selector (key : AbstractServiceKey)
[error]   does not uniquely determine parameter t in
[error]     case Aux[t] => ActorRef[t]
[error]   The computed bounds for the parameter are:
[error]     t
[error]     val fails: Set[ActorRef[key.Protocol]] = newState.services.get(key) // error
[error]                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] ./test.scala:38:77
[error] Found:    Set[Subscriber[(key : AbstractServiceKey)]]
[error] Required: Set[ActorRef[ReceptionistMessages.Listing[key.Protocol]]]
[error] 
[error] Note: a match type could not be fully reduced:
[error] 
[error]   trying to reduce  Subscriber[(key : AbstractServiceKey)]
[error]   failed since selector (key : AbstractServiceKey)
[error]   does not uniquely determine parameter t in
[error]     case Aux[t] => ActorRef[ReceptionistMessages.Listing[t]]
[error]   The computed bounds for the parameter are:
[error]     t
[error]     val fails2: Set[ActorRef[ReceptionistMessages.Listing[key.Protocol]]] = newState.subscriptions.get(key) // error
[error]                                         
```

## Expectation

This kind of issues might pop-up more often as projects would migrate to Scala 3.4+. It would be great if we could propose some workarounds that would allow for their compilation..

### PR DESCRIPTION
**Pull request by sjrd**
Previously, through the various code paths, we basically allowed type member extraction for stable scrutinees if the type member was an alias or a class member. In the alias case, we took the alias, whereas in the class case, we recreated a selection on the stable scrutinee. We did not allow that on abstract type members.

We now uniformly do it for all kinds of type members. If the scrutinee is a (non-skolem) stable type, we do not even look at the info of the type member. We directly create a selection to it, which corresponds to what we did before for class members.

We only try to dealias type members if the scrutinee type is not a stable type.

---

Note that this goes against the current spec and should in theory require (yet another) SIP amendment. The core meeting decided a few ago to go for it anyway and "ask for forgiveness" later so that we can have it in 3.6.0 :man_shrugging:.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -3681,19 +3681,36 @@ class MatchReducer(initctx: Context) extends TypeComparer(initctx) {
...
-                        case info: TypeBounds  => info                       // Will already trigger a MatchResult.NoInstances
-                        case _                 => RealTypeBounds(info, info) // Explicitly trigger a MatchResult.NoInstances
-                  case _ => info
-                rec(capture, info1, variance = 0, scrutIsWidenedAbstract)
+                    /* If it is a skolem type, we cannot have class selections nor
+                     * abstract type selections. If it is an alias, we try to remove
+                     * any reference to the skolem from the right-hand-side. If that
+                     * succeeds, we take the result, otherwise we fail as not-specific.
+                     */
+                    def adaptToTriggerNotSpecific(info: Type): Type = info match
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:3691]: It looks like this comment refers to the code below starting with `denot.info match`, not to the behavior of the def itself.

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: It's about the whole body of the `case SkolemType`. I added a blank line, which hopefully makes it not misleading anymore?

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Ah I see, usually we write those comments with `//`.

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I thought `/*` was just the multi-line version of `//`, whereas `/**` is the doc-of-the-`def` thing.

**Review by smarter — APPROVED** [review]
It would be nice to add a minimal testcase to illustrate the feature.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 1 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Yeah using `/*` is fine, just uncommon in this codebase I think

Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I always doc'd local defs with `/*` seeing as the docs don't appear anywhere in the scaladocs anyways, to not be misleading as to that.  It's funny how that thought process leads to unintended confusion in this case 😄

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 2]
```diff
@@ -3681,19 +3681,37 @@ class MatchReducer(initctx: Context) extends TypeComparer(initctx) {
...
-                rec(capture, info1, variance = 0, scrutIsWidenedAbstract)
+                    /* If it is a skolem type, we cannot have class selections nor
+                     * abstract type selections. If it is an alias, we try to remove
+                     * any reference to the skolem from the right-hand-side. If that
+                     * succeeds, we take the result, otherwise we fail as not-specific.
+                     */
+
+                    def adaptToTriggerNotSpecific(info: Type): Type = info match
+                      case info: TypeBounds => info
+                      case _                => RealTypeBounds(info, info)
```
Comment (dwijnand) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:3694]: This looks similar to Type#bounds.  That might or might not be appropriate here, but wanted to bring it to your attention.

**Comment by dwijnand** [comment]
I'm surprised that the spec language in https://docs.scala-lang.org/sips/match-types-spec.html isn't part of the spec in this repo.

**Comment by sjrd** [comment]
> I'm surprised that the spec language in https://docs.scala-lang.org/sips/match-types-spec.html isn't part of the spec in this repo.

I did not have time to integrate it yet. :(
