### PR TITLE
Partial function synthesis changesOwner of selector

### LINKED ISSUE #23025: IllegalArgumentException: Could not find proxy
## Compiler version

- 3.7.1-RC1-bin-20250417-05b102a-NIGHTLY
- 3.7.0-RC3
- 3.6.4
- 3.3.5

## Minimized code

build.sbt

```scala
scalaVersion := "3.7.1-RC1-bin-20250417-05b102a-NIGHTLY"
```

A.scala

```Scala
class A {
  def f: PartialFunction[Int, Int] =
    a => { (try a catch { case e : Throwable => throw e}) match { case n => n } }
}
```

## Output (click arrow to expand)

```
[error] java.lang.IllegalArgumentException: Could not find proxy for case val e: Throwable in [value e, method $anonfun, method f, class A, package <empty>, package <root>], encl = method isDefinedAt, owners = method isDefinedAt, anonymous class scala.runtime.AbstractPartialFunction with java.io.Serializable
[error]   {...}, method f, class A, package <empty>, package <root>; enclosures = method isDefinedAt, anonymous class scala.runtime.AbstractPartialFunction with java.io.Serializable
[error]   {...}, package <empty>, package <root>
[error] dotty.tools.dotc.transform.LambdaLift$Lifter.searchIn$1(LambdaLift.scala:137)
[error] dotty.tools.dotc.transform.LambdaLift$Lifter.proxy(LambdaLift.scala:150)
[error] dotty.tools.dotc.transform.LambdaLift$Lifter.proxyRef(LambdaLift.scala:168)
[error] dotty.tools.dotc.transform.LambdaLift.transformIdent(LambdaLift.scala:287)
[error] dotty.tools.dotc.transform.MegaPhase.goIdent(MegaPhase.scala:621)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:240)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:452)
[error] dotty.tools.dotc.transform.MegaPhase.loop$3(MegaPhase.scala:486)
[error] dotty.tools.dotc.transform.MegaPhase.transformTrees(MegaPhase.scala:486)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:296)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:454)
[error] dotty.tools.dotc.transform.MegaPhase.loop$2$$anonfun$1(MegaPhase.scala:474)
[error] dotty.tools.dotc.transform.MegaPhase.loop$2(MegaPhase.scala:476)
[error] dotty.tools.dotc.transform.MegaPhase.transformBlock(MegaPhase.scala:476)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:315)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:454)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:345)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:454)
[error] dotty.tools.dotc.transform.MegaPhase.loop$3(MegaPhase.scala:486)
[error] dotty.tools.dotc.transform.MegaPhase.transformTrees(MegaPhase.scala:486)
[error] dotty.tools.dotc.transform.MegaPhase.transformSpecificTrees(MegaPhase.scala:489)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:404)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:454)
[error] dotty.tools.dotc.transform.MegaPhase.mapValDef$1(MegaPhase.scala:251)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:256)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:452)
[error] dotty.tools.dotc.transform.MegaPhase.loop$2(MegaPhase.scala:471)
[error] dotty.tools.dotc.transform.MegaPhase.transformBlock(MegaPhase.scala:476)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:315)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:454)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:278)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:452)
[error] dotty.tools.dotc.transform.MegaPhase.mapDefDef$1(MegaPhase.scala:265)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:268)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:452)
[error] dotty.tools.dotc.transform.MegaPhase.loop$1(MegaPhase.scala:465)
[error] dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:465)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:376)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:454)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:272)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:452)
[error] dotty.tools.dotc.transform.MegaPhase.loop$2(MegaPhase.scala:471)
[error] dotty.tools.dotc.transform.MegaPhase.transformBlock(MegaPhase.scala:476)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:315)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:454)
[error] dotty.tools.dotc.transform.MegaPhase.mapDefDef$1(MegaPhase.scala:265)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:268)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:452)
[error] dotty.tools.dotc.transform.MegaPhase.loop$1(MegaPhase.scala:465)
[error] dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:465)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:376)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:454)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:272)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:452)
[error] dotty.tools.dotc.transform.MegaPhase.loop$1(MegaPhase.scala:465)
[error] dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:465)
[error] dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:396)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:399)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:454)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:481)
[error] dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:493)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:383)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:334)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:376)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:368)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1324)
[error] dotty.tools.dotc.Run.runPhases$1(Run.scala:361)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$2(Run.scala:408)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$adapted$1(Run.scala:408)
[error] scala.Function0.apply$mcV$sp(Function0.scala:42)
[error] dotty.tools.dotc.Run.showProgress(Run.scala:470)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:408)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:420)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:420)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:307)
[error] dotty.tools.dotc.Run.compile(Run.scala:292)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:141)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:196)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:252)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:166)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:241)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:166)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:214)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:542)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:542)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$3(Incremental.scala:182)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$3$adapted(Incremental.scala:180)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:458)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:264)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:413)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:500)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:400)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:208)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:542)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:496)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:433)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2471)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2421)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:41)
[error] sbt.internal.io.Retry$.sbt$internal$io$Retry$$impl(Retry.scala:114)
[error] sbt.internal.io.Retry$.io(Retry.scala:102)
[error] sbt.internal.io.Retry$.io(Retry.scala:78)
[error] sbt.internal.io.Retry$.io(Retry.scala:67)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:41)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2419)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] sbt.Execute.work(Execute.scala:292)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] java.base/java.lang.Thread.run(Thread.java:1583)
[error]            
[error] stack trace is suppressed; run last Compile / compileIncremental for the full output
[error] (Compile / compileIncremental) java.lang.IllegalArgumentException: Could not find proxy for case val e: Throwable in [value e, method $anonfun, method f, class A, package <empty>, package <root>], encl = method isDefinedAt, owners = method isDefinedAt, anonymous class scala.runtime.AbstractPartialFunction with java.io.Serializable
[error]   {...}, method f, class A, package <empty>, package <root>; enclosures = method isDefinedAt, anonymous class scala.runtime.AbstractPartialFunction with java.io.Serializable
[error]   {...}, package <empty>, package <root>
```

### LINKED ISSUE #23054: Bad owner of anonymous function after expandSAMs
## Compiler version

3.6.4

## Minimized code

```Scala
object Bug:

  def m0(f: PartialFunction[Char, Unit]): Unit = ()

  def m1(): Unit =
    m0: x =>
      "abc".filter(_ == x) match
        case _ => ()

```

## Output (click arrow to expand)

See bug.log (or the more readable bug-nocolor.log) in attached zip file.

[files.zip](https://github.com/user-attachments/files/19924824/files.zip)

### LINKED ISSUE #23310: Compiler crash when chaining two matches
## Compiler version

3.3.5 and 3.3.6 

## Minimized code

```Scala
object Example {
    val pf: PartialFunction[Unit, Unit] = s => (s match {
      case a => a
    }) match {
      case a => ()
    }
}
```

## Output (click arrow to expand)

<details>

```scala
java.util.NoSuchElementException: key not found: method $anonfun while traversing x4
java.util.NoSuchElementException: key not found: method $anonfun while traversing case val a: scala.runtime.BoxedUnit = x4
java.util.NoSuchElementException: key not found: method $anonfun while traversing {
  case val x4: scala.runtime.BoxedUnit = x
  case val a: scala.runtime.BoxedUnit = x4
  return[matchResult2]
    {
      ()
    }
}
java.util.NoSuchElementException: key not found: method $anonfun while traversing matchResult2[Unit]: 
  {
    case val x4: scala.runtime.BoxedUnit = x
    case val a: scala.runtime.BoxedUnit = x4
    return[matchResult2]
      {
        ()
      }
  }
java.util.NoSuchElementException: key not found: method $anonfun while traversing {
  matchResult2[Unit]: 
    {
      case val x4: scala.runtime.BoxedUnit = x
      case val a: scala.runtime.BoxedUnit = x4
      return[matchResult2]
        {
          ()
        }
    }
  scala.runtime.BoxedUnit.UNIT
}
java.util.NoSuchElementException: key not found: method $anonfun while traversing case val x5: scala.runtime.BoxedUnit =
  {
    matchResult2[Unit]: 
      {
        case val x4: scala.runtime.BoxedUnit = x
        case val a: scala.runtime.BoxedUnit = x4
        return[matchResult2]
          {
            ()
          }
      }
    scala.runtime.BoxedUnit.UNIT
  }
java.util.NoSuchElementException: key not found: method $anonfun while traversing {
  case val x5: scala.runtime.BoxedUnit =
    {
      matchResult2[Unit]: 
        {
          case val x4: scala.runtime.BoxedUnit = x
          case val a: scala.runtime.BoxedUnit = x4
          return[matchResult2]
            {
              ()
            }
        }
      scala.runtime.BoxedUnit.UNIT
    }
  case val a: scala.runtime.BoxedUnit = x5
  return[matchResult3] true
}
java.util.NoSuchElementException: key not found: method $anonfun while traversing matchResult3[Boolean]: 
  {
    case val x5: scala.runtime.BoxedUnit =
      {
        matchResult2[Unit]: 
          {
            case val x4: scala.runtime.BoxedUnit = x
            case val a: scala.runtime.BoxedUnit = x4
            return[matchResult2]
              {
                ()
              }
          }
        scala.runtime.BoxedUnit.UNIT
      }
    case val a: scala.runtime.BoxedUnit = x5
    return[matchResult3] true
  }
java.util.NoSuchElementException: key not found: method $anonfun while traversing override final def isDefinedAt(x: scala.runtime.BoxedUnit): Boolean =
  matchResult3[Boolean]: 
    {
      case val x5: scala.runtime.BoxedUnit =
        {
          matchResult2[Unit]: 
            {
              case val x4: scala.runtime.BoxedUnit = x
              case val a: scala.runtime.BoxedUnit = x4
              return[matchResult2]
                {
                  ()
                }
            }
          scala.runtime.BoxedUnit.UNIT
        }
      case val a: scala.runtime.BoxedUnit = x5
      return[matchResult3] true
    }
java.util.NoSuchElementException: key not found: method $anonfun while traversing  extends scala.runtime.AbstractPartialFunction, java.io.Serializable {
  def <init>(): Unit =
    {
      super()
      ()
    }
  override final def isDefinedAt(x: scala.runtime.BoxedUnit): Boolean =
    matchResult3[Boolean]: 
      {
        case val x5: scala.runtime.BoxedUnit =
          {
            matchResult2[Unit]: 
              {
                case val x4: scala.runtime.BoxedUnit = x
                case val a: scala.runtime.BoxedUnit = x4
                return[matchResult2]
                  {
                    ()
                  }
              }
            scala.runtime.BoxedUnit.UNIT
          }
        case val a: scala.runtime.BoxedUnit = x5
        return[matchResult3] true
      }
  override final def applyOrElse(x: scala.runtime.BoxedUnit, default: Function1)
    : Object =
    {
      matchResult5[Unit]: 
        {
          case val x7: scala.runtime.BoxedUnit =
            {
              matchResult4[Unit]: 
                {
                  case val x6: scala.runtime.BoxedUnit = x
                  case val a: scala.runtime.BoxedUnit = x6
                  return[matchResult4]
                    {
                      ()
                    }
                }
              scala.runtime.BoxedUnit.UNIT
            }
          case val a: scala.runtime.BoxedUnit = x7
          return[matchResult5]
            {
              ()
            }
        }
      scala.runtime.BoxedUnit.UNIT
    }
  override final def isDefinedAt(x: Object): Boolean =
    this.isDefinedAt(x.asInstanceOf[scala.runtime.BoxedUnit])
  override final def applyOrElse(x: Object, default: Function1): Object =
    this.applyOrElse(x.asInstanceOf[scala.runtime.BoxedUnit], default)
}
java.util.NoSuchElementException: key not found: method $anonfun while traversing final class $anon extends scala.runtime.AbstractPartialFunction, 
  java.io.Serializable {
  def <init>(): Unit =
    {
      super()
      ()
    }
  override final def isDefinedAt(x: scala.runtime.BoxedUnit): Boolean =
    matchResult3[Boolean]: 
      {
        case val x5: scala.runtime.BoxedUnit =
          {
            matchResult2[Unit]: 
              {
                case val x4: scala.runtime.BoxedUnit = x
                case val a: scala.runtime.BoxedUnit = x4
                return[matchResult2]
                  {
                    ()
                  }
              }
            scala.runtime.BoxedUnit.UNIT
          }
        case val a: scala.runtime.BoxedUnit = x5
        return[matchResult3] true
      }
  override final def applyOrElse(x: scala.runtime.BoxedUnit, default: Function1)
    : Object =
    {
      matchResult5[Unit]: 
        {
          case val x7: scala.runtime.BoxedUnit =
            {
              matchResult4[Unit]: 
                {
                  case val x6: scala.runtime.BoxedUnit = x
                  case val a: scala.runtime.BoxedUnit = x6
                  return[matchResult4]
                    {
                      ()
                    }
                }
              scala.runtime.BoxedUnit.UNIT
            }
          case val a: scala.runtime.BoxedUnit = x7
          return[matchResult5]
            {
              ()
            }
        }
      scala.runtime.BoxedUnit.UNIT
    }
  override final def isDefinedAt(x: Object): Boolean =
    this.isDefinedAt(x.asInstanceOf[scala.runtime.BoxedUnit])
  override final def applyOrElse(x: Object, default: Function1): Object =
    this.applyOrElse(x.asInstanceOf[scala.runtime.BoxedUnit], default)
}
java.util.NoSuchElementException: key not found: method $anonfun while traversing {
  final class $anon extends scala.runtime.AbstractPartialFunction, 
    java.io.Serializable {
    def <init>(): Unit =
      {
        super()
        ()
      }
    override final def isDefinedAt(x: scala.runtime.BoxedUnit): Boolean =
      matchResult3[Boolean]: 
        {
          case val x5: scala.runtime.BoxedUnit =
            {
              matchResult2[Unit]: 
                {
                  case val x4: scala.runtime.BoxedUnit = x
                  case val a: scala.runtime.BoxedUnit = x4
                  return[matchResult2]
                    {
                      ()
                    }
                }
              scala.runtime.BoxedUnit.UNIT
            }
          case val a: scala.runtime.BoxedUnit = x5
          return[matchResult3] true
        }
    override final def applyOrElse(x: scala.runtime.BoxedUnit,
      default: Function1): Object =
      {
        matchResult5[Unit]: 
          {
            case val x7: scala.runtime.BoxedUnit =
              {
                matchResult4[Unit]: 
                  {
                    case val x6: scala.runtime.BoxedUnit = x
                    case val a: scala.runtime.BoxedUnit = x6
                    return[matchResult4]
                      {
                        ()
                      }
                  }
                scala.runtime.BoxedUnit.UNIT
              }
            case val a: scala.runtime.BoxedUnit = x7
            return[matchResult5]
              {
                ()
              }
          }
        scala.runtime.BoxedUnit.UNIT
      }
    override final def isDefinedAt(x: Object): Boolean =
      this.isDefinedAt(x.asInstanceOf[scala.runtime.BoxedUnit])
    override final def applyOrElse(x: Object, default: Function1): Object =
      this.applyOrElse(x.asInstanceOf[scala.runtime.BoxedUnit], default)
  }
  new scala.runtime.AbstractPartialFunction with java.io.Serializable {...}():
    scala.runtime.AbstractPartialFunction
}
java.util.NoSuchElementException: key not found: method $anonfun while traversing Playground.Example.pf =
  {
    final class $anon extends scala.runtime.AbstractPartialFunction, 
      java.io.Serializable {
      def <init>(): Unit =
        {
          super()
          ()
        }
      override final def isDefinedAt(x: scala.runtime.BoxedUnit): Boolean =
        matchResult3[Boolean]: 
          {
            case val x5: scala.runtime.BoxedUnit =
              {
                matchResult2[Unit]: 
                  {
                    case val x4: scala.runtime.BoxedUnit = x
                    case val a: scala.runtime.BoxedUnit = x4
                    return[matchResult2]
                      {
                        ()
                      }
                  }
                scala.runtime.BoxedUnit.UNIT
              }
            case val a: scala.runtime.BoxedUnit = x5
            return[matchResult3] true
          }
      override final def applyOrElse(x: scala.runtime.BoxedUnit,
        default: Function1): Object =
        {
          matchResult5[Unit]: 
            {
              case val x7: scala.runtime.BoxedUnit =
                {
                  matchResult4[Unit]: 
                    {
                      case val x6: scala.runtime.BoxedUnit = x
                      case val a: scala.runtime.BoxedUnit = x6
                      return[matchResult4]
                        {
                          ()
                        }
                    }
                  scala.runtime.BoxedUnit.UNIT
                }
              case val a: scala.runtime.BoxedUnit = x7
              return[matchResult5]
                {
                  ()
                }
            }
          scala.runtime.BoxedUnit.UNIT
        }
      override final def isDefinedAt(x: Object): Boolean =
        this.isDefinedAt(x.asInstanceOf[scala.runtime.BoxedUnit])
      override final def applyOrElse(x: Object, default: Function1): Object =
        this.applyOrElse(x.asInstanceOf[scala.runtime.BoxedUnit], default)
    }
    new scala.runtime.AbstractPartialFunction with java.io.Serializable {...}():
      scala.runtime.AbstractPartialFunction
  }
java.util.NoSuchElementException: key not found: method $anonfun while traversing {
  super()
  Playground.Example.pf =
    {
      final class $anon extends scala.runtime.AbstractPartialFunction, 
        java.io.Serializable {
        def <init>(): Unit =
          {
            super()
            ()
          }
        override final def isDefinedAt(x: scala.runtime.BoxedUnit): Boolean =
          matchResult3[Boolean]: 
            {
              case val x5: scala.runtime.BoxedUnit =
                {
                  matchResult2[Unit]: 
                    {
                      case val x4: scala.runtime.BoxedUnit = x
                      case val a: scala.runtime.BoxedUnit = x4
                      return[matchResult2]
                        {
                          ()
                        }
                    }
                  scala.runtime.BoxedUnit.UNIT
                }
              case val a: scala.runtime.BoxedUnit = x5
              return[matchResult3] true
            }
        override final def applyOrElse(x: scala.runtime.BoxedUnit,
          default: Function1): Object =
          {
            matchResult5[Unit]: 
              {
                case val x7: scala.runtime.BoxedUnit =
                  {
                    matchResult4[Unit]: 
                      {
                        case val x6: scala.runtime.BoxedUnit = x
                        case val a: scala.runtime.BoxedUnit = x6
                        return[matchResult4]
                          {
                            ()
                          }
                      }
                    scala.runtime.BoxedUnit.UNIT
                  }
                case val a: scala.runtime.BoxedUnit = x7
                return[matchResult5]
                  {
                    ()
                  }
              }
            scala.runtime.BoxedUnit.UNIT
          }
        override final def isDefinedAt(x: Object): Boolean =
          this.isDefinedAt(x.asInstanceOf[scala.runtime.BoxedUnit])
        override final def applyOrElse(x: Object, default: Function1): Object =
          this.applyOrElse(x.asInstanceOf[scala.runtime.BoxedUnit], default)
      }
      new scala.runtime.AbstractPartialFunction with java.io.Serializable {...}(
        ):scala.runtime.AbstractPartialFunction
    }
  ()
}
java.util.NoSuchElementException: key not found: method $anonfun while traversing def <init>(): Unit =
  {
    super()
    Playground.Example.pf =
      {
        final class $anon extends scala.runtime.AbstractPartialFunction, 
          java.io.Serializable {
          def <init>(): Unit =
            {
              super()
              ()
            }
          override final def isDefinedAt(x: scala.runtime.BoxedUnit): Boolean =
            matchResult3[Boolean]: 
              {
                case val x5: scala.runtime.BoxedUnit =
                  {
                    matchResult2[Unit]: 
                      {
                        case val x4: scala.runtime.BoxedUnit = x
                        case val a: scala.runtime.BoxedUnit = x4
                        return[matchResult2]
                          {
                            ()
                          }
                      }
                    scala.runtime.BoxedUnit.UNIT
                  }
                case val a: scala.runtime.BoxedUnit = x5
                return[matchResult3] true
              }
          override final def applyOrElse(x: scala.runtime.BoxedUnit,
            default: Function1): Object =
            {
              matchResult5[Unit]: 
                {
                  case val x7: scala.runtime.BoxedUnit =
                    {
                      matchResult4[Unit]: 
                        {
                          case val x6: scala.runtime.BoxedUnit = x
                          case val a: scala.runtime.BoxedUnit = x6
                          return[matchResult4]
                            {
                              ()
                            }
                        }
                      scala.runtime.BoxedUnit.UNIT
                    }
                  case val a: scala.runtime.BoxedUnit = x7
                  return[matchResult5]
                    {
                      ()
                    }
                }
              scala.runtime.BoxedUnit.UNIT
            }
          override final def isDefinedAt(x: Object): Boolean =
            this.isDefinedAt(x.asInstanceOf[scala.runtime.BoxedUnit])
          override final def applyOrElse(x: Object, default: Function1): Object
             =
            this.applyOrElse(x.asInstanceOf[scala.runtime.BoxedUnit], default)
        }
        new 
          scala.runtime.AbstractPartialFunction with java.io.Serializable {...}(
          ):scala.runtime.AbstractPartialFunction
      }
    ()
  }
java.util.NoSuchElementException: key not found: method $anonfun while traversing  extends Object {
  def <init>(): Unit =
    {
      super()
      Playground.Example.pf =
        {
          final class $anon extends scala.runtime.AbstractPartialFunction, 
            java.io.Serializable {
            def <init>(): Unit =
              {
                super()
                ()
              }
            override final def isDefinedAt(x: scala.runtime.BoxedUnit): Boolean
               =
              matchResult3[Boolean]: 
                {
                  case val x5: scala.runtime.BoxedUnit =
                    {
                      matchResult2[Unit]: 
                        {
                          case val x4: scala.runtime.BoxedUnit = x
                          case val a: scala.runtime.BoxedUnit = x4
                          return[matchResult2]
                            {
                              ()
                            }
                        }
                      scala.runtime.BoxedUnit.UNIT
                    }
                  case val a: scala.runtime.BoxedUnit = x5
                  return[matchResult3] true
                }
            override final def applyOrElse(x: scala.runtime.BoxedUnit,
              default: Function1): Object =
              {
                matchResult5[Unit]: 
                  {
                    case val x7: scala.runtime.BoxedUnit =
                      {
                        matchResult4[Unit]: 
                          {
                            case val x6: scala.runtime.BoxedUnit = x
                            case val a: scala.runtime.BoxedUnit = x6
                            return[matchResult4]
                              {
                                ()
                              }
                          }
                        scala.runtime.BoxedUnit.UNIT
                      }
                    case val a: scala.runtime.BoxedUnit = x7
                    return[matchResult5]
                      {
                        ()
                      }
                  }
                scala.runtime.BoxedUnit.UNIT
              }
            override final def isDefinedAt(x: Object): Boolean =
              this.isDefinedAt(x.asInstanceOf[scala.runtime.BoxedUnit])
            override final def applyOrElse(x: Object, default: Function1):
              Object =
              this.applyOrElse(x.asInstanceOf[scala.runtime.BoxedUnit], default)
            }
          new 
            scala.runtime.AbstractPartialFunction with java.io.Serializable
              {...}
          ():scala.runtime.AbstractPartialFunction
        }
      ()
    }
  private def writeReplace(): Object =
    new scala.runtime.ModuleSerializationProxy(classOf[Playground.Example])
  private val pf: PartialFunction
  def pf(): PartialFunction = Playground.Example.pf
}
java.util.NoSuchElementException: key not found: method $anonfun while traversing final module class Example extends Object {
  def <init>(): Unit =
    {
      super()
      Playground.Example.pf =
        {
          final class $anon extends scala.runtime.AbstractPartialFunction, 
            java.io.Serializable {
            def <init>(): Unit =
              {
                super()
                ()
              }
            override final def isDefinedAt(x: scala.runtime.BoxedUnit): Boolean
               =
              matchResult3[Boolean]: 
                {
                  case val x5: scala.runtime.BoxedUnit =
                    {
                      matchResult2[Unit]: 
                        {
                          case val x4: scala.runtime.BoxedUnit = x
                          case val a: scala.runtime.BoxedUnit = x4
                          return[matchResult2]
                            {
                              ()
                            }
                        }
                      scala.runtime.BoxedUnit.UNIT
                    }
                  case val a: scala.runtime.BoxedUnit = x5
                  return[matchResult3] true
                }
            override final def applyOrElse(x: scala.runtime.BoxedUnit,
              default: Function1): Object =
              {
                matchResult5[Unit]: 
                  {
                    case val x7: scala.runtime.BoxedUnit =
                      {
                        matchResult4[Unit]: 
                          {
                            case val x6: scala.runtime.BoxedUnit = x
                            case val a: scala.runtime.BoxedUnit = x6
                            return[matchResult4]
                              {
                                ()
                              }
                          }
                        scala.runtime.BoxedUnit.UNIT
                      }
                    case val a: scala.runtime.BoxedUnit = x7
                    return[matchResult5]
                      {
                        ()
                      }
                  }
                scala.runtime.BoxedUnit.UNIT
              }
            override final def isDefinedAt(x: Object): Boolean =
              this.isDefinedAt(x.asInstanceOf[scala.runtime.BoxedUnit])
            override final def applyOrElse(x: Object, default: Function1):
              Object =
              this.applyOrElse(x.asInstanceOf[scala.runtime.BoxedUnit], default)
            }
          new 
            scala.runtime.AbstractPartialFunction with java.io.Serializable
              {...}
          ():scala.runtime.AbstractPartialFunction
        }
      ()
    }
  private def writeReplace(): Object =
    new scala.runtime.ModuleSerializationProxy(classOf[Playground.Example])
  private val pf: PartialFunction
  def pf(): PartialFunction = Playground.Example.pf
}
java.util.NoSuchElementException: key not found: method $anonfun while traversing  extends Object, com.olegych.scastie.api.runtime.package.ScastieApp {
  def <init>(): Unit =
    {
      super()
      super[App].<init>()
      Playground.instrumentationMap =
        _root_.scala.collection.mutable.Map.empty().asInstanceOf[
          scala.collection.mutable.Map]
      scala.runtime.Statics.releaseFence()
      ()
    }
  private var executionStart: Long
  final def executionStart(): Long = Playground.executionStart
  private var scala$App$$_args: String[]
  def scala$App$$_args(): String[] = Playground.scala$App$$_args
  private var scala$App$$initCode: scala.collection.mutable.ListBuffer
  def scala$App$$initCode(): scala.collection.mutable.ListBuffer =
    Playground.scala$App$$initCode
  def scala$App$$_args_=(x$1: String[]): Unit =
    Playground.scala$App$$_args = x$1
  def scala$App$_setter_$executionStart_$eq(x$0: Long): Unit =
    Playground.executionStart = x$0
  def scala$App$_setter_$scala$App$$initCode_$eq(
    x$0: scala.collection.mutable.ListBuffer): Unit =
    Playground.scala$App$$initCode = x$0
  protected final def args(): String[] = super[App].args()
  @deprecated(message = "the delayedInit mechanism will disappear",
    since = "2.11.0") override def delayedInit(body: Function0): Unit =
    super[App].delayedInit(body)
  final def main(args: String[]): Unit = super[App].main(args)
  private def writeReplace(): Object =
    new scala.runtime.ModuleSerializationProxy(classOf[Playground])
  private val instrumentationMap: scala.collection.mutable.Map
  def instrumentations(): scala.collection.immutable.List =
    Playground.instrumentationMap.toList().map(
      {
        def $anonfun(x$1: Tuple2): com.olegych.scastie.api.Instrumentation =
          matchResult1[com.olegych.scastie.api.Instrumentation]: 
            {
              case val x1: Tuple2 = x$1
              if x1.ne(null) then
                {
                  case val pos: com.olegych.scastie.api.Position =
                    x1._1().asInstanceOf[com.olegych.scastie.api.Position]
                  case val r: com.olegych.scastie.api.Render =
                    x1._2().asInstanceOf[com.olegych.scastie.api.Render]
                  return[matchResult1]
                    {
                      _root_.com.olegych.scastie.api.Instrumentation.apply(pos,
                        r)
                    }
                }
               else ()
              throw new MatchError(x1)
            }
        closure($anonfun)
      }
    )
  final lazy module val Example: Playground.Example = new Playground.Example()
  final module class Example extends Object {
    def <init>(): Unit =
      {
        super()
        Playground.Example.pf =
          {
            final class $anon extends scala.runtime.AbstractPartialFunction, 
              java.io.Serializable {
              def <init>(): Unit =
                {
                  super()
                  ()
                }
              override final def isDefinedAt(x: scala.runtime.BoxedUnit):
                Boolean =
                matchResult3[Boolean]: 
                  {
                    case val x5: scala.runtime.BoxedUnit =
                      {
                        matchResult2[Unit]: 
                          {
                            case val x4: scala.runtime.BoxedUnit = x
                            case val a: scala.runtime.BoxedUnit = x4
                            return[matchResult2]
                              {
                                ()
                              }
                          }
                        scala.runtime.BoxedUnit.UNIT
                      }
                    case val a: scala.runtime.BoxedUnit = x5
                    return[matchResult3] true
                  }
              override final def applyOrElse(x: scala.runtime.BoxedUnit,
                default: Function1): Object =
                {
                  matchResult5[Unit]: 
                    {
                      case val x7: scala.runtime.BoxedUnit =
                        {
                          matchResult4[Unit]: 
                            {
                              case val x6: scala.runtime.BoxedUnit = x
                              case val a: scala.runtime.BoxedUnit = x6
                              return[matchResult4]
                                {
                                  ()
                                }
                            }
                          scala.runtime.BoxedUnit.UNIT
                        }
                      case val a: scala.runtime.BoxedUnit = x7
                      return[matchResult5]
                        {
                          ()
                        }
                    }
                  scala.runtime.BoxedUnit.UNIT
                }
              override final def isDefinedAt(x: Object): Boolean =
                this.isDefinedAt(x.asInstanceOf[scala.runtime.BoxedUnit])
              override final def applyOrElse(x: Object, default: Function1):
                Object =
                this.applyOrElse(x.asInstanceOf[scala.runtime.BoxedUnit],
                  default)
            }
            new 
              scala.runtime.AbstractPartialFunction with java.io.Serializable
                {...}
            ():scala.runtime.AbstractPartialFunction
          }
        ()
      }
    private def writeReplace(): Object =
      new scala.runtime.ModuleSerializationProxy(classOf[Playground.Example])
    private val pf: PartialFunction
    def pf(): PartialFunction = Playground.Example.pf
  }
}
java.util.NoSuchElementException: key not found: method $anonfun while traversing @SourceFile("src/main/scala/main.scala") final module class Playground extends
  Object, com.olegych.scastie.api.runtime.package.ScastieApp {
  def <init>(): Unit =
    {
      super()
      super[App].<init>()
      Playground.instrumentationMap =
        _root_.scala.collection.mutable.Map.empty().asInstanceOf[
          scala.collection.mutable.Map]
      scala.runtime.Statics.releaseFence()
      ()
    }
  private var executionStart: Long
  final def executionStart(): Long = Playground.executionStart
  private var scala$App$$_args: String[]
  def scala$App$$_args(): String[] = Playground.scala$App$$_args
  private var scala$App$$initCode: scala.collection.mutable.ListBuffer
  def scala$App$$initCode(): scala.collection.mutable.ListBuffer =
    Playground.scala$App$$initCode
  def scala$App$$_args_=(x$1: String[]): Unit =
    Playground.scala$App$$_args = x$1
  def scala$App$_setter_$executionStart_$eq(x$0: Long): Unit =
    Playground.executionStart = x$0
  def scala$App$_setter_$scala$App$$initCode_$eq(
    x$0: scala.collection.mutable.ListBuffer): Unit =
    Playground.scala$App$$initCode = x$0
  protected final def args(): String[] = super[App].args()
  @deprecated(message = "the delayedInit mechanism will disappear",
    since = "2.11.0") override def delayedInit(body: Function0): Unit =
    super[App].delayedInit(body)
  final def main(args: String[]): Unit = super[App].main(args)
  private def writeReplace(): Object =
    new scala.runtime.ModuleSerializationProxy(classOf[Playground])
  private val instrumentationMap: scala.collection.mutable.Map
  def instrumentations(): scala.collection.immutable.List =
    Playground.instrumentationMap.toList().map(
      {
        def $anonfun(x$1: Tuple2): com.olegych.scastie.api.Instrumentation =
          matchResult1[com.olegych.scastie.api.Instrumentation]: 
            {
              case val x1: Tuple2 = x$1
              if x1.ne(null) then
                {
                  case val pos: com.olegych.scastie.api.Position =
                    x1._1().asInstanceOf[com.olegych.scastie.api.Position]
                  case val r: com.olegych.scastie.api.Render =
                    x1._2().asInstanceOf[com.olegych.scastie.api.Render]
                  return[matchResult1]
                    {
                      _root_.com.olegych.scastie.api.Instrumentation.apply(pos,
                        r)
                    }
                }
               else ()
              throw new MatchError(x1)
            }
        closure($anonfun)
      }
    )
  final lazy module val Example: Playground.Example = new Playground.Example()
  final module class Example extends Object {
    def <init>(): Unit =
      {
        super()
        Playground.Example.pf =
          {
            final class $anon extends scala.runtime.AbstractPartialFunction, 
              java.io.Serializable {
              def <init>(): Unit =
                {
                  super()
                  ()
                }
              override final def isDefinedAt(x: scala.runtime.BoxedUnit):
                Boolean =
                matchResult3[Boolean]: 
                  {
                    case val x5: scala.runtime.BoxedUnit =
                      {
                        matchResult2[Unit]: 
                          {
                            case val x4: scala.runtime.BoxedUnit = x
                            case val a: scala.runtime.BoxedUnit = x4
                            return[matchResult2]
                              {
                                ()
                              }
                          }
                        scala.runtime.BoxedUnit.UNIT
                      }
                    case val a: scala.runtime.BoxedUnit = x5
                    return[matchResult3] true
                  }
              override final def applyOrElse(x: scala.runtime.BoxedUnit,
                default: Function1): Object =
                {
                  matchResult5[Unit]: 
                    {
                      case val x7: scala.runtime.BoxedUnit =
                        {
                          matchResult4[Unit]: 
                            {
                              case val x6: scala.runtime.BoxedUnit = x
                              case val a: scala.runtime.BoxedUnit = x6
                              return[matchResult4]
                                {
                                  ()
                                }
                            }
                          scala.runtime.BoxedUnit.UNIT
                        }
                      case val a: scala.runtime.BoxedUnit = x7
                      return[matchResult5]
                        {
                          ()
                        }
                    }
                  scala.runtime.BoxedUnit.UNIT
                }
              override final def isDefinedAt(x: Object): Boolean =
                this.isDefinedAt(x.asInstanceOf[scala.runtime.BoxedUnit])
              override final def applyOrElse(x: Object, default: Function1):
                Object =
                this.applyOrElse(x.asInstanceOf[scala.runtime.BoxedUnit],
                  default)
            }
            new 
              scala.runtime.AbstractPartialFunction with java.io.Serializable
                {...}
            ():scala.runtime.AbstractPartialFunction
          }
        ()
      }
    private def writeReplace(): Object =
      new scala.runtime.ModuleSerializationProxy(classOf[Playground.Example])
    private val pf: PartialFunction
    def pf(): PartialFunction = Playground.Example.pf
  }
}
java.util.NoSuchElementException: key not found: method $anonfun while traversing package <empty> {
  final lazy module val Playground: Playground = new Playground()
  @SourceFile("src/main/scala/main.scala") final module class Playground extends
     Object, com.olegych.scastie.api.runtime.package.ScastieApp {
    def <init>(): Unit =
      {
        super()
        super[App].<init>()
        Playground.instrumentationMap =
          _root_.scala.collection.mutable.Map.empty().asInstanceOf[
            scala.collection.mutable.Map]
        scala.runtime.Statics.releaseFence()
        ()
      }
    private var executionStart: Long
    final def executionStart(): Long = Playground.executionStart
    private var scala$App$$_args: String[]
    def scala$App$$_args(): String[] = Playground.scala$App$$_args
    private var scala$App$$initCode: scala.collection.mutable.ListBuffer
    def scala$App$$initCode(): scala.collection.mutable.ListBuffer =
      Playground.scala$App$$initCode
    def scala$App$$_args_=(x$1: String[]): Unit =
      Playground.scala$App$$_args = x$1
    def scala$App$_setter_$executionStart_$eq(x$0: Long): Unit =
      Playground.executionStart = x$0
    def scala$App$_setter_$scala$App$$initCode_$eq(
      x$0: scala.collection.mutable.ListBuffer): Unit =
      Playground.scala$App$$initCode = x$0
    protected final def args(): String[] = super[App].args()
    @deprecated(message = "the delayedInit mechanism will disappear",
      since = "2.11.0") override def delayedInit(body: Function0): Unit =
      super[App].delayedInit(body)
    final def main(args: String[]): Unit = super[App].main(args)
    private def writeReplace(): Object =
      new scala.runtime.ModuleSerializationProxy(classOf[Playground])
    private val instrumentationMap: scala.collection.mutable.Map
    def instrumentations(): scala.collection.immutable.List =
      Playground.instrumentationMap.toList().map(
        {
          def $anonfun(x$1: Tuple2): com.olegych.scastie.api.Instrumentation =
            matchResult1[com.olegych.scastie.api.Instrumentation]: 
              {
                case val x1: Tuple2 = x$1
                if x1.ne(null) then
                  {
                    case val pos: com.olegych.scastie.api.Position =
                      x1._1().asInstanceOf[com.olegych.scastie.api.Position]
                    case val r: com.olegych.scastie.api.Render =
                      x1._2().asInstanceOf[com.olegych.scastie.api.Render]
                    return[matchResult1]
                      {
                        _root_.com.olegych.scastie.api.Instrumentation.apply(
                          pos, r)
                      }
                  }
                 else ()
                throw new MatchError(x1)
              }
          closure($anonfun)
        }
      )
    final lazy module val Example: Playground.Example = new Playground.Example()
    final module class Example extends Object {
      def <init>(): Unit =
        {
          super()
          Playground.Example.pf =
            {
              final class $anon extends scala.runtime.AbstractPartialFunction, 
                java.io.Serializable {
                def <init>(): Unit =
                  {
                    super()
                    ()
                  }
                override final def isDefinedAt(x: scala.runtime.BoxedUnit):
                  Boolean =
                  matchResult3[Boolean]: 
                    {
                      case val x5: scala.runtime.BoxedUnit =
                        {
                          matchResult2[Unit]: 
                            {
                              case val x4: scala.runtime.BoxedUnit = x
                              case val a: scala.runtime.BoxedUnit = x4
                              return[matchResult2]
                                {
                                  ()
                                }
                            }
                          scala.runtime.BoxedUnit.UNIT
                        }
                      case val a: scala.runtime.BoxedUnit = x5
                      return[matchResult3] true
                    }
                override final def applyOrElse(x: scala.runtime.BoxedUnit,
                  default: Function1): Object =
                  {
                    matchResult5[Unit]: 
                      {
                        case val x7: scala.runtime.BoxedUnit =
                          {
                            matchResult4[Unit]: 
                              {
                                case val x6: scala.runtime.BoxedUnit = x
                                case val a: scala.runtime.BoxedUnit = x6
                                return[matchResult4]
                                  {
                                    ()
                                  }
                              }
                            scala.runtime.BoxedUnit.UNIT
                          }
                        case val a: scala.runtime.BoxedUnit = x7
                        return[matchResult5]
                          {
                            ()
                          }
                      }
                    scala.runtime.BoxedUnit.UNIT
                  }
                override final def isDefinedAt(x: Object): Boolean =
                  this.isDefinedAt(x.asInstanceOf[scala.runtime.BoxedUnit])
                override final def applyOrElse(x: Object, default: Function1):
                  Object =
                  this.applyOrElse(x.asInstanceOf[scala.runtime.BoxedUnit],
                    default)
              }
              new 
                scala.runtime.AbstractPartialFunction with java.io.Serializable
                  {...}
              ():scala.runtime.AbstractPartialFunction
            }
          ()
        }
      private def writeReplace(): Object =
        new scala.runtime.ModuleSerializationProxy(classOf[Playground.Example])
      private val pf: PartialFunction
      def pf(): PartialFunction = Playground.Example.pf
    }
  }
  final lazy module val Main: Main = new Main()
  @SourceFile("src/main/scala/main.scala") final module class Main extends 
    Object {
    def <init>(): Unit =
      {
        super()
        Main.playground = Playground
        ()
      }
    private def writeReplace(): Object =
      new scala.runtime.ModuleSerializationProxy(classOf[Main])
    def suppressUnusedWarnsScastie(): com.olegych.scastie.api.Html =
      com.olegych.scastie.api.runtime.Html()
    private val playground: Playground
    def playground(): Playground = Main.playground
    def main(args: String[]): Unit =
      {
        Main.playground().main([ : String].asInstanceOf[String[]])
        scala.Predef.println(
          "\n".+(
            _root_.com.olegych.scastie.api.runtime.Runtime.write(
              Main.playground().instrumentations())
          )
        )
      }
  }
}

  unhandled exception while running MegaPhase{lambdaLift, elimStaticThis, countOuterAccesses} on /tmp/scastie16092225585572490684/src/main/scala/main.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/lampepfl/dotty/issues/new/choose
  For non-enriched exceptions, compile with -Yno-enrich-error-messages.

     while compiling: /tmp/scastie16092225585572490684/src/main/scala/main.scala
        during phase: MegaPhase{lambdaLift, elimStaticThis, countOuterAccesses}
                mode: Mode(ImplicitsEnabled)
     library version: version 2.13.15
    compiler version: version 3.3.5
            settings: -classpath /tmp/scastie16092225585572490684/target/scala-3.3.5/classes:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.5/scala3-library_3-3.3.5.jar:/home/sbtRunnerContainer/.ivy2/local/org.scastie/runtime-scala_3/1.0.0-SNAPSHOT/jars/runtime-scala_3.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.15/scala-library-2.13.15.jar:/home/sbtRunnerContainer/.ivy2/local/org.scastie/api_3/0.30.0-SNAPSHOT/jars/api_3.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-json_3/2.10.0-RC5/play-json_3-2.10.0-RC5.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-functional_3/2.10.0-RC5/play-functional_3-2.10.0-RC5.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.11.4/jackson-core-2.11.4.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.11.4/jackson-annotations-2.11.4.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.11.4/jackson-datatype-jdk8-2.11.4.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.11.4/jackson-datatype-jsr310-2.11.4.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.11.4/jackson-databind-2.11.4.jar -d /tmp/scastie16092225585572490684/target/scala-3.3.5/classes -deprecation true -feature true
```
</details>

### PR DESCRIPTION
**Pull request by som-snytt**
The selector expression may be non-trivial.

Fixes #23054 
Fixes #23025 
Fixes #23310 

The fix is the small refactor to `matchExpr.changeOwner` where previously only the cases were included.

Another small refactor addresses an unused var.

There is a mild attempt to remedy the missing spec verbiage via a kind of post-script intended to suggest that it is a mere relaxation of the existing mechanism.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 1]
```diff
@@ -6032,19 +6032,18 @@ object Types extends TypeUtils {
     end samParent
 
     def samClass(tp: Type)(using Context): Symbol = tp match
-      case tp: ClassInfo =>
-        val cls = tp.cls
+      case tp @ ClassInfo(_, cls, _, _, _) =>
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/Types.scala]: Nitpick: I much prefer the previous `tp: ClassInfo` to this see of underscores.

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/core/Types.scala]: I do not disagree. I grepped for similar usages so I conceded.
```
compiler/src/dotty/tools/dotc/core/TypeComparer.scala:      case ClassInfo(_, cls, _, _, _) => cls.showLocated
```
I've forgotten whether I'm allowed to `case ClassInfo(cls = cls)` yet. I guess not. They say the chef is the last to eat, and it's the same with compiler features.
