### PR TITLE
Fix #25624: Scoverage and separation checking failures

### LINKED ISSUE #25624: Scoverage & Captures interaction during separation: broken assumptions about each other cause failures
## Compiler version

`3.8.3-RC3`. Checked against `upstream/main` locally, commit `5d03b33d4d3d84b53b973292bf64b474164c0e0f` as of 25th March 2026.

## Minimaled code

```scala
import caps.unsafe.unsafeAssumeSeparate

class C
type Cap = C^
def f1(c: Cap): () ->{c} c.type = () => c

def repro(): C^ =
  val x: C^ = ???
  val z1: () => Cap = f1(x)

  val z2 = unsafeAssumeSeparate:
    if x == null then
      () => x
    else
      () => C()
  unsafeAssumeSeparate(x)
```

Run with:

```bash
scalac \
  -coverage-out tmp \
  -language:experimental.captureChecking \
  -language:experimental.separationChecking \
  Minimal.scala"
```

## Output

```text
-- Error: /Users/anatolii/Projects/scala3/ctxlayer/scoverage/issue-fixing/issues/030-separation-checking-failures/reproduction/Minimal.scala:12:7
12 |    if x == null then
   |       ^
   | Separation failure: Illegal access to {x} which is hidden by the previous definition
   | of value z1 with type () => C^.
   | This type hides capabilities  {x}
   |
   | where:    => refers to a root capability in the type of value z1
   |           ^  refers to a root capability in the type of value z1
-- Error: /Users/anatolii/Projects/scala3/ctxlayer/scoverage/issue-fixing/issues/030-separation-checking-failures/reproduction/Minimal.scala:13:12
13 |      () => x
   |            ^
   | Separation failure: Illegal access to {x} which is hidden by the previous definition
   | of value z1 with type () => C^.
   | This type hides capabilities  {x}
   |
   | where:    => refers to a root capability in the type of value z1
   |           ^  refers to a root capability in the type of value z1
2 errors found
[error] nonzero exit code returned from runner: 1
[error] (scala3-compiler-bootstrapped / Compile / runMain) nonzero exit code returned from runner: 1
```

## Expectation

The same source code without `--coverage-out` passes. With `--coverage-out`, it should pass as well.

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**
Fixes #25624

Separation checking for captures relies on `unsafeAssumeSeparate` to opt out of separation checking. To detect such code, `SepCheck` uses structural matching on the trees. Coverage phase may lift some trees, breaking the assumptions about the structure.

This PR:
- Opts `unsafeAssumeSeparate` out of coverage instrumentation - we aren't really interested in coverage info on it anyway, only the body is interesting
- On lifting time, marks coverage-lifted synthetic trees with an explicit attachment
- On `SepCheck` time, opts-out synthetic trees created by coverage from separation checking - rationalle being we have already checked their rhs for separation on assignment time

## How much have you relied on LLM-based tools in this contribution?

Moderately.

## How was the solution tested?

- Ran the full bootstrapped `testCompilation --enable-coverage-phase` suite
- Run the compiler `pos` suite
- Reproduced failing tests individually before and after the fix

## Additional notes

I am not  familiar with the captures codebase, so can use help of someone familiar with it to review this PR.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala [hunk 1]
```diff
@@ -202,20 +208,35 @@ object LiftCoverage extends LiftImpure {
...
   private def noLiftArg(arg: tpd.Tree)(using Context): Boolean =
     arg match
+      case arg if isUnsafeAssumeSeparate(arg) => true
       case a: tpd.Apply => a.symbol.is(Erased) // don't lift erased applications, but lift all others
       case tpd.Block(stats, expr) => stats.forall(noLiftArg) && noLiftArg(expr)
       case tpd.Inlined(_, bindings, expr) => noLiftArg(expr)
       case tpd.Typed(expr, _) => noLiftArg(expr)
       case _ => super.noLift(arg)
 
+  def isUnsafeAssumeSeparate(tree: tpd.Tree)(using Context): Boolean = tree match
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala]: I wonder whether `LiftCoverage` should move to `InstrumentCoverage`. That seems more cohesive. But it can be done in a separate, refactor-only PR.

**Review by odersky — APPROVED** [review]
Sorry for the late review!

File: compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala (hunk 1 above)
Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala]: Good point, fixed that. The CI is currently failing on `main`, will rebase once `main` issue is fixed.

**Comment by SolalPirelli** [comment]
@anatoliykmetyuk main is green now, you can rebase this + the other one, sorry for the break

**Comment by anatoliykmetyuk** [comment]
@SolalPirelli, rebased, green now
