### PR TITLE
Fix regression: do not approximate prefixes when using memberType in reflect API

### LINKED ISSUE #22424: Regression in `scalamock/scalamock` for accessing nested types
Based on OpenCB failure `scalamock/scalamock`, version 7.1.0

## Compiler version
Fails in 3.7.0-RC1-bin-20250120-db23c08-NIGHTL
Works in 3.6.3

## Minimized code

Not minimized yet

## Output

```scala
info] compiling 71 Scala sources and 7 Java sources to /Users/wmazur/projects/scala/community-build3/repo/core/jvm/target/scala-3.7.0-RC1-bin-20250120-db23c08-NIGHTLY/test-classes ...
[error] -- Error: /Users/wmazur/projects/scala/community-build3/repo/core/shared/src/test/scala/com/paulbutcher/test/mock/MockTest.scala:318:16 
[error] 318 |        val e = mock[m.Embedded[Double]]
[error]     |                ^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |Exception occurred while executing macro expansion.
[error]     |java.lang.AssertionError: assertion failed: asTerm called on not-a-Term val <none>
[error]     |   at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error]     |   at dotty.tools.dotc.core.Symbols$Symbol.asTerm(Symbols.scala:186)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$DefDef$.apply$$anonfun$3(QuotesImpl.scala:306)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$.scala$quoted$runtime$impl$QuotesImpl$reflect$$$withDefaultPos(QuotesImpl.scala:3144)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$DefDef$.apply(QuotesImpl.scala:306)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$DefDef$.apply(QuotesImpl.scala:303)
[error]     |   at org.scalamock.clazz.MockMaker$.$anonfun$5(MockMaker.scala:141)
[error]     |   at scala.collection.immutable.List.flatMap(List.scala:294)
[error]     |   at org.scalamock.clazz.MockMaker$.instance(MockMaker.scala:98)
[error]     |   at org.scalamock.clazz.MockImpl$.mock(MockImpl.scala:34)
[error]     |
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from Mock.scala:30
[error]  30 |  inline def mock[T](implicit mockContext: MockContext): T = ${MockImpl.mock[T]('{mockContext})}
[error]     |                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]      ---------------------------------------------------------------------------
[error] -- Error: /Users/wmazur/projects/scala/community-build3/repo/core/shared/src/test/scala/newapi/NewApiSpec.scala:274:16 
[error] 274 |    val e = stub[m.Embedded[Double]]
[error]     |            ^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |Exception occurred while executing macro expansion.
[error]     |java.lang.AssertionError: assertion failed: asTerm called on not-a-Term val <none>
[error]     |   at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error]     |   at dotty.tools.dotc.core.Symbols$Symbol.asTerm(Symbols.scala:186)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$DefDef$.apply$$anonfun$3(QuotesImpl.scala:306)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$.scala$quoted$runtime$impl$QuotesImpl$reflect$$$withDefaultPos(QuotesImpl.scala:3144)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$DefDef$.apply(QuotesImpl.scala:306)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$DefDef$.apply(QuotesImpl.scala:303)
[error]     |   at org.scalamock.stubs.internal.StubMaker.$anonfun$4(StubMaker.scala:131)
[error]     |   at scala.collection.immutable.List.flatMap(List.scala:294)
[error]     |   at org.scalamock.stubs.internal.StubMaker.newInstance(StubMaker.scala:112)
[error]     |   at org.scalamock.stubs.Stubs$package$.stubMacro(Stubs.scala:210)
[error]     |   at org.scalamock.stubs.Stubs$package$.inline$stubMacro(Stubs.scala:209)
[error]     |
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from Stubs.scala:183
[error] 183 |  ${ stubMacro[T]('{ collector }) }
[error]     |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from Stubs.scala:183
[error]  42 |  inline def stub[T]: Stub[T] = stubImpl[T]
[error]     |                                ^^^^^^^^^^^
[error]      ---------------------------------------------------------------------------
[error] two errors found
[error] (scalamockJVM / Test / compileIncremental) Compilation failed
```

### PR DESCRIPTION
**Pull request by jchyb**
Fixes #22424

### CODE REVIEW

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala [hunk 1]
```diff
@@ -1826,7 +1826,7 @@ class QuotesImpl private (using val ctx: Context) extends Quotes, QuoteUnpickler
         def termSymbol: Symbol = self.termSymbol
         def isSingleton: Boolean = self.isSingleton
         def memberType(member: Symbol): TypeRepr =
-          member.info.asSeenFrom(self, member.owner)
+          member.info.asSeenFrom(self, member.owner, approximateUnstablePrefixes = false)
```
Comment (dwijnand) [inline compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:1829]: No, I don't think we should do it this way.  Perhaps we should do something like `member.info.asSeenFrom(self.<thisType>, member.owner)` .

**Comment by jchyb** [comment]
After spending some time on this, I don’t think I’m able to use thisType without it causing further regressions after all. Replacing symbols with thisType can cause certain type applications from the prefix to get ignored.
At first, as the memberType implementation,  I tried a simple:
```scala
          val classSymbol = self.classSymbol
          member.info
            .asSeenFrom(classSymbol.thisType, member.owner)
            .substThis(classSymbol.asClass, self) // we remove the added This(_) for compatibility
```
But this caused issues for nested classes, like:
```
trait A2[T]:
  case class C(t: T)
```
`TypeRepr.of[A2[Int]#C].memberType(tFieldSymbol)` would then return `TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),trait A2)),type T)`, instead of an `Int` - the `substThis` cannot help here like it does in other cases, as it looks for the C class which is not part of the TypeRef.

Then, to make sure any previously generated thisType class gets replaced with correct part of the original `self` I tried walking through `self` and trying to replace this-type of every class I find there:
```scala
          val qualTypeRepr = if self.typeSymbol.isClassDef then self.typeSymbol.thisType else self
          val memberTypeWithThis = member.info
            .asSeenFrom(qualTypeRepr, member.owner)
          new TypeAccumulator[Types.Type] {
            def apply(x: Types.Type, tp: Types.Type): Types.Type = tp match
              case at @ AppliedType(prefix, args) => apply(
                if at.typeSymbol.isClassDef then x.substThis(at.typeSymbol.asClass, at) else at,
                prefix.asInstanceOf[Types.Type]
              )
              case other => foldOver(x, other)
          }.apply(
            if self.typeSymbol.isClassDef then memberTypeWithThis.substThis(self.typeSymbol.asClass, self) else memberTypeWithThis,
            self
          )
```
This fixes the simple nested types like the example above, however it does not work for the following:
```scala
trait B2T:
  type T; case class C(t: T)
class B2C[U] extends B2T:
  final override type T = U
```
Where for `(TypeRepr.of[B2C[Int]#C].memberType(tFieldSymbol)` we obtain `TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),trait B2T)),type T)` instead of an Int.
I suppose I could, for any class that is a part of AppliedType, also go through its parents, but at that point I am just reinventing asSeenFrom. 
WIth that in mind, I’d like to resubmit the previous fix with the new asSeenFrom parameter.

**Comment by dwijnand** [comment]
> Where for `(TypeRepr.of[B2C[Int]#C].memberType(tFieldSymbol)` we obtain `TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),trait B2T)),type T)` instead of an Int.

From your example it seems like you create a `(B2C[Int]#C).this` value (for `qualTypeRepr`), where I would think you need a specific instance (i.e. stable) of `B2C[Int]`, and then a specific instance of C, in order to select the precise type of the `t` field.

I really don't like just pipelining a boolean into the algorithm, to crudely toggle it off.  I feel like the problem is in the input data.

**Comment by jchyb** [comment]
I don't think I'm able to fix it then - I tried once again to concoct something like:
```scala
          val tempReplacements = scala.collection.mutable.ListBuffer[(dotc.core.Symbols.ClassSymbol, Types.Type)]();
          val newSelf = new Types.TypeMap {
            def apply(tp: Types.Type) = tp match
              case t @ TermRef(prefix, _) if !t.isStable && t.typeSymbol.isClassDef =>
                tempReplacements.addOne((t.typeSymbol.asClass, t))
                t.typeSymbol.thisType
              case other => mapOver(other)
          }.apply(self)
          val res = member.info
            .asSeenFrom(newSelf, member.owner)
          tempReplacements.reverse.foldLeft(res) {
            case (memberTypeResult, (clsSymbol, replacingType)) =>
              memberTypeResult.substThis(clsSymbol, replacingType)
          }
```
but artificially adding those thisTypes that still breaks shapeless-3 community build, no matter how much I try to minimize the this-type additions, and how much I try to strip them out later after the `asSeenFrom`. `asSeenFrom` usually is used for the typechecking algorithm, but from the perspective of the reflect API, memberType is the only way we can actually get the type of a symbol. This means that, for that particular use case we want this type to be as precise as possible, and we never want anything replaced with `Nothing`. It's very possible that I just don't understand the concept of stability here and there is an obvious answer to all of this - I'm sorry.

**Comment by jchyb** [comment]
@dwijnand I finally found a solution that works well without changing asSeenFrom - it looks like it's easier to adjust `member.info` to always fit `self`, than doing the opposite and then stripping the unnecessary `This` trees later. It passed the new test and the tests with `memberType` in the closed community build (I did have to rerun just now, as I realized I incorrectly named a val).

**Review by dwijnand — APPROVED** [review]
LGTM, nicely done!!!

**Comment by jchyb** [comment]
Thank you!
