### PR TITLE
Require named arguments for java defined annotations

### LINKED ISSUE #20554: Compiler should enforce named arguments for Java annotations
Java annotation "parameters" are declared as fields

```
public @interface Ann {
  int a() default 41;
  int b() default 42;
  int c() default 43;
}
```

Scala 3 allows `@Ann(1)`. Reordering the fields in `Ann` is a binary compatible change, but it affects the meaning of `@Ann(1)`.

Scala 2 does the same as Java: arguments to Java annotations always have to be specified by name. The only exception is a single positional argument, which always expands to the field named `value`, i.e., `@Ann(value = 1)`.

### PR DESCRIPTION
**Pull request by hamzaremmal**
Closes #20554

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 1]
```diff
@@ -1527,6 +1527,17 @@ trait Checking {
       // TODO: Add more checks here
     }
 
+  /** check that parameters of a java defined annotations are all named arguments if we have more than one parameter */
+  def checkNamedArgumentForJavaAnnotation(annot: untpd.Tree)(using Context): Unit = 
+    assert(annot.symbol.is(JavaDefined))
+    annot match
+      case untpd.Apply(_, params) if params.length > 1 =>
```
[the remark this answers is not in the document]
Comment (hamzaremmal) [reply compiler/src/dotty/tools/dotc/typer/Checking.scala:1534]: Yep, it's the last thing I had to do. I wanted to check the Java spec before doing it

**Comment by hamzaremmal** [comment]
It seems that this is breaking some code (as expected), but should we make it a warning in 3.6.x and an error in >= 3.7.0 ?

File: compiler/src/dotty/tools/dotc/typer/Namer.scala [hunk 2]
```diff
@@ -868,15 +868,20 @@ class Namer { typer: Typer =>
...
-          if (cls eq sym)
-            report.error(em"An annotation class cannot be annotated with iself", annotTree.srcPos)
-          else {
-            val ann = Annotation.deferred(cls)(typedAheadExpr(annotTree)(using annotCtx))
-            sym.addAnnotation(ann)
-          }
-        }
+        original.setMods: 
+          original.mods.withAnnotations :
+            for (annotTree <- original.mods.annotations) yield
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/typer/Namer.scala:873]: In the overwhelming majority of the cases, this is going to return an equivalent list, but since it will be non-`eq`, the `with/set` methods will have to create new instances. Use `mapConverse` to avoid this issue:
```suggestion
            original.mods.annotations.mapConserve { annotTree =>
```
(or whatever is its correct syntax)

**Review by sjrd — CHANGES_REQUESTED** [review]

**Review by sjrd — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 3]
```diff
@@ -883,6 +883,34 @@ object Checking {
...
+      params.exists(!_.isInstanceOf[untpd.NamedArg])
+
+    def mapPositionalToNamed(param: untpd.Tree): untpd.Tree = param match
+      case tree: untpd.NamedArg => tree
+      case tree => untpd.cpy.NamedArg(param)(nme.value, param)
+    end mapPositionalToNamed
+
+    annot match
+      case untpd.Apply(fun, params) if hasOnePositionalParameter(params) && annotationHasValueField => 
+        untpd.cpy.Apply(annot)(fun, params.mapConserve(mapPositionalToNamed))
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala:904]: This does not seem to match the spec anymore. It would allow `@JavaAnnot(1, other = 2)`, if there is `value` and `other`, which should not be allowed. Also it's probably going to do the wrong thing for `@JavaAnnot(1, 2)` if there is a `value` field, as it will transform them both to `@JavaAnnot(value = 1, value = 2)`.

The auto-`value =` treatment should only be considered with `params.size == 1`.

**Review by sjrd — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/typer/Checking.scala (hunk 3 above)
Comment (hamzaremmal) [reply compiler/src/dotty/tools/dotc/typer/Checking.scala:904]: Mmmh, I was pretty sure it worked with Scala 2.13.13 when I tried yesterday 😅 . I will revert it.

**Review by sjrd — APPROVED** [review]
