### PR TITLE
Fix scaladoc TastyInspector regressions

### LINKED ISSUE #20476: doc fails to read scala.scalajs.js.Promise.then symbol
This seems similar to #14143, but the affected scala versions are much newer and the bug does not occur when downgrading to scala 3.3.1:

## Compiler version

scala 3.3.3 ; 3.4.0 ;  3.4.1 ; 3.4.2

scala-js 1.16.0
sbt 1.10.0

## Minimized code

```Scala
package demo

import scala.scalajs.js

def bar: js.Promise[Int] = js.Promise.resolve(()).`then`(_ => 1)

```

```Scala
# plugins.sbt
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.16.0")

```

```Scala
# build.sbt
ThisBuild / version := "0.1.0-SNAPSHOT"

ThisBuild / scalaVersion := "3.3.3" // or any of 3.4.0 to 3.4.2

lazy val root = (project in file("."))
  .enablePlugins(ScalaJSPlugin)
  .settings(
    name := "doc_bug_report"
  )
```

## Output

```
[IJ]doc
[info] compiling 1 Scala source to /redacted/doc_bug_report/target/scala-3.3.3/classes ...
[info] done compiling
[info] Main Scala API documentation to /redacted/doc_bug_report/target/scala-3.3.3/api...
-- Error: src/main/scala/demo/demo.scala:5:27 ----------------------------------
5 |def bar: js.Promise[Int] = js.Promise.resolve(()).`then`(_ => 1)
  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |undefined: $1$.then # -1: TermRef(TermRef(NoPrefix,val $1$),then) at readTasty
1 error found
[info] Main Scala API documentation successful.
[success] Total time: 0 s, completed 27.05.2024, 10:08:40
```

## Expectation

No error occurs (as with scala 3.3.1).

### PR DESCRIPTION
**Pull request by jchyb**
Fixes #20476 (which would previously crash in the `ReadTasty` phase) and #18231 (LTS-only issue, only applicable after backport)

Adds an `inspectAllTastyFilesInContext` method in scaladoc-only version of TastyInspector (similarly to how it was before https://github.com/scala/scala3/pull/18989, where the regressions were introduced). I still do not know the exact reason why those regressions happen, but I think this is kind of a fix is better than a whole revert we would have to do otherwise.

Notably, those issues are not being fixed in the stable TastyInspector - this is scaladoc only. 

Also the scaladoc copy of the TastyInspector had to be renamed, as otherwise we run into classpath issues with the stable tasty inspector taking precedence.

I really wanted to include the test for both issues, but both required non-standard specification, so I could not use `scaladoc-testcases` and ended up having to use sbt scripted tests unfortunately.

### CODE REVIEW

File: scaladoc/src/scala/tasty/inspector/TastyInspector.scala [hunk 1]
```diff
@@ -1,5 +1,7 @@
-// Copy of tasty-inspector/src/scala/tasty/inspector/TastyInspector.scala
+// Renamed copy of tasty-inspector/src/scala/tasty/inspector/TastyInspector.scala
 // FIXME remove this copy of the file
+// Since copying, an inspectAllTastyFilesInContext ,ethod was added for scaladoc only
```
Comment (Florian3k) [inline scaladoc/src/scala/tasty/inspector/TastyInspector.scala:3]:
```suggestion
// Since copying, an inspectAllTastyFilesInContext method was added for scaladoc only
```

**Review by Florian3k — APPROVED** [review]
