### PR TITLE
Fix #20287: Add flexible types to Quotes library

### LINKED ISSUE #20287: `FlexibleTypes` are not handled in `Quotes`
Issue found in OpenCB for `scalacenter/tasty-mima` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/8855242584/job/24320431487)

## Compiler version
3.5.0-RC1-bin-20240417-b93c337-NIGHTLY 

## Minimized code
Not minimized yet

## Output

```scala
Error:  -- Error: /build/repo/tasty-mima/src/test/scala/tastymima/intf/ProblemSuite.scala:41:18 
Error:  41 |      assert(clue(TestProblem(kind, "<path-string>").getFilterIncantation()) == clue(expected))
Error:     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error:     |Exception occurred while executing macro expansion.
Error:     |scala.MatchError: FlexibleType(OrType(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class String),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Null)),TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class String)) (of class dotty.tools.dotc.core.Types$FlexibleType)
Error:     |	at scala.quoted.runtime.impl.printers.Extractors$ExtractorsPrinter.visitType(Extractors.scala:241)
Error:     |	at scala.quoted.runtime.impl.printers.Extractors$.showType(Extractors.scala:12)
Error:     |	at scala.quoted.runtime.impl.QuotesImpl$$anon$19.show(QuotesImpl.scala:3219)
Error:     |	at scala.quoted.runtime.impl.QuotesImpl$$anon$19.show(QuotesImpl.scala:3218)
Error:     |	at scala.quoted.runtime.impl.QuotesImpl$reflect$TypeReprMethods$.show(QuotesImpl.scala:1804)
Error:     |	at scala.quoted.runtime.impl.QuotesImpl$reflect$TypeReprMethods$.show(QuotesImpl.scala:1804)
Error:     |	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printType(SourceCode.scala:1251)
Error:     |	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printTypeAndAnnots$1(SourceCode.scala:1020)
Error:     |	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printTypeTree(SourceCode.scala:1022)
Error:     |	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printTree(SourceCode.scala:527)
Error:     |	at scala.quoted.runtime.impl.printers.SourceCode$.showTree(SourceCode.scala:10)
Error:     |	at scala.quoted.runtime.impl.QuotesImpl$$anon$13.show(QuotesImpl.scala:3195)
Error:     |	at scala.quoted.runtime.impl.QuotesImpl$$anon$13.show(QuotesImpl.scala:3194)
Error:     |	at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.show(QuotesImpl.scala:108)
Error:     |	at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.show(QuotesImpl.scala:108)
Error:     |	at munit.internal.MacroCompat$.clueImpl(MacroCompat.scala:31)
Error:     |
Error:     |----------------------------------------------------------------------------
Error:     |Inline stack trace
Error:     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error:     |This location contains code that was inlined from MacroCompat.scala:24
Error:      ----------------------------------------------------------------------------```
```

## Expectation
Audit and fix the corner cases where `FlexibleType` might lead to `MatchError`

### PR DESCRIPTION
**Pull request by noti0na1**
Fix #20287

To fix the missing case, we have to add flexible types to `Quotes` library.

### CODE REVIEW

File: library/src/scala/quoted/Quotes.scala [hunk 1]
```diff
@@ -3428,6 +3428,23 @@ trait Quotes { self: runtime.QuoteUnpickler & runtime.QuoteMatching =>
       def unapply(x: NoPrefix): true
     }
 
+    // ----- Flexible Type --------------------------------------------
+
+    /** Flexible types for explicit nulls */
+    type FlexibleType <: TypeRepr
```
Comment (nicolasstucki) [inline library/src/scala/quoted/Quotes.scala:3434]: All these definitions should be annotated with `@experimental`. The documentation in of `reflectModule` must also be updated.

**Review by nicolasstucki — CHANGES_REQUESTED** [review]

**Comment by noti0na1** [comment]
Hi @nicolasstucki, do you have any idea why the extractor for `FlexibleType` does not work in `Extractors.scala` and `SourceCode.scala`: `TypeRepr is not a valid result type of an unapply method of an extractor.`

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala [hunk 2]
```diff
@@ -2343,6 +2343,21 @@ class QuotesImpl private (using val ctx: Context) extends Quotes, QuoteUnpickler
...
+      def unapply(x: TypeRepr): Option[FlexibleType & x.type] = x match
+        case x: (Types.FlexibleType & x.type) => Some(x)
+        case _ => None
+    end FlexibleTypeTest
+
+    object FlexibleType extends FlexibleTypeModule:
+      def apply(tp: TypeRepr): FlexibleType =
+        // why object FlexibleType.apply(Type) is not found here?
+        Types.FlexibleType(tp, tp)
+      def unapply(x: FlexibleType): TypeRepr = x.hi
```
Comment (nicolasstucki) [inline compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:2358]: The type cannot be tested at call site before calling the unapply. The type test must be done in the unapply implementation. See other examples above.

```suggestion
      def unapply(x: TypeRepr): Option[TypeRepr & x.type] = 
         ...
```

File: library/src/scala/quoted/Quotes.scala (hunk 1 above)
Comment (sjrd) [reply library/src/scala/quoted/Quotes.scala:3434]: Flexible types are not considered experimental, though. So how can a non-experimental macro deal with all possible types it manipulates if we make `FlexibleType` experimental?

Comment (nicolasstucki) [reply library/src/scala/quoted/Quotes.scala:3434]: Oh, then the MiMa filters must be updated.

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala (hunk 2 above)
Comment (nicolasstucki) [inline compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:2358]:
```suggestion
      def unapply(x: FlexibleType): Some[TypeRepr] = Some(x.hi)
```

File: library/src/scala/quoted/Quotes.scala (hunk 1 above)
Comment (noti0na1) [reply library/src/scala/quoted/Quotes.scala:3435]: MiMa filters updated

File: library/src/scala/quoted/Quotes.scala [hunk 3]
```diff
@@ -3428,6 +3429,23 @@ trait Quotes { self: runtime.QuoteUnpickler & runtime.QuoteMatching =>
...
+
+    /** Module object of `type FlexibleType`  */
+    val FlexibleType: FlexibleTypeModule
+
+    /** Methods of the module object `val FlexibleType` */
+    trait FlexibleTypeModule { this: FlexibleType.type =>
+      def apply(tp: TypeRepr): FlexibleType
+      def unapply(x: FlexibleType): Option[TypeRepr]
+    }
+
```
Comment (nicolasstucki) [inline library/src/scala/quoted/Quotes.scala:3448]: We should also add methods to FlexibleType. At least we need the field accessor.

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala [hunk 4]
```diff
@@ -2343,6 +2343,19 @@ class QuotesImpl private (using val ctx: Context) extends Quotes, QuoteUnpickler
...
+    type FlexibleType = dotc.core.Types.FlexibleType
+
+    object FlexibleTypeTypeTest extends TypeTest[TypeRepr, FlexibleType]:
+      def unapply(x: TypeRepr): Option[FlexibleType & x.type] = x match
+        case x: (Types.FlexibleType & x.type) => Some(x)
+        case _ => None
+    end FlexibleTypeTypeTest
+
+    object FlexibleType extends FlexibleTypeModule:
+      def apply(tp: TypeRepr): FlexibleType = Types.FlexibleType(tp)
```
Comment (nicolasstucki) [inline compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:2355]: I noticed that `Types.FlexibleType` is a case class with 2 fields but here we only have one. Why is this difference ok? Is this aligned with the representation in TASTy?

**Comment by nicolasstucki** [comment]
This should probably be included in 3.5 as it is a part of https://github.com/scala/scala3/pull/18112. Specifically, the changes in the TASTy format require this change in the reflection API.

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala (hunk 4 above)
Comment (noti0na1) [reply compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:2355]: The first field `lo` is just a nullable version of `hi` computed internally. Hence, we only store the `hi` in TASTy as well.

**Comment by sjrd** [comment]
The core meeting decided to take this PR in on 3.5.0.

**Review by jchyb — APPROVED** [review]
LGTM! The only thing missing here is the scaladoc for FlexibleTypeMethods, but this can be done in a separate PR, and with another review cycle we may not meet the deadline today for the cutoff for 3.5.0

File: tests/explicit-nulls/run/tasty-flexible-type.check [hunk 5]
```diff
@@ -0,0 +1,7 @@
+Inlined(None, Nil, Literal(StringConstant("hello")))
+ConstantType(StringConstant("hello"))
+
+Inlined(None, Nil, Apply(Select(Literal(StringConstant("world")), "trim"), Nil))
+FlexibleType(TypeRef(ThisType(TypeRef(NoPrefix(), "lang")), "String"))
```
[the remark this answers is not in the document]
Comment (noti0na1) [reply tests/explicit-nulls/run/tasty-flexible-type.check:5]: I guess because it is from a Java method?

File: tests/explicit-nulls/run/tasty-flexible-type/quoted_1.scala [hunk 6]
```diff
@@ -0,0 +1,34 @@
+import scala.quoted.*
+
+object Macros {
+
+  implicit inline def printTree[T](inline x: T): Unit =
```
[the remark this answers is not in the document]
Comment (noti0na1) [reply tests/explicit-nulls/run/tasty-flexible-type/quoted_1.scala]: removed
