### PR TITLE
Adjustments to the capability trilogy

### LINKED ISSUE #23421: Lack of support in CC: fresh caps inside type arguments
> Another question about this example is how do we actually instantiate such collections:
> ```scala
> import language.experimental.captureChecking
> import caps.*
> 
> trait Collection[T] extends Mutable:
>   update def add(elem: T): Unit
>   update def remove(elem: T): Unit
>   def get(index: Int): Option[T]
> 
> object Collection:
>   def empty[T]: Collection[T] = ???
> 
> trait Foo:
>   val thunks: Collection[() => Unit] // that's fine
> 
> object FooImpl1 extends Foo:
>   val thunks: Collection[() => Unit] = Collection.empty // error
> 
> ```
> Looks like a bug?
> ```scala
> -- [E007] Type Mismatch Error: local/i21675.scala:17:39 ------------------------
> 16 |  val thunks: Collection[() => Unit] = Collection.empty
>    |                                       ^^^^^^^^^^^^^^^^
>    |Found:    Collection[() ->? Unit]^{cap.rd}
>    |Required: Collection[() => Unit]^{cap².rd}
>    |
>    |where:    cap  is a fresh root capability in the result type of method empty
>    |          cap² is a fresh root capability in the type of value thunks
>    |
>    | longer explanation available when compiling with `-explain`
> ``` 

 _Originally posted by @bracevac in [#21675](https://github.com/scala/scala3/issues/21675#issuecomment-2983588049)_

### PR DESCRIPTION
**Pull request by Linyxus**
Fixes #23421.

This PR includes the following two changes:
1. In `capToFresh`, turn `cap`s in invariant occurrences also to `Fresh`es. Previously, in the follow code:
```
val xs: ArrayBuffer[() ->{cap} Unit] = ...
```
The `cap` is kept intact since it is invariant. Now, it gets converted into a `Fresh` owned by `xs`.
2. In `toResultInResults`, convert fresh caps of `def`-method with only type parameters into result caps, just like parameterless defs. Specifically, for the following code:
```
def empty[T]: ArrayBuffer[T]^ = ...
```
The `^` will be turned into a result cap, just like what happens for a parameterless def:
```
def mkRef: Ref^ = ...
```
The `^` is a result cap that gets instantiated to a new fresh at each application of `mkRef`. Doing the same thing for `empty` is the arguably more desirable behavior.

### CODE REVIEW

**Comment by Linyxus** [comment]
To be merged after #23427.

File: compiler/src/dotty/tools/dotc/cc/Capability.scala [hunk 1]
```diff
@@ -703,6 +703,8 @@ object Capabilities:
             this(CapturingType(parent1, ann.tree.toCaptureSet))
           else
             t.derivedAnnotatedType(parent1, ann)
+        case t @ FunctionOrMethod(_, _) if t.isAliasFun =>
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/cc/Capability.scala]: The pattern does not describe a dependent function type. I believe you have to match with 
```scala
case RefinedFunctionOf(_) ->
```
instead.

**Review by odersky — APPROVED** [review]
