### PR TITLE
Resolve name when named imp is behind wild imps

### LINKED ISSUE #18529: Java type name resolution with wildcard imports is incorrect
## Compiler version

3.3.1

## Minimized code

[Repo](https://github.com/andrew-boyarshin/ScalaJavaBug) (branch `1`)

TLDR:
```java
package bug.code;

import bug.util.List;
import bug.util.*;
import java.util.*;

public class Code {
    public List<Long> work(List<Integer> list) {
        return null;
    }
}
```

## Output

```text
-- [E049] Reference Error: .\src\code\Code.java:8:27 ---------------------------
8 |    public List<Long> work(List<Integer> list) {
  |                           ^^^^
  |                           Reference to List is ambiguous.
  |                           It is both imported by import bug.util._
  |                           and imported subsequently by import java.util._
  |
  | longer explanation available when compiling with `-explain`
-- [E049] Reference Error: .\src\code\Code.java:8:11 ---------------------------
8 |    public List<Long> work(List<Integer> list) {
  |           ^^^^
  |           Reference to List is ambiguous.
  |           It is both imported by import bug.util._
  |           and imported subsequently by import java.util._
  |
  | longer explanation available when compiling with `-explain`
```

## Expectation

Scala code compiles successfully in mixed mode, like in Scala 2.13.11.

### PR DESCRIPTION
**Pull request by dwijnand**
When a named import (such as `import bug.util.List`) is defined before
two clashing wildcard imports (`import bug.util.*; import java.util.*`)
the name "List" should resolve to it, rather than a resolution error
being emitted.

This was due to the fact that `findRefRecur` didn't return the
precedence at which it found that import, `checkImportAlternatives` used
the `prevPrec` to `checkNewOrShadowed`.  Now we check against the entire
`foundResult`, allowing an early named import to be picked over later
wildcard imports.

Fixes #18529
(Replaces #21871)

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -238,38 +238,40 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
         !owner.isEmptyPackage || ctx.owner.enclosingPackageClass.isEmptyPackage
       }
 
+    import BindingPrec.*
+    type Result = (Type, BindingPrec)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:242]: I don't think we should use a boxed type here. `findRefRecur` is very hot, we should avoid allocating where we can.

**Review by odersky — CHANGES_REQUESTED** [review]
The boxing is a heavy price to pay here. I am worried that we make findRefRecur slower for a niche case which is what #18529 is. It's trivially fixed by moving the named import behind the two wildcard imports. And the error message is informative enough to suggest something like that. 

What we could do: If we get an ambiguity, try a targeted action to see whether we get a
named import in the same import sequence that would resolve the problem. That can be done without changing the signature of `findRefRecur`.

**Review by odersky — APPROVED** [review]
That looks good now.
