### PR TITLE
fix #22833: allow unroll annotation in methods of final class

### LINKED ISSUE #22833: `@unroll` should work on `final class`es without needing a `final` on each method
## Compiler version

3.7.0-RC1

## Minimized code

```Scala
final class Foo{
  def bar(@scala.annotation.unroll x: Int = 0) = x + 1
}
```

## Output

```scala
[44] [error] -- [E207] Declaration Error: /Users/lihaoyi/test/src/test.scala:2:35 -----------
[44] [error] 2 |  def bar(@scala.annotation.unroll x: Int = 0) = x + 1
[44] [error]   |                                   ^
[44] [error]   |                   Cannot unroll parameters of method bar: it is not final
[44] [error] one error found

```

## Expectation

`@unroll` should be able to see that the enclosing `Foo` is a `final class`, and thus allow us to elide `final` modifiers on the `def bar`. It already recognizes enclosing `object`s as `final`, so recognizing enclosing `final class` and `final case class`es is a straightforward extension

### PR DESCRIPTION
**Pull request by olhotak**
Closes #22833

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/PostTyper.scala [hunk 1]
```diff
@@ -132,9 +132,9 @@ class PostTyper extends MacroTransform with InfoTransformer { thisPhase =>
         then
           false // not an error, but not an expandable unrolled method
         else if
-          method.is(Deferred)
+            method.isLocal
+          || !method.isEffectivelyFinal
```
Comment (hamzaremmal) [inline compiler/src/dotty/tools/dotc/transform/PostTyper.scala:136]: @lihaoyi confirmed that *abstract methods* shouldn't be allowed to have `@unroll`. 

```suggestion
            method.is(Deferred)
          || method.isLocal
          || !method.isEffectivelyFinal
```

Comment (hamzaremmal) [reply compiler/src/dotty/tools/dotc/transform/PostTyper.scala:136]: I'm surprised that no tests were affected by this change!

File: compiler/src/dotty/tools/dotc/reporting/messages.scala [hunk 2]
```diff
@@ -3430,12 +3430,12 @@ extends DeclarationMsg(IllegalUnrollPlacementID):
       val isCtor = method.isConstructor
       def what = if isCtor then i"a ${if method.owner.is(Trait) then "trait" else "class"} constructor" else i"method ${method.name}"
       val prefix = s"Cannot unroll parameters of $what"
-      if method.is(Deferred) then
-        i"$prefix: it must not be abstract"
```
Comment (hamzaremmal) [inline compiler/src/dotty/tools/dotc/reporting/messages.scala:3434]: We also need to revert this change

File: compiler/src/dotty/tools/dotc/transform/PostTyper.scala (hunk 1 above)
Comment (lihaoyi) [reply compiler/src/dotty/tools/dotc/transform/PostTyper.scala:136]: I've never seen `final abstract`, I didn't know that was even allowed?

Comment (olhotak) [reply compiler/src/dotty/tools/dotc/transform/PostTyper.scala:136]: I believe the only place it's used is for the primitive classes in the standard library like `scala.Int`.

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/transform/PostTyper.scala:136]: Yeah ... that's really just primitives. A `final abstract` class cannot possibly be instantiated *nor* subclassed. So who cares what happens inside. It's basically an uninhabited type. ;)

Comment (hamzaremmal) [reply compiler/src/dotty/tools/dotc/transform/PostTyper.scala:136]: > I'm surprised that no tests were affected by this change!

@olhotak You're right, I was context switching when I made the comment. I've rechecked the diff and it everything seems correct to me.

File: compiler/src/dotty/tools/dotc/reporting/messages.scala (hunk 2 above)
Comment (hamzaremmal) [reply compiler/src/dotty/tools/dotc/reporting/messages.scala:3434]: Context switching is very bad 😭 when reviewing things...
We don't need to revert this.

**Comment by hamzaremmal** [comment]
I've assigned Lukas as he is the manager of [SIP-61](https://github.com/scala/improvement-proposals/pull/78).

File: compiler/src/dotty/tools/dotc/reporting/messages.scala [hunk 3]
```diff
@@ -3430,12 +3430,12 @@ extends DeclarationMsg(IllegalUnrollPlacementID):
...
+      if method.isLocal then
+        i"$prefix because it is a local method"
+      else if !method.isEffectivelyFinal then
+        i"$prefix: it is not effectively final"
```
Comment (lrytz) [inline compiler/src/dotty/tools/dotc/reporting/messages.scala:3436]: is "effectively final" compiler-internal terminology? maybe `i"$prefix because it can be overridden"?

File: compiler/src/dotty/tools/dotc/transform/UnrollDefinitions.scala [hunk 4]
```diff
@@ -79,7 +79,8 @@ class UnrollDefinitions extends MacroTransform, IdentityDenotTransformer {
               else Some((paramClauseIndex, annotationIndices))
           if indices.nonEmpty then
             // pre-validation should have occurred in posttyper
-            assert(annotated.is(Final, butNot = Deferred) || annotated.isConstructor || annotated.owner.is(ModuleClass) || annotated.name.is(DefaultGetterName),
+            assert(!annotated.isLocal, i"$annotated is local")
+            assert(annotated.isEffectivelyFinal || annotated.isConstructor || annotated.owner.is(ModuleClass) || annotated.name.is(DefaultGetterName),
```
Comment (lrytz) [inline compiler/src/dotty/tools/dotc/transform/UnrollDefinitions.scala:83]:
```suggestion
            assert(annotated.isEffectivelyFinal || annotated.name.is(DefaultGetterName),
```

**Review by lrytz — APPROVED** [review]
LGTM, should just squash the commits into one.

**Comment by lihaoyi** [comment]
I opened a bounty on this issue on the Scala 2/3 backport compiler plugin if anyone wants to take a crack at it, 300USD https://github.com/com-lihaoyi/unroll/issues/12
