### PR TITLE
Refine rules for capture parameters and members

### LINKED ISSUE #21999: Improve Captureset Subtyping and Intervals
From discussions in PR https://github.com/scala/scala3/pull/21875 

## Compiler version

Latest NIGHTLY

## Minimized code

```scala
import language.experimental.captureChecking
import caps.*

trait Abstract[X >: Nothing]: // Concrete2 and 3 fail with this lower bound, but work with X >: CapSet^{}
    type C >: X <: CapSet^
    def boom(): Unit^{C^}

class Concrete extends Abstract[CapSet^{}]:
    type C = CapSet^{}
    def boom() = () // ok

class Concrete2 extends Abstract[CapSet^{}]:
    type C = CapSet^{} & CapSet^{}
    def boom() = () // error

class Concrete3 extends Abstract[CapSet^{}]:
    type C = CapSet^{} | CapSet^{}
    def boom() = () // error
```

## Output

```scala
-- Error: local/i21868.scala:14:14 ---------------------------------------------
14 |    def boom() = () // error
   |              ^
   |          Illegal capture reference: (caps.CapSet^{}) & (caps.CapSet^{})
-- Error: local/i21868.scala:18:14 ---------------------------------------------
18 |    def boom() = () // error
   |              ^
   |          Illegal capture reference: (caps.CapSet^{}) | (caps.CapSet^{})
```

## Expectation

* I would expect those to work even if the lower bound of `X` in `trait Abstract[X]` is set to `Nothing`.
* Can we make union and intersection on `CapSet` commute with capture set union and intersection, i.e., `CapSet^c1 | CapSet^c2 <:> CapSet^(c1 | c2)` and `CapSet^c1 & CapSet^c2 <:> CapSet^(c1 & c2)`? Probably, that involves improving `normalizeCaptures` in `Setup`.
* Can we let the syntax `C^` for declaring a type variable automatically desugar to the interval `CapSet^{} <: C <: CapSet^`? 
  * Is this always airtight, or will it cause trouble?

### PR DESCRIPTION
**Pull request by noti0na1**
This PR refines rules for capture set variables (parameters and members).

Fix #21999, #22005, #22030

## Add requirements for capture set variables 

When a capture set is encoded as a type, the type must refer to `CapSet` and bounded by `>: CapSet <: CapSet^`.

An unbounded capture parameter would be `C >: CapSet <: CapSet^`, which can be desugared from `C^`.

```scala
def f[C^](io: IO^{C^}) = ???

// becomes

def f[C >: CapSet <: CapSet^](io: IO^{C^}) = ???
```

We may consider the similar desugaring for type member in the future:

```scala
class A:
  type C^

// becomes

class A:
  type C >: CapSet <: CapSet^
```

Then, constaints between capture variables become possible:

```scala
def test[X^, Y^, Z >: X <: Y](x: C^{X^}, y: C^{Y^}, z: C^{Z^}) = ???
// Z is still bounded by >: CapSet <: CapSet^
```

Update definitions in the library `caps.scala`, such that a type following the rule can be used inside a capture set.

```scala
// Rule out C^{(Nothing)^} during typer
def capsOf[CS >: CapSet <: CapSet @retainsCap]: Any = ???

sealed trait Contains[+C >: CapSet <: CapSet @retainsCap, R <: Singleton]
```

## Add cases to handle `CapSet` in `subsumes`

```
*   X = CapSet^cx, exists rx in cx, rx subsumes y ==>  X subsumes y
*   Y = CapSet^cy, forall ry in cy, x subsumes ry ==>  x subsumes Y
*   X: CapSet^c1...CapSet^c2, (CapSet^c1) subsumes y  ==> X subsumes y
*   Y: CapSet^c1...CapSet^c2, x subsumes (CapSet^c2) ==> x subsumes Y
*   Contains[X, y]  ==>  X subsumes y
```

## Fix some issues related to overriding

When deciding whether a class has a non-trivial self type, we look at the underlying type without capture set.

[test_scala2_library_tasty]

### CODE REVIEW

**Comment by noti0na1** [comment]
TODO: treat capture variables/members like type variables/members.

File: tests/neg/cc-poly-2.scala [hunk 1]
```diff
@@ -10,7 +10,7 @@ object Test:
 
   def test(c1: C, c2: C) =
     val d: D^ = D()
-    f[Nothing](d) // error
+    // f[Nothing](d) // already rule out at typer
```
Comment (bracevac) [inline tests/neg/cc-poly-2.scala:13]:
```suggestion
    // f[Nothing](d) // already ruled out at typer
```

File: compiler/src/dotty/tools/dotc/cc/CaptureRef.scala [hunk 2]
```diff
@@ -93,12 +93,19 @@ trait CaptureRef extends TypeProxy, ValueType:
   final def invalidateCaches() =
     myCaptureSetRunId = NoRunId
 
-  /** x subsumes x
-   *   this subsumes this.f
```
Comment (bracevac) [inline compiler/src/dotty/tools/dotc/cc/CaptureRef.scala:97]: Why remove this rule?

Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/cc/CaptureRef.scala:97]: I'm still updating the comments. This should be:

```
x subsumes y ==> x subsumes y.f
```

File: tests/pos-custom-args/captures/cc-poly-varargs.scala [hunk 3]
```diff
@@ -1,20 +1,19 @@
...
   val right = src2.transformValuesWith(Right(_))
-  race(left, right)
-
-
-
-
-
-
-
+  race[Either[T1, T2], Cap](left, right)
```
[the remark this answers is not in the document]
Comment (noti0na1) [reply tests/pos-custom-args/captures/cc-poly-varargs.scala:15]: The subtyping `Cap <:< CapSet^{Cap^}` should work. We will fix this in a different PR.

**Comment by noti0na1** [comment]
@bracevac This PR should be ready to review. The one error in `test_scala2_library_tasty` is not related to this PR.

**Review by bracevac — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/cc/CaptureRef.scala [hunk 4]
```diff
@@ -135,14 +142,26 @@ trait CaptureRef extends TypeProxy, ValueType:
               case _ => false
           || viaInfo(y.info)(subsumingRefs(this, _))
         case MaybeCapability(y1) => this.stripMaybe.subsumes(y1)
+        case y: TypeRef if y.derivesFrom(defn.Caps_CapSet) =>
+          y.info match
+            case TypeBounds(_, hi: CaptureRef) => this.subsumes(hi)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/cc/CaptureRef.scala:147]: Can this case happen? I thought the upper bound has to be of the form `CapSet^cs`? If it can happen, maybe add a comment explaining why.

File: compiler/src/dotty/tools/dotc/cc/CaptureRef.scala [hunk 5]
```diff
@@ -135,14 +142,26 @@ trait CaptureRef extends TypeProxy, ValueType:
...
         case ReachCapability(x1) => x1.subsumes(y.stripReach)
         case x: TermRef => viaInfo(x.info)(subsumingRefs(_, y))
         case x: TermParamRef => subsumesExistentially(x, y)
-        case x: TypeRef if x.symbol.info.derivesFrom(defn.Caps_CapSet) =>
-          x.captureSetOfInfo.elems.exists(_.subsumes(y))
-        case x: TypeRef => assumedContainsOf(x).contains(y)
+        case x: TypeRef if assumedContainsOf(x).contains(y) => true
+        case x: TypeRef if x.derivesFrom(defn.Caps_CapSet) =>
+          x.info match
+            case TypeBounds(lo: CaptureRef, _) =>
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/cc/CaptureRef.scala:159]: Same as above; can this case happen?

**Review by odersky — CHANGES_REQUESTED** [review]
Otherwise LGTM

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 6]
```diff
@@ -4057,8 +4057,11 @@ object Parsers {
               || sourceVersion.isAtLeast(`3.6`) && in.isColon =>
             makeTypeDef(typeAndCtxBounds(tname))
           case _ =>
-            syntaxErrorOrIncomplete(ExpectedTypeBoundOrEquals(in.token))
-            return EmptyTree // return to avoid setting the span to EmptyTree
+            if in.isIdent(nme.UPARROW) && Feature.ccEnabled then
```
[the remark this answers is not in the document]
Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala:4060]: Sure

File: compiler/src/dotty/tools/dotc/cc/CaptureRef.scala (hunk 4 above)
Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/cc/CaptureRef.scala:147]: The upper and lower bounds don't have to be in the form of `CapSet^{...}`. They can also be other capture set variables, which are bounded by `CapSet`, like `def test[X^, Y^, Z >: X <: Y]`. With this set up, both cases would happen during `subsumes`.

**Review by odersky — APPROVED** [review]
Might need a rebase to make the tests pass.

**Comment by noti0na1** [comment]
Currently blocked by error on main branch: #22058

**Review by Linyxus — APPROVED** [review]
LGTM
