### PR TITLE
Generate mirrors for named tuples

### LINKED ISSUE #22382: Mirror.Of is not implemented for named tuples
## Compiler version

3.6.2

## Minimized code

```Scala
import scala.language.experimental.namedTuples
import scala.deriving.*

summon[Mirror.Of[(Int, String)]] // OK

summon[Mirror.Of[(foo: Int, bla: String)]] // error
```

## Output

```scala
  |No given instance of type scala.deriving.Mirror.Of[(foo : Int, bar : String)] was found for parameter x of method summon in object Predef. Failed to synthesize an instance of type scala.deriving.Mirror.Of[(foo : Int, bar : String)]:
  |     * class Any is not a generic product because it is not a case class
  |     * class Any is not a generic sum because it is not a sealed class
```

## Expectation

Just like regular tuples, named tuples should have mirror instances because they are product types and mirrors allow for uniform meta-programming on sums and products types.

### PR DESCRIPTION
**Pull request by jchyb**
Fixes #22382
For `summon[Mirror.Of[(foo: Int, bla: String)]]` we generate:
```scala
new scala.runtime.TupleMirror(2).$asInstanceOf[
    scala.deriving.Mirror.Product{
      type MirroredMonoType = (foo : Int, bla : String);
        type MirroredType = (foo : Int, bla : String);
        type MirroredLabel = ("NamedTuple" : String);
        type MirroredElemTypes = (Int, String);
        type MirroredElemLabels = (("foo" : String),
          ("bla" : String))
    }
]
```

We reuse scala.runtime.TupleMirror, because it pretty much does everything we want it to, and fromProduct (with supplied Product types) call on that mirror still works there.
Since NamedTuple is not technically a `Product` type, I imagine users might be a little confused why they can't put a named tuple into a `fromProduct` argument, but this is easily worked around with `.toTuple`

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala [hunk 1]
```diff
@@ -398,6 +404,8 @@ class Synthesizer(typer: Typer)(using @constructorOnly c: Context):
                 // avoid type aliases for tuples
                 Right(MirrorSource.GenericTuple(types))
               case _ => reduce(tp.underlying)
+          case tp @ AppliedType(tref: TypeRef, List(_, typeTuple)) if tref == defn.NamedTupleTypeRef =>
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:407]:
```suggestion
          case tp @ AppliedType(tref: TypeRef, List(_, _)) if tref == defn.NamedTupleTypeRef =>
```

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala [hunk 2]
```diff
@@ -398,6 +404,8 @@ class Synthesizer(typer: Typer)(using @constructorOnly c: Context):
...
+            Right(MirrorSource.NamedTuple(tp.namedTupleElementTypes(false)))
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:408]: what changes with `derived=true` instead of `false`?

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala [hunk 3]
```diff
@@ -501,6 +522,10 @@ class Synthesizer(typer: Typer)(using @constructorOnly c: Context):
         val arity = tps.size
         val cls = if arity <= Definitions.MaxTupleArity then defn.TupleType(arity).nn.classSymbol else defn.PairClass
         ("", NoType, cls)
+      case Right(MirrorSource.NamedTuple(nameTypePairs)) =>
+        val arity = nameTypePairs.size
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:526]: (also unused)

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala (hunk 1 above)
Comment (jchyb) [reply compiler/src/dotty/tools/dotc/typer/Synthesizer.scala]: I ended up changing it into `defn.NamedTupleDirect(_, _)` (same AppliedType internally), for readability (I don't think that unapply was there when I started making this PR)

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala (hunk 2 above)
Comment (jchyb) [reply compiler/src/dotty/tools/dotc/typer/Synthesizer.scala]: `derived=true` allows to convert union and intersection types of NamedTuples into NamedTuple `AppliedType` types. We already know it's a `NamedTupleDirect` from the unapply above, so we don't need to do that (and setting `true` would not change anything here).

**Review by bishabosha — APPROVED** [review]
