### PR TITLE
Append instead of prepending import selectors for the current scope when collecting them in CheckUnused

### LINKED ISSUE #21420: Regression for `-Wunused:import` in `business4s/decisions4s`
## Compiler version
3.5.0 and later
Bisect points to 975df4a136910fe0451514ef0dc34aa29a60aef7

## Minimized code

```Scala
//> using options -Wunused:imports -Werror
object decisions4s{
  trait HKD
  trait DecisionTable
}

object DiagnosticsExample {
  import decisions4s.HKD
  case class Input[F[_]]() extends HKD
  import decisions4s.*
  val decisionTable: DecisionTable = ??? // warn
}
```

## Output

```scala
[warn] ./test.scala:8:22
[warn] unused import
[warn]   import decisions4s.HKD
[warn]                
```

## Expectation
Should not report warnings if wildcard import is placed after usages of explicit import statement.

### PR DESCRIPTION
**Pull request by KacperFKorban**
Also make the wildcard selectors exclusion-aware in CheckUnused

closes #21420

### CODE REVIEW

**Comment by som-snytt** [comment]
I have already marked this fixed by my PR, which rewrites the linting phase.

**Comment by KacperFKorban** [comment]
@som-snytt If you can manage to get your PR into the next release, then I'll gladly close this one. Otherwise, merging this one now and replacing it with your rewrite won't hurt.

**Comment by som-snytt** [comment]
@KacperFKorban no problem, just to avoid duplicate effort. The other PR has items to clean up before I ask someone to spend time on review.

File: compiler/src/dotty/tools/dotc/transform/CheckUnused.scala [hunk 1]
```diff
@@ -832,11 +844,14 @@ object CheckUnused:
 
     final class ImportSelectorData(val qualTpe: Type, val selector: ImportSelector):
       private var myUsed: Boolean = false
+      var exclusedMembers: Set[TermName] = Set.empty
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/CheckUnused.scala:847]:
```suggestion
      var excludedMembers: Set[TermName] = Set.empty
```

File: compiler/src/dotty/tools/dotc/transform/CheckUnused.scala [hunk 2]
```diff
@@ -719,17 +727,21 @@ object CheckUnused:
...
-          if !selData.qualTpe.member(sym.name).hasAltWith(_.symbol == sym) then
+          if altName.fold(
+            selData.exclusedMembers.contains(sym.name.toTermName)
+          )(n => selData.exclusedMembers.contains(n.toTermName)) then
+            // Wildcard with exclusions that match the symbol
+            false
+          else if !selData.qualTpe.member(sym.name).hasAltWith(_.symbol == sym) then
             // The qualifier does not have the target symbol as a member
             false
+          else if selector.isGiven then
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/CheckUnused.scala:738]: Please leave that `if` inside the `else` not to generate irrelevant diffs.

File: compiler/src/dotty/tools/dotc/transform/CheckUnused.scala [hunk 3]
```diff
@@ -719,17 +727,21 @@ object CheckUnused:
               selData.allSymbolsForNamed.contains(sym)
         else
           // Wildcard
-          if !selData.qualTpe.member(sym.name).hasAltWith(_.symbol == sym) then
+          if altName.fold(
+            selData.exclusedMembers.contains(sym.name.toTermName)
+          )(n => selData.exclusedMembers.contains(n.toTermName)) then
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/CheckUnused.scala:732]: Simplify to
```suggestion
          if selData.excludedMembers.contains(altName.getOrElse(sym.name).toTermName) then
```
?

**Review by sjrd — CHANGES_REQUESTED** [review]

**Review by sjrd — APPROVED** [review]

**Comment by som-snytt** [comment]
The funny thing is that the conflict makes rebasing a PR with many commits excessively painful.

**Comment by sjrd** [comment]
Ugh. I did not think you wanted to keep the history intact. In that case a "keep mine" resolution would have been enough.

What you can do is start by *reverting* this commit on your branch, then rebase the rest. Then the rebase should be free, and at the end of the day you reintroduce the test case.

**Comment by som-snytt** [comment]
Thanks, I'll try to improve my gitfu. I have the test case, of course. I tried to be open on my PR about what is to do.
