### PR TITLE
Fix copy of annotation on @main methods

### LINKED ISSUE #22364: Compiler crash with annotation on main method
```scala
//> using scala 3.6.2

import util.chaining.*

class ann(x: Int = 1, y: Int) extends annotation.Annotation

@ann(y = 22.tap(println)) @main def main = ()
```

```
Error: scala.MatchError: Block(List(ValDef(y$1,TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Int)],Apply(TypeApply(Select(Apply(TypeApply(TypedSplice(Ident(scalaUtilChainingOps)),List(TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Int)])),List(Literal(Constant(22)))),tap),List(TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Unit)])),List(Block(List(DefDef($anonfun,List(List(ValDef(x,TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any)],EmptyTree))),TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Unit)],Apply(TypedSplice(Ident(println)),List(TypedSplice(Ident(x)))))),Closure(List(),TypedSplice(Ident($anonfun)),EmptyTree))))), ValDef(x$1,TypeTree[AnnotatedType(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),class Int),ConcreteAnnotation(Apply(Select(New(TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class unchecked)),class uncheckedVariance)]),<init>),List())))],Select(TypedSplice(Ident(ann)),$lessinit$greater$default$1))),Apply(Select(New(TypedSplice(Ident(ann))),<init>),List(TypedSplice(Ident(x$1)), NamedArg(y,TypedSplice(Ident(y$1)))))) (of class dotty.tools.dotc.ast.Trees$Block)
	at dotty.tools.dotc.typer.Namer.typedAheadAnnotationClass(Namer.scala:1774)
	at dotty.tools.dotc.typer.Namer$Completer.addAnnotations$$anonfun$1(Namer.scala:883)
```

### PR DESCRIPTION
**Pull request by mbovel**
Fixes #22364.

See https://github.com/scala/scala3/pull/13858#discussion_r1951084285.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/ast/MainProxies.scala [hunk 1]
```diff
@@ -98,17 +98,17 @@ object MainProxies {
...
-      def insertTypeSplices = new TreeMap {
-          override def transform(tree: Tree)(using Context): Tree = tree match
-            case tree: tpd.Ident @unchecked => TypedSplice(tree)
-            case tree => super.transform(tree)
-      }
+      val annotsCtx = ctx.fresh.setOwner(mainFun)
       val annots = mainFun.annotations
         .filterNot(_.matches(defn.MainAnnot))
-        .map(annot => insertTypeSplices.transform(annot.tree))
+        .map(annot => TypedSplice(annot.tree)(using annotsCtx))
```
Comment (lrytz) [inline compiler/src/dotty/tools/dotc/ast/MainProxies.scala:111]: IIUC, here the annotations are copied from the top-level method (`mainFun`) to the synthetic `main` method. Does the AST not need to be duplicated? Or does `changeOwner` in `typedTypedSplice` duplicate it?

Comment (mbovel) [reply compiler/src/dotty/tools/dotc/ast/MainProxies.scala:111]: > Or does `changeOwner` in `typedTypedSplice` duplicate it?

Yes, the `TypeTreeMap` in `changeOwner` will copy the subtrees that differ. I think that should be enough?

**Review by lrytz — APPROVED** [review]
