### PR TITLE
Fix for #22461 Empty ClassPath attribute in one or more classpath jars causes crash

### LINKED ISSUE #22461: scala_legacy crash caused by any jar in classpath with empty Class-Path: attribute
## Compiler version

```scala
# scala -version
Scala code runner version: 1.5.4
Scala version (default): 3.6.3
```

## Minimized code

```Scala
#!/usr/bin/env -S scala_legacy -classpath ./pallet_3.jar

object LegacyBug {
  def main(args: Array[String]): Unit = {
    printf("hello legacy!\n")
  }
}
```
Can be reproduced by a jar with empty `Class-Path:` attribute.

If the jar has an empty `Class-Path:` attribute in the MANIFEST, it crashes.
If it has no `Class-Path:` attribute, or a non-empty `Class-Path:` attribute, no problem.

## Output

```scala
[warning] MainGenericRunner class is deprecated since Scala 3.5.0, and Scala CLI features will not work.
[warning] Please be sure to update to the Scala CLI launcher to use the new features.
[warning] Check the Scala 3.5.0 release notes to troubleshoot your installation.

  Exception while compiling C:\opt\ue\jsrc\legacyBug.sc

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.


     while compiling: <no file>
        during phase: <some phase>
                mode: Mode()
     library version: version 2.13.15
    compiler version: version 3.6.3
            settings: -classpath C:/opt/scala3/lib/scala.jar;C:/opt/scala3/lib/with_compiler.jar;emptyClassPath.jar -d C:\tmp\scala3-scripting13458733512999800816

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "dotty.tools.io.AbstractFile.ext()" because "file" is null
	at dotty.tools.dotc.classpath.FileUtils$.isJarOrZip(FileUtils.scala:37)
	at dotty.tools.dotc.classpath.ClassPathFactory$.newClassPath(ClassPathFactory.scala:94)
	at dotty.tools.dotc.classpath.ClassPathFactory.newClassPath(ClassPathFactory.scala:20)
	at dotty.tools.dotc.classpath.ClassPathFactory.$anonfun$2$$anonfun$3(ClassPathFactory.scala:73)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
	at scala.collection.immutable.List.prependedAll(List.scala:153)
	at scala.collection.immutable.List$.from(List.scala:685)
	at scala.collection.immutable.List$.from(List.scala:682)
	at scala.collection.IterableOps$WithFilter.map(Iterable.scala:900)
	at dotty.tools.dotc.classpath.ClassPathFactory.$anonfun$2(ClassPathFactory.scala:69)
	at scala.collection.immutable.List.flatMap(List.scala:294)
	at dotty.tools.dotc.classpath.ClassPathFactory.classesInPathImpl(ClassPathFactory.scala:68)
	at dotty.tools.dotc.classpath.ClassPathFactory.classesInExpandedPath(ClassPathFactory.scala:46)
	at dotty.tools.dotc.config.PathResolver$Calculated$.basis(PathResolver.scala:232)
	at dotty.tools.dotc.config.PathResolver$Calculated$.containers$lzyINIT1(PathResolver.scala:236)
	at dotty.tools.dotc.config.PathResolver$Calculated$.containers(PathResolver.scala:236)
	at dotty.tools.dotc.config.PathResolver.containers(PathResolver.scala:258)
	at dotty.tools.dotc.config.PathResolver.result$lzyINIT1(PathResolver.scala:261)
	at dotty.tools.dotc.config.PathResolver.result(PathResolver.scala:260)
	at dotty.tools.dotc.config.JavaPlatform.classPath(JavaPlatform.scala:18)
	at dotty.tools.dotc.config.JavaPlatform.rootLoader(JavaPlatform.scala:38)
	at dotty.tools.dotc.core.Contexts$ContextBase.rootLoader(Contexts.scala:909)
	at dotty.tools.dotc.core.Definitions.RootClass$$anonfun$1(Definitions.scala:203)
	at dotty.tools.dotc.core.Symbols$.$anonfun$2(Symbols.scala:655)
	at dotty.tools.dotc.core.Symbols$.newClassSymbol(Symbols.scala:589)
	at dotty.tools.dotc.core.Symbols$.newModuleSymbol(Symbols.scala:655)
	at dotty.tools.dotc.core.Symbols$.newPackageSymbol(Symbols.scala:716)
	at dotty.tools.dotc.core.Definitions.RootClass(Definitions.scala:203)
	at dotty.tools.dotc.core.Denotations$.recurSimple$1(Denotations.scala:1352)
	at dotty.tools.dotc.core.Denotations$.recur$1(Denotations.scala:1356)
	at dotty.tools.dotc.core.Denotations$.staticRef(Denotations.scala:1360)
	at dotty.tools.dotc.core.Symbols$.requiredPackage(Symbols.scala:944)
	at dotty.tools.dotc.core.Definitions.ScalaPackageVal(Definitions.scala:215)
	at dotty.tools.dotc.core.Definitions.ScalaPackageClass(Definitions.scala:218)
	at dotty.tools.dotc.core.Definitions.AnyClass(Definitions.scala:281)
	at dotty.tools.dotc.core.Definitions.syntheticScalaClasses(Definitions.scala:2184)
	at dotty.tools.dotc.core.Definitions.syntheticCoreClasses(Definitions.scala:2199)
	at dotty.tools.dotc.core.Definitions.init(Definitions.scala:2215)
	at dotty.tools.dotc.core.Contexts$ContextBase.initialize(Contexts.scala:922)
	at dotty.tools.dotc.core.Contexts$Context.initialize(Contexts.scala:544)
	at dotty.tools.dotc.Run.rootContext(Run.scala:502)
	at dotty.tools.dotc.Run.<init>(Run.scala:523)
	at dotty.tools.dotc.Compiler.newRun(Compiler.scala:178)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
	at dotty.tools.scripting.ScriptingDriver.compileAndRun(ScriptingDriver.scala:22)
	at dotty.tools.scripting.Main$.process(Main.scala:39)
	at dotty.tools.MainGenericRunner$.run$1(MainGenericRunner.scala:250)
	at dotty.tools.MainGenericRunner$.process(MainGenericRunner.scala:286)
	at dotty.tools.MainGenericRunner$.main(MainGenericRunner.scala:297)
	at dotty.tools.MainGenericRunner.main(MainGenericRunner.scala)

```

## Expectation
Should not crash.
The following script verifies that scala3-3.3.1 has no problem with the jar file.
```scala
#!/opt/scala3-3.3.1/bin/scala -classpath ./emptyClassPath.jar
object LegacyBug {
  def main(args: Array[String]): Unit = {
    printf("hello legacy!\n")
  }
}
```

An empty string is a legal `classpath` entry, interpreted by the `jvm` as the current working directory, although it might have been created by accident.   The following entry in `build.sbt` can produce a problem jar:

```scala
Compile / packageBin / packageOptions += Package.ManifestAttributes(java.util.jar.Attributes.Name.CLASS_PATH -> "")
```

Here's a script to create a problem jar named `emptyClassPath.jar` in the current directory:
```sh
#!/bin/bash

HERE=`pwd -P`
WORK_NAME=emptyClassPath
PROBLEM_JAR="$HERE"/$WORK_NAME.jar

WORK_DIR=/tmp/${WORK_NAME}$$
MANIFEST="$WORK_DIR"/META-INF/MANIFEST.MF
set -x
mkdir -p $WORK_DIR/META-INF

cd $WORK_DIR
touch main.class
cat > $MANIFEST <<- EOF
Manifest-Version: 1.0
Class-Path:  
Created-By: $WORK_NAME
EOF
cat $MANIFEST
/opt/jdk8/bin/jar -cmf $MANIFEST "$PROBLEM_JAR" .
```

### PR DESCRIPTION
**Pull request by philwalk**
Change to how an empty or `null` jar manifest `ClassPath:` property is handled:

in dotty.tools.dotc.classpath.ClassPathFactory:

- `classesInExpandedPath(...)` returns and empty `IndexedSeq` rather than crash
- `isJarOrZip` returns `false` on a `null` reference rather than crash

in dotty.tools.dotc.classpath.FileUtils:

- `createSourcePath`  fails with an error message on a `null` file parameter.

In the context of #22461, this causes an empty `ClassPath:` property to be treated the same as a mispelled or missing classpath entry, which are silently ignored, matching the behaviour of legacy scripts.

Closes #22461

### CODE REVIEW

**Comment by som-snytt** [comment]
I was interested in trying it out because this is more-or-less shared code with Scala 2. I did not yet reproduce.

I would not expect to handle a possible null in more than one place. Dotty is usually complaining to me that such-and-such might be null, I have to sprinkle `| Null` if I think that is desired.

**Comment by philwalk** [comment]
> I would not expect to handle a possible null in more than one place.

The critical change is [here](https://github.com/scala/scala3/blob/89c20f83c0319d1abe00daa9cec14d23528ce928/compiler/src/dotty/tools/dotc/classpath/ClassPathFactory.scala#L71C1-L73C51) consisting of a `null` check inserted after line 71.
As shown in the stacktrace of #22461, `null` slips past the `if Files.exists(path)`

The other changes don't address this bug, and are optional, intended to provide a more to-the-point error message.

**Comment by philwalk** [comment]
The changes are now reduced to the bare minimum necessary.
A hypothesis as to why the fix is necessary:
```scala
          if Files.exists(path)               // `path` is NOT null
          entry = AbstractFile.getFile(path)  // `entry` IS null (Windows only)
```

**Comment by philwalk** [comment]
The `JVM` does the same thing in `WSL` as in `Windows`, so the reason this bug is Windows-only must be due to what `AbstractFile` does with an empty String `Path`.

```scala
# WSL
$ wsl /opt/scala/bin/scala -e 'printf("%s\n", java.nio.file.Files.exists(java.nio.file.Paths.get("")))'
true
```
```scala
# Windows
$ /opt/scala/bin/scala -e 'printf("%s\n", java.nio.file.Files.exists(java.nio.file.Paths.get("")))'
true
```

**Comment by philwalk** [comment]
To my surprise, the problem exists also in `WSL`, at least implied by the result of the `abstractFileTest.sc` script.
Here's how I did the test in WSL:

```bash
cd ~/workspace/scala3
sbt dist/Universal/packageBin
export SCALA_HOME=`pwd -P`/dist/linux-x86_64/target/universal/stage
export PATH="$SCALA_HOME/bin:$PATH"
```
BTW, the universal distribution includes `scala_legacy` in the `bin` directory.
Here's the test script:
```scala
#!/usr/bin/env -S scala_legacy

object AbstractFileTest {
  def main(args: Array[String]): Unit = {
    import dotty.tools.io.AbstractFile
    import java.nio.file.{Path, Paths, Files}
    val path = Paths.get("")
    printf("path [%s] exists : %s\n", path,  Files.exists(path))
    val entry = AbstractFile.getFile(path)
    printf("entry [%s]\n", entry)
  }
}
```
and here's the output:
```bash
(base) philwalk@d5:~/workspace/scala3$ ./abstractFileTest.sc
[warning] MainGenericRunner class is deprecated since Scala 3.5.0, and Scala CLI features will not work.
[warning] Please be sure to update to the Scala CLI launcher to use the new features.
[warning] Check the Scala 3.5.0 release notes to troubleshoot your installation.
path [] exists : true
entry [null]
```

**Comment by som-snytt** [comment]
FYI the equivalent code on Scala 2 was changed to test `!isDirectory` instead of `isFile`. I even touched `ScriptRunner`! by coincidence.

https://github.com/scala/scala/pull/6365

I see there was one ancient attempt to improve the code in dotty, but I understand the assumption was that it would be replaced altogether at some point. I assume no one would object to any change you deem useful.

I don't know whether this is useful information.
```
➜  cat af-test.scala

object AbstractFileTest {
  def main(args: Array[String]): Unit = {
    //import dotty.tools.io.AbstractFile
    import scala.reflect.io.{AbstractFile, Path}
    import java.nio.file.{Paths, Files}
    val path = Paths.get("")
    printf("path [%s] exists : %s\n", path,  Files.exists(path))
    val x = Path(path.toFile)
    val entry = AbstractFile.getFile(x)
    printf("entry [%s]\n", entry)
  }
}
➜  scala af-test.scala
path [] exists : true
entry []
```

**Review by hamzaremmal — CHANGES_REQUESTED** [review]
I would suggest making the change here instead: 
https://github.com/scala/scala3/blob/fb66f347b5e1d9a493168cf7a4916a2be9e92e27/compiler/src/dotty/tools/io/Jar.scala#L53

```scala
def classPathString: Option[String] =
  for (m <- manifest ; cp <- m.attrs.get(Name.CLASS_PATH) if !cp.isBlank()) yield cp
```

**Comment by philwalk** [comment]
> @philwalk Can you please drop the first commit and adjust the second ? The first commit has nothing to do this the original issue, and reverting it's change will only cause conflicts with your other PR when merging.

Looking into it ...

**Comment by som-snytt** [comment]
I commented on the ticket that the empty attribute is out of spec, so I like the clever idea of pushing the filter down to Jar.

**Comment by philwalk** [comment]
> @philwalk Can you please drop the first commit and adjust the second ? The first commit has nothing to do this the original issue, and reverting it's change will only cause conflicts with your other PR when merging.

It's sounds like I can revert both commits and make your suggested change to `Jar.scala`, does that sound right?

**Comment by hamzaremmal** [comment]
> > @philwalk Can you please drop the first commit and adjust the second ? The first commit has nothing to do this the original issue, and reverting it's change will only cause conflicts with your other PR when merging.
> 
> It's sounds like I can revert both commits and make your suggested change to `Jar.scala`, does that sound right?

Yes, just make sure to have a single commit please

**Comment by philwalk** [comment]
Also, just to be clear, this will revert the change to `dist/libexec/common-shared`,  undoing a needed fix, but with the intent of creating a new PR for that fix later?

**Comment by hamzaremmal** [comment]
> Also, just to be clear, this will revert the change to `dist/libexec/common-shared`, undoing a needed (but unrelated) fix, but with the intent of creating a new PR for that fix later?

There is already a PR for that change: https://github.com/scala/scala3/pull/22444

File: compiler/src/dotty/tools/io/Jar.scala [hunk 1]
```diff
@@ -50,7 +50,7 @@ class Jar(file: File) {
   def mainClass: Option[String]     = manifest.map(_(Name.MAIN_CLASS))
   /** The manifest-defined classpath String if available. */
   def classPathString: Option[String] =
-    for (m <- manifest ; cp <- m.attrs.get(Name.CLASS_PATH)) yield cp
+    for (m <- manifest ; cp <- m.attrs.get(Name.CLASS_PATH) if !cp.isBlank()) yield cp
```
Comment (hamzaremmal) [inline compiler/src/dotty/tools/io/Jar.scala:53]: Well, `String:isBlank` was introduced in Java 11 and we need to compile against Java 8... Sorry for overlooking this detail. Can you instead do the following:
```suggestion
    for (m <- manifest ; cp <- m.attrs.get(Name.CLASS_PATH) if !cp.trim().isEmpty()) yield cp
```

**Review by hamzaremmal — APPROVED** [review]
