### PR TITLE
Avoid erasure/preErasure issues around Any in transformIsInstanceOf

### LINKED ISSUE #21544: For comprehension bug when using type casting
## Compiler version

3.5.0, 3.3.3

## Minimized code

https://scastie.scala-lang.org/road21/GozkhzC7QXaGpkbM7mNYUg/3

```scala
for {
  (x: Any) <- (List[Boolean]())
} yield x
```

## Output

Compile error:
```
[error] cannot test if value of type Boolean is a reference of class Object
[error]   (x: Any) <- (List[Boolean]())
[error]    ^^^^^^
```

## Expectation

No compiler error

Same code works fine in Scala 2.13

### PR DESCRIPTION
**Pull request by dwijnand**
The testType Any is erased to Object, but the expr type Int isn't erased
to Integer, so then it fails as Int `!<:` Object.  We avoid the problem by
feeding in AnyVal, leading to a (possibly elided) non-null test only.

Fixes #21544

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala [hunk 1]
```diff
@@ -358,7 +358,11 @@ object TypeTestsCasts {
                 report.error(em"$untestable cannot be used in runtime type tests", tree.srcPos)
                 constant(expr, Literal(Constant(false)))
               case _ =>
-                val erasedTestType = erasure(testType)
+                val erasedTestType =
+                  if testType.isAny && expr.tpe.isPrimitiveValueType then
+                    defn.AnyValType
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:363]: Isn't that going to trigger with the same issue with any *other* type that erases to `Object`? Like ... `AnyVal` itself?

There's supposed to already be logic in `transformIsInstanceOf` to avoid a type test when `expr.tpe <:< testType`:
https://github.com/scala/scala3/blob/9961e707a65ca9f8adb0128071bbecad43fa0a7e/compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala#L259-L261
The problem is that it tests on erased types, instead of the original types. Addressing that at the root should be more robust, shouldn't it?

File: tests/pos/i21544.scala [hunk 2]
```diff
@@ -0,0 +1,4 @@
+class Test():
+  def m1(xs: List[Boolean]) = for (x: Any) <- xs yield x
+  def m2(xs: List[Boolean]) = for (x: AnyVal) <- xs yield x
+  def m3(xs: List[Boolean]) = for (x: Matchable) <- xs yield x
```
Comment (sjrd) [inline tests/pos/i21544.scala:4]: A few more suggestions for tests:
```scala
  def m1(xs: List[AnyVal]) = for (x: Any) <- xs yield x
  def m1(xs: List[AnyVal]) = for (x: Matchable) <- xs yield x
  def m1(xs: List[Matchable]) = for (x: Any) <- xs yield x
  def m1(xs: List[Any]) = for (x: Any) <- xs yield x
```

**Review by sjrd — APPROVED** [review]
