### PR TITLE
Fix Java generic signatures for context functions

### LINKED ISSUE #10039: Java generic signature and descriptor alignment for context functions
## Minimized code

```Scala
object CtxFns {

  abstract class Context:
    def puts[T](t: T): Unit

  def puts[T](t: T): Context ?=> Unit = summon[Context].puts(t)

}
```

## Output

javap for `CtxFns.puts`:
```java
public <T extends java.lang.Object> scala.Function1<CtxFns$Context, scala.runtime.BoxedUnit> puts(T);
    descriptor: (Ljava/lang/Object;LCtxFns$Context;)V
    flags: ACC_PUBLIC
    Code:
      stack=2, locals=3, args_size=3
         0: aload_2
         1: aload_1
         2: invokevirtual #36                 // Method CtxFns$Context.puts:(Ljava/lang/Object;)V
         5: return
```

## Expectation

the user signature for puts should show that `puts` was simplified to a method with two parameters and void return type

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #10039

## How much have you relied on LLM-based tools in this contribution?

not

## How was the solution tested?

test from the issue turned into a fully automated one

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 1]
```diff
@@ -529,7 +530,14 @@ object GenericSignatures {
     @tailrec def recur(tpe: Type): Type = tpe match
       case mtd: MethodType =>
         vparams ++= mtd.paramInfos.filterNot(_.hasAnnotation(defn.ErasedParamAnnot))
-        recur(mtd.resType)
+        mtd.resType match
+          // Returned context functions are erased by putting their parameters into the method's parameters,
+          // so we must duplicate that logic here
+          case AppliedType(tycon, args) if tycon.typeSymbol.name.isContextFunction =>
+            vparams ++= args.take(args.length - 1)
```
Comment (tanishiking) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:547]: We might want to filter out `.filterNot(_.hasAnnotation(defn.ErasedParamAnnot))` similar to for normal parameters, otherwise, erased type parameter will remain in generic signature, while it is removed in descriptor ?

```scala
import language.experimental.erasedDefinitions

class CanSerialize extends compiletime.Erased

object Test:
  trait Ctx
  def foo(x: Int): CanSerialize ?=> Ctx ?=> String = "foo"
```

(I didn't know about this feature until I see the `vparams ++= mtd.paramInfos.filterNot(_.hasAnnotation(defn.ErasedParamAnnot))` line above :p
https://docs.scala-lang.org/scala3/reference/experimental/erased-defs.html

Comment (tanishiking) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:547]: it seems that for method that contains Erased parameter, the result type will be `RefinedType` instead of `AppliedType`.

We'd like to pattern match against 

```scala
case defn.FunctionTypeOfMethod(mt: MethodType) if mt.isContextualMethod
```

?

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 2]
```diff
@@ -529,7 +530,14 @@ object GenericSignatures {
     @tailrec def recur(tpe: Type): Type = tpe match
       case mtd: MethodType =>
         vparams ++= mtd.paramInfos.filterNot(_.hasAnnotation(defn.ErasedParamAnnot))
-        recur(mtd.resType)
+        mtd.resType match
```
Comment (tanishiking) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala]:
```suggestion
        mtd.resType.dealias match
```

otherwise, it doesn't catch the following case?

```scala
object Test:
   trait Ctx
   type Handler = Ctx ?=> String
   def foo(x: Int): Handler = "hello"
```

**Review by tanishiking — CHANGES_REQUESTED** [review]
Nice catch! I left some concerns but otherwise looks good

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala (hunk 2 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala]: nice catch, thanks!

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala (hunk 1 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:547]: yup, in fact Martin mentioned erased stuff will come out of experimental mode at some point soon the other day, I still forgot about it though... thanks for catching this!

**Review by tanishiking — APPROVED** [review]
LGTM :100:
