### PR TITLE
Mostly fix REPL in sbt

### LINKED ISSUE #25401: REPL doesn't return the prompt when ran through sbt
## Compiler version

3.8.2

## Short description

When I start the repl through sbt (`sbt`, then `console`) using scala 3.8.2, it doesn't return my prompt. I need to press any key to get it back. This doesn't happen with previous scala versions (including 3.8.1).

## Minimized example (incorrect behaviour - 3.8.2)

https://github.com/user-attachments/assets/e13ccfcc-0658-41fd-9610-6a502f85c427

## Expectation (good behaviour - 3.8.1)

https://github.com/user-attachments/assets/35b6b136-ba5a-41e8-903a-cd343b0e8f79

## Environment

Fedora Linux 43 (workstation edition)
Gnome 49 (wayland)
Terminal: Ptyxis
Same results with or without tmux

## Comments

I'm not entirely sure if this issue belongs to this repository. This path was suggested by @eed3si9n on discord. Clearly, something has changed because even the colour of the prompt is different :)

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #25401

Ctrl+C _still_ doesn't work within SBT to interrupt the running task, but it does work in standalone and within Mill...

## How much have you relied on LLM-based tools in this contribution?

Not at all

## How was the solution tested?

Manual tests because writing automated tests is impractical, described below (in detail)

Run the REPL:
- in standalone as bin/replQ,
- within SBT (`console`)
- within Mill

And for each of these, try:
- inputting "whatever" and hit Enter, you should see an error, and then the "scala>" prompt without having to input anything else
- inputting "Console.in.readLine()", you should see what you type, then erase what you typed, type something else, hit Enter, exactly the second input should be the result
- inputting "Console.in.readLine()", then Ctrl+C, then Ctrl+D, you should not see a stack trace

For running inside Mill, run `./mill repl` with the`./mill` from the instructions [here](https://mill-build.org/mill/cli/installation-ide.html#_bootstrap_scripts) with the following `build.mill` file (delete `out` if you need to re-run it after re-`publishLocalBin`-ing a compiler)
```scala
package build

import mill.*, scalalib.*
import mill.api.*

object `package` extends ScalaModule:
  object JvmWorker extends JvmWorkerModule:
    override def repositories =
      super.repositories() ++ Seq(CoursierModule.KnownRepositories.ScalaLangNightlies)

  override def jvmWorker: ModuleRef[JvmWorkerModule] = ModuleRef(JvmWorker)
  override def repositories =
    super.repositories() ++ Seq(CoursierModule.KnownRepositories.ScalaLangNightlies)
  def scalaVersion = "3.9.0-RC1-bin-SNAPSHOT" // change this
```

### CODE REVIEW

File: repl/src/dotty/tools/repl/JLineTerminal.scala [hunk 1]
```diff
@@ -362,10 +371,8 @@ private final class UserInputStream(
             val lineBytes = (line + System.lineSeparator()).getBytes(encoding)
             enqueueBytes(lineBytes)
           catch
-            case _: EndOfFileException =>
+            case _: EndOfFileException | _: UserInterruptException | _: InterruptedException =>
               return -1
-            case _: UserInterruptException =>
-              throw new InterruptedIOException()
```
Comment (SolalPirelli) [inline repl/src/dotty/tools/repl/JLineTerminal.scala:368]: changed + added InterruptException because otherwise if you hit Ctrl+D while SBT is already trying to close your process after you hit Ctrl+C then you get a stack trace which is ugly

**Review by tgodzik — APPROVED** [review]
Looks reasonable 😅

**Comment by SolalPirelli** [comment]
cc @WojciechMazur for a backport to 3.8.4 🙏

**Comment by SethTisue** [comment]
@som-snytt note that `sbt buildQuick` followed by `bin/replQ` should now work, and so should `scala3-repl/run`... or at least they should again after #25969
