### PR TITLE
Fix SemantiDB production of method signature with shadowed parameters

### LINKED ISSUE #23160: Incorrect SemantiDB production of method signatures with shadowed parameters
## Compiler version

scala version 3.7.2

## Minimized code

class IncorrectScalaBehavior {
  def foo(x: Int) = {val x: Boolean = true}
}

## SemanticDB output

Summary:
Schema => SemanticDB v4
Uri => tests/pos/HelloWorld2.scala
Text => empty
Language => Scala
Symbols => 5 entries
Occurrences => 7 entries

Symbols:
_empty_/IncorrectScalaBehavior# => class IncorrectScalaBehavior extends Object { self: IncorrectScalaBehavior => +2 decls }
_empty_/IncorrectScalaBehavior#`<init>`(). => primary ctor <init>(): IncorrectScalaBehavior
_empty_/IncorrectScalaBehavior#foo(). => method foo(val x: Boolean): Unit
_empty_/IncorrectScalaBehavior#foo().(x) => param x: Int
local0 => val local x: Boolean

Occurrences:
[0:6..0:28) <= _empty_/IncorrectScalaBehavior#
[1:2..1:2) <= _empty_/IncorrectScalaBehavior#`<init>`().
[1:6..1:9) <= _empty_/IncorrectScalaBehavior#foo().
[1:10..1:11) <= _empty_/IncorrectScalaBehavior#foo().(x)
[1:13..1:16) => scala/Int#
[1:25..1:26) <= local0
[1:28..1:35) => scala/Boolean#

## Expectation
We expect this line 
_empty_/IncorrectScalaBehavior#foo(). => method foo(val x: Boolean): Unit
to be 
_empty_/IncorrectScalaBehavior#foo(). => method foo(x: Int): Unit

### PR DESCRIPTION
**Pull request by MatthieuSLR9**
Fixes #23160

The problem was caused by the way we populated the  paramRefSymtab in TypeOps.scala.

In #23160  when looking at val x, we will enterParamRef of its owner which is foo. However foo also has a param with name x so it will enter the symbol of the val x in the paramRefSymTab which is incorrect.

We therefore must make sure the symbol is a param to be entered if it's owner was a method.

New test cases were added to confirm the fix.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/semanticdb/TypeOps.scala [hunk 1]
```diff
@@ -96,7 +96,9 @@ class TypeOps:
             // We try to find the "actual" binder of <y>: `inner`,
             // and register them to the symbol table with `(<y>, inner) -> <y>`
             // instead of `("y", outer) -> <y>`
-            if lam.paramNames.contains(sym.name) then
+            // We must also check for parameter shadowing such as def shadowParam(x: Int) = {val x = true}
+
+            if (sym.is(Flags.Param) || !sym.owner.info.isInstanceOf[LambdaType]) &&  lam.paramNames.contains(sym.name) then
```
Comment (natsukagami) [inline compiler/src/dotty/tools/dotc/semanticdb/TypeOps.scala:101]: Any reason to have the `isInstanceOf[LambdaType]` condition here? I tried removing it and semanticdb test fails with 

```diff
❯ diff tests/semanticdb/metac.expect tests/semanticdb/metac.expect.out
2378c2378
< Symbols => 10 entries
---
> Symbols => 13 entries
2385a2386,2387
> example/MatchType$package.Concat#[x] => typeparam x 
> example/MatchType$package.Concat#[xs] => typeparam xs  <: Tuple
2387a2390
> example/MatchType$package.Elem#[t] => typeparam t
```

But I'm not too sure what causes it.

**Review by natsukagami — COMMENTED** [review]
Just one comment about the condition, otherwise looks good, tests are passing as well.

File: compiler/src/dotty/tools/dotc/semanticdb/TypeOps.scala (hunk 1 above)
Comment (MatthieuSLR9) [reply compiler/src/dotty/tools/dotc/semanticdb/TypeOps.scala:101]: It will fail this test as some fakeSymbol will be registered if this condition is removed. This is caused by the fact that for MatchType when we enter the paramRef we will not correctly enter them in the paramRef.

Comment (natsukagami) [reply compiler/src/dotty/tools/dotc/semanticdb/TypeOps.scala:101]: Sounds good. Would be great if we have this comment (shortened if possible) in the source to explain the condition!

Thanks for explaining!

**Review by natsukagami — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/semanticdb/TypeOps.scala (hunk 1 above)
Comment (MatthieuSLR9) [reply compiler/src/dotty/tools/dotc/semanticdb/TypeOps.scala:103]: Yes good idea, I added a short comment just now with a link to this discussion.

**Review by natsukagami — APPROVED** [review]
LGTM!!
