### PR TITLE
Some fixes for AnnotatedTypes mapping

### LINKED ISSUE #5789: Unresolved symbols when pickling annotation referring to parameters or variables
An annotation that refers to parameters or variables compiles fine, but using a method or class with such annotation can lead to this error.
Seems to be easier to hit with separate compilation.

Test A (type parameter):
```scala
class Annot[T] extends scala.annotation.Annotation

class D[T](val f: Int@Annot[T])

object A{
  def main(a:Array[String]) = {
    val c = new D[Int](1)
    c.f
  }
}
```
Output:
```
exception occurred while compiling A.scala
java.lang.AssertionError: assertion failed: unresolved symbols: type T when pickling A.scala while compiling A.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: unresolved symbols: type T when pickling A.scala
	at scala.Predef$.assert(Predef.scala:223)
	at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:691)
	at dotty.tools.dotc.transform.Pickler.$anonfun$run$3(Pickler.scala:60)
	at dotty.tools.dotc.transform.Pickler.$anonfun$run$3$adapted(Pickler.scala:53)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at dotty.tools.dotc.transform.Pickler.$anonfun$run$2(Pickler.scala:53)
	at dotty.tools.dotc.transform.Pickler.$anonfun$run$2$adapted(Pickler.scala:52)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at dotty.tools.dotc.transform.Pickler.run(Pickler.scala:52)
	at dotty.tools.dotc.core.Phases$Phase.$anonfun$runOn$1(Phases.scala:306)
	at scala.collection.immutable.List.map(List.scala:286)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
	at dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:87)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$3(Run.scala:158)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at dotty.tools.dotc.util.Stats$.trackTime(Stats.scala:49)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2(Run.scala:155)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2$adapted(Run.scala:153)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:153)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:178)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:102)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:133)
	at dotty.tools.dotc.Run.compileSources(Run.scala:120)
	at dotty.tools.dotc.Run.compile(Run.scala:104)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:33)
	at dotty.tools.dotc.Driver.process(Driver.scala:166)
	at dotty.tools.dotc.Driver.process(Driver.scala:135)
	at dotty.tools.dotc.Driver.process(Driver.scala:147)
	at dotty.tools.dotc.Driver.main(Driver.scala:174)
	at dotty.tools.dotc.Main.main(Main.scala)
```

Test B (value parameter):
First compile B_1.scala:
```scala
class Annot(val x: Int) extends scala.annotation.Annotation

object B_1{
  def m(x: Int): Int @Annot(x) = 1
}
```
Then compile B_2.scala:
```scala
object B_2{
  def main(a: Array[String]) = {
     val v = B_1.m(2)
  }
}
```
Output:
```
exception occurred while compiling B_2.scala
java.lang.AssertionError: assertion failed: unresolved symbols: value x when pickling B_2.scala while compiling B_2.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: unresolved symbols: value x when pickling B_2.scala
	at scala.Predef$.assert(Predef.scala:223)
	at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:691)
	...
```

Test C (local variable):
First compile C_1.scala:
```scala
class Annot(val x: Int) extends scala.annotation.Annotation

class D[T](val f: T)

object C_1{
  def m() = {
    val y = 1
    new D[Int@Annot(y)](2)
  }
}
```
Then compile C_2.scala:
```scala
object C_2{
  def main(a:Array[String]) = {
     val z = C_1.m()
  }
}
```
Output:
```
exception occurred while compiling C_2.scala
java.lang.AssertionError: assertion failed: unresolved symbols: value y when pickling C_2.scala while compiling C_2.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: unresolved symbols: value y when pickling C_2.scala
	at scala.Predef$.assert(Predef.scala:223)
	at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:691)

```

### LINKED ISSUE #18064: Polymorphic annotations can leak type parameters
## Compiler version

3.3.1-RC1 (on current main)

## Minimized code

Command:
`run path/to/file.scala -Xprint:typer`

File:
```Scala
import scala.annotation.Annotation

class myAnnot[T]() extends Annotation

trait Tensor[T]:

  def add: Tensor[T] @myAnnot[T]()


class TensorImpl[A]() extends Tensor[A]:
  def add = this
```
See also example below without subtyping or inference

## Output

```scala
[[syntax trees at end of                     typer]] // path/to/file.scala
package <empty> {
  import scala.annotation.Annotation
  class myAnnot[T >: Nothing <: Any]() extends scala.annotation.Annotation() {
    T
  }
  trait Tensor[T >: Nothing <: Any]() extends Object {
    T
    def add: Tensor[Tensor.this.T] @myAnnot[T]
  }
  class TensorImpl[A >: Nothing <: Any]() extends Object(), Tensor[
    TensorImpl.this.A] {
    A
    def add: Tensor[A] @myAnnot[T] = this // This T refers to the parent trait's T !
  }
}
```

## Expectation

```scala
[[syntax trees at end of                     typer]] // path/to/file.scala
package <empty> {
  import scala.annotation.Annotation
  class myAnnot[T >: Nothing <: Any]() extends scala.annotation.Annotation() {
    T
  }
  trait Tensor[T >: Nothing <: Any]() extends Object {
    T
    def add: Tensor[Tensor.this.T] @myAnnot[T]
  }
  class TensorImpl[A >: Nothing <: Any]() extends Object(), Tensor[
    TensorImpl.this.A] {
    A
    def add: Tensor[A] @myAnnot[A] = this // Only change
  }
}
```

### LINKED ISSUE #19846: Parameters are not substituted in lambdas in type annotation
## Compiler version

Scala 3.4.2-RC1-bin-20240229-9fe0111-NIGHTLY-git-9fe0111 (17.0.8, Java OpenJDK 64-Bit Server VM)

## Minimized code

Let `dependentAnnotation.scala` contain:

```Scala
package dependentAnnotation

class lambdaAnnot(g: () => Int) extends annotation.StaticAnnotation
def f(x: Int): Int @lambdaAnnot(() => x + 1) = x

@main def main =
  val y: Int = 5
  val z = f(y)
```

## Output

```
scala-cli compile -S 3.nightly -Xprint:typer --server=false dependentAnnotation.scala
```

outputs

```scala
...
val z:
    
      Int @lambdaAnnot(
        {
          def $anonfun(): Int = x.+(1) // Not substituted 😱
          closure($anonfun)
        }
      )
    
    = dependentAnnotation.f(y)
  ()
}
...
```

## Expectation

`x` should be substituted to `y`.

This is the case if the annotation takes an `Int` parameter instead of `() => Int`.

<details>

<summary>Example without a lambda</summary>

```scala
package dependentAnnotation2

class intAnnot(predicate: Int) extends annotation.StaticAnnotation
def f(x: Int): Int @intAnnot(x + 1) = x

@main def main =
  val y: Int = 5
  val z = f(y)
```

```
scala-cli compile -S 3.nightly -Xprint:typer --server=false dependentAnnotation2.scala
```

```scala
...
val z: Int @intAnnot(y.+(1)) = dependentAnnotation2.f(y)
...
```

</details>

### PR DESCRIPTION
**Pull request by mbovel**
Fixes #5789, ~fixes~ #17939, fixes #18064 and ~fixes~ #19846.

Description of 3e1667c3c3930bfeec03355181cced5651e0d642:
> `Annotation.mapWith` maps an `Annotation` with a type map `tm`. As an optimization, this function first checks if `tm` would result in any change (by traversing the annotation’s argument trees with a `TreeAccumulator`) before applying `tm` to the whole annotation tree. This optimization had two problems: 1. it didn’t include type parameters, and  2. it used `frozen_=:=` to compare types, which didn’t work as expected with `NoType`. This commit fixes these issues.
>
> Additionally, positions of trees that appear only inside `AnnotatedType` were not pickled. This commit also fixes this.

### CODE REVIEW

**Comment by mbovel** [comment]
2 test failures in `dotty.tools.scripting.BashExitCodeTests`:

``` 
Error:  Test dotty.tools.scripting.BashExitCodeTests.runPos failed: java.lang.AssertionError: expected 0 but got 1
Error:  stderr:
Error:    No main methods detected for [/tmp/exit-code-tests16570023260888957621/BashExitCodeTests18250568141216098210.sc] expected:<0> but was:<1>, took 2.715 sec
Error:      at dotty.tools.scripting.BashExitCodeTests.verifyExit(BashExitCodeTests.scala:29)
Error:      at dotty.tools.scripting.BashExitCodeTests.scala$$anonfun$1(BashExitCodeTests.scala:32)
Error:      at dotty.tools.scripting.BashExitCodeTests.runPos(BashExitCodeTests.scala:46)
bashCmd: /usr/bin/bash -c "/__w/scala3/scala3/dist/target/pack/bin/scala /tmp/exit-code-tests12984782338892998733/BashExitCodeTests6292908361233855493.sc"
Error:      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Error:      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:      at java.lang.reflect.Method.invoke(Method.java:568)
Error:      ...
Error:  Test dotty.tools.scripting.BashExitCodeTests.scPos failed: java.lang.AssertionError: expected 0 but got 1
Error:  stderr:
Error:    dotty.tools.scripting.StringDriverException: No main methods detected for [/tmp/exit-code-tests17273406077719898552/BashExitCodeTests9163024565476305325.sc]
Error:    	at dotty.tools.scripting.StringDriverException$.apply(StringDriver.scala:52)
Error:    	at dotty.tools.scripting.Util$.detectMainClassAndMethod(Util.scala:54)
Error:    	at dotty.tools.scripting.ScriptingDriver.compileAndRun(ScriptingDriver.scala:28)
Error:    	at dotty.tools.scripting.Main$.process(Main.scala:45)
Error:    	at dotty.tools.scripting.Main$.main(Main.scala:49)
Error:    	at dotty.tools.MainGenericCompiler$.run$1(MainGenericCompiler.scala:177)
Error:    	at dotty.tools.MainGenericCompiler$.main(MainGenericCompiler.scala:186)
Error:    	at dotty.tools.MainGenericCompiler.main(MainGenericCompiler.scala) expected:<0> but was:<1>, took 2.776 sec
Error:      at dotty.tools.scripting.BashExitCodeTests.verifyExit(BashExitCodeTests.scala:29)
Error:      at dotty.tools.scripting.BashExitCodeTests.scalacRaw$$anonfun$1(BashExitCodeTests.scala:33)
Error:      at dotty.tools.scripting.BashExitCodeTests.scPos(BashExitCodeTests.scala:50)
Error:      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Error:      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
bashCmd: /usr/bin/bash -c "/__w/scala3/scala3/dist/target/pack/bin/scalac -d /tmp/exit-code-tests15800954831614427502 -script /tmp/exit-code-tests15800954831614427502/BashExitCodeTests9673740865682828781.sc"
Error:      at java.lang.reflect.Method.invoke(Method.java:568)
Error:      ...
```

```scala
  @Test def runNeg = scala(f("@main def Test = prin", ".sc"))(1)
  @Test def runRun = scala(f("@main def Test = ???", ".sc"))(1)
  @Test def runPos = scala(f("@main def Test = ()", ".sc"))(0)

  @Test def scNeg = scalac("-script", f("@main def Test = prin", ".sc"))(1)
  @Test def scRun = scalac("-script", f("@main def Test = ???", ".sc"))(1)
  @Test def scPos = scalac("-script", f("@main def Test = ()", ".sc"))(0)
```

**Comment by mbovel** [comment]
Overriding `withSymbols` to call `mapSymbols` with `mapAlways = true` alone yields pickling tests failures, as in #17939. I may be missing some substitutions?

```diff
➜  ~/dotty git:(mb/annotations) ✗ diff before-pickling.txt after-pickling.txt
32,34c32
<             def $anonfun(
<               it: scala.Int@tests/pos/annot-19846.scala[136..138]@@(it=tests/pos/annot-19846.scala:<136..136>)):
<               scala.Boolean =
---
>             def $anonfun(it: scala.Int@tests/pos/annot-19846.scala<138..138>@@(it=?)): scala.Boolean =
36,42c34,40
<                 <<it:scala.Int>@tests/pos/annot-19846.scala<142..144>.==:((x: scala.Int): scala.Boolean)>@
<                   tests/pos/annot-19846.scala<142..147>
<               (<EqualPair.this.x:scala.Int>@tests/pos/annot-19846.scala<148..149>):scala.Boolean>@
<                 tests/pos/annot-19846.scala<142..149>
<             @tests/pos/annot-19846.scala[136..139..149]@@($anonfun=tests/pos/annot-19846.scala:<139..139>)
<             <closure(<$anonfun:(it: scala.Int): scala.Boolean>@tests/pos/annot-19846.scala<136..136>):scala.Int =>
<               scala.Boolean>@tests/pos/annot-19846.scala<136..149>
---
>                 <<it:scala.Int>@tests/pos/annot-19846.scala<no position>.==:((x: scala.Int): scala.Boolean)>@
>                   tests/pos/annot-19846.scala<no position>
>               (<EqualPair.this.x:scala.Int>@tests/pos/annot-19846.scala<no position>):scala.Boolean>@
>                 tests/pos/annot-19846.scala<no position>
>             @tests/pos/annot-19846.scala<138..138>@@($anonfun=?)
>             <closure(<$anonfun:(it: scala.Int): scala.Boolean>@tests/pos/annot-19846.scala<138..138>):scala.Int =>
>               scala.Boolean>@tests/pos/annot-19846.scala<138..138>
44c42
<         :scala.Int => scala.Boolean>@tests/pos/annot-19846.scala<136..149>
---
>         :scala.Int => scala.Boolean>@tests/pos/annot-19846.scala<138..138>
➜  ~/dotty git:(mb/annotations) ✗ diff before-pickling.txt after-pickling.txt
39,42c39,40
<             def $anonfun(
<               x: scala.Int@tests/pos/annot-17939.scala<221..224>@tests/pos/annot-17939.scala[218..224]@@(x=
<                 tests/pos/annot-17939.scala:<218..218>)
<             ): scala.Boolean =
---
>             def $anonfun(x: scala.Int@tests/pos/annot-17939.scala<221..224>@tests/pos/annot-17939.scala<221..224>@@(x=?)
>               ): scala.Boolean =
55,57c53,55
<             @tests/pos/annot-17939.scala[217..226..243]@@($anonfun=tests/pos/annot-17939.scala:<226..226>)
<             <closure(<$anonfun:(x: scala.Int): scala.Boolean>@tests/pos/annot-17939.scala<217..217>):scala.Int =>
<               scala.Boolean>@tests/pos/annot-17939.scala<217..243>
---
>             @tests/pos/annot-17939.scala<221..224>@@($anonfun=?)
>             <closure(<$anonfun:(x: scala.Int): scala.Boolean>@tests/pos/annot-17939.scala<224..224>):scala.Int =>
>               scala.Boolean>@tests/pos/annot-17939.scala<224..224>
59c57
<         :scala.Int => scala.Boolean>@tests/pos/annot-17939.scala<217..243>
---
>         :scala.Int => scala.Boolean>@tests/pos/annot-17939.scala<221..224>
➜  ~/dotty git:(mb/19846) diff before-pickling.txt after-pickling.txt
32,34c32
<             def $anonfun(
<               it: scala.Int@tests/pos/annot-19846.scala[136..138]@@(it=tests/pos/annot-19846.scala:<136..136>)):
<               scala.Boolean =
---
>             def $anonfun(it: scala.Int@tests/pos/annot-19846.scala<138..138>@@(it=?)): scala.Boolean =
36,42c34,40
<                 <<it:scala.Int>@tests/pos/annot-19846.scala<142..144>.==:((x: scala.Int): scala.Boolean)>@
<                   tests/pos/annot-19846.scala<142..147>
<               (<EqualPair.this.x:scala.Int>@tests/pos/annot-19846.scala<148..149>):scala.Boolean>@
<                 tests/pos/annot-19846.scala<142..149>
<             @tests/pos/annot-19846.scala[136..139..149]@@($anonfun=tests/pos/annot-19846.scala:<139..139>)
<             <closure(<$anonfun:(it: scala.Int): scala.Boolean>@tests/pos/annot-19846.scala<136..136>):scala.Int =>
<               scala.Boolean>@tests/pos/annot-19846.scala<136..149>
---
>                 <<it:scala.Int>@tests/pos/annot-19846.scala<no position>.==:((x: scala.Int): scala.Boolean)>@
>                   tests/pos/annot-19846.scala<no position>
>               (<EqualPair.this.x:scala.Int>@tests/pos/annot-19846.scala<no position>):scala.Boolean>@
>                 tests/pos/annot-19846.scala<no position>
>             @tests/pos/annot-19846.scala<138..138>@@($anonfun=?)
>             <closure(<$anonfun:(it: scala.Int): scala.Boolean>@tests/pos/annot-19846.scala<138..138>):scala.Int =>
>               scala.Boolean>@tests/pos/annot-19846.scala<138..138>
44c42
<         :scala.Int => scala.Boolean>@tests/pos/annot-19846.scala<136..149>
---
>         :scala.Int => scala.Boolean>@tests/pos/annot-19846.scala<138..138>
```

File: tests/pos-custom-args/captures/i20272b.scala
Comment (Linyxus) [inline tests/pos-custom-args/captures/i20272b.scala:1]: This file seems to be identical to i20272a.scala. I guess you meant to add the example from this [comment](https://github.com/scala/scala3/issues/20272#issuecomment-2083907515)?

Comment (mbovel) [reply tests/pos-custom-args/captures/i20272b.scala:1]: Ah, right! And the correct version fails on this branch 😢

```
Fatal compiler crash when compiling: tests/pos-custom-args/captures/i20272b.scala:
AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),trait Function1),List(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class String), TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class String)))
        at dotty.tools.dotc.cc.CaptureOps$package$.toCaptureRef(CaptureOps.scala:87)
        at dotty.tools.dotc.cc.CaptureOps$package$.$anonfun$1(CaptureOps.scala:96)
        at scala.collection.immutable.List.map(List.scala:250)
        at dotty.tools.dotc.cc.CaptureOps$package$.toCaptureSet(CaptureOps.scala:96)
        at dotty.tools.dotc.cc.Setup$$anon$3.apply(Setup.scala:289)
        at dotty.tools.dotc.cc.Setup.dotty$tools$dotc$cc$Setup$$transformExplicitType(Setup.scala:305)
        at dotty.tools.dotc.cc.Setup.dotty$tools$dotc$cc$Setup$$transformTT(Setup.scala:316)
```

Comment (mbovel) [reply tests/pos-custom-args/captures/i20272b.scala:1]: I removed both `i20272a` and `i20272b` from this PR, as it seems not to fix #20272.

**Comment by mbovel** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
(let's do it again, to see whether this is a fluke or a trend)

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 1]
```diff
@@ -134,10 +134,10 @@ trait TreeInfo[T <: Untyped] { self: Trees.Instance[T] =>
       case _ => argss
     loop(tree, Nil)
 
-  /** All term arguments of an application in a single flattened list */
+  /** All type and term arguments of an application in a single flattened list */
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala:137]: `allArguments` is used by `Annotation#arguments`, which is used by lots of code. How can we be sure the change does not break anything?

File: compiler/src/dotty/tools/dotc/core/Annotations.scala [hunk 2]
```diff
@@ -57,15 +58,25 @@ object Annotations {
...
+        // Checks if `tm` would result in any change by applying it to types
+        // inside the annotations' arguments and checking if the resulting types
+        // are different.
         val findDiff = new TreeAccumulator[Type]:
           def apply(x: Type, tree: Tree)(using Context): Type =
             if tm.isRange(x) then x
             else
               val tp1 = tm(tree.tpe)
-              foldOver(if tp1 frozen_=:= tree.tpe then x else tp1, tree)
+              foldOver(if tp1 == tree.tpe then x else tp1, tree)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/Annotations.scala:69]: We basically never use `==` since it's not very well defined. What breaks if we would still use `frozen_=:=`?

File: compiler/src/dotty/tools/dotc/core/Annotations.scala [hunk 3]
```diff
@@ -57,15 +58,25 @@ object Annotations {
...
         val diff = findDiff(NoType, args)
         if tm.isRange(diff) then EmptyAnnotation
-        else if diff.exists then derivedAnnotation(tm.mapOver(tree))
+        else if diff.exists then
+          // In case of changes, the symbol in the annotation's tree should be
+          // copied so that the same symbol is not used for different trees.
+          val ttm =
+            new TreeTypeMap(typeMap = tm):
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/Annotations.scala:76]: This part LGTM

**Review by odersky — CHANGES_REQUESTED** [review]

**Review by odersky — COMMENTED** [review]
Overall LGTM I only had two questions.

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala (hunk 1 above)
Comment (mbovel) [reply compiler/src/dotty/tools/dotc/ast/TreeInfo.scala:145]: The tests don't show any problem, probably because most annotations don't have type parameters. But we can keep the old behavior: 12ad08527ef1cc89326e672d89eee4a2102ebbdb.

**Comment by mbovel** [comment]
I addressed both questions (in 2 separate commits to ease review, but I can squash them afterward).

File: compiler/src/dotty/tools/dotc/core/Annotations.scala [hunk 4]
```diff
@@ -54,18 +55,26 @@ object Annotations {
...
             if tm.isRange(x) then x
             else
               val tp1 = tm(tree.tpe)
-              foldOver(if tp1 frozen_=:= tree.tpe then x else tp1, tree)
+              foldOver(if !tp1.exists || (tp1 frozen_=:= tree.tpe) then x else tp1, tree)
         val diff = findDiff(NoType, args)
         if tm.isRange(diff) then EmptyAnnotation
-        else if diff.exists then derivedAnnotation(tm.mapOver(tree))
+        else if diff.exists then
+          // If the annotation has been transformed, we need to make sure that the
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/Annotations.scala:73]: Why does transforming an annotation duplicate symbols? Don't we forget the old copy and use only the transformed one?

File: compiler/src/dotty/tools/dotc/transform/PostTyper.scala [hunk 5]
```diff
@@ -157,7 +157,14 @@ class PostTyper extends MacroTransform with InfoTransformer { thisPhase =>
       val saved = inJavaAnnot
       inJavaAnnot = annot.symbol.is(JavaDefined)
       if (inJavaAnnot) checkValidJavaAnnotation(annot)
-      try transform(annot)
+      try
+        val res = transform(annot)
+        if res ne annot then
+          // If the annotation has been transformed, we need to make sure that the
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/transform/PostTyper.scala:163]: Why do we need to handle this here as well? I thought annotation transforms already took care of this themselves?

**Review by odersky — COMMENTED** [review]
I still have several questions about the logic. Why the duplication? Why single out PostTyper? And, why does transforming an annotation require its symbols to be copied separately? Isn't that logic already handled in TreeTypeMap?

File: compiler/src/dotty/tools/dotc/core/Annotations.scala (hunk 4 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/Annotations.scala:73]: The problem is that we have an `Annotated` tree whose type is an `AnnotatedType`, the `Annotated` tree has an `annot` field which is a tree and the `AnnotatedType` has `.annot.tree`. Initially, these tree are equal, but in PostTyper we call `transformAnnot` on both separately, se if PostTyper does some transformation, we end up with two non-referentially-equal trees that define the same symbol and crash in pickler (if PostTyper is the identity, then there is only shared tree and pickler is happy).

I think we could fix this locally in pickler by not pickling the `annot` field of the Annotated tree and instead reconstructing it from the type on unpickling, but more generally for type trees, it seems that `Annotation#annot` should just be a forward call to `.tpe.tree.annot`

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/Annotations.scala:73]: Actually I spoke too soon, it seems that in practice the `Annotated` trees are kept in sync with their  `AnnotatedType`. Things start going wrong when that `AnnotatedType` is used to type another tree (for example in https://github.com/scala/scala3/blob/99f431ef102b6991378003aae793e129f18e235e/compiler/src/dotty/tools/dotc/ast/Desugar.scala#L153 but likely also just through type inference). Since there's no easy way to know if the same `AnnotatedType` is shared by multiple trees, this PR assumes this is always the case and defensively performs symbol copies.

**Comment by smarter** [comment]
The following still fails with this PR:
```scala
class dummy(b: Boolean) extends annotation.StaticAnnotation with annotation.RefiningAnnotation

object Test:
  def foo(elem: Int, bla: Int @dummy(elem == 0)) = bla
```
```scala
-- Error: try/annn2.scala:9:37 -------------------------------------------------
9 |  def foo(elem: Int, bla: Int @dummy(elem == 0)) = bla
  |                                     ^^^^^^^^^
  |          undefined: elem.== # -1: TermRef(TermParamRef(elem),==) at typer
```

The initial typing of the arguments work, but when we want to create the MethodType using `fromSymbols` we perform a substitution. We correctly substitute `TermRef(NoPrefix, elem)` by a `TermParamRef` representing the first parameter of the MethodType, the TypeMap goes back up one level, and creates a new `elem.==`  which can be done without forcing the underlying type of `elem`, but when we go back up one more level and create a new `elem.==(0)`, the TypeAssigner for Apply forces the computation of the underlying type of `elem.==`, which in turn requires computing the underlying type of `elem`, where we get `NoType` because we're in the middle of computing `paramInfos`:

https://github.com/scala/scala3/blob/d490d13e0ccd4279b7586ab0236dd673f884d63f/compiler/src/dotty/tools/dotc/core/Types.scala#L4697-L4700

https://github.com/scala/scala3/blob/d490d13e0ccd4279b7586ab0236dd673f884d63f/compiler/src/dotty/tools/dotc/core/Types.scala#L4091

To avoid this issue it seems we'd need `paramInfos` to be filled progressively as we compute each parameter, so the second parameter can at least safely refer to the first one.

**Comment by mbovel** [comment]
I rebased on top of `main` and reverted the logic that always copies symbols in annotations. As it stands, this PR would fix https://github.com/scala/scala3/issues/5789 and https://github.com/scala/scala3/issues/18064, but not https://github.com/scala/scala3/issues/17939 and https://github.com/scala/scala3/issues/19846. Could we merge this already and tackle other problems—including duplicate symbols and what @smarter described above—in separate PRs?

**Comment by mbovel** [comment]
I squashed two commits together to minimize the changes. No code changes.
