### PR TITLE
Make Ref.apply() return trees usable in the largest scope possible

### LINKED ISSUE #20349: Assertion error during macro generation for an enum
## Compiler version

3.3.3

## Minimized code

`repro.scala`

```scala
//> using scala 3.3.3

import scala.quoted.*

object Macros {


  def valuesImpl[A: Type](using quotes: Quotes): Expr[List[A]] = {
    import quotes.*, quotes.reflect.*

    extension (sym: Symbol)
     def isPublic: Boolean = !sym.isNoSymbol &&
          !(sym.flags.is(Flags.Private) || sym.flags.is(Flags.PrivateLocal) || sym.flags.is(Flags.Protected) ||
            sym.privateWithin.isDefined || sym.protectedWithin.isDefined)

    def isSealed[A: Type]: Boolean =
      TypeRepr.of[A].typeSymbol.flags.is(Flags.Sealed)

    def extractSealedSubtypes[A: Type]: List[Type[?]] = {
      def extractRecursively(sym: Symbol): List[Symbol] =
        if sym.flags.is(Flags.Sealed) then sym.children.flatMap(extractRecursively)
        else if sym.flags.is(Flags.Enum) then List(sym.typeRef.typeSymbol)
        else if sym.flags.is(Flags.Module) then List(sym.typeRef.typeSymbol.moduleClass)
        else List(sym)

      extractRecursively(TypeRepr.of[A].typeSymbol).distinct.map(typeSymbol =>
        typeSymbol.typeRef.asType
      )
    }

    if isSealed[A] then {
      val refs = extractSealedSubtypes[A].flatMap { tpe =>
        val sym = TypeRepr.of(using tpe).typeSymbol
        val isCaseVal = sym.isPublic && sym.flags
          .is(Flags.Case | Flags.Enum) && (sym.flags.is(Flags.JavaStatic) || sym.flags.is(Flags.StableRealizable))

        if (isCaseVal) then List(Ref(sym).asExprOf[A])
        else Nil
      }
      Expr.ofList(refs)
    } else '{ Nil }
  }

  inline def values[A]: List[A] = ${ valuesImpl[A] }
}

```

`repro.test.sc`

```scala
//> using dep org.scalameta::munit:1.0.0-RC1

object domain:
  enum PaymentMethod:
    case PayPal(email: String)
    case Card(digits: Long, name: String)
    case Cash

println(Macros.values[domain.PaymentMethod])
```

```bash
scala-cli test .
```

## Output

```scala
Compiling project (Scala 3.3.3, JVM (17))
Error compiling project (Scala 3.3.3, JVM (17))
Error: Unexpected error when compiling eldupa7_d832c8dfee: java.lang.AssertionError: assertion failed: missing outer accessor in class repro$u002Etest$_
```

## Expectation

`repro.test.sc` should compile successfully (and print something like `List(Cash)`).

### PR DESCRIPTION
**Pull request by jchyb**
Previously for symbols contained in objects (prefixed by, let's say, 'pre'), we would return:
* an Ident if `pre` contained only static object and packages;
* `Select(This(moduleClassSymbol), sym)` if `pre` contained a class.
    
However, this meant that in the second case, the generated tree would require the macro to be expanded inside of the object, even though it should be enough to just expand inside of the innermost class.
This was unexpected and confusing, so it was changed to not return innermost module classes wrapped with This().

Fixes #20349

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 1]
```diff
@@ -1950,7 +1950,6 @@ object SymDenotations {
 
     /** The this-type depends on the kind of class:
      *  - for a package class `p`:  ThisType(TypeRef(Noprefix, p))
-     *  - for a module class `m`: A term ref to m's source module.
```
Comment (jchyb) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala:1953]: Removed because it has not been true since dc02760eac04accb9e0d5e34128f4c79cfa8c327

**Review by hamzaremmal — APPROVED** [review]
