### PR TITLE
Fix extending protected nested java classes

### LINKED ISSUE #21631: Unable to extend protected nested class
Based on Open CB failure in `playframework/playframework` - [builds logs](https://github.com/VirtusLab/community-build3/actions/runs/10857261122/job/30133902315)
Extracted from similar issue: https://github.com/scala/scala3/issues/21599#issuecomment-2367548970

## Compiler version
3.6.0-RC1-bin-20240915-ad8c21a-NIGHTLY
Bisect points to e7d479f80a29c6ae21d0755047e563963b87ac82 / #21362

If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

## Minimized code
When creating a fix for playframework I've seen one interesting issue in their Netty integration 

```Java
// AbstractChannel.java
public abstract class AbstractChannel {
    protected AbstractChannel() {}
    protected abstract AbstractUnsafe newUnsafe();
    protected abstract class AbstractUnsafe {
        public abstract void connect();
    }
}
```

```Scala 
// test.scala
class Channel extends AbstractChannel() {
  override def newUnsafe(): AbstractChannel#AbstractUnsafe = new AbstractUnsafe {
    override def connect(): Unit = ???
  }
}
```

## Output

Fails with 
```scala
[error] ./test.scala:2:66
[error] Unable to emit reference to constructor AbstractUnsafe in class AbstractUnsafe, class AbstractUnsafe is not accessible in anonymous class AbstractChannel.this.AbstractUnsafe {...}
[error]   override def newUnsafe(): AbstractChannel#AbstractUnsafe = new AbstractUnsafe {
[error]                                                                  ^^^^^^^^^^^^^^
Error compiling project (Scala 3.6.0-RC1-bin-20240922-22ed2fb-NIGHTLY, JVM (17))
```

## Expectation
Should compile

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #21631

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/printing/Formatting.scala [hunk 1]
```diff
@@ -109,6 +109,13 @@ object Formatting {
           case Atoms.Range(lo, hi) => CtxShow(s"Range(${toStr(lo.toList)}, ${toStr(hi.toList)})")
       end given
 
+      given Show[ast.untpd.Modifiers] with
+        def show(x: ast.untpd.Modifiers) =
+          CtxShow(s"Modifiers(${toStr(x.flags)}, ${toStr(x.privateWithin)}, ${toStr(x.annotations)}, ${toStr(x.mods)})")
```
Comment (eed3si9n) [inline compiler/src/dotty/tools/dotc/printing/Formatting.scala:114]: nit: Potentially this should be split off into a new PR?

**Review by eed3si9n — APPROVED** [review]
Overall LGTM

File: compiler/src/dotty/tools/dotc/printing/Formatting.scala (hunk 1 above)
Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/printing/Formatting.scala:114]: I've started to keep reasonable debugging changes in my PRs, rather than reapplying them locally every time or having to pull them into a dedicated PR. 😄

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 2]
```diff
@@ -401,7 +401,8 @@ class ClassfileParser(
       classRoot.setFlag(sflags)
       moduleRoot.setFlag(Flags.JavaDefined | Flags.ModuleClassCreationFlags)
 
-      val privateWithin = getPrivateWithin(jflags)
+      val jflags1 = innerClasses.get(currentClassName.toString).fold(jflags: Int)(_.jflags)
```
[the remark this answers is not in the document]
Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:404]: Your "breakage" (not really a breakage) was making correct usage of an accessibility check - which now revealed a bug in determining the accessibility of inner classes, which I'm now fixing.

I'll amend my comment message.

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 3]
```diff
@@ -401,7 +401,8 @@ class ClassfileParser(
...
+      val privateWithin = getPrivateWithin(jflags1)
```
Comment (lrytz) [inline compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:405]: Scala 2 sets the `privateWithin` for inner classes when creating the symbol in `enterOwnInnerClasses`

https://github.com/scala/scala/blob/v2.13.15/src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala#L1055-L1058

Maybe Scala 3 should also do it there?

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 4]
```diff
@@ -1058,13 +1059,18 @@ class ClassfileParser(
...
-      SymbolLoaders.enterClassAndModule(
+      val (cls, mod) = SymbolLoaders.enterClassAndModule(
           getOwner(jflags),
-          entry.originalName,
+        entry.originalName,
           new ClassfileLoader(file),
           classTranslation.flags(jflags),
           getScope(jflags))
 
+      val privateWithin = getPrivateWithin(jflags)
```
Comment (lrytz) [inline compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:1069]: `if privateWithin.exists then` here as well for consistency?

**Review by lrytz — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala (hunk 4 above)
Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:1069]: Sure

**Review by lrytz — APPROVED** [review]
