### PR TITLE
Skip test of legacy compiler if not JDK 17

### LINKED ISSUE #23090: tests with latest master failed with JDK-21 on MacOS
## Compiler version

master of May 2 2024

commit 77401faaa5d57d427748a6ef0da59010635302ee (HEAD -> master, origin/master, origin/HEAD)

## Minimized example

checkout latest version on dotty with 
java version "21" 2023-09-19 LTS
Java(TM) SE Runtime Environment (build 21+35-LTS-2513)
Java HotSpot(TM) 64-Bit Server VM (build 21+35-LTS-2513, mixed mode, sharing)

cd dotty
sbt compile
sbt test

## Output

rssh@rssh4 dotty % sbt test   
[info] welcome to sbt 1.10.7 (Oracle Corporation Java 21)
[info] loading global plugins from /Users/rssh/.sbt/1.0/plugins
[info] loading settings for project dotty-build-build from build.sbt...
[info] loading project definition from /Users/rssh/packages/dotty/dotty/project/project
[info] loading settings for project dotty-build from build.sbt, plugins.sbt...
[info] loading project definition from /Users/rssh/packages/dotty/dotty/project
[info] loading settings for project scala3 from build.sbt...
[info] resolving key references (46024 settings) ...
[info] set current project to scala3 (in build file:/Users/rssh/packages/dotty/dotty/)
[info] compiling 2 Scala sources to /Users/rssh/packages/dotty/dotty/tasty/target/scala-3.7.0-RC4/test-classes ...
[info] Unpacking scalajs-ir sources to /Users/rssh/packages/dotty/dotty/compiler/../out/bootstrap/scala3-compiler-bootstrapped/scala-3.7.1-RC1-bin-SNAPSHOT-nonbootstrapped/src_managed/main/scalajs-ir-src...
[info] compiling 137 Scala sources and 3 Java sources to /Users/rssh/packages/dotty/dotty/compiler/target/scala-3.7.0-RC4/test-classes ...
[info] compiling 5 Java sources to /Users/rssh/packages/dotty/dotty/sbt-bridge/src/target/classes ...
[info] compiling 104 Scala sources and 25 Java sources to /Users/rssh/packages/dotty/dotty/out/bootstrap/scala3-library-bootstrapped/scala-3.7.1-RC1-bin-SNAPSHOT-nonbootstrapped/classes ...
[info] Test run dotty.tools.tasty.BuildTastyVersionTest started
[info] Test dotty.tools.tasty.BuildTastyVersionTest.testBuildTastyVersion started
[info] Test run dotty.tools.tasty.BuildTastyVersionTest finished: 0 failed, 0 ignored, 1 total, 0.269s
[info] Test run dotty.tools.tasty.TastyVersionFormatTest started
[info] Test dotty.tools.tasty.TastyVersionFormatTest.reject_ExperimentalReadFinal_GTEqualMinor started
[info] Test dotty.tools.tasty.TastyVersionFormatTest.accept_FinalReadFinal_LTEqualMinor started
[info] Test dotty.tools.tasty.TastyVersionFormatTest.accept_ExperimentalReadFinal_LTMinor started
[info] Test dotty.tools.tasty.TastyVersionFormatTest.reject_ExperimentalReadNEExperimental started
[info] Test dotty.tools.tasty.TastyVersionFormatTest.reject_NEMajor started
[info] Test dotty.tools.tasty.TastyVersionFormatTest.reject_FinalReadFinal_GTMinor started
[info] Test dotty.tools.tasty.TastyVersionFormatTest.accept_ExperimentalReadEQExperimental_EQMinor started
[info] Test dotty.tools.tasty.TastyVersionFormatTest.reject_FinalReadExperimental started
[info] Test run dotty.tools.tasty.TastyVersionFormatTest finished: 0 failed, 0 ignored, 8 total, 0.01s
[info] Passed: Total 9, Failed 0, Errors 0, Passed 9
[info] compiling 8 Scala sources to /Users/rssh/packages/dotty/dotty/out/bootstrap/tasty-core-bootstrapped/scala-3.7.1-RC1-bin-SNAPSHOT-nonbootstrapped/classes ...
[info] Test run dotty.tools.dotc.classpath.JrtClassPathTest started
[info] Test dotty.tools.dotc.classpath.JrtClassPathTest.lookupJavaClasses started
[info] Test run dotty.tools.dotc.classpath.JrtClassPathTest finished: 0 failed, 0 ignored, 1 total, 0.454s
[info] Test run dotty.tools.io.AbstractFileTest started
[info] Test dotty.tools.io.AbstractFileTest.t6450 started
[info] Test run dotty.tools.io.AbstractFileTest finished: 0 failed, 0 ignored, 1 total, 0.026s
[info] Test run dotty.tools.dotc.parsing.ParserEdgeTest started
[info] Test dotty.tools.dotc.parsing.ParserEdgeTest.t9944 respect line separator started
[info] compiling 600 Scala sources and 8 Java sources to /Users/rssh/packages/dotty/dotty/out/bootstrap/scala3-compiler-bootstrapped/scala-3.7.1-RC1-bin-SNAPSHOT-nonbootstrapped/classes ...
[info] Test run dotty.tools.dotc.parsing.ParserEdgeTest finished: 0 failed, 0 ignored, 1 total, 1.087s
[info] Test run dotty.tools.dotc.core.tasty.PathPicklingTest started
[info] Test dotty.tools.dotc.core.tasty.PathPicklingTest.test started
[info] Test run dotty.tools.dotc.core.tasty.PathPicklingTest finished: 0 failed, 0 ignored, 1 total, 3.278s
[info] Test run dotty.tools.backend.jvm.ClassfileParserTest started
[info] Test dotty.tools.backend.jvm.ClassfileParserTest.noConstantPoolLag started
[info] Test run dotty.tools.backend.jvm.ClassfileParserTest finished: 0 failed, 0 ignored, 1 total, 0.003s
[info] Test run dotty.tools.dotc.FromTastyTests started
[info] Test dotty.tools.dotc.FromTastyTests.runTestFromTasty started
[======================================> ] completed (1643/1645, 0 failed, 188s)class file /modules/java.base/java/lang/reflect/AccessFlag.class is broken, reading aborted with class java.lang.RuntimeException
Full error output:
    ╭┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╮
    ┆class file /modules/java.base/java/lang/reflect/AccessFlag.class is broken, reading aborted with class java.lang.RuntimeException┆
    ┆bad constant pool index: 0 at pos: 5189                                                             ┆
    ╰┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╯
[======================================> ] completed (1643/1645, 0 failed, 188s)-- [E006] Not Found Error: tests/run/backwardsCompat-implicitParens/Test_2.scala:7:14 ----------------------------------
7 |  println(new Bar(""))
  |              ^^^
  |              Not found: type Bar
  |
  | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: tests/run/backwardsCompat-implicitParens/Test_2.scala:8:10 ----------------------------------
8 |  println(Bar(""))
  |          ^^^
  |          Not found: Bar

## Expectation

dorty tests should pass

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #23090 

## How much have your relied on LLM-based tools in this contribution?

LLM-free. 

That is reminiscent of [Ollie, ollie, in come free](https://www.appalachianhistory.net/2017/06/ollie-ollie-in-come-free.html), which is how we said it.

## How was the solution tested?

Manually tested locally under JDK 25, to show that
```
tests/run/backwardsCompat-implicitParens/A_1_c3.0.2.scala
```
causes that test to be skipped.

Single test files were not compiled correctly (with the legacy compiler), so also test that this fails without the fix and is skipped with the fix:
```
tests/run/lazyVals_c3.1.0.scala
```

## Additional notes

Left the unused import of `chaining` because lacking it results in a tangential rabbit hole:

https://github.com/scala/scala3/issues/25451

### CODE REVIEW

**Comment by som-snytt** [comment]
It should also skip "individual" test files.

Edit: tests such as `tests/run/lazyVals_c3.1.0.scala` did not compile with the intended legacy compiler. It would be nice to have test infrastructure for these behaviors, of course.

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala [hunk 1]
```diff
@@ -224,15 +224,33 @@ trait ParallelTesting extends RunnerOrchestration with CoverageSupport:
...
 
     def checkFileBasePathCandidates: Array[String] =
       Array(dir.getPath)
   }
-
+  object SeparateCompilationSource:
+    val CompilerVersion = """c([\d\.]+)""".r
+    val HasCompilerVersion = """_c([\d\.]+)""".r.unanchored
+    val GroupOrdinal = """(\d+)""".r
+    val usingCanonicalJava = javaSpecVersion.startsWith("17")
```
Comment (SolalPirelli) [inline compiler/test/dotty/tools/vulpix/ParallelTesting.scala]: Does "canonical" have a specific meaning in context here?

Comment (som-snytt) [reply compiler/test/dotty/tools/vulpix/ParallelTesting.scala]: Thank-you for asking the hard questions. I will answer when I have a canonical answer.

**Comment by som-snytt** [comment]
The failure is coverage blah blah the single test with legacy compiler `tests/run/lazyVals_c3.1.0.scala`.

Aggravated by bootstrapped test not taking a single test name, so I'm running the entire suite per cycle. Maybe I'll figure out why the test rig is broken.

**Comment by som-snytt** [comment]
Realized that I have to use JDK 17 to run that test, stop laughing.

The bigger joke is that bootstrapped test suite crashed my WSL process.

```
Catastrophic failure
Error code: Wsl/Service/E_UNEXPECTED
Press any key to continue...
```

**Comment by som-snytt** [comment]
The error when trying to select tests is
```
[error] `test / test` tasks in a Scala.js project require `test / fork := false`.
```

**Comment by som-snytt** [comment]
After running the successful suite, I only just noticed:

image

Tossing in options is unexpected. Why isn't it part of the test suite itself?

**Comment by som-snytt** [comment]
Really any test relying on legacy compilation should be excluded from coverage; there aren't many, so I'll look at why more tests don't fail.

**Comment by som-snytt** [comment]
I was too "lazy" to check for more tests to exclude, viz,
```
Test 'tests/run/lazyVals_c3.0.0.scala' failed with output:                      
java.lang.ClassNotFoundException: Test

```
so obviously I wish I'd just implemented my previous suggestion.

**Comment by som-snytt** [comment]
Why I'm not a fan of "list of things everyone must continually edit".

image

If my test can ask to be excluded from Scala-js `scalajs: --skip` then surely it can do the same for coverage or any facility.

File: compiler/test/dotty/tools/vulpix/TestConfiguration.scala [hunk 2]
```diff
@@ -3,11 +3,14 @@ package tools
 package vulpix
 
 import scala.language.unsafeNulls
+import scala.util.Properties.javaSpecVersion
 
 import java.io.File
 
 object TestConfiguration {
 
+  val usingBaselineJava = javaSpecVersion.startsWith("17")
```
Comment (SolalPirelli) [inline compiler/test/dotty/tools/vulpix/TestConfiguration.scala]: any way we can reuse https://github.com/dotty-staging/dotty/blob/main/compiler/src/dotty/tools/dotc/config/ScalaSettingsProperties.scala#L13 to avoid introducing another place that needs changing when we bump the minimum JDK?

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala [hunk 3]
```diff
@@ -1529,6 +1554,8 @@ trait ParallelTesting extends RunnerOrchestration with CoverageSupport:
    *    target all files are grouped according to the file suffix `_X` where `X`
    *    is a number. These groups are then ordered in ascending order based on
    *    the value of `X` and each group is compiled one after the other.
+   *    A file can request compilation by a legacy compiler via a version suffix:
+   *    `A_1_c3.2.0.scala` in group 1 is compiled by 3.2.0 under canonical JDK 17.
```
Comment (SolalPirelli) [inline compiler/test/dotty/tools/vulpix/ParallelTesting.scala]:
```suggestion
   *    `A_1_c3.2.0.scala` in group 1 is compiled by 3.2.0 under the default JDK.
```
the exact version doesn't really matter here and this comment will become obsolete otherwise, IMHO

**Review by SolalPirelli — CHANGES_REQUESTED** [review]
looks nice now, can we future-proof it?

**Comment by som-snytt** [comment]
I see I kept the ignore list in lex order. And there is a quirk that I am configured to terminate text files with a newline, because that is how my mother raised me.

**Comment by som-snytt** [comment]
Don't forget to reconcile with the other PR after dust settles.

**Review by SolalPirelli — APPROVED** [review]
needs conflict resolving but aside from that I think it's good?

**Comment by SolalPirelli** [comment]
poke @som-snytt

**Comment by som-snytt** [comment]
Contention in the plain text exclude list is too bad; did it help or hinder to make changes in lex order (instead of at EOF) to avoid contention? It did not help.

**Comment by SolalPirelli** [comment]
Guess why you need another rebase 🥲

**Comment by som-snytt** [comment]
Awake in the middle of my night, I was going to solve the wordle, but I might as well do something useful, if not productive.

**Comment by SolalPirelli** [comment]
I like https://worldle.teuteuf.fr better anyway
