### PR TITLE
Handle FlexibleTypes in asContextFunctionType

### LINKED ISSUE #23845: `-Yexplicit-nulls` breaks macros expecting `Type` context bound
Based on OpenCB failure in https://github.com/tabdulradi/nullable - [OpenCB logs](https://github.com/VirtusLab/community-build3/actions/runs/17341674243/job/49236443444#step:3:704)
## Compiler version

Last good release: 3.8.0-RC1-bin-20250822-658c8bd-NIGHTLY
First bad release: 3.8.0-RC1-bin-20250823-712d5bc-NIGHTLY

Bisect pointed to 712d5bcb5aad0c69ad612ea9ecd2b45d8c976222 but it does not make sense - this change was not touching the compiler. 

## Minimized code

```scala
//> using options -Yexplicit-nulls
import scala.quoted.*

private def typeNameMacro[A: Type](using Quotes) = Expr(Type.show[A])
transparent inline def typeName[A]: String = ${typeNameMacro[A]}
```

## Output

```scala
-- [E007] Type Mismatch Error: /Users/wmazur/projects/scala/community-build3/example.scala:4:47 ---------------------------------------------------------------------------------------------
4 |transparent inline def typeName[A]: String = ${typeNameMacro[A]}
  |                                               ^^^^^^^^^^^^^^^^
  |                                               Found:    (scala.quoted.Type[A], scala.quoted.Quotes) ?=> (scala.quoted.Expr[(String)?])?
  |                                               Required: (((scala.quoted.Quotes)?) ?=> (scala.quoted.Expr[(String)?])?)?
  |
  | longer explanation available when compiling with `-explain`
```

## Expectation
Should compile

### PR DESCRIPTION
**Pull request by HarrisL2**
Fixes #23845

### CODE REVIEW

**Review by olhotak — APPROVED** [review]
This is great, thank you! Could you please also add the original test from #23845 (with the macro/Quote)? Otherwise LGTM.

**Comment by HarrisL2** [comment]
I don't think the macro/quote version of the issue is reproducible in the test setup, but added nonetheless.

**Comment by olhotak** [comment]
Ah, OK, good point.

File: compiler/src/dotty/tools/dotc/core/Definitions.scala [hunk 1]
```diff
@@ -1996,6 +1996,8 @@ class Definitions {
         asContextFunctionType(TypeComparer.bounds(tp1).hiBound)
       case tp1 @ PolyFunctionOf(mt: MethodType) if mt.isContextualMethod =>
         tp1
+      case tp1: FlexibleType =>
+        asContextFunctionType(tp1.underlying)
```
Comment (hamzaremmal) [inline compiler/src/dotty/tools/dotc/core/Definitions.scala:2000]: Maybe I'm missing something here so I do have a question: Why do we drop the information that this was a Flexible Type (FT) instead of wrapping it over FT?

Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/core/Definitions.scala:2000]: For the purpose here, we only want to extract the information of a context function, so it's ok to widen a flexible type. I would prefer to strip any OrNull/flexible type at the beginning of this function.

Comment (olhotak) [reply compiler/src/dotty/tools/dotc/core/Definitions.scala:2000]: So do you mean changing
```
    tp.stripTypeVar.dealias match
```
to 
```
    tp.stripTypeVar.dealias.stripNull match
```
at the beginning (instead of adding this case)?

Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/core/Definitions.scala:2000]: Yes, maybe before `stripTypeVar`
