### PR TITLE
Fix #21918: Disallow value classes extending type aliases of AnyVal

### LINKED ISSUE #21918: Compiler crashes when value class extends an alias of `AnyVal`
## Compiler version

https://github.com/scala/scala3/commit/cc38962e04a842695647f7006384e18e59ec6c56

## Minimized code

```scala
type AliasToAnyVal = AnyVal
class Foo(a: Int) extends AliasToAnyVal
```

## Output (click arrow to expand)

<details>

```scala
scalac anyval.scala

  unhandled exception while running erasure on anyval.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.

     while compiling: anyval.scala
        during phase: erasure
                mode: Mode(ImplicitsEnabled)
     library version: version 2.13.14
    compiler version: version 3.5.0
            settings:

Exception in thread "main" java.lang.AssertionError: NoDenotation.owner
	at dotty.tools.dotc.core.SymDenotations$NoDenotation$.owner(SymDenotations.scala:2623)
	at dotty.tools.dotc.ast.tpd$.ref(tpd.scala:462)
	at dotty.tools.dotc.transform.Erasure$Boxing$.wrap$1(Erasure.scala:338)
	at dotty.tools.dotc.transform.Erasure$Boxing$.cast(Erasure.scala:366)
	at dotty.tools.dotc.transform.Erasure$Boxing$.unbox(Erasure.scala:320)
	at dotty.tools.dotc.transform.Erasure$Boxing$.adaptToType(Erasure.scala:403)
	at dotty.tools.dotc.transform.Erasure$Typer.adapt(Erasure.scala:1098)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3554)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3558)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3669)
	at dotty.tools.dotc.transform.Erasure$Typer.$anonfun$7(Erasure.scala:863)
	at dotty.tools.dotc.core.Decorators$.zipWithConserve(Decorators.scala:160)
	at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:863)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3392)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3477)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3554)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3558)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3669)
	at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:850)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3392)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3477)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3554)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3558)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3669)
	at dotty.tools.dotc.typer.Typer.$anonfun$64(Typer.scala:2816)
	at dotty.tools.dotc.inlines.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:256)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2816)
	at dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:967)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3374)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3476)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3554)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3558)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3580)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3626)
	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1080)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:3074)
	at dotty.tools.dotc.transform.Erasure$Typer.typedClassDef(Erasure.scala:1056)
	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:3380)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3384)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3476)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3554)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3558)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3580)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3626)
	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1080)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:3207)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3426)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3477)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3554)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3558)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3669)
	at dotty.tools.dotc.transform.Erasure.run(Erasure.scala:145)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:380)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:373)
	at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:343)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:336)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:384)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:396)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:396)
	at dotty.tools.dotc.Run.compileSources(Run.scala:282)
	at dotty.tools.dotc.Run.compile(Run.scala:267)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
	at dotty.tools.dotc.Driver.process(Driver.scala:201)
	at dotty.tools.dotc.Driver.process(Driver.scala:169)
	at dotty.tools.dotc.Driver.process(Driver.scala:181)
	at dotty.tools.dotc.Driver.main(Driver.scala:211)
	at dotty.tools.MainGenericCompiler$.run$1(MainGenericCompiler.scala:162)
	at dotty.tools.MainGenericCompiler$.main(MainGenericCompiler.scala:186)
	at dotty.tools.MainGenericCompiler.main(MainGenericCompiler.scala)
```
</details>

## Notes

The check to determine if a class is a value class doesn't take aliasing into account. See:

https://github.com/scala/scala3/blob/cc38962e04a842695647f7006384e18e59ec6c56/compiler/src/dotty/tools/dotc/ast/Desugar.scala#L597-L601

### PR DESCRIPTION
**Pull request by nox213**
closes https://github.com/scala/scala3/issues/21918

This PR forbids value classes from inheriting type aliases of AnyVal.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/reporting/ErrorMessageID.scala [hunk 1]
```diff
@@ -223,6 +223,7 @@ enum ErrorMessageID(val isActive: Boolean = true) extends java.lang.Enum[ErrorMe
   case IllegalUnrollPlacementID // errorNumber: 207
   case ExtensionHasDefaultID // errorNumber: 208
   case FormatInterpolationErrorID // errorNumber: 209
+  case ValueClassCannotExtendAliasOfAnyValID // errorNumber: 210
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/reporting/ErrorMessageID.scala:226]: awesome errors is an endless source of conflict.
https://github.com/scala/scala3/pull/23002/files

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 2]
```diff
@@ -760,6 +760,10 @@ object Checking {
     // enum extending a value class type (AnyVal or an alias of it)
     // The error message 'EnumMayNotBeValueClassesID' will take care of generating the error message (See #22236)
     if (clazz.isDerivedValueClass && !clazz.isEnumAnonymClass) {
+      val implTree @ Template(_, _, _, _) = cdef.rhs: @unchecked
+      val parent = implTree.parents.head
+      val isExtendingAliasOfAnyVal = parent.tpe.nn.dealias =:= defn.AnyValType && parent.symbol.isAliasType
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala:765]: `rhs match case implTree: Template => etc`. I would put `=:=` last, since it is probably more expensive.

Comment (nox213) [reply compiler/src/dotty/tools/dotc/typer/Checking.scala]: fixed it, thanks for the review

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 3]
```diff
@@ -760,6 +760,15 @@ object Checking {
...
     // The error message 'EnumMayNotBeValueClassesID' will take care of generating the error message (See #22236)
     if (clazz.isDerivedValueClass && !clazz.isEnumAnonymClass) {
+      val parentOpt = cdef.rhs match {
+        case impl: Template =>
+          impl.parents.headOption
+        case _ => None
+      }
+      val isExtendingAliasOfAnyVal = parentOpt.exists { parent =>
+        parent.symbol.isAliasType && parent.tpe.nn.dealias =:= defn.AnyValType
+      }
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala:770]: To avoid the `Option` (incurred for every VC), you could `inline def checkSyntax(): Unit = rhs match etc error()` and then use it below. 

I haven't checked if we only need to check the first parent. I see that `clazz.info` does not help, and now I understand the remark that `AnyVal` is just syntax for inline class. The sibling tickets are for incorrectly not creating a companion (here) or creating one unnecessarily (the other ticket).

It's too bad to add this extra check or restriction. Oh, I wonder if the check really is that the value class has a companion. That is the bug? Right, it compiles if user adds a companion.

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/typer/Checking.scala:770]: `clazz` will always have a companion because of constructor proxies, but it only has a real companion if
```
clazz.companionModule.info.decls.exists(_.isConstructor)
```
So that might suffice as a check.

Speculatively, typer could add the companion tree at that point. I guess extmethods needs a tree to see the module, even though it is all symbolic fiction.

**Comment by som-snytt** [comment]
I pushed the other idea (try to detect "real" companion) at https://github.com/scala/scala3/compare/main...som-snytt:issue/21943-anyval-validation?expand=1

but I didn't want to push it here, since it may be preferable to "outlaw" the alias.

I wasn't able to get it to "inject" the companion late in typer (that is, right after the checks when returning the cdef). I would be more keen about allowing the alias if that worked under the hood for the user (without being a lot of work to implement).

**Comment by nox213** [comment]
So if we decide to forbid this case for the issue, it seems there are two possible approaches:
1. Forbid extending an alias of AnyVal, as in the current PR.
2. Since a companion object isn’t created when extending an alias of AnyVal, check for the presence of a companion object.

Both approaches look fine to me.

**Comment by som-snytt** [comment]
Superficially, I don't see where the red ❌ comes from.

**Comment by nox213** [comment]
I don't know the reason but [Dotty / test_windows_fast (pull_request)](https://github.com/scala/scala3/actions/runs/14618017896/job/41010682232?pr=23021) was cancelled.

**Comment by Gedochao** [comment]
@nox213 @sjrd @som-snytt is this ready to get merged?
