### PR TITLE
Fix #25388: Enhance safe check for synthetic annotations

### LINKED ISSUE #25388: experimental.safe cant define case class or enum "Cannot refer to type AnyRef"
## Compiler version

`3.8.4-RC1-bin-20260227-4e9c706-NIGHTLY`

## Minimized code

```scala
package example
import scala.language.experimental.safe

case class X()
enum Y { case Z }
```

## Output

```scala
-- Error: foo.scala:4:0 --------------------------------------------------------
4 |case class X()
  |^
  |Cannot refer to type AnyRef from safe code since it is neither compiled in safe mode nor tagged with @assumedSafe
-- Error: foo.scala:5:9 --------------------------------------------------------
5 |enum Y { case Z }
  |         ^
  |Cannot refer to type AnyRef from safe code since it is neither compiled in safe mode nor tagged with @assumedSafe
2 errors found
```

### PR DESCRIPTION
**Pull request by noti0na1**
Fixes #25388 

We check if the span of the annotation tree is zero extent to better identify synthetic annotations.

Also update the assumed safe list.

## How much have you relied on LLM-based tools in this contribution?

Not at all for the code; LLM is used to double-check all java api

## How was the solution tested?

Add a test from the original issue

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/cc/SafeRefs.scala [hunk 1]
```diff
@@ -207,6 +236,9 @@ object SafeRefs {
   }
 
   private def checkSafeAnnot(ann: Annotation, pos: SrcPos)(using Context): Unit =
+    val span = ann.tree.span
+    // Skip compiler inserted annotations that have no or zero extent span.
+    if !span.exists || span.isZeroExtent then return
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/cc/SafeRefs.scala:241]: Why `isSynthetic`/`isSourceDerived` on the span of an annotation tree does not work here? Even the annotations written by user are also considered "synthetic".

**Review by odersky — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/cc/SafeRefs.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/cc/SafeRefs.scala:241]: I am not sure. Maybe annotations copied from some othert symbol are synthetic? It would be good to clean that up.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/cc/SafeRefs.scala:241]: For now, we can leave the `isZeroExtent` test.
