### PR TITLE
Regression: fix compilation performance on Windows

### LINKED ISSUE #19924: Compilation performance regression on 3.4.0
## Compiler version

3.4.0

## Expectation

using sbt 1.9.8 in a project of about 500 files split equally between 4 modules compilation time was 70 seconds on scala 3.3.3
scalacOptions is `-feature, -unchecked, -deprecation, -explaintypes, -encoding, UTF8, -language:_, -Yretain-trees, -Xmax-inlines:100, -no-indent`

## Actual

with scala version 3.4.0 same sources with same libs compile in about 120 seconds

### PR DESCRIPTION
**Pull request by OlegYch**
Caches isDirectory calls

Too many of them were added in https://github.com/scala/scala3/commit/607e4d59d93e4ceb0e46469923161516c4e04b60 and this degraded compilation performance by up to 100% on Windows

Fixes #19924
backport to release-3.4.2

### CODE REVIEW

**Comment by OlegYch** [comment]
signed CLA

**Comment by som-snytt** [comment]
We need a "platform linter".

File: compiler/src/dotty/tools/io/PlainFile.scala [hunk 1]
```diff
@@ -78,7 +78,7 @@ class PlainFile(val givenPath: Path) extends AbstractFile {
   }
 
   /** Is this abstract file a directory? */
-  def isDirectory: Boolean = givenPath.isDirectory
+  val isDirectory: Boolean = givenPath.isDirectory
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/io/PlainFile.scala:81]: This is not the best approach. The `givenPath` object is a `dotty.tools.io.Path`. In theory, directories should be `dotty.tools.io.Directory`. Therefore we should optimize `dotty.tools.io.Directory` instead.

```diff
class Directory(jpath: JPath) extends Path(jpath) {
+  override def isDirectory: Boolean = true
+  override def isRegularFile: Boolean = false
  ...
}
```

And we can do the same for `dotty.tools.io.File`

```diff
class Directory(jpath: JPath) extends Path(jpath) {
+  override def isRegularFile: Boolean = true
+  override def isDirectory: Boolean = false
  ...
}
```

**Review by nicolasstucki — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/io/PlainFile.scala (hunk 1 above)
Comment (OlegYch) [reply compiler/src/dotty/tools/io/PlainFile.scala:81]: that doesn't work for some reason
i could cache in dotty.tools.io.Path instead

Comment (OlegYch) [reply compiler/src/dotty/tools/io/PlainFile.scala:81]: hm actually caching might break something as both dotty.tools.io.AbstractFile and dotty.tools.io.Path are mutable

Comment (OlegYch) [reply compiler/src/dotty/tools/io/PlainFile.scala:80]: updated pr

File: compiler/src/dotty/tools/io/PlainFile.scala [hunk 2]
```diff
@@ -78,7 +77,7 @@ class PlainFile(val givenPath: Path) extends AbstractFile {
...
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/io/PlainFile.scala:80]: We should add a comment here
```suggestion
  val isDirectory: Boolean = givenPath.isDirectory // cached for performance on Windows
```

File: compiler/src/dotty/tools/io/AbstractFile.scala [hunk 3]
```diff
@@ -136,12 +136,6 @@ abstract class AbstractFile extends Iterable[AbstractFile] {
   /** Does this abstract file represent something which can contain classfiles? */
   def isClassContainer: Boolean = isDirectory || (jpath != null && ext.isJarOrZip)
 
-  /** Create a file on disk, if one does not exist already. */
-  def create(): Unit
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/io/AbstractFile.scala:140]: We should not delete these now. These might be useful later. Either way, this is not part of the windows performance fix.

**Review by nicolasstucki — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/io/AbstractFile.scala (hunk 3 above)
Comment (OlegYch) [reply compiler/src/dotty/tools/io/AbstractFile.scala:140]: it is part of pr because it conflicts with cached isDirectory
can't leave it be, waiting to bite someone

**Review by jchyb — APPROVED** [review]
Removing `create()` and `delete()` directories is dangerous - dotty.tools.io is a stable library that is being used in other projects, and those methods were implemented for PlainDirectory and PlainFile. With that said I looked through GitHub for all of the usages of those two, and they do not appear to be used anywhere (e.g. PlainDirectory is used in twirl and scalafix, but only to pass output directory to the compiler, PlainFile is only used in the compiler). With that in mind, and considering the performance benefit, I believe this should be merged

**Comment by jchyb** [comment]
Looks like in between the reviews I embarrassingly added a PlainFile.delete() method (which I of course forgot about), which of course I missed during my check right now, meaning we have a failing main. I will revert the revert after removing that delete method for the next release. Apologies for the inconvenience!

**Comment by OlegYch** [comment]
is it possible to add this to 3.4.3 ?

**Comment by SethTisue** [comment]
> is it possible to add this to 3.4.3 ?

(I don't make these decisions myself but) that seems implausible, as 3.4.3 wasn't even a planned release, it's a special hotfix release for a particular problem affecting compatibility, as per https://contributors.scala-lang.org/t/3-4-3-release-thread/6718

project attention is now on the 3.3.x and 3.5.x, and forthcoming 3.6.x series

**Comment by OlegYch** [comment]
@SethTisue i don't think this ended up in 3.5.0
but it seems to be present in 3.5.1-RC2
just a heads up
