### PR TITLE
Fix #20211

### LINKED ISSUE #20211: Vulpix will print a compiler crash when it shouldn't
## Compiler version

Since #20188 was merged

## Reproduce

Running `testCompilation neg-macros` in the `scala3-bootstrapped` project.

## Expectation

Whe testing `neg-macros`, the content of the checkfiles should not be printed in the terminal. This behaviour not only is wrong, but it can also create some confusion.

### PR DESCRIPTION
**Pull request by hamzaremmal**
I'm not sure yet if this is the best was to fix it as it is in contradiction with #20188 

/cc @nicolasstucki

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/TreeChecker.scala [hunk 1]
```diff
@@ -418,35 +418,30 @@ object TreeChecker {
...
-              """.stripMargin + core.TypeComparer.explained(_.isSubType(tp1, tp2))
-            if (tree.hasType) // it might not be typed because Typer sometimes constructs new untyped trees and resubmits them to typedUnadapted
-              assert(isSubType(tree1.tpe, tree.typeOpt), divergenceMsg(tree1.tpe, tree.typeOpt))
-            tree1
-        checkNoOrphans(res.tpe)
-        phasesToCheck.foreach(_.checkPostCondition(res))
-        res
-      catch case NonFatal(ex) if !ctx.run.enrichedErrorMessage =>
-        val treeStr = tree.show(using ctx.withPhase(ctx.phase.prev.megaPhase))
-        println(ctx.run.enrichErrorMessage(s"exception while retyping $treeStr of class ${tree.className} # ${tree.uniqueId}"))
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/TreeChecker.scala:448]: Another option is to print this to one of the loggers.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/transform/TreeChecker.scala:448]: So why is `ctx.run.enrichedErrorMessage` not set?

**Review by odersky — APPROVED** [review]
