### PR TITLE
Extra check to avoid converting block expressions on the rhs of an in…

### LINKED ISSUE #20002: Wrong rewrite of a partial function passed to a symbolic operator
## Compiler version

3..4.1-RC2

## Minimized code

Use `-indent -rewrite` on following code:

```Scala
@main
def main: Unit = {

  object reactions {
    def += (f: PartialFunction[String, Unit]) = ???
  }

  reactions += {
    case a =>
    case b =>
  }
}
```

## Output

```scala
@main
def main: Unit =

  object reactions:
    def += (f: PartialFunction[String, Unit]) = ???

  reactions += :
    case a =>
    case b =>
```

Compiling this results in following error:

> C:\Dev\Sandbox\src\main\scala\Main.scala:7:16
> expression expected but : found
>   reactions += :

## Expectation

The output of "-indent", "-rewrite" should compile without errors

## Note

This pattern is common when using Scala Swing.

### PR DESCRIPTION
**Pull request by LucySMartin**
…fix expression.

Tests added for:
* Original cast as per the ticket should not be changed
* Similar match statement that should update
* Code blocks in this position, as opposed to a partial function, cant update here
* Simple change that should apply but in a code position where the op stack is nonempty
* Equivalent code, but passing in the partial function as a single parameter, again, not updating

Fixes #20002

### CODE REVIEW

**Comment by LucySMartin** [comment]
Fixes #20002

**Comment by som-snytt** [comment]
Does the fixes link need to be in the OP comment? I don't see the ticket saying may be fixed by.

File: tests/rewrites/i20002.scala [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+        ???
+        ???
+      }
+      pp1 orElse pp2
+    }
+
+    val partialFunction = partPartial(1) orElse partPartial(2)
+    Reactions += {
+      partialFunction
+    }
```
Comment (LucySMartin) [inline tests/rewrites/i20002.scala:32]: Technically, this could be rewritten to remove the braces (we would have to add a condition on the match clause that blocks contained elements other than the return - and update the flag that determines if we need to add a colon), however, given that these braces are optional under the old syntax, I chose to leave these ones in.
If it would be preferred that this reduces, I can draft that up next week.

**Comment by LucySMartin** [comment]
> Does the fixes link need to be in the OP comment? I don't see the ticket saying may be fixed by.

It might be because I have no permissions to resolve an issue - its not my bug report and I'm very new here.

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 2]
```diff
@@ -827,10 +829,20 @@ object Parsers {
       }
       var canRewrite = allBraces(in.currentRegion) && // test (1)
         !testChars(in.lastOffset - 3, " =>") // test(6)
+
+      def isStartOfFunction: Boolean =
+        opStack.headOption.exists(x => x.offset > startOpening && x.offset < endOpening)
```
Comment (hamzaremmal) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala:834]:
```suggestion
        opStack.headOption.exists(x => startOpening < x.offset && x.offset < endOpening)
```

**Review by hamzaremmal — CHANGES_REQUESTED** [review]
Thank you for your collaboration to Scala 3. The main issue of this ticket is that at the moment, we rewrite when we have braces after a *symbolic* operator. The syntax doesn't allow us to have an indented block in this case. For this PR, I would expect at least the following test to work: 
- No rewrite:
```scala
Reactions += {
  partialFunction
}
```

- Should rewrite (because the operator is not symbolic): 
```scala
infix def run(f: PartialFunction[Int, Unit]) = ???
    
Reactions run {
  case 0 => ???
}
```

File: tests/rewrites/i20002.scala (hunk 1 above)
Comment (hamzaremmal) [reply tests/rewrites/i20002.scala:32]: We cannot rewrite this to the following:
```scala
 Reactions += :
      partialFunction
```

but we can rewrite it to `Reactions += partialFunction`. Which is out of the scope of this PR and the ticket and should be left for tooling to do.

**Comment by LucySMartin** [comment]
> Thank you for your collaboration to Scala 3. The main issue of this ticket is that at the moment, we rewrite when we have braces after a _symbolic_ operator. The syntax doesn't allow us to have an indented block in this case. For this PR, I would expect at least the following test to work:
> 
> * No rewrite:
> 
> ```scala
> Reactions += {
>   partialFunction
> }
> ```
> 
> * Should rewrite (because the operator is not symbolic):
> 
> ```scala
> infix def run(f: PartialFunction[Int, Unit]) = ???
>     
> Reactions run {
>   case 0 => ???
> }
> ```

Oh! 
Yep - thats a thing.
My professional roll we use brackets everywhere, thats not a place I new you could ignore them.
Ill look into that in some more detail this evening.

**Review by hamzaremmal — APPROVED** [review]
LGTM

**Comment by hamzaremmal** [comment]
@LucySMartin Can you squash your commits before I merge it ? Thanks

**Comment by LucySMartin** [comment]
@hamzaremmal  Squashed. Do you also want a rebase or no?
