### PR TITLE
Fix #21868, #21869, and #21870: handle CapsOf in more places

### LINKED ISSUE #21868: Instantiating abstract types bounded by CapSet with Nothing crashes the capture checker
## Compiler version

Latest nightly.

## Minimized code

```scala
import language.experimental.captureChecking
import caps._

trait Abstract:
    type C <: CapSet
    def boom(): Unit^{this.C^}

class Concrete extends Abstract:
    type C = Nothing
    def boom() = () // dotty.tools.dotc.cc.IllegalCaptureRef: Nothing
```

## Output

The compiler crashes with `dotty.tools.dotc.cc.IllegalCaptureRef: Nothing`.

### LINKED ISSUE #21869: Using abstract types to encode explicit capture polymorphism fails
## Compiler version

Latest NIGHTLY.

## Minimized code

```scala
import language.experimental.captureChecking
import caps._

trait Foo extends Capability

trait CaptureSet:
  type C <: CapSet^

def capturePoly[C^](x: Foo^{C^}): Foo^{C^} = x
def capturePoly2(c: CaptureSet)(x: Foo^{c.C^}): Foo^{c.C^} = x

def test =
  val x: Foo^ = ???

  object X extends CaptureSet:
    type C = CapSet^{x}

  val y: Foo^{x} = capturePoly(x)     // ok
  val z: Foo^{x} = capturePoly2(X)(x) // error
```

## Output

```scala
-- [E007] Type Mismatch Error: local/ccpaths.scala:19:35 -----------------------
19 |  val z: Foo^{x} = capturePoly2(X)(x)
   |                                   ^
   |                                   Found:    (x : Foo^)
   |                                   Required: Foo^{c.C^}
   |
   | longer explanation available when compiling with `-explain`
```

## Expectation

It should be accepted.

### PR DESCRIPTION
**Pull request by noti0na1**
Fix #21868, #21869, and #21870

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/cc/CaptureOps.scala [hunk 1]
```diff
@@ -198,7 +198,7 @@ extension (tp: Type)
       || tp.isRootCapability
       ) && !tp.symbol.isOneOf(UnstableValueFlags)
     case tp: TypeRef =>
-      tp.symbol.isAbstractOrParamType && tp.derivesFrom(defn.Caps_CapSet)
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/cc/CaptureOps.scala:201]: @odersky Do you remember why we require the arguments of `CapsOf` to be abstract before? I think any type derived from CapSet should work.

**Comment by bracevac** [comment]
Strange, we're consistently getting a CI failure `Errors found on incorrect row numbers when compiling tests/vulpix-tests/unit/negNoPositionAnnots.scala`. That does not look related at all to the changes.

File: tests/neg-custom-args/captures/i21868.scala [hunk 2]
```diff
@@ -0,0 +1,14 @@
+import caps.*
+
+trait AbstractWrong:
+    type C <: CapSet
+    def boom(): Unit^{C^} // error
+
+trait Abstract:
+    type C <: CapSet^
```
Comment (noti0na1) [inline tests/neg-custom-args/captures/i21868.scala:8]: Idealy, we'd like to retrict the capture parameter and member bounded by `>: CapSet^{} <: CapSet^`, which can forbid instantiating to meaningless types, like `Nothing`.

Comment (bracevac) [reply tests/neg-custom-args/captures/i21868.scala:8]: That's certainly cleaner. The question is how far we want to take it for now. A fully general solution would also have to deal with the presence of explicit lower bounds, which could be themselves type variables, etc.
```scala
trait Abstract[L >: CapSet^{}]:
    type T >: L <: CapSet^
```
Maybe let's track this in a separate issue? The point of the current fix is to prevent the uncaught exception and compiler crash.

**Comment by bracevac** [comment]
At some point, we should probably make intersection and unions work as well:
```scala
class Concrete2 extends Abstract:
    type C = CapSet^{} & CapSet^{}
    def boom() = () // error

class Concrete3 extends Abstract:
    type C = CapSet^{} | CapSet^{}
    def boom() = () // error
```
It's not unreasonable to expect `CapSet^c1 | CapSet^c2 <:> CapSet^(c1 | c2)` and `CapSet^c1 & CapSet^c2 <:> CapSet^(c1 & c2)`.

**Comment by bracevac** [comment]
OK, so this is weird:
```scala
import language.experimental.captureChecking
import caps.*

trait Abstract[X >: Nothing]: // Concrete2 and 3 fail with this lower bound, but work with X >: CapSet^{}
    type C >: X <: CapSet^
    def boom(): Unit^{C^}

class Concrete extends Abstract[CapSet^{}]:
    type C = CapSet^{}
    def boom() = () // ok

class Concrete2 extends Abstract[CapSet^{}]:
    type C = CapSet^{} & CapSet^{}
    def boom() = () // error

class Concrete3 extends Abstract[CapSet^{}]:
    type C = CapSet^{} | CapSet^{}
    def boom() = () // error
```

**Review by bracevac — APPROVED** [review]
LGTM!

File: tests/neg-custom-args/captures/i21868.scala (hunk 2 above)
Comment (bracevac) [reply tests/neg-custom-args/captures/i21868.scala:8]: As the below examples show, there's a still a few quirks. I'm also somewhat uneasy with automatically presuming that the lower bound of a `CapSet^`-bounded type variable is `CapSet^{}`. E.g., should this always be the case, or only with cc enabled? 

Since the specific issues are resolved, let's merge this and have a separate issue to make capture set intervals and subtyping airtight.
