### PR TITLE
Tighten closure extractor in TreeInfo

### LINKED ISSUE #21620: Captures of curried function are incorrectly dropped
## Compiler version

3.6.0

## Minimized example

```Scala
class C
def test(x: C^) =
  val f = () =>
    def foo() =
      x
      ()
    println(s"hey: $x")
    () => foo()
  val _: () -> () ->{x} Unit = f  // should be error, but compiles
  ()
```

## Output

compiles

## Expectation

An error, since the outer lambda also captures `x` in its println statement.

### PR DESCRIPTION
**Pull request by odersky**
The previous extractor for closures matches also arbitrary blocks that ended in a (possible deeply nested) closure. This caused wrong use sets in #21620. The new definition is stricter. There is also a new blockEndingInclosure extractor that keeps the old behavior.

Fixes #21620

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 1]
```diff
@@ -814,17 +814,31 @@ trait TypedTreeInfo extends TreeInfo[Type] { self: Trees.Instance[Type] =>
       case _ => false
     }
 
-  /** An extractor for closures, either contained in a block or standalone.
+  /** An extractor for closures, possibly typed, and possibly including the
+   *  definition of the ananonymous def.
```
Comment (dwijnand) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala:818]: ... the definition of an anonymous def or _the_ anonymous def?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/ast/TreeInfo.scala:818]: `the` def that corresponds to the closure node.

Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/ast/TreeInfo.scala:818]:
```suggestion
   *  definition of the anonymous def.
```

**Review by dwijnand — APPROVED** [review]
