### PR TITLE
Named arg may be deprecatedName

### LINKED ISSUE #19077: dotc ignores deprecatedName
## Compiler version

3.4.0-RC1-bin-SNAPSHOT-git-3b974c5

## Minimized code

```Scala
Welcome to Scala 3.4.0-RC1-bin-SNAPSHOT-git-3b974c5 (21, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> def f(@deprecatedName x: Int) = x*2
def f(x: Int): Int

scala> f(x=21)
val res0: Int = 42

scala> def f(@deprecatedName("y") x: Int) = x*2
def f(x: Int): Int

scala> f(y=21)
-- Error: --------------------------------------------------------------------------------------------------------------
1 |f(y=21)
  |  ^^^^
  |  method f: (x: Int): Int does not have a parameter y
1 error found
```

## Expectation
```Scala
Welcome to Scala 2.13.12 (OpenJDK 64-Bit Server VM, Java 21).
Type in expressions for evaluation. Or try :help.

scala> def f(@deprecatedName x: Int) = x*2
def f(x: Int): Int

scala> f(x=21)
          ^
       warning: naming parameter x is deprecated.
val res0: Int = 42

scala> def f(@deprecatedName("y") x: Int) = x*2
def f(x: Int): Int

scala> f(y=21)
          ^
       warning: the parameter name y is deprecated: use x instead
val res1: Int = 42
```

Perhaps Dotty hasn't been around long enough for anyone to change a parameter name.

This means it doesn't respect
```Scala
scala> locally(x = 42)
                 ^
       warning: naming parameter x is deprecated.
val res0: Int = 42
```

### PR DESCRIPTION
**Pull request by som-snytt**
For a method definition
```
def f(@deprecatedName("x") x: Int, @deprecatedName y: Int, @deprecatedName("w") z: Int) = x+y+z
```
emit a deprecation warning if `x`, `y`, or `w` are named in an application.

Fixes #19077 

Supersedes https://github.com/scala/scala3/pull/19086

The check for a deprecated name is when an arg is deemed missing: that is when draining the list of args and the current arg is named. Instead of `missingArgs = true`, first check whether this arg is a deprecated name for the current parameter. Fix up that arg to use the canonical name and continue.

`handlePositional` also consumes leading named args that are in position. Common applications such as `f(i, b = true, j)` need not `handleNamed`.

Checking for a deprecated name is expensive but only happens for named args. (Looking for the deprecated name as a fallback would be fine, but every named arg is checked; that is not usually every arg.)

### CODE REVIEW

**Comment by som-snytt** [comment]
Taking the prefix of both named and positional args while no positions change results in `positional after named argument` becoming `parameter is already instantiated` in that subtle test 18122; that's when there is a repeating parameter.

**Comment by som-snytt** [comment]
An interesting pc test failure involving overloading and polytypes.

**Comment by som-snytt** [comment]
That test is still

image

**Comment by som-snytt** [comment]
That is
```
object X { def m[T](i: Int)(s: String) = s*i; def m[T](i: Int)(d: Double) = d*i }

object Y:
  def f = X.m(42)(s = "") // overloading resolution objects to methRef.symbol.paramSymss
```
where `paramss` will step through param lists while `info.paramNames` is nonempty, but param namess has the "extra" type param name, so params are exhausted and Nil.head.

```
SETRAW(method m) List(List(val d))
SETRAW(method m) List(List(val s))
reorder (List(s = "")) meth = TermRef(NoPrefix,method m) or method m
DRILL(method m) List(T) where pss List(List(val d))
DRILL(method m) List(d) where pss List()
```

**Comment by som-snytt** [comment]
The last bit was to use `rawParamss` instead of failing `paramSymss` if it looks like we're in the middle of overload resolution.

**Comment by som-snytt** [comment]
Re-drafting to pre-review the "clean-up".

Edit: squashed. The "refactor" just made it cleaner to add logic for alternative names. Otherwise, the algo is the same.

Note the tweak to `handlePositional` results in the mild progression in `i18122` (just a change in wording).

**Comment by som-snytt** [comment]
I needed this today because `StringOps#apply(i: Int)` should use it.
```
  given Int = 42
  given String = "y"
  def ff(implicit i: Int, s: String = "x") = s * i
  def gg(using i: Int, s: String = "x") = s * i
  ff(using i = 10) // uses default arg
  gg(using i = 10)
  ff(i = 10)
  gg(i = 10) // remarkably, augmentString(gg(given_Int, given_String)).apply(i = 10)
  "hello(i = 1)"
```
It's impossible to warn about "you forgot to say `using`" in a successful application.

Here it was by chance that the parameter names collide, but that's what warnings are for. It's like health insurance.

**Comment by Gedochao** [comment]
Bump @noti0na1

**Comment by noti0na1** [comment]
I saw the CI is still failing?

**Comment by Gedochao** [comment]
Right. 
Rebased, to rule out the flaky tests in that area we had.
@som-snytt is this ready to review?

**Comment by som-snytt** [comment]
Any PR with a "less fewer braces" commit should be ready for review; and the button says green.

File: tests/warn/i19077.scala [hunk 1]
```diff
@@ -0,0 +1,26 @@
+//> using options -deprecation
+
+def f(@deprecatedName("x") x: Int, @deprecatedName y: Int, @deprecatedName("w") z: Int) = x+y+z
```
Comment (noti0na1) [inline tests/warn/i19077.scala:3]: What will happen if two different parameters have the same `deprecatedName` annotation, like `def f(@deprecatedName("x") a: Int, @deprecatedName("x") b: Int)`?

**Review by noti0na1 — APPROVED** [review]
Small question, otherwise LGTM

File: tests/warn/i19077.scala (hunk 1 above)
Comment (som-snytt) [reply tests/warn/i19077.scala:3]: I don't recall, but I'll add a test and find out!

Actually, possibly all names need not be pair-wise distinct, if assigning names in an application just take the first one; then all that matters is that the resulting application has no conflicts.

`def f(@dN("x") y: Int, @dn("y") x: Int)` to allow swapped order. That's to say order of names cannot matter, but the names in an application must be distinct.

I will stop talking now and try a test.

Comment (som-snytt) [reply tests/warn/i19077.scala:3]: As I suspected, scala 2
```
error: deprecated parameter name y has to be distinct from any other parameter name (deprecated or not).
```

Also scala 3 doesn't construct `f(42, x=27)`.

**Comment by som-snytt** [comment]
github is out to lunch.

**Review by noti0na1 — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -3108,6 +3108,16 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
     val paramss1 = paramss.nestedMapConserve(typed(_)).asInstanceOf[List[ParamClause]]
     for case ValDefs(vparams) <- paramss1 do
+      if !ctx.isAfterTyper && !sym.is(Synthetic) then
+        vparams.foldLeft(mutable.Set.empty[Name]): (seen, p) =>
+          if seen(p.name) then
+            report.error(em"parameter name must be distinct from deprecated name", p.srcPos)
+          for annot <- p.symbol.getAnnotation(defn.DeprecatedNameAnnot) do
+            val nm = annot.argumentConstantString(0).map(_.toTermName).getOrElse(nme.NO_NAME)
+            if seen(nm) then
+              report.error(em"deprecated parameter name must be distinct from other names", annot.tree.srcPos)
```
Comment (xuwei-k) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:3118]: - https://github.com/scala/scala3/issues/27038

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 3]
```diff
@@ -669,67 +654,119 @@ trait Applications extends Compatibility {
...
      *      parameter name.
      */
-    def reorder[T <: Untyped](args: List[Trees.Tree[T]]): List[Trees.Tree[T]] = {
+    def reorder[T <: Untyped](args: TreeList[T]): TreeList[T] = {
+
+      extension [A](list: List[A]) inline def dropOne = if list.isEmpty then list else list.tail // aka list.drop(1)
+
+      extension (dna: Annotation)
+        def deprecatedName: Name =
+          dna.argumentConstantString(0).map(_.toTermName).getOrElse(nme.NO_NAME)
```
Comment (xuwei-k) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala:667]: - https://github.com/scala/scala3/issues/27042
