### PR TITLE
Handle TypeProxy of Named Tuples in unapply

### LINKED ISSUE #22150: Named Tuple binding from IArray.unapplySeq pattern can't select fields.
## Compiler version

3.6.2-RC3

## Minimized code

```Scala
//> using options -experimental -language:experimental.namedTuples
val dirs = IArray(
  (dx = 0, dy = 1), // up
  (dx = 1, dy = 0), // right
  (dx = 0, dy = -1), // down
  (dx = -1, dy = 0), // left
)

val IArray(Up @ _, _, _, _) = dirs

def Test = println(Up.dx)
```

## Output

```scala
-- [E008] Not Found Error: -----------------------------------------------------
10 |def Test = println(Up.dx)
   |                   ^^^^^
   |value dx is not a member of Array.UnapplySeqWrapper[? <: (dx : Int, dy : Int)]#T
1 error found
```

## Expectation

selection should work, like it does if the pattern were `Array.unapplySeq` or `Seq.unapplySeq`

### PR DESCRIPTION
**Pull request by aherlihy**
Fixes #22150.
Previously, there were several ways to check if something was a Named Tuple (`derivesFromNamedTuple`, `isNamedTupleType` and `NamedTuple.unapply`), this PR moves everything into `NamedTuple.unapply`.  `namedTupleElementTypes` now takes an argument `derived` that when false will skip `unapply` (to avoid infinite recursion, used in desugaring and RefinedPrinter where trees can have invalid cycles).

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeUtils.scala [hunk 1]
```diff
@@ -128,13 +128,28 @@ class TypeUtils:
...
     def namedTupleElementTypesUpTo(bound: Int, normalize: Boolean = true)(using Context): List[(TermName, Type)] =
+      if bound < 0 then Nil else
       (if normalize then self.normalized else self).dealias match
         case defn.NamedTuple(nmes, vals) =>
           val names = nmes.tupleElementTypesUpTo(bound, normalize).getOrElse(Nil).map(_.dealias).map:
             case ConstantType(Constant(str: String)) => str.toTermName
             case t => throw TypeError(em"Malformed NamedTuple: names must be string types, but $t was found.")
           val values = vals.tupleElementTypesUpTo(bound, normalize).getOrElse(Nil)
           names.zip(values)
+        case tp: TypeProxy =>
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeUtils.scala:139]: Not sure about this. In principle it looks OK, but TypeProxy#superType goes through normalize AFAIK, so it is as if the `normalize` argument has no effect anymore. Does that break things somewhere? What do the tests say?

Comment (aherlihy) [reply compiler/src/dotty/tools/dotc/core/TypeUtils.scala:139]: All compilation tests are passing, haven't finished the full suite yet. From what I could tell the `normalize` argument is just used for [pretty-printing](https://github.com/scala/scala3/blob/main/compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala#L251)? 

The only unrelated tests that failed with this change were [i12456](https://github.com/scala/scala3/blob/main/tests/neg/i12456.scala) and [i9328](https://github.com/scala/scala3/blob/main/tests/neg/i9328.scala) which were fixed with the `bounds` check. I'm really not sure this is the right use of `bounds`, but I noticed it wasn't used anywhere in this method but was used in the [regular tuple method](https://github.com/scala/scala3/blob/main/compiler/src/dotty/tools/dotc/core/TypeUtils.scala#L68-L70) to limit recursion. Given the docstring, this is a bit of a misuse, but for the moment I couldn’t find a nice way to check for cycles / don’t know if that’s done anywhere else I can reuse?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeUtils.scala:139]: OK, should we predicate `TypeProxy` and following cases on `normalize = false` then?

File: compiler/src/dotty/tools/dotc/core/TypeUtils.scala [hunk 2]
```diff
@@ -128,6 +128,7 @@ class TypeUtils:
         case None => throw new AssertionError("not a tuple")
 
     def namedTupleElementTypesUpTo(bound: Int, normalize: Boolean = true)(using Context): List[(TermName, Type)] =
+      if bound < 0 then Nil else
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeUtils.scala:131]: I think that's a bit too coarse. You recurse 2^31 times in the normal case. It's a bit tricky to limit recursion in the face of illegal recursive aliases, because we do the `namedTupleElementTypesUpTo` before Typer in desugaring. There we have not yet checked and ruled out such illegal cycles. 

One idea would be to leave namedTupleElementTypesUpTo as it is for desugaring, but have another version that follows superTypes of TypeProxies in Typer and Completions. Or have another Boolean flag that says whether we should follow proxies and &/I.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeUtils.scala]: > One idea would be to leave namedTupleElementTypesUpTo as it is for desugaring, but have another version that follows superTypes of TypeProxies in Typer and Completions. 

It's not clear to me why desugaring should be treated specially, in https://github.com/scala/scala3/blob/0677702aa4b73dea8740a66296423747fd9bf4ee/compiler/src/dotty/tools/dotc/ast/Desugar.scala#L1747-L1748 immediately after calling `pt.namedTupleElementTypes` we call `pt.classSymbol` and `classSymbol` also recurses on TypeProxy: https://github.com/scala/scala3/blob/0677702aa4b73dea8740a66296423747fd9bf4ee/compiler/src/dotty/tools/dotc/core/Types.scala#L580-L581

Comment (aherlihy) [reply compiler/src/dotty/tools/dotc/core/TypeUtils.scala]: But `selNames.isEmpty` will be false

File: tests/run/i22150.scala [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+
+val directionsNT = IArray(
+  (dx = 0, dy = 1), // up
+  (dx = 1, dy = 0), // right
+  (dx = 0, dy = -1), // down
+  (dx = -1, dy = 0), // left
+)
+val IArray(UpNT @ _, _, _, _) = directionsNT
+
+object NT:
```
Comment (aherlihy) [inline tests/run/i22150.scala:12]: This will pass when https://github.com/scala/scala3/pull/22340 is merged

File: compiler/src/dotty/tools/dotc/core/TypeUtils.scala (hunk 1 above)
Comment (aherlihy) [reply compiler/src/dotty/tools/dotc/core/TypeUtils.scala]: This was resolved by avoiding recurring on TypeProxy when called from the printer.

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 4]
```diff
@@ -110,7 +110,7 @@ object Applications {
   }
 
   def namedTupleOrProductTypes(tp: Type)(using Context): List[Type] =
-    if tp.isNamedTupleType then tp.namedTupleElementTypes.map(_(1))
+    if tp.isNamedTupleType then tp.namedTupleElementTypes(true).map(_(1))
```
[the remark this answers is not in the document]
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:113]: And the same for the other boolean arguments.

File: compiler/src/dotty/tools/dotc/core/TypeUtils.scala [hunk 5]
```diff
@@ -127,8 +127,17 @@ class TypeUtils:
         case Some(types) => TypeOps.nestedPairs(types)
         case None => throw new AssertionError("not a tuple")
 
-    def namedTupleElementTypesUpTo(bound: Int, normalize: Boolean = true)(using Context): List[(TermName, Type)] =
+    def namedTupleElementTypesUpTo(bound: Int, derived: Boolean, normalize: Boolean = true)(using Context): List[(TermName, Type)] =
       (if normalize then self.normalized else self).dealias match
+        // for desugaring and printer, ignore derived types to avoid infinite recursion in NamedTuple.unapply
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeUtils.scala:132]: Can we avoid the duplication with the extractor? Maybe have two extractors `NamedTuple.unapply` and `NamedTupleDirect.unapply` that share the same logic?

**Review by odersky — APPROVED** [review]
The logic looks correct. One can probably streamline this a bit more. But this can be dine later.
