### PR TITLE
Fix active param index for empty param lists

### LINKED ISSUE #19969: Signature help shows wrong active parameter for methods with type params and empty param list.
## Compiler version
3.4.1
## Minimized code

```Scala
  // file dotty/tools/pc/tests/signaturehelp/SignatureHelpSuite.scala
  @Test def `proper-param-empty-list` =
    check(
      """
        |object x {
        |  def foo[K, V](): Unit = ???
        |  foo(@@)
        |}
        |""".stripMargin,
      "foo[K, V](): Unit"
    )

```
## Output
Last parameter is selected as current argument.
## Expectation
No element should be selected as active parameter.

### PR DESCRIPTION
**Pull request by iusildra**
Fixes #19969 with @mbovel @rochala

### CODE REVIEW

File: presentation-compiler/src/main/dotty/tools/pc/SignatureHelpProvider.scala [hunk 1]
```diff
@@ -70,7 +70,7 @@ object SignatureHelpProvider:
         new l.SignatureHelp(
           signatureInfos.map(signatureToSignatureInformation).asJava,
           callableN,
-          paramN
+          if signatureInfos.isEmpty then null else paramN
```
Comment (iusildra) [inline presentation-compiler/src/main/dotty/tools/pc/SignatureHelpProvider.scala:73]: Still need to decide wether we use -1 or null

Comment (rochala) [reply presentation-compiler/src/main/dotty/tools/pc/SignatureHelpProvider.scala:73]: I didn't see this. I've answered below

[the remark this answers is not in the document]
Comment (iusildra) [reply presentation-compiler/src/main/dotty/tools/pc/SignatureHelpProvider.scala:73]: Okay, will push the true fix this evening ^^

**Review by rochala — APPROVED** [review]
