### PR TITLE
Fix implicit search failure reporting

### LINKED ISSUE #19414: Wrong error message for ambiguous given instances
## Compiler version
3.3.1, 3.4.0-RC1-bin-20240109-91db06a-NIGHTLY

## Minimized code
```scala
trait JsValue
trait JsObject extends JsValue

trait JsonWriter[T]
trait BodySerializer[-B]

class JsonPrinter

given JsonWriter[JsValue] = ???
given JsonWriter[JsObject] = ???

given[B : JsonWriter](using printer: JsonPrinter = new JsonPrinter): BodySerializer[B] = ???

def f: Unit =
  summon[BodySerializer[JsObject]]
```

## Output
```
[error] No given instance of type BodySerializer[JsObject] was found for parameter x of method summon in object Predef.
[error] I found:
[error]
[error]     given_BodySerializer_B[B]()
[error]
[error] But given instance given_BodySerializer_B does not match type BodySerializer[JsObject].
[error]   summon[BodySerializer[JsObject]]
[error]                                   ^
```

## Expectation
```
[error] Ambiguous given instances: both given instance given_JsonWriter_JsValue and given instance given_JsonWriter_JsObject match type JsonWriter[B] of parameter x of method summon in object Predef
[error]   summon[BodySerializer[JsObject]]
[error]                                   ^
```

note: the expectation is what I got when I removed the implicit `JsonPrinter` parameter from the given `BodySerializer`:
```scala
given[B : JsonWriter]: BodySerializer[B] = ???
```

### PR DESCRIPTION
**Pull request by mbovel**
Fixes #19414.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -3923,18 +3912,36 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
+            // If the retyped tree still has an error type and is an `Apply`
+            // node, we can report the errors for each argument nicely.
+            // Otherwise, we don't report anything here.
+            retyped match
+              case retyped: Apply if retyped.tpe.isError => reportErrors(retyped, wtp)
+              case _ => ()
+
+            retyped
+          else
+            val res = untpd.Apply(tree, args).withType(firstFailure.get)
```
Comment (mbovel) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:3942]: Before we would use the first non-ambiguous error if there is one; here I simplified it to just use the first error.

@odersky commented on #19414 that:

> Ambiguous implicits often arise when something else is failing (for instance a variable was not instantiated enough). That's why we try to find first other errors. That was the thinking behind the current semantic.

But I think this is not relevant anymore after the changes in this PR; as we're anyway reporting all errors by recursively visiting the argument trees.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -3872,49 +3871,39 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
+                val paramStr = implicitParamString(paramName, methodStr, fun)
+                val paramSymWithMethodCallTree =
+                  fun.symbol.paramSymss.flatten
+                    .find(_.name == paramName)
+                    .map((_, appTree))
+                val message = missingArgMsg(arg, formal, paramStr, paramSymWithMethodCallTree)
+                // Note: if the same error type appears on several trees, we
+                // might report it several times, but this is not a problem
+                // because only the first one will be displayed. We traverse in
+                // post-order, so that the most detailed message gets displayed.
```
Comment (mbovel) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:3900]: Can I rely on this? I observed this behavior but haven't dug into it.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:3900]: Yes, that's what's implemented.

File: tests/neg/implicitSearch.check [hunk 3]
```diff
@@ -1,12 +1,7 @@
 -- [E172] Type Error: tests/neg/implicitSearch.scala:13:12 -------------------------------------------------------------
 13 |    sort(xs)  // error (with a partially constructed implicit argument shown)
    |            ^
-   |      No given instance of type Test.Ord[List[List[T]]] was found for parameter o of method sort in object Test.
-   |      I found:
-   |
-   |          Test.listOrd[List[T]](Test.listOrd[T](/* missing */summon[Test.Ord[T]]))
-   |
-   |      But no implicit values were found that match type Test.Ord[T].
+   |            No given instance of type Test.Ord[T] was found for parameter o of method listOrd in object Test
```
Comment (odersky) [inline tests/neg/implicitSearch.check:4]: The change in parameter name is good, but I think we should keep the "I found" part of the error message. Otherwise it's not clear why a listOrd is required in the first place. The "I found" part tells you that.

**Review by odersky — CHANGES_REQUESTED** [review]
Let's discuss how we can be the functionality of "I found" in the error messages before a more detailed code review.

**Comment by mbovel** [comment]
I tried something a bit different to keep the "I found" messages.

The problematic case with the current infrastructure (apart from handling default arguments) is really ambiguous implicit that are nested. In this case, we just bubble the error up and the error message then use the wrong param names, but all the other cases are fine.

So, to solve this, I tried to just add a `nested` flag in `AmbiguousImplicits` and modified the error message to also use the ""I found"-flavored if this flag is set to `true`. This avoids having to recursively traverse the tree of the failing implicit to display error.

This approach leaves all existing tested message outputs unchanged, but only fixes the new test cases.

**Comment by mbovel** [comment]
@odersky: I changed the message to be "No best given [...]" for ambiguous implicits, as discussed.

**Comment by mbovel** [comment]
Potential regression: #20344.
