### PR TITLE
Fix #19746: Do not follow param term refs in `isConcrete`.

### LINKED ISSUE #19746: Unsound reduction of match types
## Compiler version

3.4.2-RC1

## Minimized example

```Scala
trait V:
  type X = this.type match
    case W[x] => x

trait W[+Y] extends V

extension (self: Any) def as[T]: T =
  def asX(w: W[Any]): w.X /* <- reduces to Any */ = self
  asX(new W[T] {}) /* <- reduces to T */

0.as[Boolean] // java.lang.ClassCastException
```

The issue is that `w.X` reduces to `Any` because the scrutinee `w` is widened to `W[Any]` before attempting the reduction of the match type.

### PR DESCRIPTION
**Pull request by sjrd**
Term refs that reference term parameters can be substituted later by more precise ones, which can lead to different instantiations of type captures. They must therefore be considered as non concrete when following `baseType`s to captures in variant positions, like we do for type param refs and other substitutable references.

We actually rewrite `isConcrete` in the process to be more based on an "allow list" of things we know to be concrete, rather than an "exclusion list" of things we know to be non-concrete. That should make it more straightforward to evaluate the validity of the algorithm.

### CODE REVIEW

**Comment by sjrd** [comment]
Huh, I'm surprised this didn't break anything in the (small) community build. 😅

Anyway, seems good to review, then.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -3360,37 +3360,44 @@ class MatchReducer(initctx: Context) extends TypeComparer(initctx) {
...
+            isConcrete(tp1.underlying)
+          case tp1: ExprType =>
+            isConcrete(tp1.underlying)
+          case tp1: AnnotatedType =>
+            isConcrete(tp1.parent)
+          case tp1: RefinedType =>
+            isConcrete(tp1.underlying)
+          case tp1: RecType =>
+            isConcrete(tp1.underlying)
+          case tp1: AndOrType =>
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:3395]: Note to @noti0na1 : This will need to be updated for flexibletypes.

**Review by odersky — APPROVED** [review]
LGTM
