### PR TITLE
Better error diagnostics under -explain-cyclic

### LINKED ISSUE #20245: Incremental compilation leads to Cyclic Reference Error
Incrementally recompiling leads to "Cyclic reference" while fresh compilation succeeds.

We consistently hit this issue when touching our own `Typer.scala` forcing us to *always* `clean; compile` which of course takes longer than incrementally compiling.

## Compiler version
3.3.1, 3.4.1

## Minimized code
I minimized our compiler to only a few lines of code in:

https://github.com/effekt-lang/effekt/pull/446

the full minimized example (not the diff or PR) can be found here

https://github.com/effekt-lang/effekt/tree/34b9e79126db91604df4785aaabace15d154f8cb

## Output

```scala
[error] -- [E046] Cyclic Error: /private/tmp/effekt/effekt/shared/src/main/scala/effekt/Typer.scala:15:57
[error] 15 |  private[typer] val unification = new Unification(using this)
[error]    |                                                         ^
[error]    |                                Cyclic reference involving class Context
[error]    |
[error]    | longer explanation available when compiling with `-explain`
[error] one error found
[error] (root / Compile / compileIncremental) Compilation failed
```

## Expectation
It should consistently compile or always report the error, if this is indeed a problem.

### PR DESCRIPTION
**Pull request by odersky**
Also report type-checked right hand sides and export expansions.

Streamline trace-handling code using inline functions.

Fixes #20245

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeErrors.scala [hunk 1]
```diff
@@ -198,20 +198,31 @@ object CyclicReference:
...
+  type TraceElement = Context ?=> String
   type Trace = mutable.ArrayBuffer[TraceElement]
   val Trace = Property.Key[Trace]
 
-  def isTraced(using Context) =
+  private def isTraced(using Context) =
     ctx.property(CyclicReference.Trace).isDefined
 
-  def pushTrace(info: TraceElement)(using Context): Unit =
+  private def pushTrace(info: Context ?=> String)(using Context): Unit =
```
Comment (mbovel) [inline compiler/src/dotty/tools/dotc/core/TypeErrors.scala:208]: Couldn't the type of `info` stay `TraceElement?

**Review by mbovel — APPROVED** [review]
Looks good to me!

File: compiler/src/dotty/tools/dotc/core/TypeErrors.scala (hunk 1 above)
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeErrors.scala:208]:
```suggestion
  private def pushTrace(info: TraceElement)(using Context): Unit =
```
