### PR TITLE
Preventing compilation of a @tailrec method when it does not rewrite, but an inner method does

### LINKED ISSUE #20105: @tailrec and nested definitions
## Compiler version

3.4.0
(also validated on near latest local build `3.5.0-RC1-bin-SNAPSHOT-nonbootstrapped-git-9a5b9b4`

## Minimized code

This compiles:
```Scala
  @tailrec
  def foo(): Unit =
    def bar(): Unit =
      if (???)
        foo()
      else
        bar()
    bar()
```
This does not:
```Scala
  @tailrec
  def foo(): Unit =
    def bar(): Unit =
      if (???)
        foo()
    bar()

```

## Output

These should no compile, as there are no tail recursive calls within the outer `@tailrec` annotated block. It has erroneously detected that this is ok, due to the rewrite of the inner `bar` method. This should not compile, and if this were not annotated with `@tailrec`, the outer `tailLabel` should not be generated.

Looking into the one that does compile, it generates an unutilised label `testLabel2[Unit]:` , and fails to warn about having no tail
l recursion optimised calls on the to level method:

```Scala
    @tailrec def foo(): Unit =
      {
        while <empty> do 
          tailLabel2[Unit]: 
            return
              {
                def bar(): Unit =
                  {
                    while <empty> do 
                      tailLabel1[Unit]: 
                        return
                          if ???() then Test.foo() else 
                            (return[tailLabel1] ()):Unit
                  }
                bar()
              }
      }
```

## Expectation

For the behaviour between these two (weather this is an acceptable place to recur or not) to be consistent between these cases - or in the alternative - to support multi tiered tail recursion.

## Notes

This compiles (and indeed rewrites to a loop) if the inner method is declared as inline. Potentially a rule that within annotated `@tailrec` methods, any inner methods that call the top level method are handled as `inline` for simple uses directly within this method?

I was having a play around, and while complex, it does look feasible that we could have some sort of rewrite that processes this as a single larger rewrite. What would people thing of optimiseing to something like this:
```Scala
import scala.annotation.tailrec
import scala.util.boundary
import scala.util.boundary.break

object Test extends App {
    
  //println(a(0))
  println(a_tr(0))

  var count = 0

  def f(tNum: Int): Boolean = {
    count = count + 1
    if (count > 100000) {
      throw new Exception("Infinitely looping")
    }
    tNum == 4 || tNum == 1
  }

  @tailrec
  def a(i: Int): Int = {
    @tailrec
    def b(j: Int): Int = {
      if (f(1)) {
        a(j + 1)
      } else if (f(2)) {
        b(j + 1)
      } else {
        j
      }
    }

    if (f(3)) {
      a(i + 1)
    } else if (f(4)) {
      b(i + 1)
    } else {
      i
    }
  }

 //identical to a, but with tail recursion logic applied
  def a_tr(i: Int): Int = {
    class AExit
    class ATail

    var aRes: Int | Null = null

    boundary[AExit] {
      var aIState = i
      while (true) {
        boundary[ATail] {
          while (true) {
            def b(j: Int): Int = {
              var bJState = i
              while (true) {
                if (f(1)) {
                  aIState = bJState + 1
                  break(new ATail)
                } else if (f(2)) {
                  bJState = bJState + 1
                } else {
                  aRes = bJState
                  break(new AExit())
                }
              }
              ???
            }

            if (f(3)) {
              aIState = aIState + 1
            } else if (f(4)) {
              b(aIState + 1)
            } else {
              aRes = aIState
              break(new AExit)
            }
          }
          ???
        }
      }
      ???
    }

    aRes.nn
  }

}
```

### PR DESCRIPTION
**Pull request by LucySMartin**
Adding warnings if there is an annotated def at the top level that is referenced from an inner def

Fixes #20105

### CODE REVIEW

**Comment by som-snytt** [comment]
Sorry, I complained about having to rewrite error IDs repeatedly. Probably there is a way to make that part of the build. Or maybe they use it as a right of passage of sorts.

**Comment by LucySMartin** [comment]
> Sorry, I complained about having to rewrite error IDs repeatedly.

No worries. I've had much much worse hand numbered files to merge in my time.

File: tests/neg/i20105.scala
Comment (sjrd) [inline tests/neg/i20105.scala:1]: For new neg tests, we should always add a corresponding `.check` file that reproduces the exact output of the compiler. My workflow to do that is to add an empty `.check` file with the same name, run the test (which therefore fails), then execute the `mv` command that the test failures suggests.

File: compiler/src/dotty/tools/dotc/transform/TailRec.scala [hunk 1]
```diff
@@ -446,14 +459,28 @@ class TailRec extends MiniPhase {
 
         case Return(expr, from) =>
           val fromSym = from.symbol
-          val inTailPosition = !fromSym.is(Label) || tailPositionLabeledSyms.contains(fromSym)
+          val inTailPosition = (!fromSym.is(Label) || tailPositionLabeledSyms.contains(fromSym)) // Label returns are only tail if the label is in tail position
+            && (!fromSym.is(Method) || (fromSym eq method)) // Method returns are only tail if we are looking at the original method
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/TailRec.scala:463]: Since `fromSym` can only be a `Label` or a `Method`, consider rewriting as
```suggestion
          val inTailPosition =
            if fromSym.is(Label) then tailPositionLabeledSyms.contains(fromSym)) // Label returns are only tail if the label is in tail position
            else fromSym eq method // Method returns are only tail if we are looking at the original method
```

File: compiler/src/dotty/tools/dotc/transform/TailRec.scala [hunk 2]
```diff
@@ -429,10 +429,23 @@ class TailRec extends MiniPhase {
...
+        case tree: DefDef =>
+          if (isMandatory)
+            if (tree.symbol.is(Synthetic))
+              noTailTransform(tree.rhs)
+            else
+              // We cant tail recurse through nested definitions, so dont want to propagate to child nodes
+              // We dont want to fail if there is a call that would recurse (as this would be a non self recurse), so dont
+              // want to call noTailTransform
+              // We can however warn in this case, as its likely in this situation that someone would expect a tail
+              // recursion optimization and enabling this to optimise would be a simple case of inlining the inner method
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/TailRec.scala:445]: Typos:
cant -> can't
dont -> don't

File: compiler/src/dotty/tools/dotc/reporting/messages.scala [hunk 3]
```diff
@@ -1907,6 +1907,20 @@ class TailrecNotApplicable(symbol: Symbol)(using Context)
...
+  extends SyntaxMsg(TailrecNestedCallID) {
+  def msg(using Context) = {
+    s"The tail recursive def ${definition.name} contains a recursive call inside the non-inlined inner def ${innerDef.name}"
+  }
+
+  def explain(using Context) =
+    """Tail recursion is only validated and optimised directly in the definition
+      |any calls to the recursive method via an inner def cannot be validated as
+      |tail recursive, nor optimised if they are. To enable tail recursion from
+      |inner calls, mark the inner def as inline
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/reporting/messages.scala:1920]: Some punctuation:
```suggestion
    """Tail recursion is only validated and optimised directly in the definition.
      |Any calls to the recursive method via an inner def cannot be validated as
      |tail recursive, nor optimised if they are. To enable tail recursion from
      |inner calls, mark the inner def as inline.
```

File: tests/warn/i20105.scala
Comment (sjrd) [inline tests/warn/i20105.scala:1]: This should also get a `.check` file to make sure we emit the correct warning.

**Review by sjrd — CHANGES_REQUESTED** [review]
Looks reasonable overall. Missing check files + some minor suggestions.

File: tests/neg/i5397.scala [hunk 4]
```diff
@@ -16,8 +16,10 @@ object Test {
         rec3 // error: not in tail position
     })
 
-  @tailrec def rec4: Unit = {
-    def local = rec4 // error: not in tail position
+  // This is technically not breaching tail recursion as rec4 does not call itself, local does
+  // This instead fails due to having no tail recursion at all
+  @tailrec def rec4: Unit = { // error: no recursive calls
+    def local = rec4
```
Comment (LucySMartin) [inline tests/neg/i5397.scala:22]: The more I think about this, the more counterintuitive it seems.
I'm fairly confident that we will get people complaining about cases like this, even if technically correct.

Do we need to consider having an option on the annotation to allow or deny indirect calls?
This could also allow handeling of non-calls such as:
```Scala
  def bar(f: Int => Long): Long =
    ???

  @tailrec
  def foo(i: Int): Long =
    if (???)
      bar(foo)
    else
      foo(i + 1)
```

Comment (sjrd) [reply tests/neg/i5397.scala:22]: It is of course possible to craft examples that will be confusing. We should focus on what the usual scenario is. The usual scenario is that I'm writing a tail-recursive method, and I want the compiler to make sure I did not mess it up.

Indirect calls are usually a case of "I messed it up". For example, using `Option.fold` instead of pattern-matching prevents tail-recursive call elimination:
```scala
def foo(x: Option[Foo]): Unit =
  x.fold {
    0
  } { someFoo =>
    foo(None) // oops, this is not tail-recursive!
  }
```
I don't think complicating `@tailrec` with options will help that usual scenario. It will only make it more difficult to teach what `@tailrec` does.

Comment (LucySMartin) [reply tests/neg/i5397.scala:22]: Ok, read the prior debates on this issue.
While I don't fully agree, its clear that this is the group intent, and very happy that we can now simply pick up this warning in CI tools.

**Comment by sjrd** [comment]
@LucySMartin What's the status of this PR? Do you need help getting the CI to pass?

**Comment by LucySMartin** [comment]
Sorry for leaving this abruptly - ill be back in the sane world on Monday
and can pick this up then.

**Comment by LucySMartin** [comment]
Please ignore the excess off way too many commits. Was fighting either git or the build as it kept putting /weird/ CR and LF tokens into things.
I know Ill need to squash it.

**Comment by sjrd** [comment]
On Windows I strongly suggest disabling the "autocrlf" config. I even recommend to that globally. git pretends to be "helpful" with that setting but I have never seen it useful and always harmful.

To disable it:
```bash
$ git config --global core.autocrlf false
```
taken from [the git book](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf)

**Comment by LucySMartin** [comment]
Yeah - I turned autocrlf off for the reattempt today (and have nuked it on other projects too - I agree from the docs its just bad).
They then generated via sbt with the wonderful line endings of CR-CR-LF.

I saw that comparable check files were just LF (please correct me if that's not right!) so stripped the files down to just LF by hand, and copied them across.

I'm honestly not sure what is wrong with them, and (sorry if this is a problem with my limited use of github) I cant see any way to view what files were actually generated via the CI tests, to validate what line endings its generated in the server side .out files.

**Comment by LucySMartin** [comment]
Im an idiot - I see the issue.

File: compiler/test/dotty/tools/vulpix/FileDiff.scala
Comment (LucySMartin) [inline compiler/test/dotty/tools/vulpix/FileDiff.scala:1]: Note to self: srop this when sqashing commits.

**Review by sjrd — COMMENTED** [review]
Looks good, thank you :)

I'll let you squash in order to have a single commit with a clean commit message. Other than that it will be good to go.

**Comment by sjrd** [comment]
Thanks. Is it intended that the commit is not linked to your GitHub account? That's not a problem for us, but it means you won't get the statistics in your favor. :p

**Comment by LucySMartin** [comment]
Note in addition to the squash I removed the hex-logging of the comparison.
I might try and make that error message slightly more user friendly at some point, but that's a super low priority.

**Review by sjrd — APPROVED** [review]

**Comment by LucySMartin** [comment]
Anything I need to do to merge this at this point?
I have another little fix that is going to conflict with this one, would be good to get it in while I still have some downtime.

**Comment by som-snytt** [comment]
In case sjrd's comment was overlooked, the commit author is
```
Author: Lucy Martin <lucy.martin@nttdata.com>
```
I had that issue once, but I don't remember how I managed my .gitconfig, maybe with a project-specific one?

**Comment by LucySMartin** [comment]
Oh oops. 
While I don't have any real attachment to my github stats (heck this is a brand new account) I really should be being a lot more careful with that.
Thanks for the call out.
