### PR TITLE
Test chars safely when highlighting

### LINKED ISSUE #22906: Incorrect code causes the parser to crash when trying to rewrite
## Compiler version

Scala 3.6.4/3.7.0-RC1

## Minimized code

```Scala
//> using options -rewrite -indent

def program: Int => Int =
    {`1`: Int  =>  5}
```

## Output (click arrow to expand)

<details>

```scala
[error] java.lang.ArrayIndexOutOfBoundsException: Index -3 out of bounds for length 22
[error] dotty.tools.dotc.parsing.Parsers$Parser.testChar(Parsers.scala:740)
[error] dotty.tools.dotc.parsing.Parsers$Parser.testChars(Parsers.scala:745)
[error] dotty.tools.dotc.parsing.Parsers$Parser.bracesToIndented(Parsers.scala:863)
[error] dotty.tools.dotc.parsing.Parsers$Parser.inBracesOrIndented(Parsers.scala:648)
[error] dotty.tools.dotc.parsing.Parsers$Parser.inDefScopeBraces(Parsers.scala:652)
......
```
</details>

### PR DESCRIPTION
**Pull request by som-snytt**
The arrow test at lastOffset - 3 is out-of-range when highlighting, which parses a snippet of source.

Fixes #22906 

Reproduces under scala-cli `-rewrite -indent` but not under vulpix. (It would be nice to know why.) (Needless to add, it shouldn't be a research project to get the test rig to just run a compilation. There is programmatic flag-setting that defies expectations.)

This commit also allows a test to `using scala` by ignoring it, as a convenience. When the directive parsing is completely aligned with scala-cli, it should completely ignore what is not supported, so that test files can be used both ways.

### CODE REVIEW

**Comment by som-snytt** [comment]
It would be nice if the nuisance message did not make its way into the check file. The test rig could de-duplicate. Again, the goal is that I don't have to change my scala-cli reproduction just to use it as a test.
```
Output from 'tests/neg/i22906.scala' did not match check file. Actual output:
Flag -indent set repeatedly
-- Error: tests/neg/i22906.scala:5:15 ----------------------------------------------------------------------------------
```

File: tests/neg/i22906.scala [hunk 1]
```diff
@@ -0,0 +1,5 @@
+//> using scala 3.7.0-RC1
+//> using options -rewrite -indent
```
Comment (som-snytt) [inline tests/neg/i22906.scala:2]: This is nominally a no-op without `-source 3.0-migration` but would throw; it requires the other options to demonstrate the behavior.

Comment (som-snytt) [reply tests/neg/i22906.scala:1]: updated to document my comment that vulpix doesn't demonstrate the error.

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 2]
```diff
@@ -744,6 +744,9 @@ object Parsers {
       str.isEmpty ||
       testChar(from, str.head) && testChars(from + 1, str.tail)
 
+    def testCharsSafe(from: Int, str: String): Boolean =
+      from >= 0 && testChars(from, str)
```
[the remark this answers is not in the document]
Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala:748]: I don't mind. `testChar` has an upperbound check already. I think this case is "really just a bug" and it shouldn't be calculating a negative index; I can't guess at the performance diff, but "it must be small"?

**Comment by som-snytt** [comment]
Squashed. Some tests such as `skipBlanks` could be written as `indexWhere` or `lastIndexWhere` (going backward). (Not done here.)

**Review by noti0na1 — APPROVED** [review]
