### PR TITLE
Constructor proxy is restricted if class is protected

### LINKED ISSUE #22560: Objects leak protected inner classes
## Compiler version

3.6.3

## Minimized code

```Scala
class A:
  protected class B

// This fails to compile, as expected
// val x = A().B()

object C:
  protected val p = "protected"
  protected def getString() = "Hello!"
  protected class D

// This fails to compile
// val y = C.p

// And this also fails to compile
// val z = C.getString()

// However, this compiles just fine.
val alpha = C.D()
```

## Output

The code compiles, even though a protected inner class is being accessed outside of the declaring object.

## Expectation

I know that there isn't any point in declaring members of objects `protected`, since an object can't be extended. However, the way that protected inner classes are handled (which, as far as I can tell, is to ignore the `protected` keyword) is inconsistent with the way that protected vars/vals/defs are treated inside objects.

### PR DESCRIPTION
**Pull request by som-snytt**
Calling a constructor proxy should be at least as restricted as using `new`.

Add `Protected` to a constructor companion if the class is protected.

If the companion exists but is not protected, then make the constructor proxy protected.

Explicit `new` already errored for access.

Fixes #22560

### CODE REVIEW

**Comment by som-snytt** [comment]
Silly how-I-fixed-it parody:

How I fixed it: I searched github for something similar Prof Odersky had fixed, and I tried to copy that. I saw some bit flags, and since I miss coding in C, I thought I'd try that. It didn't work but threw an exception. It's way past midnight because I had an extra coffee this afternoon. I've already done the word puzzles for tomorrow. I said I better use the class symbol to check if it's protected, so I did that and the test passed, so that's when I stopped. The test is just the OP, plus a line to show something else that doesn't work and something else that does.

**Comment by som-snytt** [comment]
Refresher that qualified protected does not mean access is granted to subclasses of the privateWIthin boundary symbol.

The expectation is that this works:
```
class Enumeration:
  protected class Val(i: Int):
    def this() = this(42)
  object Val:
    protected[Enumeration] def apply(i: Int) = new Val(i)

class Test extends Enumeration:
  val Hearts = Val(27)
  val Diamonds = Val()
```
Scala 2 has the same behavior.

An alternative is to require the companion to have the same access modifiers (that is, also be protected for this use case).

**Comment by som-snytt** [comment]
The :x: is an unrelated server failure.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -4173,9 +4173,9 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
           readapt(tree.appliedToNone) // insert () to primary constructors
         else
           errorTree(tree, em"Missing arguments for $methodStr")
-      case _ => tryInsertApplyOrImplicit(tree, pt, locked) {
-        errorTree(tree, MethodDoesNotTakeParameters(tree))
-      }
+      case _ =>
+        tryInsertApplyOrImplicit(tree, pt, locked):
+          errorTree(tree, MethodDoesNotTakeParameters(tree))
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:4178]: This delta was due to a println. Philosophically, `tryInsert` is the important part, and putting it right of the arrow makes it less visible, and unduly highlights `errorTree`. The edit with new syntax is clearer.

Usual idiom where "thing to the right" is less important for understanding because it doesn't carry much information:
```
def f(x: X) = x match
  case _: Y =>
```
