### PR TITLE
Copy `@use` and `@consume` annotations to parameter types

### LINKED ISSUE #23302: `@use` parameter gets ignored in value classes
## Compiler version

`main`

## Minimized code

```scala
import language.experimental.captureChecking
import caps.*

final class Runner(val dummy: Int) extends AnyVal {
  def runOps(@use ops: List[() => Unit]): Unit = ops.foreach(op => op())  // error
}

final class Runner1 {
  def runOps(@use ops: List[() => Unit]): Unit = ops.foreach(op => op())  // ok
}
```

## Output

```scala
-- Error: issues/cc-reach-ext.scala:5:61 ---------------------------------------
5 |  def runOps(@use ops: List[() => Unit]): Unit = ops.foreach(op => op())  // error
  |                                                             ^^^^^^^^^^
  |Local reach capability ops* leaks into capture scope of method runOps$extension.
  |To allow this, the parameter ops should be declared with a @use annotation
```

## Expectation

Both `runOps` methods should compile. Note that the only differences between them are whether they are a value class (whether it `extends AnyVal`).

### PR DESCRIPTION
**Pull request by Linyxus**
... so that they will persist after tree copying. 

fixes #23302.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/cc/CaptureOps.scala [hunk 1]
```diff
@@ -490,18 +493,24 @@ extension (sym: Symbol)
...
+    || sym.info.hasAnnotation(defn.UseAnnot)
     || sym.is(TypeParam)
         && sym.owner.rawParamss.nestedExists: param =>
             param.is(TermParam) && param.hasAnnotation(defn.UseAnnot)
             && param.info.deepCaptureSet.elems.exists:
                 case c: TypeRef => c.symbol == sym
                 case _ => false
 
+  /** `sym` or its info is annotated with `@consume`. */
+  def isConsumeParam(using Context): Boolean =
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/cc/CaptureOps.scala:510]: Do we need the `sym.hasAnnotation(...)` part? If not it's better to remove that clause.

File: compiler/src/dotty/tools/dotc/cc/CaptureOps.scala [hunk 2]
```diff
@@ -490,18 +493,24 @@ extension (sym: Symbol)
   def hasTrackedParts(using Context): Boolean =
     !CaptureSet.ofTypeDeeply(sym.info).isAlwaysEmpty
 
-  /** `sym` is annotated @use or it is a type parameter with a matching
+  /** `sym` itself or its info is annotated @use or it is a type parameter with a matching
    *  @use-annotated term parameter that contains `sym` in its deep capture set.
    */
   def isUseParam(using Context): Boolean =
     sym.hasAnnotation(defn.UseAnnot)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/cc/CaptureOps.scala:500]: Do we still need the `sym.hasAnnotation(...)` part? If not it's better to remove that clause.

File: compiler/src/dotty/tools/dotc/cc/CaptureOps.scala (hunk 1 above)
Comment (Linyxus) [reply compiler/src/dotty/tools/dotc/cc/CaptureOps.scala:510]: I tried to drop the check but the tests failed. I think we still need it because there are cases when we check whether a symbol is declared `@use` (or `@consume`) that comes directly from the original method, whose info is not adapted by the new logic.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/cc/CaptureOps.scala:510]: OK, let's leave it in then.
