### PR TITLE
Regression test for extension nullification, nowarn for different opacities

### LINKED ISSUE #21190: Extensions declared next to opaque types warn that they won't be used even though when used externally they will be used
## Compiler version

3.5.0-RC3 or 3.6 nightly

## Minimized code

```Scala
//> using scala 3.nightly
//> using mainClass reproduction.opaqueoverwarning.Main

package reproduction.opaqueoverwarning

opaque type FromEnd = Int
object FromEnd:
  inline def apply(i: Int): FromEnd = i
  extension (fe: FromEnd)
    inline def value: Int = fe

// Warning appears when extension is in same namespace as opaque type
// under 3.5.0-RC3 (and 3.6.0 nightly)
extension [A](a: Array[A])
  inline def apply(fe: FromEnd): A =
    a(a.length - 1 - FromEnd.value(fe))
    
object Main:
  def run(): Unit =
    val xs = Array(1, 2, 3)

    println(s"First element = ${xs(0)}")
    println(s"Last element = ${xs(FromEnd(0))}")

  def main(args: Array[String]): Unit =
    run()
```

## Output

```scala
[warn] ./Reproduction.scala:15:14
[warn] Extension method apply will never be selected
[warn] because Array already has a member with the same name and compatible parameter types.
[warn]   inline def apply(fe: FromEnd): A =
[warn]              ^
First element = 1
Last element = 3
```

## Expectation

```scala
First element = 1
Last element = 3
```

because, obviously, the extension method apply _was_ selected, so it certainly isn't the case that it will "never be selected".

If we want to retain the warning in case someone wants to try to use the extension within the same file, _at least_ it should go away when the full path is used (e.g. `reproduction.opaqueoverwarning.FromEnd`) as a signal that you are taking the external rather than the privileged view of the opaque type.

(Note that there are a number of cases where the full path has to be used already in order to get the desired behavior--in inline matches, for example.)

The warning doesn't happen if the opaque type and extension method are inside an object (see e.g. https://scastie.scala-lang.org/SHWSAqOPSVGV7gdA80WJTA and contrast to https://scastie.scala-lang.org/fes52gRsSmiFpSlHP7r7QA).

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #21190 

~Adjust~ test that params must not be of different opacity ~opaque~.

~Other aliases are permitted, but could check if they are effectively final. String alias can't be overridden.~

The tweak was https://github.com/scala/scala3/pull/22268 and the ticket was a duplicate. In the meantime, it also doesn't warn for any override, so the previous concern about aliases doesn't apply.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/RefChecks.scala [hunk 1]
```diff
@@ -1148,6 +1148,9 @@ object RefChecks {
         def strippedResultType = Applications.stripImplicit(tp.stripPoly, wildcardOnly = true).resultType
         def firstExplicitParamTypes = Applications.stripImplicit(tp.stripPoly, wildcardOnly = true).firstParamTypes
         def hasImplicitParams = tp.stripPoly match { case mt: MethodType => mt.isImplicitMethod case _ => false }
+        def isAnyAlias =
+          val denot = tp.typeSymbol.denot
+          denot.isAliasType || denot.isOpaqueAlias
```
Comment (Ichoran) [inline compiler/src/dotty/tools/dotc/typer/RefChecks.scala:1153]: I'm not sure this is right.  `type Foo = Int` is an alias type, isn't it?

But if you omit the `opaque`, the warning is correct: you _can't_ ever call the extension method as an extension method.

I guess it's okay to not warn when there should be a warning, but the tricky part here is that opaque types look different depending on context.

Since I don't understand how much work is being done here and how much is being done by the later `.isOpaqueAlias` bit, I'm not sure this under-warns, but it seems like it might.

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/typer/RefChecks.scala:1153]: Where the "receiver" is an alias, https://github.com/scala/scala3/blob/main/tests/warn/i16743.scala#L56

The current diff is at L1165 where the params are checked; the `frozen_<:<` is not sufficient.

For non-opaque aliases, I think the screws could be tightened where there can be no override (of the alias member).

The goal is indeed to prefer underwarn to overwarn.

File: tests/warn/i21190.scala [hunk 2]
```diff
@@ -0,0 +1,23 @@
+
+//> using options -Werror
```
Comment (KacperFKorban) [inline tests/warn/i21190.scala:2]: `-Werror` isn't needed here, `warn` tests will fail if an error is reported in an unspecified location.

Comment (som-snytt) [reply tests/warn/i21190.scala:2]: It's a way to say "expect no warnings" without scanning the source visually or grepping.

Comment (KacperFKorban) [reply tests/warn/i21190.scala:2]: Ok, that sounds like a good practice actually. :sweat_smile:

**Review by KacperFKorban — APPROVED** [review]
