### PR TITLE
Mention extension in unused param warning

### LINKED ISSUE #23125: False positive unused given  in extensions
## Compiler version

3.7.0
3.7.1-RC1

Fixed in 3.7.2-RC1-NIGHTLY 

Bisect points it was fixed in 32defdf95710f358ef6041cb62401844f777cb05

## Minimized code

```Scala
//> using options -Wunused:all 

trait MonadThrow[F[_]]
extension [T](value: T) def liftTo[F[_]](using MonadThrow[F]): F[T] = ???

trait Api[F[_]]:
  def setMaxAge(value: Int): F[Unit]
  def truncate(): F[Unit]

trait MetaStreamsSyntax:
  extension [F[_]](ms: Api[F])(using MonadThrow[F]) // warns: 
    def withMaxAge(): F[Unit] = 
      val lifted = 0.liftTo[F] // uses MonadThrow
      assert(lifted != null) // to enusre this val is used
      assert(ms != null) // to ensure ms is used
      ???
      
    def truncated(): F[Unit] = 
      ms.truncate() // required to trigger warning, does not warn if ms is not used
```

## Output

```scala
[warn] ./example.scala:11:38
[warn] unused implicit parameter
[warn]   extension [F[_]](ms: Api[F])(using MonadThrow[F])
[warn]            
```

## Expectation
Should not warn.  Bisected fix should be backported to 3.7.1-RC2 and regression test should be added

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #23125 

Make the message more verbose by stating the extension method name.

This could be improved by only adding words if the param pos is on a different line from the method pos.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/CheckUnused.scala [hunk 1]
```diff
@@ -500,6 +500,8 @@ object CheckUnused:
     val warnings = ArrayBuilder.make[MessageInfo]
     def warnAt(pos: SrcPos)(msg: UnusedSymbol, origin: String = ""): Unit = warnings.addOne((msg, pos, origin))
     val infos = refInfos
+    //println(infos.defs.mkString("DEFS\n", "\n", "\n---"))
+    //println(infos.refs.mkString("REFS\n", "\n", "\n---"))
```
Comment (tgodzik) [inline compiler/src/dotty/tools/dotc/transform/CheckUnused.scala:504]:
```suggestion
```

**Review by tgodzik — APPROVED** [review]
LGTM with the minor nitpick

File: compiler/src/dotty/tools/dotc/transform/CheckUnused.scala (hunk 1 above)
Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/transform/CheckUnused.scala:504]: I could use the local convention
```
// checkConsistent() // DEBUG
```
which appears to have a special code
```
// println(owner.info.decls.toList.map(_.debugString).mkString("\n  ")) // !!! DEBUG
```
or add `config.Printers.lint` but frankly I never edit that config to enable printing. If I want to enable some `typr.println` I just remove `typr`. The many layers of just getting debug output from a test means I don't get debug output.

Comment (tgodzik) [reply compiler/src/dotty/tools/dotc/transform/CheckUnused.scala:504]: if that's on purpose then it's fine, thanks for explaning!

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/transform/CheckUnused.scala:504]: Thanks, normally I have been deleting it, but I've written it a few times now. Uncommented would definitely be accidental; I should add the DEBUG for easy grepping. Or maybe just add the debug printer for lint. I will try that when fully caffeinated.

File: tests/warn/i15503g.scala [hunk 2]
```diff
@@ -15,10 +15,17 @@ object Foo {
...
     def causesIssue: Unit = println("oh no")
     def isAnIssue(y: A): Boolean = x == x // warn
   }
+
+object i23125:
+  trait Show:
+    def show(s: String) = s
+  extension (s: String)(using Show) // warn not used in repeat
+    def echo = println(summon[Show].show(s))
+    def repeat = s * 2
```
Comment (som-snytt) [inline tests/warn/i15503g.scala:31]: it's OK if the warning is repeated for a second method. Alternatively, collect warnings by "site" and/or "origin" for helpful grouping. Maybe a future enhancement.
