### PR TITLE
Bring back ambiguity filter when we report an implicit not found error

### LINKED ISSUE #20344: Regression in `armanbilge/schrodinger` for implicit search
Based on OpenCB failure in `armanbilge/schrodinger` - [builds logs](https://github.com/VirtusLab/community-build3/actions/runs/8945914916/job/24577440577)

## Compiler version
Last good release: 3.5.0-RC1-bin-20240429-e2c456f-NIGHTLY
First bad release: 3.5.0-RC1-bin-20240501-e6bc130-NIGHTLY
Bisect points to 0890e7ae50f72592928e350c450ca949ff1a3873

## Minimized code

```Scala
trait Monad[F[_]] extends Invariant[F]

trait Invariant[F[_]]
object Invariant:
  implicit def catsInstancesForList: Monad[List] = ???
  implicit def catsInstancesForVector: Monad[Vector] = ???
  
trait Shrink[T]
object Shrink extends ShrinkLowPriorityImplicits:
  trait Buildable[T,C] 
  implicit def shrinkContainer[C[_],T](implicit v: C[T] => Traversable[T], s: Shrink[T], b: Buildable[T,C[T]]): Shrink[C[T]] = ???
trait ShrinkLowPriorityImplicits:
  implicit def shrinkAny[T]: Shrink[T] = ???
  
trait Distribution[F[_], -P, X] extends (P => F[X])
type GenBeta[A, B, X] = [F[_]] =>> Distribution[F, Beta.Params[A, B], X]
type Beta[R] = [F[_]] =>> GenBeta[R, R, R][F]

object Beta:
  trait Params[+A, +B]
trait BetaInstances:
  given schrodingerRandomBetaForDouble[F[_]: Monad]: Beta[Double][F] = ???

object all extends BetaInstances

@main def Test = 
  import all.given
  summon[Shrink[Beta.Params[Double, Double]]]
```

## Output

```scala
[error] No best given instance of type Shrink[Beta.Params[Double, Double]] was found for parameter x of method summon in object Predef.
[error] I found:
[error] 
[error]     Shrink.shrinkContainer[[B] =>> Beta.Params[Double, B], Double](
[error]       all.schrodingerRandomBetaForDouble[F](
[error]         /* ambiguous: both method catsInstancesForList in object Invariant and method catsInstancesForVector in object Invariant match type Monad[F] */
[error]           summon[Monad[F]]
[error]       ),
[error]     Shrink.shrinkAny[Double],
[error]       /* missing */summon[Shrink.Buildable[Double, Beta.Params[Double, Double]]])
[error] 
[error] But both method catsInstancesForList in object Invariant and method catsInstancesForVector in object Invariant match type Monad[F].
[error]   summon[Shrink[Beta.Params[Double, Double]]]
[error]                                              ^
Error compiling project (Scala 3.5.0-RC1-bin-20240502-05354ba-NIGHTLY, JVM (17))
```

## Expectation
Should compile

### PR DESCRIPTION
**Pull request by odersky**
This reverts one part of #20261. When we fail with both an ambiguity on one implicit argument and another error on another argument we prefer the other error. I added a comment why this is needed.

Fixes #20344

### CODE REVIEW

**Comment by odersky** [comment]
I added to a 3.5.0-RC2 milestone since this fixes a regression

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -4113,7 +4113,14 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
           * `SearchFailureType`.
           */
         def issueErrors(fun: Tree, args: List[Tree]): Tree =
-          def firstFailure = args.tpes.find(_.isInstanceOf[SearchFailureType]).getOrElse(NoType)
+          // Prefer other errors over ambiguities. If nested in outer searches a missing
+          // implicit can be healed by simply dropping this alternative and tryng something
```
Comment (mbovel) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:4117]:
```suggestion
          // implicit can be healed by simply dropping this alternative and trying something
```

**Review by mbovel — APPROVED** [review]
