### PR TITLE
fix: better error messages when an enum derives from AnyVal

### LINKED ISSUE #21944: Better error message when an enum extends AnyVal
## Compiler version

https://github.com/scala/scala3/commit/bed0e86180b8e1d83547e99a8ac28efe13cca6c6

## Minimized example

```scala
enum Orientation extends AnyVal:
    case North, South, East, West
```

## Output Error/Warning message

```scala
-- [E074] Syntax Error: t.scala:2:5 --------------------------------------------
2 |enum Orientation extends AnyVal:
  |     ^
  |     Value classes may not be abstract
-- [E093] Syntax Error: t.scala:3:29 -------------------------------------------
3 |    case North, South, East, West
  |                             ^
  |               anonymous class {...} cannot extend final class Orientation
  |-----------------------------------------------------------------------------
  | Explanation (enabled by `-explain`)
  |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  | A class marked with the final keyword cannot be extended
   -----------------------------------------------------------------------------
```

## Why this Error/Warning was not helpful

The message leaks implementation details about desugaring...

## Suggested improvement

A message saying that enums cannot extend `AnyVal` is better here

### PR DESCRIPTION
**Pull request by hamzaremmal**
Closes #21944

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/reporting/messages.scala [hunk 1]
```diff
@@ -3399,3 +3399,7 @@ class GivenSearchPriorityWarning(
        |$migrationHints"""
 
   def explain(using Context) = ""
+final class EnumMayNotBeValueClasses(sym: Symbol)(using Context) extends SyntaxMsg(EnumMayNotBeValueClassesID):
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/reporting/messages.scala:3402]: Blank line please :-p
```suggestion
  def explain(using Context) = ""

final class EnumMayNotBeValueClasses(sym: Symbol)(using Context) extends SyntaxMsg(EnumMayNotBeValueClassesID):
```

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 2]
```diff
@@ -734,11 +734,16 @@ object Checking {
       case _ =>
         report.error(ValueClassesMayNotContainInitalization(clazz), stat.srcPos)
     }
-    if (clazz.isDerivedValueClass) {
+    // We don't check synthesised enum anonymous classes that are generated from
+    // enum extending a value class type (AnyVal or an alias of it)
+    // The error message with ID 205 will take care of generating the error message (See #22235)
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala:739]: Write the message ID *name* instead of the numeric value? As a reader here I don't want to have to go look up what it is.

File: compiler/src/dotty/tools/dotc/typer/Namer.scala [hunk 3]
```diff
@@ -1626,7 +1626,8 @@ class Namer { typer: Typer =>
           }
           else {
             val pclazz = pt.typeSymbol
-            if pclazz.is(Final) then
+            // The second condition avoid generating a useless message (See #22235 for more details)
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/typer/Namer.scala:1629]:
```suggestion
            // The second condition avoids generating a useless message (See #22235 for more details)
```

**Review by sjrd — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/reporting/messages.scala (hunk 1 above)
Comment (hamzaremmal) [reply compiler/src/dotty/tools/dotc/reporting/messages.scala:3402]: Ah, it was a merge conflict with #22189 and the blank line was dropped when resolving the conflict 😅
