### PR TITLE
Fix completion mode filtering + optimize scopeCompletions

### LINKED ISSUE #23150: Presentation compiler still tries to complete package definition
## Compiler version
3.7.0

## Minimized code

```scala
package super.@@ // shows nn + runtimeChecked
```

## Output

```scala
nn
runtimeChecked
```

## Expectation

Nothing or package name inferred from directory structure

### PR DESCRIPTION
**Pull request by rochala**
I've changed scopeCompletions to lazy val to memoize because I beliveve we don't need to recompute it. The actual fix is at the comment. There is no need to create a new Completer just to filter all of remaining completions at later stage.

Fixes #23150

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/interactive/Completion.scala [hunk 1]
```diff
@@ -610,17 +602,15 @@ object Completion:
...
           val tpe = tp.widenExpr
           tpe.membersBasedOnFlags(required = ExtensionMethod, excluded = EmptyFlags)
             .collect { case DenotWithMatchingName(denot, name) => TermRef(tpe, denot.symbol) -> name }
-        }
 
       // There are four possible ways for an extension method to be applicable
 
       // 1. The extension method is visible under a simple name, by being defined or inherited or imported in a scope enclosing the reference.
-      val termCompleter = new Completer(Mode.Term, pos, untpdPath, matches)
-      val extMethodsInScope = termCompleter.scopeCompletions.names.toList.flatMap:
```
Comment (rochala) [inline compiler/src/dotty/tools/dotc/interactive/Completion.scala:623]: Actual fix, I was also thinking about adding
```scala
case d: SymDenotation if d.isTerm && d.termRef.symbol.is(Extension) && include(d, name)
``` 
but the issue was actually the whole creation of new completer

**Comment by rochala** [comment]
Actually, the only unrelated change here is the change of `{` into fewer braces. The rest was necessary to handle all the test cases.

**Review by tgodzik — APPROVED** [review]
LGTM
