### PR TITLE
Scaladoc: fixes and improvements to context bounds and extension methods

### LINKED ISSUE #21662: Scaladoc: fails to generate doc for ScAS
## Compiler version

3.5.1

## Minimized code

```
git clone https://github.com/rjolly/scas.git
cd scas
./mill -i -D dottyVersion=3.5.1 scas.docJar
```

## Output

```
Problem parsing projects\scas\scas\src\scas\base\BigInteger.scala:[0..13..2002], documentation may not be generated.
[...]
```

## Expectation

It would be good to at least uncomment `e.printStackTrace()` in dotty/scaladoc/src/dotty/tools/scaladoc/tasty/TastyParser.scala (and put it under a flag eventually), so as to know more about the problem.

### PR DESCRIPTION
**Pull request by Florian3k**
Closes #21662 

More specifically:
- Fixed issue with ambiguity of type params in right-associative extension methods (see `\:` and `\\:` in `extensionMethodSignatures.scala`, also see #22170)
- Fixed issue with context bounds in type parameters in extensions (`><` in `extensionMethodSignatures.scala`)

Additionally fixed and improved simplifying of type lambdas (`TypesSupport.scala`)

Removed `MemberInfo` and `unwrapMemberInfo`, which were quite complicated, doing several things at the same time and caused `parseMember` to have two sources of truth.

### CODE REVIEW

**Comment by rjolly** [comment]
The change works for me.

**Comment by rjolly** [comment]
@Florian3k , if you do not have more changes, maybe we could remove the draft status, what do you think? @mbovel please could you consider a review? Thanks!

**Comment by rjolly** [comment]
The new changes work for me.

**Comment by Florian3k** [comment]
Those new changes seem to be working fine.
It's a bit unfortunate that we have to render `Documentation.this.T` instead of `T` (this effect will be also visible in some places in std lib docs), but I understand that correctness beats prettiness.
I think improving that should be tracked in separate issue.

File: scaladoc-testcases/src/tests/classSignatureTestSource.scala [hunk 1]
```diff
@@ -26,7 +26,7 @@ abstract class Documentation[T, A <: Int, B >: String, -X, +Y](c1: String, val c
 
     sealed trait CaseImplementThis(id: Int)
 
-    case class IAmACaseClass(x: Documentation.this.T, id: Int) extends CaseImplementThis/*<-*/(id)/*->*/
+    case class IAmACaseClass(x: T, id: Int) extends CaseImplementThis(id) //expected: case class IAmACaseClass(x: Documentation.this.T, id: Int) extends CaseImplementThis
```
Comment (Florian3k) [inline scaladoc-testcases/src/tests/classSignatureTestSource.scala:29]: I've adjusted this test case to better reflect what is really going on here.

File: scaladoc/src/dotty/tools/scaladoc/tasty/TypesSupport.scala [hunk 2]
```diff
@@ -353,18 +364,23 @@ trait TypesSupport:
...
+
+    val classOwner = findClassOwner(originalOwner)
 
     tr match
       case NoPrefix() => true
-      case ThisType(tp) if owners(tp.typeSymbol) => true
-      case tp if owners(tp.typeSymbol) => true
+      case ThisType(tp) if tp.typeSymbol == classOwner || tp.typeSymbol == elideThis.symbol => true
+      case ThisType(_) if skipThisTypePrefix => true
+      // case ThisType(_) if elideThis.symbol == classOwner =>
```
Comment (tgodzik) [inline scaladoc/src/dotty/tools/scaladoc/tasty/TypesSupport.scala]: Total FYI maybe worth removing, but I guess it can also stay for debugging purposes
