### PR TITLE
Fix trailing comma Ident's span

### LINKED ISSUE #16872: Span includes trailing coma
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
  for {
    a <- List(1)
    b <- List(a)
    if (
      a,
      b,
    ) == (1, 2)
 } yield b
```

## Output

second `b`'s span will include the trailing coma. This shows up both when using Interactive as well in semanticdb

## Expectation

Trailing coma is excluded from span

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #16872

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/parsing/Scanners.scala [hunk 1]
```diff
@@ -736,7 +736,10 @@ object Scanners {
                  && currentRegion.commasExpected
                  && (token == RPAREN || token == RBRACKET || token == RBRACE || token == OUTDENT)
               then
-                () /* skip the trailing comma */
+                // encountered a trailing comma
+                // reset only the lastOffset
+                // so that the Ident's span is correct
```
Comment (jan-pieter) [inline compiler/src/dotty/tools/dotc/parsing/Scanners.scala:741]: I don't think this is specific to `Ident`s so maybe just say `so that the span is correct`

**Comment by rochala** [comment]
I'm also adding a comment from the spree session:
image
It actually is working in metals, so the bug is in IntelliJ idea debugger implementation

**Review by odersky — APPROVED** [review]
