### PR TITLE
Fix error message on setter with wrong type

### LINKED ISSUE #20338: Wrong error message when using setter extension method with wrong type
## Compiler version

3.4.1

## Minimized example

```Scala
//> using scala 3.4.1

object types:
  opaque type Struct = Int
  val test: Struct = 25
  extension (s: Struct) 
    def field: Int = s
    def field_=(other: Int) = ()

@main def hello = 
  import types.*
  test.field = "hello"
```

## Output Error/Warning message

```
[error] ./test.scala:12:3
[error] Reassignment to val field
[error]   test.field = "hello"
[error]   ^^^^^^^^^^^^^^^^^^^^
```

## Why this Error/Warning was not helpful

I expected there to be any information about type mismatch in the error message.

-explain doesn't help:

```
[error] Explanation
[error] ===========
[error] You can not assign a new value to field as values can't be changed.
[error] Keep in mind that every statement has a value, so you may e.g. use
[error]   val field = if (condition) 2 else 5
[error] In case you need a reassignable name, you can declare it as
[error] variable
[error]   var field = ...
[error]   test.field = "hello"
[error]   ^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by iusildra**
Fixes #20338
Poke @mbovel @nicolasstucki @hamzaremmal @AnotherMedo

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -1334,12 +1334,9 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
 
             val setter = toSetter(lhsCore)
             if setter.isEmpty then reassignmentToVal
```
Comment (mbovel) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:1336]: When can `setter` actually be empty? We haven't found any such cases.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:1336]: When the pattern match in `toSetter` gets to the default case. But I am not sure this is ever the case. On the other hand, programs with parse errors can give uncommon trees, so better be defensive.

**Review by odersky — APPROVED** [review]
