### PR TITLE
Quotes reflect: Allow to return DefDef from a val symbol tree

### LINKED ISSUE #22584: Quoted API has broken impl for `fields` (`case fields` / `declared fields` / ...)
## Compiler version

`3.6.3 `  
note, was not an issue before I bumped from `3.3.0`  
`edit`: I reverted to `3.3.0`, and apparently it was still an issue, actually

## Minimized code

```Scala
TypeRepr.of[A].typeSymbol.caseFields.map(_.tree)
TypeRepr.of[A].typeSymbol.declaredFields.map(_.tree)
```

## Output

```scala
[error]    |Exception occurred while executing macro expansion.
[error]    |scala.MatchError: DefDef(int,List(List()),TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Int)],EmptyTree) (of class dotty.tools.dotc.ast.Trees$DefDef)
```

## Expectation

1. Expect that compiler wont throw `MatchError`
2. In `3.3.0`, these were returning as `ValDef`

Code I was using:
```scala
typeSymbol: Symbol = typeRepr.typeSymbol
caseFieldSymbols: List[Symbol] = typeSymbol.caseFields

caseFieldSymbols.traverse { sym =>
            sym.tree match {
              case valDef: ValDef => valDef.asRight
              case _      => s"Somehow not a `ValDef`: ${sym.fullName}".asLeft
            }
```

### PR DESCRIPTION
**Pull request by jchyb**
Fixes #22584 
During the `Getters` phase, the compiler replaces class member vals with defs. Meanwhile `.tree` returns a tree most recently associated with a symbol (if currently compiled), or one read from tasty (if compiled before).  An interesting thing happens in the issue - since all of the files are tried being compiled in one compilation run, the file with a macro call is suspended, and then the macro and the MyClass class definition are compiled to the end (also including the `Getters` phase, where the tree stops being a ValDef). 

Initially I thought about manually replacing that returned DefDef with a ValDef in quotes reflection (like what happens when the tree is not available), but that would have been pointless - there would be little use of calling `.tree` on a symbol if we cannot read the rhs of the definition. Returning raw DefDef seems like a less bad choice, especially `.tree` is meant to be for power users anyway, and is full of other, more dangerous warts.

### CODE REVIEW

**Comment by jchyb** [comment]
@prolativ Since you already looked at the issue, I though you might have been interested. Feel free to not do a review or unassign yourself if you feel uncomfortable with that/ don't have time.

File: library/src/scala/quoted/Quotes.scala [hunk 1]
```diff
@@ -4060,9 +4060,10 @@ trait Quotes { self: runtime.QuoteUnpickler & runtime.QuoteMatching =>
          *
          *  If this symbol `isClassDef` it will return `a `ClassDef`,
```
Comment (prolativ) [inline library/src/scala/quoted/Quotes.scala:4061]:
```suggestion
         *  If this symbol `isClassDef` it will return a `ClassDef`,
```

File: library/src/scala/quoted/Quotes.scala [hunk 2]
```diff
@@ -4060,9 +4060,10 @@ trait Quotes { self: runtime.QuoteUnpickler & runtime.QuoteMatching =>
...
          *  if this symbol `isTypeDef` it will return `a `TypeDef`,
```
Comment (prolativ) [inline library/src/scala/quoted/Quotes.scala:4062]:
```suggestion
         *  if this symbol `isTypeDef` it will return a `TypeDef`,
```

File: library/src/scala/quoted/Quotes.scala [hunk 3]
```diff
@@ -4060,9 +4060,10 @@ trait Quotes { self: runtime.QuoteUnpickler & runtime.QuoteMatching =>
...
-         *  if this symbol `isValDef` it will return `a `ValDef`,
          *  if this symbol `isDefDef` it will return `a `DefDef`
```
Comment (prolativ) [inline library/src/scala/quoted/Quotes.scala:4063]:
```suggestion
         *  if this symbol `isDefDef` it will return a `DefDef`
```

File: library/src/scala/quoted/Quotes.scala [hunk 4]
```diff
@@ -4060,9 +4060,10 @@ trait Quotes { self: runtime.QuoteUnpickler & runtime.QuoteMatching =>
...
          *  if this symbol `isBind` it will return `a `Bind`,
```
Comment (prolativ) [inline library/src/scala/quoted/Quotes.scala:4064]:
```suggestion
         *  if this symbol `isBind` it will return a `Bind`,
```

File: library/src/scala/quoted/Quotes.scala [hunk 5]
```diff
@@ -4060,9 +4060,10 @@ trait Quotes { self: runtime.QuoteUnpickler & runtime.QuoteMatching =>
...
+         *  if this symbol `isValDef` it will return `a `ValDef`,
```
Comment (prolativ) [inline library/src/scala/quoted/Quotes.scala:4065]:
```suggestion
         *  if this symbol `isValDef` it will return a `ValDef`,
```

**Review by prolativ — COMMENTED** [review]
Would one now get different results for `.tree` with and without `-Yretain-trees` (with the difference other than some tree vs no/empty tree)?

BTW as this area of code is changed we could fix the doc string, which doesn't render well in scala-doc currently

File: library/src/scala/quoted/Quotes.scala (hunk 1 above)
Comment (jchyb) [reply library/src/scala/quoted/Quotes.scala:4061]: Ah, good catch!

**Comment by jchyb** [comment]
Yes, they would be different:
* no `-Yretain-trees` - we get a `ValDef` without a rhs (manually constructed in the .tree implementation).
* we have `-Yretain-trees`, and we compile the macro call together with the macro method and the type (macro call gets suspended, after which everything else finishes compilation before calling macro) - we get a `DefDef`, potentially with a rhs.
* we have `-Yretain-trees`, we already have macro implementation compiled, we compile macro call along with the inspected symbols - we get a `ValDef`, potentially with a rhs
*  we have `-Yretain-trees`, we already have macro implementation compiled and the symbol definition compiled, we compile the macro call along with the inspected symbols - we get a `ValDef`, potentially with a rhs (read from tasty)

This means that the .tree can even return different things in different incremental compilation runs of the same code.

**Comment by jchyb** [comment]
Ideally we would be able to turn back time and always be able to see what the tree looked like in Pickler and use that, but in general even then there would be inconsistencies like these when `transparent inline` were used since we cannot look into the future in that case, and the inspected symbol may or may not have already been compiled.
I am not a fan of .tree, I admit.

**Comment by Kalin-Rudnicki** [comment]
I had to remove `-Yretain-trees` for the time being in order to make progress. Is this what is causing annotations on my fields to disappear? Or a separate issue entirely?

`source code:`
```scala
  @oxygen.meta.annotation.showDerivation
  final case class CaseClass1(
      @ExampleTypeClasses.fieldName("my-int") int: Int,
      @ExampleTypeClasses.misc string: String,
      boolean: Boolean,
  )
```

`rendered tree:`
```scala
@oxygen.meta.annotation.showDerivation final case class CaseClass1(int: scala.Int, string: scala.Predef.String, boolean: scala.Boolean) extends java.lang.Object with _root_.scala.Product with java.io.Serializable {
  override def hashCode(): scala.Int
  override def equals(x$0: scala.Any): scala.Boolean
  override def toString(): java.lang.String
  override def canEqual(that: scala.Any): scala.Boolean
  override def productArity: scala.Int
  override def productPrefix: scala.Predef.String
  override def productElement(n: scala.Int): scala.Any
}
```

**Comment by soronpo** [comment]
> Would one now get different results for `.tree` with and without `-Yretain-trees` (with the difference other than some tree vs no/empty tree)?
> 

This is expected and explicitly documented for the `tree` method.

**Comment by Kalin-Rudnicki** [comment]
seems annotations are only available on the constructor symbols, not the case fields or declared fields, interesting

**Comment by Kalin-Rudnicki** [comment]
Is this going to be merged please?
Im still getting this error when I pulled into a project that has -Yretain-trees enabled

**Comment by Kalin-Rudnicki** [comment]
Hello, what is the status of this issue?

As I mentioned in the previous comments, I had to disable `-Yretain-trees` in order to get my project to compile. I now am trying to pull my macro library into another project which requires `-Yretain-trees`. Im really hoping to get some information on the timeline for this fix, because this issue is now a complete blocker.

**Comment by Kalin-Rudnicki** [comment]
❤️  thank you for getting on this!! any idea what compiler version this will go out in?

**Comment by jchyb** [comment]
@Kalin-Rudnicki sorry for sitting on this PR for all this time. It will most likely be included in 3.8.0
