### PR TITLE
Fix deterministically adding additional interfaces

### LINKED ISSUE #20496: 'implements' list order not deterministic
## Compiler version

3.3.3

## Minimized code

(not minimized yet)

On version 1.1.0-M1 of [Pekko](https://github.com/apache/pekko), the order of the imports on `org.apache.pekko/cluster.sharding.PersistentShardCoordinator` was not deterministic: it ended with `Timers, Actor` in one build but with `Actor, Timers` on another.

The definition of this class is:

```Scala
class PersistentShardCoordinator(
    override val typeName: String,
    settings: ClusterShardingSettings,
    allocationStrategy: ShardCoordinator.ShardAllocationStrategy)
    extends ShardCoordinator(settings, allocationStrategy)
    with PersistentActor
```

where:

```
class ShardCoordinator extends Actor with Timers
trait PersistentActor extends Eventsourced with PersistenceIdentity
trait Eventsourced extends Snapshotter with PersistenceStash with PersistenceIdentity with PersistenceRecovery
trait Snapshotter extends Actor
trait PersistenceRecovery
trait PersistenceIdentity
trait PersistenceStash extends Stash with StashFactory
trait Stash extends UnrestrictedStash with RequiresMessageQueue[DequeBasedMessageQueueSemantics]
trait UnrestrictedStash extends Actor with StashSupport
trait StashSupport
trait RequiresMessageQueue[T]
trait StashFactory { this: Actor =>
}
```

I tried to put together a reproducer at https://codeberg.org/raboof/scala3-reproduce-20496/src/branch/main/Test.scala but there `ShardCoordinator.class` doesn't have `Actor` and `Timer` on the `implements` list directly at all - I'm not sure how exactly that's triggered, happy to take suggestions :)

## Expectation

Compiling the same source on a clean system should produce the same bit-by-bit result each time.

### PR DESCRIPTION
**Pull request by raboof**
When a class contains calls to 'super' for traits it does not directly implement, these are added to the list of interfaces of the generated class. Previously, because these interfaces were determined using set logic, the ordering of that list was not deterministic.

This PR makes the order deterministic assuming the order in which these calls are registered using `registerSuperCall` in the `CollectSuperCalls` phase is deterministic within each class. This seems likely to me but it'd be great if someone could confirm.

Fixes #20496

### CODE REVIEW

File: compiler/src/dotty/tools/backend/jvm/GenBCode.scala [hunk 1]
```diff
@@ -23,10 +23,10 @@ class GenBCode extends Phase { self =>
 
   override def isRunnable(using Context) = super.isRunnable && !ctx.usedBestEffortTasty
 
-  private val superCallsMap = new MutableSymbolMap[Set[ClassSymbol]]
+  private val superCallsMap = new MutableSymbolMap[List[ClassSymbol]]
   def registerSuperCall(sym: Symbol, calls: ClassSymbol): Unit = {
-    val old = superCallsMap.getOrElse(sym, Set.empty)
-    superCallsMap.update(sym, old + calls)
+    val old = superCallsMap.getOrElse(sym, List.empty)
+    superCallsMap.update(sym, old :+ calls)
```
Comment (dwijnand) [inline compiler/src/dotty/tools/backend/jvm/GenBCode.scala:29]: What about duplicates?

Comment (raboof) [reply compiler/src/dotty/tools/backend/jvm/GenBCode.scala]: good point! I filtered those out in `BTypesFromSymbols.scala` which is the only place this map seems to be used, but taking care of them here already is neater. updated.

**Review by dwijnand — APPROVED** [review]
