### PR TITLE
Handle HKT bounds in Java generic signatures

### LINKED ISSUE #15903: MalformedParameterizedTypeException in getGenericReturnType for T[X,Y] <: Iterable[(X, Y)]
## Compiler version

3.1.3

## Minimized code
```Scala
trait NotWorking:
  def example[K, A, T[X,Y] <: Iterable[(X, Y)]](ab: String): T[K,A] = ???

trait Working:
  type M[X,Y] = Iterable[(X, Y)]
  def example[K, A, T[X,Y] <: M[X,Y]](ab: String): T[K,A] = ???

// Throws java.lang.reflect.MalformedParameterizedTypeException: Mismatch of count of formal and actual type arguments in constructor of scala.collection.Iterable: 1 formal argument(s) 2 actual argument(s)
classOf[NotWorking].getMethods().map(_.getGenericReturnType())

// Works
classOf[Working].getMethods().map(_.getGenericReturnType())
```

## Output

```scala
// No output or an exception thrown
```

## Expectation

I'd expect to be able to obtain generic return type in both cases. I'd not expect observable difference between the two cases.

In the wild - stumbled upon this while trying to make GraalVM native image from an app using zio-json, where JSONEncoder has similar type parameters in keyValueIterator method:

https://github.com/zio/zio-json/blob/abb49d70ab307e983a9da479969f0256f0be0d30/zio-json/shared/src/main/scala/zio/json/JsonEncoder.scala#L431

Interestingly the exception is thrown when trying to get the return type of the trait's method, but not when accessing the completed JSONEncoder object's method.

Tested with OpenJDK 17 and OpenJDK 11.

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #15903

## How much have you relied on LLM-based tools in this contribution?

zero much

## How was the solution tested?

issue tests (+ 1 case inverting the arg order)

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 1]
```diff
@@ -486,19 +486,40 @@ object GenericSignatures {
...
-    def unapply(tp: Type)(using Context): Option[(Symbol, Type, List[Type])] = tp match {
+    // In the special case where we see a type parameter applied to type parameters,
+    // such as `K[X, Y]` given `[X, Y, K <: Iterable[(X, Y)]]`, we must find its bound
+    // and instantiate it, otherwise in our example we end up with `Iterable[X, Y]` which is nonsensical.
+    private def resolveAppliedType(a: AppliedType)(using Context): Option[Type] =
+      a.tycon match
+        case TypeParamRef(binder, paramNum) =>
+          binder.paramInfos(paramNum).hi match
+            case hkt @ HKTypeLambda(_, _) =>
+              val instantiated = hkt.instantiate(a.args).dealias
```
Comment (tanishiking) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:497]: [note]
`.dealias` is required, otherwise `type M[X,Y]` appears in generic signature in the test below. :+1:

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 2]
```diff
@@ -486,19 +486,40 @@ object GenericSignatures {
...
+              // However, since Java doesn't have a way to refer to HKTs in generic signatures,
+              // we must trade precision for termination by only resolving one level,
+              // otherwise we end up in infinite loops, e.g., in `X[A] <: Thing[X[A]]` we keep resolving `X -> Thing[X[A]]`.
+              val hasNested = instantiated.existsPart:
```
Comment (tanishiking) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:501]: [note]
```scala
def f[A, X[T] <: Iterable[X[T]]]: X[A] = ???
```
this resolves to 
`X[A]` -> `Iterable[X[A]]` -> `Iterable[Iterable[X[A]]]` -> ...

We detect `X[A]` in the next level (`Iterable[X[A]]`) and if we found a same structure in 1-level resolved signature, stop resolving.

File: tests/run/i15903.check [hunk 3]
```diff
@@ -0,0 +1 @@
+scala.collection.Iterable<scala.Tuple2<K, A>>
```
Comment (tanishiking) [inline tests/run/i15903.check:1]: maybe we wanna move these tests into `tests/generic-java-signatures` instead of `tests/run`.

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala (hunk 2 above)
Comment (tanishiking) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:501]: **[important]**
Oh wait, but what if we have slightly different resolved type signature like:

```scala
trait RecursiveSig:
  def example[A, X[t] <: Iterable[X[List[t]]]](s: String): X[A] = ???
```

`X[A]` -> `Iterable[X[List[A]]` which doesn't captured by `hasNested`. It ends up infinite loop.

We should stop if we found `X[...]` with what ever type arguments.

**Review by tanishiking — CHANGES_REQUESTED** [review]
Overall approach looks good, but `hasNested` doesn't seem capture the case where expanded type's type arguments has different shape.

File: tests/run/i15903.check (hunk 3 above)
Comment (SolalPirelli) [reply tests/run/i15903.check:1]: what's the purpose of this generic-java-signatures folder exactly? we could move a lot of tests in there indeed

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala (hunk 2 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala]: thanks, that's indeed more correct and also simpler

File: tests/run/i15903d.check [hunk 4]
```diff
@@ -0,0 +1 @@
+scala.collection.Iterable<A>
```
Comment (lrytz) [inline tests/run/i15903d.check]: Is this right? If I expand `X[A]` once to its bound I get `Iterable[X[List[A]]`, which doesn't look like `Iterable[A]`. It's not something changed / introduced by this PR, but worth a ticket?

Comment (SolalPirelli) [reply tests/run/i15903d.check]: No, indeed, that's not right... what should we have instead? `Iterable` as a raw type?

Comment (lrytz) [reply tests/run/i15903d.check]: > part of the problem is I don't know what the spec of these things is

is still true 16 years later, I guess (https://github.com/scala/bug/issues/3249)...

A raw type is probably sound? Or a wildcard argument `scala.collection.Iterable<*>`?

Comment (SolalPirelli) [reply tests/run/i15903d.check]: I tried understanding what these things are supposed to be, but in another recent PR I ran into a `javac` assert on what I believed to be a valid signature, so I stopped trying. Let's go with a raw type here as long as tests pass.

File: tests/run/i15903.check (hunk 3 above)
Comment (tanishiking) [reply tests/run/i15903.check:1]: files under `tests/generic-java-signatures` runs in separate JUnit suite https://github.com/scala/scala3/blob/d23d5ef03fff090405a388a7ec93464b8ff8ef9e/compiler/test/dotty/tools/dotc/CompilationTests.scala#L181-L184

On the other hand, files under `tests/run` could be belong to multiple JUnit suite, like `run` (with 2 different options), `pickle`, and `recheck`. That means we could run test multiple times.

So, if the test is specific for checking java generic signatures, they would be nice to go to `tests/generic-java-signatures`. (While I also somtimes forget about that...). And yeah, maybe we wanna move bunch of tests in there in another PR.

File: tests/run/i15903d.check (hunk 4 above)
Comment (tanishiking) [reply tests/run/i15903d.check]: I agree with @lrytz, from `X[A] <: Iterable[X[List[A]]]`, the best approximation seems  `Iterable<?>. A raw `Iterable` is ok`, but it loses more generic information. If javac / signature accepts it (I'm wondering when `javac` assert for wildcard 🤔) ideally we should have `Iterable<?>` here.

but I think it's good to go with raw type, and open another issue to track this?

**Review by tanishiking — APPROVED** [review]
LGTM, thanks!
I think we wanna move tests to `tests/generic-java-signatures`, but that can be done in another PR with other test files all together.

File: tests/run/i15903.check (hunk 3 above)
Comment (SolalPirelli) [reply tests/run/i15903.check:1]: Not testing multiple times is nice... also I just realized it means we don't need to explicitly add `scalajs: --skip` and that's already a good enough reason for me :D

I'll grep `scalajs: --skip` and move the ones that belong to genericJavaSignatures in another PR 👍

File: tests/run/i15903d.check (hunk 4 above)
Comment (SolalPirelli) [reply tests/run/i15903d.check]: opened https://github.com/scala/scala3/issues/25887
