### PR TITLE
use `IndexOutOfBoundsException` constructor with `Int`

### LINKED ISSUE #23971: use `scala.runtime.Statics.ioobe`. forward port of Scala 2 #7086
## Compiler version

3.7.3

## Minimized code

`scalac -Xprint:genBCode A.scala`

```scala
case class A(x: Int)
```

## Output

```scala
    override def productElement(n: Int): Object =
      Int.box(
        matchResult2[Int]: 
          {
            case val x3: Int = n
            if 0 == x3 then return[matchResult2] this._1() else ()
            throw new IndexOutOfBoundsException(Int.box(n).toString())
          }
      )
    override def productElementName(n: Int): String =
      matchResult3[String]: 
        {
          case val x4: Int = n
          if 0 == x4 then return[matchResult3] "x" else ()
          throw new IndexOutOfBoundsException(Int.box(n).toString())
        }
```

javap result

```
  public java.lang.Object productElement(int);
    descriptor: (I)Ljava/lang/Object;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=3, locals=3, args_size=2
         0: iload_1
         1: istore_2
         2: iconst_0
         3: iload_2
         4: if_icmpne     14
         7: aload_0
         8: invokevirtual #90                 // Method _1:()I
        11: goto          29
        14: new           #92                 // class java/lang/IndexOutOfBoundsException
        17: dup
        18: iload_1
        19: invokestatic  #98                 // Method scala/runtime/BoxesRunTime.boxToInteger:(I)Ljava/lang/Integer;
        22: invokevirtual #102                // Method java/lang/Integer.toString:()Ljava/lang/String;
        25: invokespecial #105                // Method java/lang/IndexOutOfBoundsException."<init>":(Ljava/lang/String;)V
        28: athrow
        29: invokestatic  #98                 // Method scala/runtime/BoxesRunTime.boxToInteger:(I)Ljava/lang/Integer;
        32: areturn
```

## Expectation

- use `scala.runtime.Statics.ioobe` for reduce class file size
- https://github.com/scala/scala/pull/7086

### PR DESCRIPTION
**Pull request by hamzaremmal**
The idea of using `scala.runtime.Statics.ioobe` was to reduce the size of the generated bytecode.
In this PR, we instead use the JDK9+ constructor of `IndexOutOfBoundsException`.
In the generated code, `checkcast` mentioned in https://github.com/scala/scala/pull/7086#issue-351143908 is also not present making the generated code more efficient than what it looked like in Scala 2.

One question remains, should we deprecate `scala.runtime.Statics.ioobe`? ~I believe we should~ I did deprecate it.
https://github.com/scala/scala3/blob/7eba9a7db49e82141078a8633007b376692bafd6/library/src/scala/runtime/Statics.java#L151

Closes #23971

### CODE REVIEW

**Comment by hamzaremmal** [comment]
Requires Scala.js 1.20.2 when released.

**Comment by hamzaremmal** [comment]
Scala.js 1.20.2 is now on the main branch (#24898), rebasing.

File: library/src/scala/runtime/Statics.java [hunk 1]
```diff
@@ -148,6 +148,7 @@ public static void releaseFence() throws Throwable {
    * Used by the synthetic `productElement` and `productElementName` methods in case classes.
    * Delegating the exception-throwing to this function reduces the bytecode size of the case class.
    */
+  @Deprecated
```
Comment (hamzaremmal) [inline library/src/scala/runtime/Statics.java:151]: I'm marking it as `needs-minor-release` just because of this deprecation. Technically, users should not use directly the `scala.runtime` package so it is fine to deprecate it anytime. Nevertheless, the rule is clear, no deprecation in patches so it has to wait.

**Review by SolalPirelli — APPROVED** [review]
Not familiar yet with the codebase but this looks reasonable to me 👍

File: library/src/scala/runtime/Statics.java (hunk 1 above)
Comment (sjrd) [reply library/src/scala/runtime/Statics.java:151]: Alternative: merge everything else now (in particular, in a way that is backportable to 3.8.x), and only differ the deprecation to a minor release.

Comment (hamzaremmal) [reply library/src/scala/runtime/Statics.java:151]: If I merge it now, that means that Scala.js 1.20.2 should be backported to 3.8.0 too. Will it be the case?
Otherwise, nothing to change in the PR itself. It is backportable as is.

Comment (hamzaremmal) [reply library/src/scala/runtime/Statics.java:151]: /cc @WojciechMazur

Comment (sjrd) [reply library/src/scala/runtime/Statics.java:151]: By "now" I mean in `main` for 3.8.x.

Comment (hamzaremmal) [reply library/src/scala/runtime/Statics.java:151]: Ah, sorry. I read your initial comment wrong and I was confused by the usage of the word "backportable". It could be, but then we split what makes sense to have in a single PR into two and this is not urgent anyways. `3.9.x` is not far away and I don't believe this falls under the feature freeze.

**Comment by SolalPirelli** [comment]
@sjrd should we merge this now that main is for 3.9.0?

**Comment by sjrd** [comment]
Yes.

**Comment by SolalPirelli** [comment]
ok, @tgodzik as an stdlib-officer can you approve? ^^

**Review by tgodzik — APPROVED** [review]
👍
