### PR TITLE
Fixes for isLegalPrefix change

### LINKED ISSUE #22062: Regression in `benhutchison/scalaswingcontrib`
Based on OpenCB failure in `benhutchison/scalaswingcontrib` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/12091465203/job/33720343436)

## Compiler version

Last good release: 3.6.4-RC1-bin-20241121-5d1d274-NIGHTLY
First bad release: 3.6.4-RC1-bin-20241122-64411b6-NIGHTLY
Bisect points to 26ecda540b93fbe1fc7be030559a78dd2db364f2 

## Minimized code

```Scala
//> using scala 3.nightly

class Label
class Component

trait RenderableCellsCompanion {
  type Renderer[-A] <: CellRenderer[A]
  type DefaultRenderer[-A] <: Label & Renderer[A]

  trait CellRendererCompanion {
    type CellInfo
    def labeled[A](): DefaultRenderer[A]
    protected trait LabelRenderer[-A] extends CellRenderer[A]:
      override abstract def componentFor(info: companion.CellInfo): Component = super.componentFor(info)
  }
  trait CellRenderer[-A]:
    val companion: CellRendererCompanion
    def componentFor(cellInfo: companion.CellInfo): Component
}
sealed trait TreeRenderers extends RenderableCellsCompanion { this: Tree.type =>
  trait Renderer[-A] extends CellRenderer[A]:
    final override val companion = Renderer

  object Renderer extends CellRendererCompanion:
    final override class CellInfo
    override def labeled[A]() = new DefaultRenderer[A] with LabelRenderer[A] {}

  class DefaultRenderer[-A] extends Label with Renderer[A]:
    override def componentFor(info: Renderer.CellInfo): Component = ???
}

class Tree extends Component
object Tree extends TreeRenderers
```

## Output

```scala
[error] ./test.scala:26:33
[error] anonymous class TreeRenderers.this.DefaultRenderer[A] with 
[error]   TreeRenderers.Renderer.LabelRenderer[A] {...} cannot be defined due to a conflict between its parents when
[error] implementing a super-accessor for componentFor in trait LabelRenderer:
[error] 
[error] 1. One of its parent (LabelRenderer) contains a call super.componentFor in its body,
[error]    and when a super-call in a trait is written without an explicit parent
[error]    listed in brackets, it is implemented by a generated super-accessor in
[error]    the class that extends this trait based on the linearization order of
[error]    the class.
[error] 2. Because DefaultRenderer comes before LabelRenderer in the linearization
[error]    order of $anon, and because DefaultRenderer overrides componentFor,
[error]    the super-accessor in $anon is implemented as a call to
[error]    super[DefaultRenderer].componentFor.
[error] 3. However,
[error]    (info: TreeRenderers.this.Renderer.CellInfo): Component (the type of super[DefaultRenderer].componentFor in $anon)
[error]    is not a subtype of
[error]    (cellInfo: Nothing): Component (the type of componentFor in trait LabelRenderer).
[error]    Hence, the super-accessor that needs to be generated in $anon
[error]    is illegal.
[error] 
[error] Here are two possible ways to resolve this:
[error] 
[error] 1. Change the linearization order of $anon such that
[error]    LabelRenderer comes before DefaultRenderer.
[error] 2. Alternatively, replace super.componentFor in the body of trait LabelRenderer by a
[error]    super-call to a specific parent, e.g. super[CellRenderer].componentFor
[error]     override def labeled[A]() = new DefaultRenderer[A] with LabelRenderer[A] {}
[error]                         
```

## Expectation
We should check if that's actual regression or a fix to false-negative error.

### LINKED ISSUE #22068: Regression in `getkyo/kyo` using `scalatest/scalatest`
Based on OpenCB failure in `getkyo/kyo` - [build logs ](https://github.com/VirtusLab/community-build3/actions/runs/12091465203/job/33720321093)

## Compiler version

Last good release: 3.6.4-RC1-bin-20241121-5d1d274-NIGHTLY
First bad release: 3.6.4-RC1-bin-20241122-64411b6-NIGHTLY
Bisect points to 26ecda540b93fbe1fc7be030559a78dd2db364f2

## Minimized code

```Scala
trait AnyFreeSpecLike:
  inline implicit def convertToFreeSpecStringWrapper(s: String): FreeSpecStringWrapper = ???
  protected final class FreeSpecStringWrapper(string: String):
    infix def in(testFun: => Any): Unit = ???


import types.Tag.*
class TagTest extends AnyFreeSpecLike{
  inline def test[T1, T2](using k1: Union[T1], k2: Union[T2]): Unit =
    "T1 <:< T2" in {
        val kresult = k1 <:< k2
        ???
    }
  class A
  class B extends A
  class C extends A
  test[B | C, A]
}

object types:
  opaque type Tag[A] = String
  object Tag:
    inline given apply[A]: Tag[A] = ???
    type Full[A] = Tag[A] | Set[A]
    sealed trait Set[A] extends Any
    case class Union[A](tags: Seq[Tag[Any]]) extends AnyVal with Set[A]:
      infix def <:<[B](t2: Full[B]): Boolean = ???
    object Union:
      inline given apply[A]: Union[A] = ???
```

## Output

```scala
-- [E007] Type Mismatch Error: /Users/wmazur/projects/scala/sandbox/test.scala:17:16 -----------------------------------------------
17 |  test[B | C, A]
   |                ^
   |                Found:    (k2$proxy1 : types.type{type Tag[A] = String}#Tag#Union[TagTest.this.A])
   |                Required: String
   |
   | longer explanation available when compiling with `-explain`
```

## Expectation
Should compile

### LINKED ISSUE #22070: Regression in `indoorvivants/genovese`
Based on OpenCB failure in `indoorvivants/genovese` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/12091422428/job/33719850582)

Related issues (same bisect result): #22068  #22062

## Compiler version

Last good release: 3.6.4-RC1-bin-20241121-5d1d274-NIGHTLY
First bad release: 3.6.4-RC1-bin-20241122-64411b6-NIGHTLY
Bisect points to 26ecda540b93fbe1fc7be030559a78dd2db364f2 

## Minimized code

```scala
case class Breaks(x: Boolean, y: Boolean) derives Featureful
```

```Scala
object types:
  opaque type NormalisedFloat <: Float = Float
import types.*

enum Feature[T]:
  case Bool extends Feature[Boolean]
  def fromNormalisedFloat(value: NormalisedFloat): this.type#T = ???

trait Featureful[T]:
  def features: IArray[Feature[?]]
  def toFeatures(value: T): IArray[NormalisedFloat]

object Featureful:
  inline def derived[T](using scala.deriving.Mirror.Of[T]) = ${ derivedImpl[T] }

  import scala.quoted.*
  private def derivedImpl[T: Type](using Quotes): Expr[Featureful[T]] =
    import quotes.reflect.*
    '{
      new Featureful[T]:
        override val features: IArray[Feature[?]] = IArray.empty

        override def toFeatures(value: T): IArray[NormalisedFloat] =
          val feats = IArray.empty[Featureful[?]]
          val product = value.asInstanceOf[Product]
          product.productIterator.zipWithIndex.foreach: (any, idx) =>
            val error = feats(idx).toFeatures(any.asInstanceOf)
          IArray.empty
    }
```

## Output

```scala
Compiling project (Scala 3.6.4-RC1-bin-20241201-6bf4483-NIGHTLY, JVM (17))
[error] ./test-usage.scala:1:51
[error] Found:    Featureful[?]#T
[error] Required: Nothing
[error] case class Breaks(x: Boolean, y: Boolean) derives Featureful
[error]       
```

## Expectation
Should compile

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #22062
Fixes #22068
Fixes #22070

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/inlines/Inliner.scala [hunk 1]
```diff
@@ -768,6 +790,7 @@ class Inliner(val call: tpd.Tree)(using Context):
     override def typedSelect(tree: untpd.Select, pt: Type)(using Context): Tree = {
       val locked = ctx.typerState.ownedVars
       val qual1 = typed(tree.qualifier, shallowSelectionProto(tree.name, pt, this, tree.nameSpan))
+      selectionType(tree, qual1) // side-effect
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/inlines/Inliner.scala:793]: It would be good to be more specific what side effect (error messages?, anything else?)

**Review by odersky — APPROVED** [review]
This will hopefully fix more issues. I particularly like how the OpaqueInlineProxy was factored out into its own abstraction.

Except for one comment LGTM

**Comment by odersky** [comment]
This should get ion before the cutoff.

**Comment by WojciechMazur** [comment]
Is there anything left to do with this changes? Would be great if we could confirm the regressions are fixed before the cutoff

**Comment by odersky** [comment]
It was just an open question. We can merge and get an answer later.

**Comment by dwijnand** [comment]
https://github.com/scala/scala3/pull/22358
