### PR TITLE
Avoid inf recursion in provablyDisjointClasses

### LINKED ISSUE #22266: ProvablyDisjointClasses StackOverflowError when using sealed decorated mixins
## Compiler version
3.6.3-RC1

## Minimized code
```scala3
sealed trait NonPolygon
sealed trait Polygon

sealed trait SymmetryAspect
sealed trait RotationalSymmetry      extends SymmetryAspect
sealed trait MaybeRotationalSymmetry extends SymmetryAspect

enum Shape:
  case Circle   extends Shape with NonPolygon with RotationalSymmetry
  case Triangle extends Shape with Polygon with MaybeRotationalSymmetry
  case Square   extends Shape with Polygon with RotationalSymmetry

object Shape:

  def hasPolygon(
    rotationalSyms: Vector[Shape & RotationalSymmetry],
    maybeSyms: Vector[Shape & MaybeRotationalSymmetry]
  ): Boolean =
    val all = rotationalSyms.concat(maybeSyms)
    all.exists:
      case _: Polygon => true
      case _          => false
```

## Output
[error] ## Exception when compiling...
[error] java.lang.StackOverflowError
[error] dotty.tools.dotc.core.SymDenotations$SymDenotation$$anon$3.applyOrElse(SymDenotations.scala:1731)
[error] dotty.tools.dotc.core.SymDenotations$SymDenotation$$anon$3.applyOrElse(SymDenotations.scala:1731)
[error] scala.collection.immutable.List.collect(List.scala:268)
[error] dotty.tools.dotc.core.SymDenotations$SymDenotation.children(SymDenotations.scala:1731)
[error] dotty.tools.dotc.core.SymUtils.hasAnonymousChild(SymUtils.scala:331)
[error] dotty.tools.dotc.core.TypeComparer.isDecomposable$1(TypeComparer.scala:3196)
[error] dotty.tools.dotc.core.TypeComparer.provablyDisjointClasses(TypeComparer.scala:3222)
[error] dotty.tools.dotc.core.TypeComparer.provablyDisjointClasses$$anonfun$1(TypeComparer.scala:3227)
[error] scala.collection.immutable.List.forall(List.scala:387)
[error] dotty.tools.dotc.core.TypeComparer.provablyDisjointClasses(TypeComparer.scala:3227)
[error] dotty.tools.dotc.core.TypeComparer.provablyDisjointClasses$$anonfun$1(TypeComparer.scala:3227)
[error] scala.collection.immutable.List.forall(List.scala:387)
... //Stack keeps on repeating

## Expectation
The code should compile without any errors or warnings.

## Observations
- If you add the explicit return type as in `val all: Vector[Any] =...` or `val all:Vector[Shape] = ...`, the code compiles.
- If either RotationalSymmetry or MaybeRotationalSymmetry do not extend SymmetryAspect, the code compiles.
- If using scala 3 LTS (3.3.4), without any changes to the code, the code compiles.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #22266

### CODE REVIEW

**Review by sjrd — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -3211,17 +3211,18 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
...
     def decompose(cls: Symbol): List[Symbol] =
-      cls.children.flatMap { child =>
+      cls.children.map: child =>
         if child.isTerm then
-          child.info.classSymbols // allow enum vals to be decomposed to their enum class (then filtered out) and any mixins
-        else child :: Nil
-      }.filter(child => child.exists && child != cls)
+          child.info.classSymbol.orElse(child)
+        else child
+      .filter(child => child.exists && child != cls)
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:3218]: The change looks good to me. However it means that recursive calls to `provablyDisjointClasses` provide arguments that are *not* classes! We should make that clear in a the doc comment of `provablyDisjointClasses`.

Also we should adjust the spec test at
https://github.com/scala/scala3/blob/590691b09bb8554dd312a4e942f91dcd43ba6b44/docs/_spec/03-types.md?plain=1#L1074-L1080
to account for that possibility. Perhaps
```diff
-Second, we define the relation ´⋔´ on *classes* (including traits and hidden classes of objects) as:
+Second, we define the relation ´⋔´ on *classes* (including traits and hidden classes of objects and enum values) as:
```

**Review by sjrd — CHANGES_REQUESTED** [review]

**Review by sjrd — APPROVED** [review]
