### PR TITLE
Fix isomorphism tests of `AndOrType`s under non-empty `BinderPairs`

### LINKED ISSUE #20858: Regression in `alterationx10/opinionated-zio` match types
One more affected project `alterationx10/opinionated-zio` it's bisect points to the same commits. This time we don't have ambigious extension methods, yet, still type reduction fails

```scala
// 1_defns.scala
import scala.compiletime.*
import scala.deriving.*

sealed trait ZIO[-R, +E, +A]
sealed abstract class ZLayer[-RIn, +E, +ROut]
object ZLayer:
    def apply[RIn, E, ROut](zio: => ZIO[RIn, E, ROut]): ZLayer[RIn, E, ROut] = ???
type URIO[-R, +A] = ZIO[R, Nothing, A]
type IAnyType[T <: Tuple] = Tuple.Fold[T, Any, [x, y] =>> x & y]
type UAnyType[T <: Tuple] = Tuple.Fold[T, Any, [x, y] =>> x | y]


trait AutoLayer[A]:
  def zlayer(using
      p: Mirror.ProductOf[A]
  ): ZLayer[IAnyType[p.MirroredElemTypes], Nothing, A]

object AutoLayer:
  inline given derived[A](using p: Mirror.ProductOf[A]): AutoLayer[A] = {
    val a: ZIO[IAnyType[p.MirroredElemTypes], Nothing, A] = ???
    new AutoLayer[A]:
      override def zlayer(using
          pp: Mirror.ProductOf[A]
      ): ZLayer[IAnyType[pp.MirroredElemTypes], Nothing, A] = ZLayer {
        a.asInstanceOf[ZIO[IAnyType[pp.MirroredElemTypes], Nothing, A]]
      }
    }
```

```scala
// 2_usage.scala
case class TestService(port: Int) derives AutoLayer
``` 

yields: 
```scala
[error] Found:    ZLayer[Tuple.Fold[pp.MirroredElemTypes, Any, [x, y] =>> x & y], Nothing,
[error]   TestService]
[error] Required: ZLayer[IAnyType[pp.MirroredElemTypes], Nothing, TestService]
[error] 
[error] Note: a match type could not be fully reduced:
[error] 
[error]   trying to reduce  Tuple.Fold[pp.MirroredElemTypes, Any, [x, y] =>> x & y]
[error]   failed since selector pp.MirroredElemTypes
[error]   does not match  case EmptyTuple => Any
[error]   and cannot be shown to be disjoint from it either.
[error]   Therefore, reduction cannot advance to the remaining case
[error] 
[error]     case h *: t => h & Tuple.Fold[t, Any, [x, y] =>> x & y]
[error] case class TestService(port: Int) derives AutoLayer
```

_Originally posted by @WojciechMazur in https://github.com/scala/scala3/issues/20288#issuecomment-2085298894_

### PR DESCRIPTION
**Pull request by EugeneFlesselle**
Before the changes, when comparing two `HKTypeLambda` result types, the list of binding pairs was lost when entering comparison of `AndOrType`s, which caused the `equals` to fail, and hence prevented hash-consing.

Even though `M1` and `M2` in pos/i20858-min should still conform to one-another, we entered a deep-subtype comparison because of the order in which the TypeComparer does dealiasing of AppliedTypes, and comparison of MatchCases and AndTypes.

Fix #20858

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 1]
```diff
@@ -3741,6 +3747,10 @@ object Types extends TypeUtils {
       case that: OrType => tp1.eq(that.tp1) && tp2.eq(that.tp2) && isSoft == that.isSoft
       case _ => false
     }
+
+    override protected def iso(that: Any, bs: BinderPairs) = that match
+      case that: OrType => tp1.equals(that.tp1, bs) && tp2.equals(that.tp2, bs)
```
Comment (EugeneFlesselle) [inline compiler/src/dotty/tools/dotc/core/Types.scala:3752]: Not sure if it should also require
```suggestion
      case that: OrType => tp1.equals(that.tp1, bs) && tp2.equals(that.tp2, bs) && isSoft == that.isSoft
```
as in `eql` ?

Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/core/Types.scala:3752]: Well it's going to be the more conservative approach to include it.

**Review by dwijnand — APPROVED** [review]
LGTM, with that change
