### PR TITLE
Replicate value class erasure binary compat hack in GenericSignatures

### LINKED ISSUE #22140: Dotty emit wrong generic signature for generic value classes
## Compiler version

`3.5.1`

## Minimized code

```scala
class Bar[T](val value: T) extends AnyVal
object Foo {
    def bar[T](implicit vt: Bar[T]) = vt.value
}
```

## Output

```scala
javap Foo.class
Compiled from "predef-issues.scala"
public final class Foo {
  public static <T> T bar(java.lang.Object);
}
```

## Expectation

Follow SIP-15 and Scala 2:

```scala
javap Foo.class
Compiled from "predef-issues.scala"
public final class Foo {
  public static <T> T bar(T);
}
```

### LINKED ISSUE #24276: Generating generic signatures in the presence of `AnyVal` is wrong
## Compiler version

https://github.com/scala/scala3/commit/ce57b712885b9c47702df971219ea743717a4c6c

## Minimized code

```scala
class Box[A](v: A) extends AnyVal
class Foo:
    def box[A]: Box[A] = ???
```

## Output

```java
//> javap Foo  
Compiled from "test.scala"
public class Foo {
  public Foo();
  public <A> java.lang.Object box();
}
```

## Expectation

```java
//> javap Foo
Compiled from "test.scala"
public class Foo {
  public <A> A box();
  public Foo();
}
```

## Notes

First mentioned in #22140 (should be the same fix)

### PR DESCRIPTION
**Pull request by SolalPirelli**
Supersedes #24284

Closes #24276
Closes #22140

## How much have you relied on LLM-based tools in this contribution?

only if you consider Hamza an LLM since this is based on his PR

## How was the solution tested?

new test + existing one

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeErasure.scala [hunk 1]
```diff
@@ -992,7 +992,7 @@ class TypeErasure(sourceLanguage: SourceLanguage, semiEraseVCs: Boolean, isConst
       //   erased like `Array[A]` as seen from its definition site, no matter
       //   the `X` (same if `A` is bounded).
       //
-      // The binary compatibility is checked by sbt-test/scala2-compat/i8001
+      // The binary compatibility is checked by tests/run/i8001
```
Comment (SolalPirelli) [inline compiler/src/dotty/tools/dotc/core/TypeErasure.scala:995]: read the comment right above this to understand the change below

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 2]
```diff
@@ -333,8 +333,17 @@ object GenericSignatures {
             else builder.append(defn.typeTag(sym.info))
           else if (sym.isDerivedValueClass) {
             if (vcBoxing == ValueClassBoxing.Unbox) {
-              val erasedUnderlying = fullErasure(tp)
-              jsig(erasedUnderlying, toplevel = toplevel)
+              val underlying = ValueClasses.underlyingOfValueClass(sym.asClass)
+              val seenUnderlying = underlying.asSeenFrom(tp, sym)
+              // For binary compatibility with Scala 2, as documented in TypeErasure,
+              // we need to use the boxed version of value classes' underlying type.
```
Comment (tanishiking) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala]: This can be read like we **always** need to use the boxed version, maybe like:?

```suggestion
              // we need to special cases for polymorphic value classes:
              // `Foo[X]` erases to `X` except that primitives use their boxed type,
              // and `Bar[X]` for `class Bar[A](x: Array[A]) extends AnyVal` erases like the definition-site `Array[A]`.
```

File: tests/run/i8001/B_2.java [hunk 3]
```diff
@@ -16,7 +16,7 @@ public static void test() {
 
     a.arr1(intArr);
     a.arr2(stringArr);
-    a.arr3(intArr);
+    a.arr3(intArr2);
```
Comment (tanishiking) [inline tests/run/i8001/B_2.java:19]: nice catch :+1:

File: tests/run/i24276.check [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+public java.lang.String Foo.foo5(java.lang.String)
+---
+public java.lang.Object Foo.foo6(java.lang.Object)
+public java.lang.Object Foo.foo6(java.lang.Object)
+---
+public java.lang.Object[] Foo.foo6b(java.lang.Object[])
+public java.lang.Object[] Foo.foo6b(java.lang.Object[])
+---
+public java.lang.Object Foo.foo7(java.lang.Object)
+public java.lang.Object Foo.foo7(java.lang.Object)
```
Comment (tanishiking) [inline tests/run/i24276.check:44]: I'm not sure this is related to this change, but it looks like Scala 2 emits generic signature like `int`, `int[]`, and `String[]` respectively. maybe we should align with Scala2?

**Review by tanishiking — CHANGES_REQUESTED** [review]
Nice!
1 nitpick on `GenericSignatures` comment, and I'm a little concerned about whether the generic signature output in the test is correct 🤔 . If that's not a regression caused by this PR, I think it's fine to merge this PR and improve it in a separate issue :)

File: tests/run/i8001/B_2.java (hunk 3 above)
Comment (SolalPirelli) [reply tests/run/i8001/B_2.java:19]: this line failed to compile after this change, thank `javac` 😂

File: tests/run/i24276.check (hunk 4 above)
Comment (SolalPirelli) [reply tests/run/i24276.check:44]: Just the generic signature? Since this PR doesn't touch the descriptors, I'd rather do any change that also changes descriptors in a separate PR

Comment (tanishiking) [reply tests/run/i24276.check:44]: Ah, yes, just about GenericSignatures.

Comment (SolalPirelli) [reply tests/run/i24276.check:44]: Wait so just to make sure I understand correctly, Scala 2 emits `Object` in the descriptor and something else in the generic signatures? Isn't that incorrect since the only difference between a descriptor and a generic signature should be for stuff that is generic?

For instance in foo7 I could totally see both descriptor and signature using `String[]`, but since we have this explicit hack to make them `Object` having both be that makes sense, but I don't see how them mismatching would work.

FWIW, I had some such mismatches (I don't remember which ones exactly) while developing this PR and i8001 was failing to compile because javac wasn't happy.

Comment (tanishiking) [reply tests/run/i24276.check:44]: > Scala 2 emits Object in the descriptor and something else in the generic signatures?
> ...
> since we have this explicit hack to make them Object having both be that makes sense, but I don't see how them mismatching would work.

Yes, Scala 2 emits something  different in generic signatures for those cases  ... but, you're right.

Since `|jl.Integer[]|` -> `jl.Integer[]` and it's not erased to `jl.Object[]`, Scala2's signature is wired indeed, and our Scala3 signatures seems correct 🤔  https://docs.oracle.com/javase/specs/jls/se21/html/jls-4.html#jls-4.6

```scala
// test.scala

class Arr[A](val value: Array[A]) extends AnyVal
class ArrR[A <: AnyRef](val value: Array[A]) extends AnyVal

class Foo {
  def foo6(a: Arr[Int]): Arr[Int] = a
  def foo6b(a: ArrR[java.lang.Integer]): ArrR[java.lang.Integer] = a
  def foo7(a: Arr[String]): Arr[String] = a
}

object CheckScala2Foo67 extends App {
  classOf[Foo].getDeclaredMethods.toList
    .filter(m => Set("foo6", "foo6b", "foo7")(m.getName))
    .sortBy(_.getName)
    .foreach { m =>
      println(m)
      println(m.toGenericString)
      println("---")
    }
}
```

```bash
❯ scala-cli run --server=false -S 2 test.scala
public java.lang.Object Foo.foo6(java.lang.Object)
public int[] Foo.foo6(int[])
---
public java.lang.Object[] Foo.foo6b(java.lang.Object[])
public java.lang.Integer[] Foo.foo6b(java.lang.Integer[])
---
public java.lang.Object Foo.foo7(java.lang.Object)
public java.lang.String[] Foo.foo7(java.lang.String[])
---
```

Comment (SolalPirelli) [reply tests/run/i24276.check:44]: sounds like this should be a new bug report for scala2 😅  thanks for checking!

**Review by tanishiking — APPROVED** [review]
LGTM!
